#!/bin/sh

# ctdbd wrapper - start or stop CTDB

usage ()
{
    echo "usage: ctdbd_wrapper { start | stop }"
    exit 1
}

[ $# -eq 1 ] || usage

action="$1"

############################################################

if [ -z "$CTDB_BASE" ] ; then
    export CTDB_BASE="/usr/local/etc/ctdb"
fi

. "${CTDB_BASE}/functions"

load_system_config "ctdb"

ctdbd="${CTDBD:-/usr/local/sbin/ctdbd}"

############################################################

start()
{
    eval "$ctdbd" || return 1
}

stop()
{
	$CTDB shutdown || return 1
}

############################################################

# Allow notifications for start/stop.
if [ -x "$CTDB_BASE/rc.ctdb" ] ; then
    "$CTDB_BASE/rc.ctdb" "$action"
fi

case "$action" in
    start) start ;;
    stop)  stop  ;;
    *)
	echo "usage: $0 {start|stop}"
	exit 1
esac
