#!/bin/sh

LIBDIR=/home/tridge/samba/source/smbwrapper

# a simple launcher for the smbwrapper.so preloadde library

if [ x$SMBW_USER = x ]; then
    echo username?
    read user
    SMBW_USER=$user
    export SMBW_USER
fi

# this doesn't hide the password - we need a proper launch app for that
if [ x$SMBW_PASSWORD = x ]; then
    echo password?
    read pass
    SMBW_PASSWORD=$pass
    export 
fi

LD_PRELOAD=$LIBDIR/smbwrapper.so
export LD_PRELOAD

export PWD
PS1='smbsh$ '
export PS1
bash
