#!/bin/sh

if [ ! -d catman ]; then
   mkdir catman
fi

# if you wish to make html versions of the man pages then uncomment
# the following section and the "rman" command below
#
# if [ ! -d html ]; then
#    mkdir html
# fi

FILES="*.?"

cd ../../docs
for FILE in  $FILES ; do
   neqn $FILE | tbl | nroff -man > ../packaging/SGI/catman/`basename $FILE`
   compress -f ../packaging/SGI/catman/`basename $FILE`
#    rman -f html -r "%s.%s.html"  $FILE > ../packaging/SGI/html/$FILE.html
done
cd ../packaging/SGI
