#!/usr/bin/env python

bld.SAMBA_LIBRARY('samba-credentials',
	source='credentials.c',
	public_headers='credentials.h',
	pc_files='samba-credentials.pc',
	deps='LIBCRYPTO samba-errors events LIBCLI_AUTH samba-security CREDENTIALS_SECRETS CREDENTIALS_KRB5 CREDENTIALS_GMSA',
	vnum='1.0.0'
	)

bld.SAMBA_SUBSYSTEM('CREDENTIALS_KRB5',
	source='credentials_krb5.c',
	deps='KERBEROS_SRV_KEYTAB KERBEROS_UTIL gssapi samba-credentials',
	public_deps='com_err authkrb5',
	)

bld.SAMBA_SUBSYSTEM('CREDENTIALS_GMSA',
	source='credentials_gmsa.c',
	deps='samba-credentials CREDENTIALS_NTLM NDR_GMSA ldb gkdi',
	)

bld.SAMBA_SUBSYSTEM('CREDENTIALS_SECRETS',
	source='credentials_secrets.c',
	deps='CREDENTIALS_KRB5 CREDENTIALS_NTLM ldb SECRETS samdb-common dbwrap',
	)

bld.SAMBA_SUBSYSTEM('CREDENTIALS_NTLM',
	source='credentials_ntlm.c',
	deps='samba-credentials GNUTLS_HELPERS')

bld.SAMBA_SUBSYSTEM('CREDENTIALS_CMDLINE',
                    source='credentials_cmdline.c',
                    deps='samba-credentials')

pyrpc_util = bld.pyembed_libname('pyrpc_util')
pytalloc_util = bld.pyembed_libname('pytalloc-util')
pyparam_util = bld.pyembed_libname('pyparam_util')

bld.SAMBA_PYTHON('pycredentials',
    source='pycredentials.c',
    public_deps='samba-credentials %s %s %s CREDENTIALS_CMDLINE CREDENTIALS_KRB5 CREDENTIALS_SECRETS' % (pyrpc_util, pytalloc_util, pyparam_util),
    realname='samba/credentials.so'
)

bld.SAMBA_BINARY('test_creds',
                 source='tests/test_creds.c',
                 deps='cmocka samba-credentials',
                 local_include=False,
                 for_selftest=True)
