#!/usr/bin/env python

bld.SAMBA_LIBRARY('samba-credentials',
	source='credentials.c',
	autoproto='credentials_proto.h',
	public_headers='credentials.h',
	pc_files='samba-credentials.pc',
	deps='LIBCRYPTO errors events LIBCLI_AUTH samba-security CREDENTIALS_SECRETS CREDENTIALS_KRB5',
	vnum='0.0.1'
	)

bld.SAMBA_SUBSYSTEM('CREDENTIALS_KRB5',
	source='credentials_krb5.c',
	deps='KERBEROS_SRV_KEYTAB KERBEROS_UTIL gssapi samba-credentials',
	public_deps='com_err authkrb5',
	)

bld.SAMBA_SUBSYSTEM('CREDENTIALS_SECRETS',
	source='credentials_secrets.c',
	deps='CREDENTIALS_KRB5 CREDENTIALS_NTLM ldb SECRETS samdb-common dbwrap',
	)

bld.SAMBA_SUBSYSTEM('CREDENTIALS_NTLM',
	source='credentials_ntlm.c',
	deps='samba-credentials')

bld.SAMBA_PYTHON('pycredentials',
	source='pycredentials.c',
	public_deps='samba-credentials cmdline-credentials pytalloc-util pyparam_util CREDENTIALS_KRB5 CREDENTIALS_SECRETS',
	realname='samba/credentials.so'
	)

