#!/usr/bin/env python

# LDBSAMBA gets included in the ldb build when we are building ldb_ildap 
# as a built-in module and this delutes the symbols in the ldb library with 
# the symbols of all of ldb_ildap's dependencies. 

bld.SAMBA_SUBSYSTEM('LDBSAMBA',
	source='ldif_handlers.c ldb_wrap.c',
	autoproto='ldif_handlers_proto.h',
	public_deps='ldb',
	public_headers='ldb_wrap.h',
	deps='LIBSECURITY SAMDB_SCHEMA LIBNDR NDR_DRSBLOBS CREDENTIALS UTIL_LDB'
	)


bld.SAMBA_PYTHON('python_samba__ldb', 'pyldb.c',
				 deps='LDBSAMBA pyparam_util',
				 realname='samba/_ldb.so')
