#!/usr/bin/env python


bld.SAMBA_SUBSYSTEM('LDBSAMBA',
	source='ldif_handlers.c ldb_wrap.c',
	autoproto='ldif_handlers_proto.h',
	public_deps='ldb',
	public_headers='ldb_wrap.h',
	deps='LIBSECURITY SAMDB_SCHEMA LIBNDR NDR_DRSBLOBS CREDENTIALS UTIL_LDB'
	)


bld.SAMBA_PYTHON('python_samba__ldb', 'pyldb.c',
				 deps='LDBSAMBA pyparam_util',
				 realname='samba/_ldb.so')
