[SUBSYSTEM::LIBCOMPRESSION]

LIBCOMPRESSION_OBJ_FILES = lib/compression/mszip.o

[SUBSYSTEM::GENCACHE]
PRIVATE_DEPENDENCIES = TDB_WRAP

GENCACHE_OBJ_FILES = gencache/gencache.o

# PUBLIC_HEADERS += lib/gencache/gencache.h

[SUBSYSTEM::LDB_WRAP]
PUBLIC_DEPENDENCIES = LIBLDB
PRIVATE_DEPENDENCIES = LDBSAMBA UTIL_LDB

LDB_WRAP_OBJ_FILES = lib/ldb_wrap.o
PUBLIC_HEADERS += lib/ldb_wrap.h

[SUBSYSTEM::TDB_WRAP]
PUBLIC_DEPENDENCIES = LIBTDB

TDB_WRAP_OBJ_FILES = lib/tdb_wrap.o
PUBLIC_HEADERS += lib/tdb_wrap.h

SMBREADLINE_OBJ_LIST = $(SMBREADLINE_OBJ_FILES)
