dnl # LIB BASIC subsystem

SMB_SUBSYSTEM_MK(LIBREPLACE,lib/basic.mk)
SMB_SUBSYSTEM_MK(LIBNETIF,lib/basic.mk)
SMB_SUBSYSTEM_NOPROTO(LIBCRYPTO)
SMB_SUBSYSTEM_MK(LIBCRYPTO,lib/basic.mk)
SMB_SUBSYSTEM_MK(LIBBASIC,lib/basic.mk)
