Import('hostenv')
#            tastes like -*- python -*-

SConscript(dirs=['talloc','charset'])
Import('talloc', 'dynconfig', 'charset')

basic_files = ['version.c', 'xfile.c', 'debug.c', 'fault.c', 
	 'signal.c', 'system.c', 'time.c', 'genrand.c', 'dprintf.c',
	 'util_str.c', 'util_strlist.c', 'util_unistr.c', 'util_file.c',
	 'data_blob.c', 'util.c', 'util_sock.c', 'substitute.c', 
	 'fsusage.c', 'ms_fnmatch.c', 'select.c', 'mutex.c', 'idtree.c',
	 'db_wrap.c']

proto_files = basic_files

basic = hostenv.StaticLibrary('basic', [dynconfig,charset,talloc,basic_files])
Export('basic')

hostenv.StaticLibrary('tdr', ['tdr/tdr.c'])
hostenv.StaticLibrary('crypto', 
		['crypto/crc32.c','crypto/md5.c','crypto/hmacmd5.c',
		'crypto/md4.c','crypto/arcfour.c'])
hostenv.StaticLibrary('compression', ['compression/mszip.c'])
hostenv.StaticLibrary('gencache',['gencache.c'])
hostenv.StaticLibrary('pidfile',['pidfile.c'])
hostenv.StaticLibrary('unix_privs',['unix_privs.c'])

SConscript(dirs=['ldb'])

Import('ldb')
gendb_files = ['gendb.c']
proto_files += gendb_files
gendb = hostenv.StaticLibrary('gendb', [gendb_files,ldb])
Export('gendb')

credentials_files = ['credentials.c']
proto_files += credentials_files
credentials = hostenv.StaticLibrary('credentials',[credentials_files,basic,gendb])
Export('credentials')

hostenv.proto_headers += hostenv.CProtoHeader('proto.h', proto_files)

SConscript(dirs=['../param/','replace','tdb','popt','cmdline','registry', 'tls','samba3','socket','socket_wrapper','messaging','com','events', 'appweb', 'netif'])

