#!/usr/bin/env python

bld.SAMBA_LIBRARY('cliauth',
                  source='',
                  deps='MSRPC_PARSE LIBCLI_AUTH COMMON_SCHANNEL PAM_ERRORS SPNEGO_PARSE krb5samba errors NTLM_CHECK UTIL_LSARPC',
                  private_library=True,
                  grouping_library=True)

bld.SAMBA_SUBSYSTEM('MSRPC_PARSE',
	source='msrpc_parse.c',
	deps='talloc'
	)

bld.SAMBA_SUBSYSTEM('NTLM_CHECK',
                    source='ntlm_check.c',
                    deps = 'talloc'
                    )

bld.SAMBA_SUBSYSTEM('LIBCLI_AUTH',
	source='credentials.c session.c smbencrypt.c smbdes.c',
	public_deps='MSRPC_PARSE',
	public_headers='credentials.h:domain_credentials.h'
	)


bld.SAMBA_SUBSYSTEM('COMMON_SCHANNEL',
	source='schannel_state_tdb.c schannel_sign.c',
	deps='tdb-wrap util_tdb samba-hostconfig NDR_NETLOGON'
	)


bld.SAMBA_SUBSYSTEM('PAM_ERRORS',
	source='pam_errors.c',
	deps='talloc'
	)

bld.SAMBA_SUBSYSTEM('SPNEGO_PARSE',
                    source='spnego_parse.c',
                    deps='asn1util')
