#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('LIBCLI_SMB2',
	source='transport.c request.c session.c tcon.c create.c close.c connect.c getinfo.c write.c read.c setinfo.c find.c ioctl.c logoff.c tdis.c flush.c lock.c notify.c cancel.c keepalive.c break.c util.c signing.c lease_break.c',
	autoproto='smb2_proto.h',
	deps='tevent-util cli_smb_common GNUTLS_HELPERS',
	public_deps='smbclient-raw gensec samba-credentials tevent',
	private_headers='smb2.h',
	)

