Import('hostenv')
proto_files = []
cli_utils_files = ['util/asn1.c', 'util/doserr.c','util/errormap.c','util/clierror.c', 'util/nterr.c','util/smbdes.c']
proto_files += cli_utils_files
hostenv.StaticLibrary('cli_utils', cli_utils_files)

hostenv.StaticLibrary('cli_lsa', ['util/clilsa.c'])
hostenv.StaticLibrary('cli_composite_base', ['composite/composite.c'])
hostenv.StaticLibrary('cli_composite', 
	['composite/loadfile.c','composite/savefile.c','composite/connect.c',
	 'composite/sesssetup.c','composite/fetchfile.c','composite/appendacl.c',
	 'composite/fsinfo.c'])

hostenv.StaticLibrary('cli_nbt',
	['nbt/nbtname.c','nbt/nbtsocket.c','nbt/namequery.c','nbt/nameregister.c',
	'nbt/namerefresh.c','nbt/namerelease.c'])

hostenv.StaticLibrary('cli_dgram',
	[ 'dgram/dgramsocket.c','dgram/mailslot.c','dgram/netlogon.c',
	 'dgram/ntlogon.c','dgram/browse.c'])

hostenv.StaticLibrary('cli_cldap', ['cldap/cldap.c'])
hostenv.StaticLibrary('cli_wrepl', ['wrepl/winsrepl.c'])
hostenv.StaticLibrary('cli_resolve', 
	['resolve/resolve.c','resolve/nbtlist.c','resolve/bcast.c','resolve/wins.c',
	'resolve/host.c'])


hostenv.StaticLibrary('smb', 
		['clireadwrite.c', 'cliconnect.c','clifile.c','clilist.c','clitrans2.c',
		'climessage.c','clideltree.c'])

hostenv.StaticLibrary('cli_raw',
		['raw/rawfile.c','raw/smb_signing.c','raw/clisocket.c',
		'raw/clitransport.c','raw/clisession.c','raw/clitree.c',
		'raw/rawrequest.c','raw/rawreadwrite.c','raw/rawsearch.c',
		'raw/rawsetfileinfo.c','raw/raweas.c','raw/rawtrans.c',
		'raw/clioplock.c','raw/rawnegotiate.c','raw/rawfsinfo.c',
		'raw/rawfileinfo.c','raw/rawnotify.c','raw/rawioctl.c',
		'raw/rawacl.c','raw/rawdate.c','raw/rawlpq.c'])

security_files = ['security/security_token.c','security/security_descriptor.c',
			   'security/dom_sid.c', 'security/access_check.c',
			   'security/privilege.c', '../librpc/ndr/ndr_sec_helper.c']
proto_files += security_files
hostenv.StaticLibrary('cli_security', security_files)

auth_files = ['auth/credentials.c','auth/session.c','auth/smbencrypt.c']
proto_files += auth_files
hostenv.StaticLibrary('cli_auth',auth_files)

ldap_files = ['ldap/ldap.c','ldap/ldap_client.c','ldap/ldap_bind.c',
		   'ldap/ldap_msg.c','ldap/ldap_ndr.c','ldap/ldap_ildap.c']
proto_files += ldap_files
hostenv.StaticLibrary('cli_ldap',ldap_files)

hostenv.proto_headers += hostenv.CProtoHeader('proto.h', proto_files)
