#ifndef __LIB_UTIL_WRAP_XATTR_H__
#define __LIB_UTIL_WRAP_XATTR_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from lib/util/wrap_xattr.c  */

_PUBLIC_ ssize_t wrap_fgetxattr(int fd, const char *name, void *value, size_t size);
_PUBLIC_ ssize_t wrap_getxattr(const char *path, const char *name, void *value, size_t size);
_PUBLIC_ int wrap_fsetxattr(int fd, const char *name, void *value, size_t size, int flags);
_PUBLIC_ int wrap_setxattr(const char *path, const char *name, void *value, size_t size, int flags);
_PUBLIC_ int wrap_fremovexattr(int fd, const char *name);
_PUBLIC_ int wrap_removexattr(const char *path, const char *name);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __LIB_UTIL_WRAP_XATTR_H__ */

