#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('fuzzing',
    source='fuzzing.c',
    deps='talloc',
    enabled=bld.env.enable_libfuzzer,
    )

bld.SAMBA_BINARY('fuzz_tiniparser',
                 source='fuzz_tiniparser.c',
                 deps='fuzzing tiniparser talloc',
                 install=False,
                 enabled=bld.env.enable_libfuzzer)

bld.SAMBA_BINARY('fuzz_oLschema2ldif',
                 source='fuzz_oLschema2ldif.c',
                 deps='fuzzing oLschema2ldif-lib',
                 install=False,
                 enabled=bld.env.enable_libfuzzer,
                 )

bld.SAMBA_BINARY('fuzz_reg_parse',
                 source='fuzz_reg_parse.c',
                 deps='fuzzing samba3-util smbconf REGFIO',
                 install=False,
                 enabled=bld.env.enable_libfuzzer,
                 )

bld.SAMBA_BINARY('fuzz_regfio',
                 source='fuzz_regfio.c',
                 deps='fuzzing samba3-util smbconf REGFIO',
                 install=False,
                 enabled=bld.env.enable_libfuzzer,
                 )
