#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('fuzzing',
    source='fuzzing.c',
    deps='talloc',
    enabled=bld.env.enable_libfuzzer,
    )

bld.SAMBA_BINARY('fuzz_tiniparser',
                 source='fuzz_tiniparser.c',
                 deps='fuzzing tiniparser talloc',
                 install=False,
                 enabled=bld.env.enable_libfuzzer)
