# German messages for international release of SWAT.
# Copyright (C) 2001 Andreas Moroder
# Copyright (C) 2007 Helge Kreutzmann, <debian@helgefjell.de>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, see <http://www.gnu.org/licenses/>.
#
msgid ""
msgstr ""
"Project-Id-Version: swat\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-07-30 12:18+0200\n"
"PO-Revision-Date: 2007-06-10 11:52+0200\n"
"Last-Translator: Helge Kreutzmann <debian@helgefjell.de>\n"
"Language-Team: German <debian-l10n-german@lists.debian.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../web/swat.c:153
#, c-format
msgid "ERROR: Can't open %s"
msgstr "FEHLER: Kann %s nicht öffnen"

#: ../web/swat.c:241
msgid "Help"
msgstr "Hilfe"

#: ../web/swat.c:247 ../web/swat.c:272 ../web/swat.c:293 ../web/swat.c:302 ../web/swat.c:311 ../web/swat.c:317 ../web/swat.c:329 ../web/swat.c:343
msgid "Set Default"
msgstr "Standardwert setzen"

#: ../web/swat.c:465
#, c-format
msgid "failed to open %s for writing"
msgstr "konnte %s nicht zum Schreiben öffnen"

#: ../web/swat.c:488
#, c-format
msgid "Can't reload %s"
msgstr "Kann %s nicht erneut laden"

#: ../web/swat.c:561
#, c-format
msgid "Logged in as <b>%s</b>"
msgstr "Verbunden als <b>%s</b>"

#: ../web/swat.c:565
msgid "Home"
msgstr "Home"

#: ../web/swat.c:567
msgid "Globals"
msgstr "Globals"

#: ../web/swat.c:568
msgid "Shares"
msgstr "Freigaben"

#: ../web/swat.c:569
msgid "Printers"
msgstr "Drucker"

#: ../web/swat.c:570
msgid "Wizard"
msgstr "Assistent"

#: ../web/swat.c:574
msgid "Status"
msgstr "Status"

#: ../web/swat.c:575
msgid "View Config"
msgstr "Zeige Konfiguration"

#: ../web/swat.c:577
msgid "Password Management"
msgstr "Passwortverwaltung"

#: ../web/swat.c:587
msgid "Current View Is"
msgstr "Aktuelle Ansicht lautet"

#: ../web/swat.c:588 ../web/swat.c:591
msgid "Basic"
msgstr "Einfache Ansicht"

#: ../web/swat.c:589 ../web/swat.c:592
msgid "Advanced"
msgstr "Erweiterte Ansicht"

#: ../web/swat.c:590
msgid "Change View To"
msgstr "Ansicht ändern in"

#: ../web/swat.c:619
msgid "Current Config"
msgstr "Aktuelle Konfiguration"

#: ../web/swat.c:623
msgid "Normal View"
msgstr "Normale Ansicht"

#: ../web/swat.c:625
msgid "Full View"
msgstr "Komplette Ansicht"

#. Here we first set and commit all the parameters that were selected
#. in the previous screen.
#: ../web/swat.c:644
msgid "Wizard Parameter Edit Page"
msgstr "Bearbeitungsseite der Assistenten-Parameter"

#: ../web/swat.c:673
msgid "Note: smb.conf file has been read and rewritten"
msgstr "Hinweis: smb.conf wurde gelesen und überschrieben"

#. Here we go ...
#: ../web/swat.c:779
msgid "Samba Configuration Wizard"
msgstr "Samba-Konfigurationsassistent"

#: ../web/swat.c:783
msgid "The \"Rewrite smb.conf file\" button will clear the smb.conf file of all default values and of comments."
msgstr "Der Knopf »Schreibe smb.conf neu« wird alle Kommentare und Standardwerte aus der smb.conf löschen."

#: ../web/swat.c:784
msgid "The same will happen if you press the commit button."
msgstr "Das gleiche passiert beim Knopf »übernehmen«."

#: ../web/swat.c:787
msgid "Rewrite smb.conf file"
msgstr "Schreibe smb.conf neu"

#: ../web/swat.c:788
msgid "Commit"
msgstr "Übernehmen"

#: ../web/swat.c:789
msgid "Edit Parameter Values"
msgstr "Bearbeite Parameterwerte"

#: ../web/swat.c:795
msgid "Server Type"
msgstr "Server-Typ"

#: ../web/swat.c:796
msgid "Stand Alone"
msgstr "Einzelserver"

#: ../web/swat.c:797
msgid "Domain Member"
msgstr "Domänenmitglied"

#: ../web/swat.c:798
msgid "Domain Controller"
msgstr "Domänencontroller"

#: ../web/swat.c:801
msgid "Unusual Type in smb.conf - Please Select New Mode"
msgstr "Ungewöhnlicher Typ in der smb.conf - Bitte wählen Sie einen neuen Modus"

#: ../web/swat.c:803
msgid "Configure WINS As"
msgstr "Konfiguriere WINS als"

#: ../web/swat.c:804
msgid "Not Used"
msgstr "Nicht benutzt"

#: ../web/swat.c:805
msgid "Server for client use"
msgstr "Server für Client-Verwendung"

#: ../web/swat.c:806
msgid "Client of another WINS server"
msgstr "Client eines anderen WINS-Servers"

#: ../web/swat.c:808
msgid "Remote WINS Server"
msgstr "Entfernter WINS-Server:"

#: ../web/swat.c:819
msgid "Error: WINS Server Mode and WINS Support both set in smb.conf"
msgstr "Fehler: Sowohl WINS-Server-Modus als auch WINS-Unterstützung in smb.conf aktiviert"

#: ../web/swat.c:820
msgid "Please Select desired WINS mode above."
msgstr "Bitte wählen Sie den gewünschten WINS-Modus oben aus."

#: ../web/swat.c:822
msgid "Expose Home Directories"
msgstr "Home-Verzeichnisse freigeben"

#: ../web/swat.c:837
msgid "The above configuration options will set multiple parameters and will generally assist with rapid Samba deployment."
msgstr "Die obigen Konfigurationsoptionen bearbeiten mehrere Parameter und dienen als Hilfe zur schnellen Samba-Einrichtung."

#: ../web/swat.c:850
msgid "Global Parameters"
msgstr "Globale Parameter"

#: ../web/swat.c:878 ../web/swat.c:986 ../web/swat.c:1344
msgid "Commit Changes"
msgstr "Änderungen speichern"

#: ../web/swat.c:882 ../web/swat.c:989 ../web/swat.c:1346
msgid "Reset Values"
msgstr "Werte zurücksetzen"

#: ../web/swat.c:908
msgid "Share Parameters"
msgstr "Parameter der Freigabe"

#: ../web/swat.c:955
msgid "Choose Share"
msgstr "Wähle Freigabe"

#: ../web/swat.c:971
msgid "Delete Share"
msgstr "Lösche Freigabe"

#: ../web/swat.c:978
msgid "Create Share"
msgstr "Erstelle Freigabe"

#: ../web/swat.c:1014
msgid "password change in demo mode rejected"
msgstr "Änderung des Passworts im Demo-Modus nicht möglich"

#: ../web/swat.c:1028
msgid "Can't setup password database vectors."
msgstr "Kann Passwort-Datenbankvektoren nicht einrichten"

#: ../web/swat.c:1056
msgid " Must specify \"User Name\" "
msgstr " »Benutzername« muss angegeben werden "

#: ../web/swat.c:1072
msgid " Must specify \"Old Password\" "
msgstr " »Altes Passwort« muss angegeben werden "

#: ../web/swat.c:1078
msgid " Must specify \"Remote Machine\" "
msgstr " »Entfernter Server« muss angegeben werden "

#: ../web/swat.c:1085
msgid " Must specify \"New, and Re-typed Passwords\" "
msgstr " »Neues/wiederholtes Passwort« muss angegeben werden "

#: ../web/swat.c:1091
msgid " Re-typed password didn't match new password "
msgstr " Das wiederholte Passwort stimmt nicht mit dem neuen Passwort überein"

#: ../web/swat.c:1124
#, c-format
msgid " The passwd for '%s' has been changed."
msgstr " Das Passwort für '%s' wurde geändert."

#: ../web/swat.c:1127
#, c-format
msgid " The passwd for '%s' has NOT been changed."
msgstr " Das Passwort für '%s' wurde NICHT geändert."

#: ../web/swat.c:1152
msgid "Server Password Management"
msgstr "Verwaltung des Server-Passwortes"

#.
#. * Create all the dialog boxes for data collection
#.
#: ../web/swat.c:1161 ../web/swat.c:1208
msgid "User Name"
msgstr "Benutzername"

#: ../web/swat.c:1164 ../web/swat.c:1210
msgid "Old Password"
msgstr "Altes Passwort"

#: ../web/swat.c:1167 ../web/swat.c:1212
msgid "New Password"
msgstr "Neues Passwort"

#: ../web/swat.c:1169 ../web/swat.c:1214
msgid "Re-type New Password"
msgstr "Wiederhole neues Passwort"

#: ../web/swat.c:1177 ../web/swat.c:1225
msgid "Change Password"
msgstr "Ändere Passwort"

#: ../web/swat.c:1180
msgid "Add New User"
msgstr "Füge neuen Benutzer hinzu"

#: ../web/swat.c:1182
msgid "Delete User"
msgstr "Lösche Benutzer"

#: ../web/swat.c:1184
msgid "Disable User"
msgstr "Deaktiviere Benutzer"

#: ../web/swat.c:1186
msgid "Enable User"
msgstr "Aktiviere Benutzer"

#: ../web/swat.c:1199
msgid "Client/Server Password Management"
msgstr "Client/Server Passwort-Verwaltung"

#: ../web/swat.c:1216
msgid "Remote Machine"
msgstr "Entfernte Maschine"

#: ../web/swat.c:1255
msgid "Printer Parameters"
msgstr "Drucker-Parameter"

#: ../web/swat.c:1257
msgid "Important Note:"
msgstr "Wichtiger Hinweis:"

#: ../web/swat.c:1258
msgid "Printer names marked with [*] in the Choose Printer drop-down box "
msgstr "Mit [*] gekennzeichnete Drucker in der »Wähle Drucker«-Auswahlliste "

#: ../web/swat.c:1259
msgid "are autoloaded printers from "
msgstr "sind automatisch geladene Drucker aus "

#: ../web/swat.c:1260
msgid "Printcap Name"
msgstr "Printcap-Name"

#: ../web/swat.c:1261
msgid "Attempting to delete these printers from SWAT will have no effect."
msgstr "Der Versuch, diese Drucker von SWAT aus zu löschen, wird keine Auswirkung haben."

#: ../web/swat.c:1310
msgid "Choose Printer"
msgstr "Wähle Drucker"

#: ../web/swat.c:1329
msgid "Delete Printer"
msgstr "Lösche Drucker"

#: ../web/swat.c:1336
msgid "Create Printer"
msgstr "Erstelle Drucker"

#: ../web/statuspage.c:151
msgid "RDWR       "
msgstr "LESE/SCHREIBE "

#: ../web/statuspage.c:153
msgid "WRONLY     "
msgstr "NUR SCHREIBE  "

#: ../web/statuspage.c:155
msgid "RDONLY     "
msgstr "NUR LESE      "

#: ../web/statuspage.c:329
msgid "Server Status"
msgstr "Server-Status"

#: ../web/statuspage.c:334
msgid "Auto Refresh"
msgstr "Automatische Aktualisierung"

#: ../web/statuspage.c:335 ../web/statuspage.c:340
msgid "Refresh Interval: "
msgstr "Aktualisierungsintervall: "

#: ../web/statuspage.c:339
msgid "Stop Refreshing"
msgstr "Stoppe Aktualisierung"

#: ../web/statuspage.c:348
msgid "version:"
msgstr "Version:"

#: ../web/statuspage.c:351
msgid "smbd:"
msgstr "smbd:"

#: ../web/statuspage.c:351 ../web/statuspage.c:364 ../web/statuspage.c:378
msgid "running"
msgstr "aktiv"

#: ../web/statuspage.c:351 ../web/statuspage.c:364 ../web/statuspage.c:378
msgid "not running"
msgstr "inaktiv"

#: ../web/statuspage.c:355
msgid "Stop smbd"
msgstr "Stoppe smbd"

#: ../web/statuspage.c:357
msgid "Start smbd"
msgstr "Starte smbd"

#: ../web/statuspage.c:359
msgid "Restart smbd"
msgstr "Starte smbd neu"

#: ../web/statuspage.c:364
msgid "nmbd:"
msgstr "nmbd:"

#: ../web/statuspage.c:368
msgid "Stop nmbd"
msgstr "Stoppe nmbd"

#: ../web/statuspage.c:370
msgid "Start nmbd"
msgstr "Starte nmbd"

#: ../web/statuspage.c:372
msgid "Restart nmbd"
msgstr "Starte nmbd neu"

#: ../web/statuspage.c:378
msgid "winbindd:"
msgstr "winbindd:"

#: ../web/statuspage.c:382
msgid "Stop winbindd"
msgstr "Stoppe winbindd"

#: ../web/statuspage.c:384
msgid "Start winbindd"
msgstr "Starte winbindd"

#: ../web/statuspage.c:386
msgid "Restart winbindd"
msgstr "Starte winbindd neu"

#. stop, restart all
#: ../web/statuspage.c:395
msgid "Stop All"
msgstr "Alle Stoppen"

#: ../web/statuspage.c:396
msgid "Restart All"
msgstr "Alle neu starten"

#. start all
#: ../web/statuspage.c:400
msgid "Start All"
msgstr "Alle starten"

#: ../web/statuspage.c:407
msgid "Active Connections"
msgstr "Aktive Verbindungen"

#: ../web/statuspage.c:409 ../web/statuspage.c:422 ../web/statuspage.c:431
msgid "PID"
msgstr "PID"

#: ../web/statuspage.c:409 ../web/statuspage.c:422
msgid "Client"
msgstr "Client"

#: ../web/statuspage.c:409
msgid "IP address"
msgstr "IP-Adresse"

#: ../web/statuspage.c:409 ../web/statuspage.c:422 ../web/statuspage.c:431
msgid "Date"
msgstr "Datum"

#: ../web/statuspage.c:411
msgid "Kill"
msgstr "Töten"

#: ../web/statuspage.c:419
msgid "Active Shares"
msgstr "Aktive Freigaben"

#: ../web/statuspage.c:422
msgid "Share"
msgstr "Freigabe"

#: ../web/statuspage.c:422
msgid "User"
msgstr "Benutzer"

#: ../web/statuspage.c:422
msgid "Group"
msgstr "Gruppe"

#: ../web/statuspage.c:428
msgid "Open Files"
msgstr "Offene Dateien"

#: ../web/statuspage.c:431
#, fuzzy
msgid "UID"
msgstr "PID"

#: ../web/statuspage.c:431
msgid "Sharing"
msgstr "Freigeben"

#: ../web/statuspage.c:431
msgid "R/W"
msgstr "Lese/Schreibe"

#: ../web/statuspage.c:431
msgid "Oplock"
msgstr "Opportunistische Sperre (Lock)"

#: ../web/statuspage.c:431
msgid "File"
msgstr "Datei"

#: ../web/statuspage.c:438
msgid "Show Client in col 1"
msgstr "Zeige Client in Spalte 1"

#: ../web/statuspage.c:439
msgid "Show PID in col 1"
msgstr "Zeige PID in Spalte 1"

#: ../param/loadparm.c:907
msgid "Base Options"
msgstr "Basisoptionen"

#: ../param/loadparm.c:1047
msgid "Security Options"
msgstr "Sicherheitsoptionen"

#: ../param/loadparm.c:1800
msgid "Logging Options"
msgstr "Protokollier-Optionen"

#: ../param/loadparm.c:1929
msgid "Protocol Options"
msgstr "Protokoll-Optionen"

#: ../param/loadparm.c:2301
msgid "Tuning Options"
msgstr "Optimierungsoptionen"

#: ../param/loadparm.c:2538
msgid "Printing Options"
msgstr "Druckoptionen"

#: ../param/loadparm.c:2858
msgid "Filename Handling"
msgstr "Dateinamen-Verwaltung"

#: ../param/loadparm.c:3088
msgid "Domain Options"
msgstr "Domänen-Optionen"

#: ../param/loadparm.c:3100
msgid "Logon Options"
msgstr "Anmelde-Optionen"

#: ../param/loadparm.c:3273
msgid "Browse Options"
msgstr "Browsing-Optionen"

#: ../param/loadparm.c:3384
msgid "WINS Options"
msgstr "WINS-Optionen"

#: ../param/loadparm.c:3432
msgid "Locking Options"
msgstr "Locking-(Sperr-)Optionen"

#: ../param/loadparm.c:3552
msgid "Ldap Options"
msgstr "LDAP-Optionen"

#: ../param/loadparm.c:3708
msgid "EventLog Options"
msgstr "EventLog-Optionen"

#: ../param/loadparm.c:3720
msgid "Miscellaneous Options"
msgstr "Sonstige Optionen"

#: ../param/loadparm.c:4301
msgid "VFS module options"
msgstr "VFS-Modul-Optionen"

#: ../param/loadparm.c:4323
#, fuzzy
msgid "MSDFS options"
msgstr "VFS-Modul-Optionen"

#: ../param/loadparm.c:4353
msgid "Winbind options"
msgstr "Winbind-Optionen"

#: ../utils/net.c:103
msgid "Enter machine password: "
msgstr ""

#: ../utils/net.c:107
msgid "Unable to write the machine account password in the secrets database"
msgstr ""

#: ../utils/net.c:111
msgid "Modified trust account password in secrets database\n"
msgstr ""

#: ../utils/net.c:115
msgid ""
"Machine account password change requires the -f flag.\n"
"Do NOT use this function unless you know what it does!\n"
"This function will change the ADS Domain member machine account password in the secrets.tdb file!\n"
msgstr ""

#: ../utils/net.c:150 ../utils/net.c:228
#, c-format
msgid "Unable to open secrets.tdb.  Can't fetch domain SID for name: %s\n"
msgstr ""

#: ../utils/net.c:163 ../utils/net.c:251
#, c-format
msgid "SID for domain %s is: %s\n"
msgstr ""

#: ../utils/net.c:175
msgid "usage: net setlocalsid S-1-5-21-x-y-z\n"
msgstr ""

#: ../utils/net.c:195
msgid "usage: net setdomainsid S-1-5-21-x-y-z\n"
msgstr ""

#: ../utils/net.c:213
msgid "usage: net getdomainsid\n"
msgstr ""

#: ../utils/net.c:238
msgid "Could not fetch local SID\n"
msgstr ""

#: ../utils/net.c:242
#, c-format
msgid "SID for local machine %s is: %s\n"
msgstr ""

#: ../utils/net.c:246
msgid "Could not fetch domain SID\n"
msgstr ""

#: ../utils/net.c:263
#, c-format
msgid "get_maxrid: Could not search %s\n"
msgstr ""

#: ../utils/net.c:297
msgid "usage: net maxrid\n"
msgstr ""

#: ../utils/net.c:302
msgid "can't get current maximum rid\n"
msgstr ""

#: ../utils/net.c:306
#, c-format
msgid "Currently used maximum rid: %d\n"
msgstr ""

#: ../utils/net.c:317
msgid "Run functions using RPC transport"
msgstr ""

#: ../utils/net.c:318
msgid "  Use 'net help rpc' to get more extensive information about 'net rpc' commands."
msgstr ""

#: ../utils/net.c:325
msgid "Run functions using RAP transport"
msgstr ""

#: ../utils/net.c:326
msgid "  Use 'net help rap' to get more extensive information about 'net rap' commands."
msgstr ""

#: ../utils/net.c:333
msgid "Run functions using ADS transport"
msgstr ""

#: ../utils/net.c:334
msgid "  Use 'net help ads' to get more extensive information about 'net ads' commands."
msgstr ""

#: ../utils/net.c:343
msgid "Functions on remote opened files"
msgstr ""

#: ../utils/net.c:344
msgid "  Use 'net help file' to get more information about 'net file' commands."
msgstr ""

#: ../utils/net.c:351
msgid "Functions on shares"
msgstr ""

#: ../utils/net.c:352
msgid "  Use 'net help share' to get more information about 'net share' commands."
msgstr ""

#: ../utils/net.c:359
msgid "Manage sessions"
msgstr ""

#: ../utils/net.c:360
msgid "  Use 'net help session' to get more information about 'net session' commands."
msgstr ""

#: ../utils/net.c:367
msgid "List servers in workgroup"
msgstr ""

#: ../utils/net.c:368
msgid "  Use 'net help server' to get more information about 'net server' commands."
msgstr ""

#: ../utils/net.c:375
msgid "List domains/workgroups on network"
msgstr ""

#: ../utils/net.c:376
msgid "  Use 'net help domain' to get more information about 'net domain' commands."
msgstr ""

#: ../utils/net.c:383
msgid "Modify printer queue"
msgstr ""

#: ../utils/net.c:384
msgid "  Use 'net help printq' to get more information about 'net printq' commands."
msgstr ""

#: ../utils/net.c:391
#, fuzzy
msgid "Manage users"
msgstr "Aktiviere Benutzer"

#: ../utils/net.c:392
msgid "  Use 'net help user' to get more information about 'net user' commands."
msgstr ""

#: ../utils/net.c:399
msgid "Manage groups"
msgstr ""

#: ../utils/net.c:400
msgid "  Use 'net help group' to get more information about 'net group' commands."
msgstr ""

#: ../utils/net.c:407
msgid "Manage group mappings"
msgstr ""

#: ../utils/net.c:408
msgid "  Use 'net help groupmap' to get more information about 'net groupmap' commands."
msgstr ""

#: ../utils/net.c:415
msgid "Functions on the SAM database"
msgstr ""

#: ../utils/net.c:416
msgid "  Use 'net help sam' to get more information about 'net sam' commands."
msgstr ""

#: ../utils/net.c:423
msgid "Validate username and password"
msgstr ""

#: ../utils/net.c:424
msgid "  Use 'net help validate' to get more information about 'net validate' commands."
msgstr ""

#: ../utils/net.c:431
msgid "Modify group memberships"
msgstr ""

#: ../utils/net.c:432
msgid "  Use 'net help groupmember' to get more information about 'net groupmember' commands."
msgstr ""

#: ../utils/net.c:438
msgid "Execute remote command on a remote OS/2 server"
msgstr ""

#: ../utils/net.c:439
msgid "  Use 'net help admin' to get more information about 'net admin' commands."
msgstr ""

#: ../utils/net.c:445
msgid "List/modify running services"
msgstr ""

#: ../utils/net.c:446
msgid "  Use 'net help service' to get more information about 'net service' commands."
msgstr ""

#: ../utils/net.c:453
#, fuzzy
msgid "Change user password on target server"
msgstr "Kann Passwort-Datenbankvektoren nicht einrichten"

#: ../utils/net.c:454
msgid "  Use 'net help password' to get more information about 'net password' commands."
msgstr ""

#: ../utils/net.c:460
#, fuzzy
msgid "Change the trust password"
msgstr "Ändere Passwort"

#: ../utils/net.c:461
msgid "  Use 'net help changetrustpw' to get more information about 'net changetrustpw'."
msgstr ""

#: ../utils/net.c:467
#, fuzzy
msgid "Change the secret password"
msgstr "Ändere Passwort"

#: ../utils/net.c:468
msgid ""
"  net [options] changesecretpw\n"
"    Change the ADS domain member machine account password in secrets.tdb.\n"
"    Do NOT use this function unless you know what it does.\n"
"    Requires the -f flag to work."
msgstr ""

#: ../utils/net.c:477
msgid "Show/set time"
msgstr ""

#: ../utils/net.c:478
msgid "  Use 'net help time' to get more information about 'net time' commands."
msgstr ""

#: ../utils/net.c:484
msgid "Look up host names/IP addresses"
msgstr ""

#: ../utils/net.c:485
msgid "  Use 'net help lookup' to get more information about 'net lookup' commands."
msgstr ""

#: ../utils/net.c:491
msgid "Join a domain/AD"
msgstr ""

#: ../utils/net.c:492
msgid "  Use 'net help join' to get more information about 'net join'."
msgstr ""

#: ../utils/net.c:498
msgid "Join/unjoin (remote) machines to/from a domain/AD"
msgstr ""

#: ../utils/net.c:499
msgid "  Use 'net help dom' to get more information about 'net dom' commands."
msgstr ""

#: ../utils/net.c:505
msgid "Operate on the cache tdb file"
msgstr ""

#: ../utils/net.c:506
msgid "  Use 'net help cache' to get more information about 'net cache' commands."
msgstr ""

#: ../utils/net.c:512
msgid "Get the SID for the local domain"
msgstr ""

#: ../utils/net.c:513
msgid "  net getlocalsid"
msgstr ""

#: ../utils/net.c:518
msgid "Set the SID for the local domain"
msgstr ""

#: ../utils/net.c:519
msgid "  net setlocalsid S-1-5-21-x-y-z"
msgstr ""

#: ../utils/net.c:524
msgid "Set domain SID on member servers"
msgstr ""

#: ../utils/net.c:525
msgid "  net setdomainsid S-1-5-21-x-y-z"
msgstr ""

#: ../utils/net.c:530
msgid "Get domain SID on member servers"
msgstr ""

#: ../utils/net.c:531
msgid "  net getdomainsid"
msgstr ""

#: ../utils/net.c:536
msgid "Display the maximul RID currently used"
msgstr ""

#: ../utils/net.c:537
msgid "  net maxrid"
msgstr ""

#: ../utils/net.c:542
#, fuzzy
msgid "IDmap functions"
msgstr "Domänen-Optionen"

#: ../utils/net.c:543
msgid "  Use 'net help idmap to get more information about 'net idmap' commands."
msgstr ""

#: ../utils/net.c:549
#, fuzzy
msgid "Display server status"
msgstr "Server-Status"

#: ../utils/net.c:550
msgid "  Use 'net help status' to get more information about 'net status' commands."
msgstr ""

#: ../utils/net.c:556
msgid "Manage user-modifiable shares"
msgstr ""

#: ../utils/net.c:557
msgid "  Use 'net help usershare to get more information about 'net usershare' commands."
msgstr ""

#: ../utils/net.c:563
msgid "Display list of all users with SID"
msgstr ""

#: ../utils/net.c:564
msgid "  Use 'net help usersidlist' to get more information about 'net usersidlist'."
msgstr ""

#: ../utils/net.c:570
msgid "Manage Samba registry based configuration"
msgstr ""

#: ../utils/net.c:571
msgid "  Use 'net help conf' to get more information about 'net conf' commands."
msgstr ""

#: ../utils/net.c:577
msgid "Manage the Samba registry"
msgstr ""

#: ../utils/net.c:578
msgid "  Use 'net help registry' to get more information about 'net registry' commands."
msgstr ""

#: ../utils/net.c:584
msgid "Open a lua interpreter"
msgstr ""

#: ../utils/net.c:585
msgid "  Use 'net help lua' to get more information about 'net lua' commands."
msgstr ""

#: ../utils/net.c:591
msgid "Process Win32 *.evt eventlog files"
msgstr ""

#: ../utils/net.c:592
msgid "  Use 'net help eventlog' to get more information about 'net eventlog' commands."
msgstr ""

#: ../utils/net.c:600
msgid "Manage AFS tokens"
msgstr ""

#: ../utils/net.c:601
msgid "  Use 'net help afs' to get more information about 'net afs' commands."
msgstr ""

#: ../utils/net.c:609
msgid "Print usage information"
msgstr ""

#: ../utils/net.c:610
msgid "  Use 'net help help' to list usage information for 'net' commands."
msgstr ""

#: ../utils/net.c:639
msgid "Encrypt SMB transport (UNIX extended servers only)"
msgstr ""

#: ../utils/net.c:703
msgid ""
"\n"
"Invalid ip address specified\n"
msgstr ""

#: ../utils/net.c:718
#, c-format
msgid ""
"\n"
"Invalid option %s: %s\n"
msgstr ""

#: ../utils/net_ads.c:52 ../utils/net_ads.c:392
msgid "CLDAP query failed!\n"
msgstr ""

#: ../utils/net_ads.c:56
#, fuzzy, c-format
msgid ""
"Information for Domain Controller: %s\n"
"\n"
msgstr "Domänencontroller"

#: ../utils/net_ads.c:59
msgid "Response Type: "
msgstr ""

#: ../utils/net_ads.c:72
#, c-format
msgid "GUID: %s\n"
msgstr ""

#: ../utils/net_ads.c:74
#, c-format
msgid ""
"Flags:\n"
"\tIs a PDC:                                   %s\n"
"\tIs a GC of the forest:                      %s\n"
"\tIs an LDAP server:                          %s\n"
"\tSupports DS:                                %s\n"
"\tIs running a KDC:                           %s\n"
"\tIs running time services:                   %s\n"
"\tIs the closest DC:                          %s\n"
"\tIs writable:                                %s\n"
"\tHas a hardware clock:                       %s\n"
"\tIs a non-domain NC serviced by LDAP server: %s\n"
"\tIs NT6 DC that has some secrets:            %s\n"
"\tIs NT6 DC that has all secrets:             %s\n"
msgstr ""

#: ../utils/net_ads.c:87 ../utils/net_ads.c:88 ../utils/net_ads.c:89 ../utils/net_ads.c:90 ../utils/net_ads.c:91 ../utils/net_ads.c:92 ../utils/net_ads.c:93 ../utils/net_ads.c:94 ../utils/net_ads.c:95 ../utils/net_ads.c:96 ../utils/net_ads.c:97
#: ../utils/net_ads.c:98
msgid "yes"
msgstr ""

#: ../utils/net_ads.c:87 ../utils/net_ads.c:88 ../utils/net_ads.c:89 ../utils/net_ads.c:90 ../utils/net_ads.c:91 ../utils/net_ads.c:92 ../utils/net_ads.c:93 ../utils/net_ads.c:94 ../utils/net_ads.c:95 ../utils/net_ads.c:96 ../utils/net_ads.c:97
#: ../utils/net_ads.c:98
msgid "no"
msgstr ""

#: ../utils/net_ads.c:101
#, c-format
msgid "Forest:\t\t\t%s\n"
msgstr ""

#: ../utils/net_ads.c:102
#, c-format
msgid "Domain:\t\t\t%s\n"
msgstr ""

#: ../utils/net_ads.c:103
#, fuzzy, c-format
msgid "Domain Controller:\t%s\n"
msgstr "Domänencontroller"

#: ../utils/net_ads.c:105
#, c-format
msgid "Pre-Win2k Domain:\t%s\n"
msgstr ""

#: ../utils/net_ads.c:106
#, c-format
msgid "Pre-Win2k Hostname:\t%s\n"
msgstr ""

#: ../utils/net_ads.c:108
#, fuzzy, c-format
msgid "User name:\t%s\n"
msgstr "Benutzername"

#: ../utils/net_ads.c:110
#, fuzzy, c-format
msgid "Server Site Name :\t\t%s\n"
msgstr "Server-Status"

#: ../utils/net_ads.c:111
#, c-format
msgid "Client Site Name :\t\t%s\n"
msgstr ""

#: ../utils/net_ads.c:113
#, fuzzy, c-format
msgid "NT Version: %d\n"
msgstr "Version:"

#: ../utils/net_ads.c:114
#, c-format
msgid "LMNT Token: %.2x\n"
msgstr ""

#: ../utils/net_ads.c:115
#, c-format
msgid "LM20 Token: %.2x\n"
msgstr ""

#: ../utils/net_ads.c:130
msgid ""
"Usage:\n"
"net ads lookup\n"
"    Find the ADS DC using CLDAP lookup.\n"
msgstr ""

#: ../utils/net_ads.c:137 ../utils/net_ads.c:381
msgid "Didn't find the cldap server!\n"
msgstr ""

#: ../utils/net_ads.c:160
msgid ""
"Usage:\n"
"net ads info\n"
"    Display information about an Active Directory server.\n"
msgstr ""

#: ../utils/net_ads.c:168 ../utils/net_ads.c:173
msgid "Didn't find the ldap server!\n"
msgstr ""

#: ../utils/net_ads.c:182
msgid "Failed to get server's current time!\n"
msgstr ""

#: ../utils/net_ads.c:187
#, c-format
msgid "LDAP server: %s\n"
msgstr ""

#: ../utils/net_ads.c:188
#, c-format
msgid "LDAP server name: %s\n"
msgstr ""

#: ../utils/net_ads.c:189
#, c-format
msgid "Realm: %s\n"
msgstr ""

#: ../utils/net_ads.c:190
#, c-format
msgid "Bind Path: %s\n"
msgstr ""

#: ../utils/net_ads.c:191
#, c-format
msgid "LDAP port: %d\n"
msgstr ""

#: ../utils/net_ads.c:192
#, fuzzy, c-format
msgid "Server time: %s\n"
msgstr "Server-Status"

#: ../utils/net_ads.c:195
#, c-format
msgid "KDC server: %s\n"
msgstr ""

#: ../utils/net_ads.c:196
#, c-format
msgid "Server time offset: %d\n"
msgstr ""

#: ../utils/net_ads.c:374
msgid ""
"Usage:\n"
"net ads workgroup\n"
"    Print the workgroup name\n"
msgstr ""

#: ../utils/net_ads.c:397
#, c-format
msgid "Workgroup: %s\n"
msgstr ""

#: ../utils/net_ads.c:458
#, c-format
msgid "ads_user_add: %s\n"
msgstr ""

#: ../utils/net_ads.c:463
#, c-format
msgid "ads_user_add: User %s already exists\n"
msgstr ""

#: ../utils/net_ads.c:477
#, c-format
msgid "Could not add user %s: %s\n"
msgstr ""

#: ../utils/net_ads.c:484 ../utils/net_ads.c:497
#, fuzzy, c-format
msgid "User %s added\n"
msgstr "Benutzername"

#. password didn't set, delete account
#: ../utils/net_ads.c:503
#, c-format
msgid "Could not add user %s. Error setting password %s\n"
msgstr ""

#: ../utils/net_ads.c:551
#, c-format
msgid "ads_user_info: failed to escape user %s\n"
msgstr ""

#: ../utils/net_ads.c:569
#, c-format
msgid "ads_search: %s\n"
msgstr ""

#: ../utils/net_ads.c:575
msgid "ads_pull_uint32 failed\n"
msgstr ""

#: ../utils/net_ads.c:582
#, c-format
msgid "ads_domain_sid: %s\n"
msgstr ""

#: ../utils/net_ads.c:642
#, c-format
msgid "User %s does not exist.\n"
msgstr ""

#: ../utils/net_ads.c:652
#, c-format
msgid "User %s deleted\n"
msgstr ""

#: ../utils/net_ads.c:656
#, c-format
msgid "Error deleting user %s: %s\n"
msgstr ""

#: ../utils/net_ads.c:669
#, fuzzy
msgid "Add an AD user"
msgstr "Füge neuen Benutzer hinzu"

#: ../utils/net_ads.c:670
msgid ""
"net ads user add\n"
"    Add an AD user"
msgstr ""

#: ../utils/net_ads.c:677
msgid "Display information about an AD user"
msgstr ""

#: ../utils/net_ads.c:678
msgid ""
"net ads user info\n"
"    Display information about an AD user"
msgstr ""

#: ../utils/net_ads.c:685
#, fuzzy
msgid "Delete an AD user"
msgstr "Lösche Benutzer"

#: ../utils/net_ads.c:686
msgid ""
"net ads user delete\n"
"    Delete an AD user"
msgstr ""

#: ../utils/net_ads.c:699
msgid ""
"Usage:\n"
"net ads user\n"
"    List AD users\n"
msgstr ""

#: ../utils/net_ads.c:711
msgid ""
"\n"
"User name             Comment\n"
"-----------------------------\n"
msgstr ""

#: ../utils/net_ads.c:751
#, c-format
msgid "ads_group_add: %s\n"
msgstr ""

#: ../utils/net_ads.c:756
#, c-format
msgid "ads_group_add: Group %s already exists\n"
msgstr ""

#: ../utils/net_ads.c:769
#, c-format
msgid "Group %s added\n"
msgstr ""

#: ../utils/net_ads.c:772
#, c-format
msgid "Could not add group %s: %s\n"
msgstr ""

#: ../utils/net_ads.c:801
#, c-format
msgid "Group %s does not exist.\n"
msgstr ""

#: ../utils/net_ads.c:811
#, c-format
msgid "Group %s deleted\n"
msgstr ""

#: ../utils/net_ads.c:815
#, c-format
msgid "Error deleting group %s: %s\n"
msgstr ""

#: ../utils/net_ads.c:828
msgid "Add an AD group"
msgstr ""

#: ../utils/net_ads.c:829
msgid ""
"net ads group add\n"
"    Add an AD group"
msgstr ""

#: ../utils/net_ads.c:836
#, fuzzy
msgid "Delete an AD group"
msgstr "Lösche Freigabe"

#: ../utils/net_ads.c:837
msgid ""
"net ads group delete\n"
"    Delete an AD group"
msgstr ""

#: ../utils/net_ads.c:850
msgid ""
"Usage:\n"
"net ads group\n"
"    List AD groups\n"
msgstr ""

#: ../utils/net_ads.c:862
msgid ""
"\n"
"Group name            Comment\n"
"-----------------------------\n"
msgstr ""

#: ../utils/net_ads.c:884
msgid ""
"Usage:\n"
"net ads status\n"
"    Display machine account details\n"
msgstr ""

#: ../utils/net_ads.c:896
#, c-format
msgid "ads_find_machine_acct: %s\n"
msgstr ""

#: ../utils/net_ads.c:902
#, c-format
msgid "No machine account for '%s' found\n"
msgstr ""

#: ../utils/net_ads.c:926
msgid ""
"Usage:\n"
"net ads leave\n"
"    Leave an AD domain\n"
msgstr ""

#: ../utils/net_ads.c:933
msgid "No realm set, are we joined ?\n"
msgstr ""

#: ../utils/net_ads.c:938 ../utils/net_ads.c:1260
msgid "Could not initialise talloc context.\n"
msgstr ""

#: ../utils/net_ads.c:948
msgid "Could not initialise unjoin context.\n"
msgstr ""

#: ../utils/net_ads.c:968
#, c-format
msgid "Failed to leave domain: %s\n"
msgstr ""

#: ../utils/net_ads.c:975
#, c-format
msgid "Deleted account for '%s' in realm '%s'\n"
msgstr ""

#: ../utils/net_ads.c:982
#, c-format
msgid "Disabled account for '%s' in realm '%s'\n"
msgstr ""

#. Based on what we requseted, we shouldn't get here, but if
#. we did, it means the secrets were removed, and therefore
#. we have left the domain
#: ../utils/net_ads.c:991
#, c-format
msgid "Machine '%s' Left domain '%s'\n"
msgstr ""

#: ../utils/net_ads.c:1035
msgid ""
"Usage:\n"
"net ads testjoin\n"
"    Test if the existing join is ok\n"
msgstr ""

#: ../utils/net_ads.c:1044
#, c-format
msgid "Join to domain is not valid: %s\n"
msgstr ""

#: ../utils/net_ads.c:1049
#, c-format
msgid "Join is OK\n"
msgstr ""

#: ../utils/net_ads.c:1060
msgid "Host is not configured as a member server.\n"
msgstr ""

#: ../utils/net_ads.c:1065
#, c-format
msgid "Our netbios name can be at most 15 chars long, \"%s\" is %u chars long\n"
msgstr ""

#: ../utils/net_ads.c:1072
#, c-format
msgid "realm must be set in in %s for ADS join to succeed.\n"
msgstr ""

#: ../utils/net_ads.c:1105
#, c-format
msgid "No DNS domain configured for %s. Unable to perform DNS Update.\n"
msgstr ""

#: ../utils/net_ads.c:1212
msgid ""
"net ads join [options]\n"
"Valid options:\n"
msgstr ""

#: ../utils/net_ads.c:1214
msgid ""
"   createupn[=UPN]    Set the userPrincipalName attribute during the join.\n"
"                      The deault UPN is in the form host/netbiosname@REALM.\n"
msgstr ""

#: ../utils/net_ads.c:1216
msgid ""
"   createcomputer=OU  Precreate the computer account in a specific OU.\n"
"                      The OU string read from top to bottom without RDNs and delimited by a '/'.\n"
"                      E.g. \"createcomputer=Computers/Servers/Unix\"\n"
"                      NB: A backslash '\\' is used as escape at multiple levels and may\n"
"                          need to be doubled or even quadrupled.  It is not used as a separator.\n"
msgstr ""

#: ../utils/net_ads.c:1221
msgid "   osName=string      Set the operatingSystem attribute during the join.\n"
msgstr ""

#: ../utils/net_ads.c:1222
msgid ""
"   osVer=string       Set the operatingSystemVersion attribute during the join.\n"
"                      NB: osName and osVer must be specified together for either to take effect.\n"
"                          Also, the operatingSystemService attribute is also set when along with\n"
"                          the two other attributes.\n"
msgstr ""

#: ../utils/net_ads.c:1254
msgid "Invalid configuration.  Exiting....\n"
msgstr ""

#: ../utils/net_ads.c:1283
msgid "Please supply a valid OU path.\n"
msgstr ""

#: ../utils/net_ads.c:1290
msgid "Please supply a operating system name.\n"
msgstr ""

#: ../utils/net_ads.c:1297
msgid "Please supply a valid operating system version.\n"
msgstr ""

#: ../utils/net_ads.c:1308
msgid "Please supply a valid domain name\n"
msgstr ""

#: ../utils/net_ads.c:1339
#, c-format
msgid ""
"The workgroup in %s does not match the short\n"
"domain name obtained from the server.\n"
"Using the name [%s] from the server.\n"
"You should set \"workgroup = %s\" in %s.\n"
msgstr ""

#: ../utils/net_ads.c:1347
#, c-format
msgid "Using short domain name -- %s\n"
msgstr ""

#: ../utils/net_ads.c:1350
#, c-format
msgid "Joined '%s' to realm '%s'\n"
msgstr ""

#: ../utils/net_ads.c:1353
#, c-format
msgid "Joined '%s' to domain '%s'\n"
msgstr ""

#: ../utils/net_ads.c:1377 ../utils/net_ads.c:1433
msgid "DNS update failed!\n"
msgstr ""

#. issue an overall failure message at the end.
#: ../utils/net_ads.c:1391 ../utils/net_dom.c:198
#, c-format
msgid "Failed to join domain: %s\n"
msgstr ""

#: ../utils/net_ads.c:1414
msgid ""
"Usage:\n"
"net ads dns register\n"
"    Register hostname with DNS\n"
msgstr ""

#: ../utils/net_ads.c:1421
msgid "Could not initialise talloc context\n"
msgstr ""

#: ../utils/net_ads.c:1439
msgid "Successfully registered hostname with DNS\n"
msgstr ""

#: ../utils/net_ads.c:1447
msgid "DNS update support not enabled at compile time!\n"
msgstr ""

#: ../utils/net_ads.c:1466
msgid ""
"Usage:\n"
"net ads dns gethostbyname <server> <name>\n"
"  Look up hostname from the AD\n"
"    server\tName server to use\n"
"    name\tName to look up\n"
msgstr ""

#: ../utils/net_ads.c:1476
#, c-format
msgid "do_gethostbyname returned %d\n"
msgstr ""

#: ../utils/net_ads.c:1488
msgid "Add host dns entry to AD"
msgstr ""

#: ../utils/net_ads.c:1489
msgid ""
"net ads dns register\n"
"    Add host dns entry to AD"
msgstr ""

#: ../utils/net_ads.c:1496
msgid "Look up host"
msgstr ""

#: ../utils/net_ads.c:1497
msgid ""
"net ads dns gethostbyname\n"
"    Look up host"
msgstr ""

#: ../utils/net_ads.c:1512
msgid ""
"\n"
"net ads printer search <printer>\n"
"\tsearch for a printer in the directory\n"
"\n"
"net ads printer info <printer> <server>\n"
"\tlookup info in directory for printer on server\n"
"\t(note: printer defaults to \"*\", server defaults to local)\n"
"\n"
"net ads printer publish <printername>\n"
"\tpublish printer in directory\n"
"\t(note: printer name is required)\n"
"\n"
"net ads printer remove <printername>\n"
"\tremove printer from directory\n"
"\t(note: printer name is required)\n"
msgstr ""

#: ../utils/net_ads.c:1536
msgid ""
"Usage:\n"
"net ads printer search\n"
"    List printers in the AD\n"
msgstr ""

#: ../utils/net_ads.c:1549
#, c-format
msgid "ads_find_printer: %s\n"
msgstr ""

#: ../utils/net_ads.c:1556
msgid "No results found\n"
msgstr ""

#: ../utils/net_ads.c:1576
msgid ""
"Usage:\n"
"net ads printer info [printername [servername]]\n"
"  Display printer info from AD\n"
"    printername\tPrinter name or wildcard\n"
"    servername\tName of the print server\n"
msgstr ""

#: ../utils/net_ads.c:1603
#, c-format
msgid "Server '%s' not found: %s\n"
msgstr ""

#: ../utils/net_ads.c:1611 ../utils/net_ads.c:1794
#, c-format
msgid "Printer '%s' not found\n"
msgstr ""

#: ../utils/net_ads.c:1640
msgid ""
"Usage:\n"
"net ads printer publish <printername> [servername]\n"
"  Publish printer in AD\n"
"    printername\tName of the printer\n"
"    servername\tName of the print server\n"
msgstr ""

#: ../utils/net_ads.c:1675
#, c-format
msgid "Unable to open a connnection to %s to obtain data for %s\n"
msgstr ""

#: ../utils/net_ads.c:1688
#, c-format
msgid "Could not find machine account for server %s\n"
msgstr ""

#: ../utils/net_ads.c:1704 ../utils/net_ads.c:1713
msgid "Internal error, out of memory!"
msgstr ""

#: ../utils/net_ads.c:1724
#, c-format
msgid "Unable to open a connnection to the spoolss pipe on %s\n"
msgstr ""

#: ../utils/net_ads.c:1766
msgid ""
"Usage:\n"
"net ads printer remove <printername> [servername]\n"
"  Remove a printer from the AD\n"
"    printername\tName of the printer\n"
"    servername\tName of the print server\n"
msgstr ""

#: ../utils/net_ads.c:1787
#, c-format
msgid "ads_find_printer_on_server: %s\n"
msgstr ""

#: ../utils/net_ads.c:1806
#, c-format
msgid "ads_del_dn: %s\n"
msgstr ""

#: ../utils/net_ads.c:1822
msgid "Search for a printer"
msgstr ""

#: ../utils/net_ads.c:1823
msgid ""
"net ads printer search\n"
"    Search for a printer"
msgstr ""

#: ../utils/net_ads.c:1830
msgid "Display printer information"
msgstr ""

#: ../utils/net_ads.c:1831
msgid ""
"net ads printer info\n"
"    Display printer information"
msgstr ""

#: ../utils/net_ads.c:1838
msgid "Publish a printer"
msgstr ""

#: ../utils/net_ads.c:1839
msgid ""
"net ads printer publish\n"
"    Publish a printer"
msgstr ""

#: ../utils/net_ads.c:1846
#, fuzzy
msgid "Delete a printer"
msgstr "Lösche Drucker"

#: ../utils/net_ads.c:1847
msgid ""
"net ads printer remove\n"
"    Delete a printer"
msgstr ""

#: ../utils/net_ads.c:1869
msgid ""
"Usage:\n"
"net ads password <username>\n"
"  Change password for user\n"
"    username\tName of user to change password for\n"
msgstr ""

#: ../utils/net_ads.c:1877
msgid "You must supply an administrator username/password\n"
msgstr ""

#: ../utils/net_ads.c:1883
msgid "ERROR: You must say which username to change password for\n"
msgstr ""

#: ../utils/net_ads.c:1915
msgid "Didn't find the kerberos server!\n"
msgstr ""

#: ../utils/net_ads.c:1923
#, c-format
msgid "Enter new password for %s:"
msgstr ""

#: ../utils/net_ads.c:1933 ../utils/net_ads.c:1982
#, fuzzy, c-format
msgid "Password change failed: %s\n"
msgstr "Passwortverwaltung"

#: ../utils/net_ads.c:1938
#, fuzzy, c-format
msgid "Password change for %s completed.\n"
msgstr "Änderung des Passworts im Demo-Modus nicht möglich"

#: ../utils/net_ads.c:1952
msgid ""
"Usage:\n"
"net ads changetrustpw\n"
"    Change the machine account's trust password\n"
msgstr ""

#: ../utils/net_ads.c:1977
#, c-format
msgid "Changing password for principal: %s\n"
msgstr ""

#: ../utils/net_ads.c:1988
#, c-format
msgid "Password change for principal %s succeeded.\n"
msgstr ""

#: ../utils/net_ads.c:1991
msgid "Attempting to update system keytab with new password.\n"
msgstr ""

#: ../utils/net_ads.c:1993
msgid "Failed to update system keytab.\n"
msgstr ""

#: ../utils/net_ads.c:2009
msgid ""
"\n"
"net ads search <expression> <attributes...>\n"
"\n"
"Perform a raw LDAP search on a ADS server and dump the results.\n"
"The expression is a standard LDAP search expression, and the\n"
"attributes are a list of LDAP fields to show in the results.\n"
"\n"
"Example: net ads search '(objectCategory=group)' sAMAccountName\n"
"\n"
msgstr ""

#: ../utils/net_ads.c:2046 ../utils/net_ads.c:2107 ../utils/net_ads.c:2171 ../utils/net_ads_gpo.c:250
#, c-format
msgid "search failed: %s\n"
msgstr ""

#: ../utils/net_ads.c:2051 ../utils/net_ads.c:2176 ../utils/net_ads_gpo.c:256
#, c-format
msgid ""
"Got %d replies\n"
"\n"
msgstr ""

#: ../utils/net_ads.c:2069
msgid ""
"\n"
"net ads dn <dn> <attributes...>\n"
"\n"
"perform a raw LDAP search on a ADS server and dump the results\n"
"The DN standard LDAP DN, and the attributes are a list of LDAP fields \n"
"to show in the results\n"
"\n"
"Example: net ads dn 'CN=administrator,CN=Users,DC=my,DC=domain' sAMAccountName\n"
"\n"
"Note: the DN must be provided properly escaped. See RFC 4514 for details\n"
"\n"
msgstr ""

#: ../utils/net_ads.c:2129
msgid ""
"\n"
"net ads sid <sid> <attributes...>\n"
"\n"
"perform a raw LDAP search on a ADS server and dump the results\n"
"The SID is in string format, and the attributes are a list of LDAP fields \n"
"to show in the results\n"
"\n"
"Example: net ads sid 'S-1-5-32' distinguishedName\n"
"\n"
msgstr ""

#: ../utils/net_ads.c:2164
msgid "could not convert sid\n"
msgstr ""

#: ../utils/net_ads.c:2193
msgid ""
"Usage:\n"
"net ads keytab flush\n"
"    Delete the whole keytab\n"
msgstr ""

#: ../utils/net_ads.c:2214
msgid ""
"Usage:\n"
"net ads keytab add <principal> [principal ...]\n"
"  Add principals to local keytab\n"
"    principal\tKerberos principal to add to keytab\n"
msgstr ""

#: ../utils/net_ads.c:2222
msgid "Processing principals to add...\n"
msgstr ""

#: ../utils/net_ads.c:2239
msgid ""
"Usage:\n"
"net ads keytab create\n"
"    Create new default keytab\n"
msgstr ""

#: ../utils/net_ads.c:2258
msgid ""
"Usage:\n"
"net ads keytab list [keytab]\n"
"  List a local keytab\n"
"    keytab\tKeytab to list\n"
msgstr ""

#: ../utils/net_ads.c:2280
msgid "Add a service principal"
msgstr ""

#: ../utils/net_ads.c:2281
msgid ""
"net ads keytab add\n"
"    Add a service principal"
msgstr ""

#: ../utils/net_ads.c:2288
#, fuzzy
msgid "Create a fresh keytab"
msgstr "Erstelle Freigabe"

#: ../utils/net_ads.c:2289
msgid ""
"net ads keytab create\n"
"    Create a fresh keytab"
msgstr ""

#: ../utils/net_ads.c:2296
msgid "Remove all keytab entries"
msgstr ""

#: ../utils/net_ads.c:2297
msgid ""
"net ads keytab flush\n"
"    Remove all keytab entries"
msgstr ""

#: ../utils/net_ads.c:2304
msgid "List a keytab"
msgstr ""

#: ../utils/net_ads.c:2305
msgid ""
"net ads keytab list\n"
"    List a keytab"
msgstr ""

#: ../utils/net_ads.c:2312
msgid ""
"\n"
"Warning: \"kerberos method\" must be set to a keytab method to use keytab functions.\n"
msgstr ""

#: ../utils/net_ads.c:2324
msgid ""
"Usage:\n"
"net ads kerberos renew\n"
"    Renew TGT from existing credential cache\n"
msgstr ""

#: ../utils/net_ads.c:2332
#, c-format
msgid "failed to renew kerberos ticket: %s\n"
msgstr ""

#: ../utils/net_ads.c:2347
msgid ""
"Usage:\n"
"net ads kerberos pac\n"
"    Dump the Kerberos PAC\n"
msgstr ""

#: ../utils/net_ads.c:2372
#, c-format
msgid "failed to query kerberos PAC: %s\n"
msgstr ""

#: ../utils/net_ads.c:2381
#, c-format
msgid "The Pac: %s\n"
msgstr ""

#: ../utils/net_ads.c:2397
msgid ""
"Usage:\n"
"net ads kerberos kinit\n"
"    Get Ticket Granting Ticket (TGT) for the user\n"
msgstr ""

#: ../utils/net_ads.c:2421
#, c-format
msgid "failed to kinit password: %s\n"
msgstr ""

#: ../utils/net_ads.c:2435
msgid "Retrieve Ticket Granting Ticket (TGT)"
msgstr ""

#: ../utils/net_ads.c:2436
msgid ""
"net ads kerberos kinit\n"
"    Receive Ticket Granting Ticket (TGT)"
msgstr ""

#: ../utils/net_ads.c:2443
msgid "Renew Ticket Granting Ticket from credential cache"
msgstr ""

#: ../utils/net_ads.c:2444
msgid ""
"net ads kerberos renew\n"
"    Renew Ticket Granting Ticket (TGT) from credential cache"
msgstr ""

#: ../utils/net_ads.c:2452
msgid "Dump Kerberos PAC"
msgstr ""

#: ../utils/net_ads.c:2453
msgid ""
"net ads kerberos pac\n"
"    Dump Kerberos PAC"
msgstr ""

#: ../utils/net_ads.c:2469
msgid "Display details on remote ADS server"
msgstr ""

#: ../utils/net_ads.c:2470
msgid ""
"net ads info\n"
"    Display details on remote ADS server"
msgstr ""

#: ../utils/net_ads.c:2477
msgid "Join the local machine to ADS realm"
msgstr ""

#: ../utils/net_ads.c:2478
msgid ""
"net ads join\n"
"    Join the local machine to ADS realm"
msgstr ""

#: ../utils/net_ads.c:2485
msgid "Validate machine account"
msgstr ""

#: ../utils/net_ads.c:2486
msgid ""
"net ads testjoin\n"
"    Validate machine account"
msgstr ""

#: ../utils/net_ads.c:2493
msgid "Remove the local machine from ADS"
msgstr ""

#: ../utils/net_ads.c:2494
msgid ""
"net ads leave\n"
"    Remove the local machine from ADS"
msgstr ""

#: ../utils/net_ads.c:2501
msgid "Display machine account details"
msgstr ""

#: ../utils/net_ads.c:2502
msgid ""
"net ads status\n"
"    Display machine account details"
msgstr ""

#: ../utils/net_ads.c:2509
msgid "List/modify users"
msgstr ""

#: ../utils/net_ads.c:2510
msgid ""
"net ads user\n"
"    List/modify users"
msgstr ""

#: ../utils/net_ads.c:2517
msgid "List/modify groups"
msgstr ""

#: ../utils/net_ads.c:2518
msgid ""
"net ads group\n"
"    List/modify groups"
msgstr ""

#: ../utils/net_ads.c:2525
msgid "Issue dynamic DNS update"
msgstr ""

#: ../utils/net_ads.c:2526
msgid ""
"net ads dns\n"
"    Issue dynamic DNS update"
msgstr ""

#: ../utils/net_ads.c:2533
#, fuzzy
msgid "Change user passwords"
msgstr "Ändere Passwort"

#: ../utils/net_ads.c:2534
msgid ""
"net ads password\n"
"    Change user passwords"
msgstr ""

#: ../utils/net_ads.c:2541
#, fuzzy
msgid "Change trust account password"
msgstr "Ändere Passwort"

#: ../utils/net_ads.c:2542
msgid ""
"net ads changetrustpw\n"
"    Change trust account password"
msgstr ""

#: ../utils/net_ads.c:2549
msgid "List/modify printer entries"
msgstr ""

#: ../utils/net_ads.c:2550
msgid ""
"net ads printer\n"
"    List/modify printer entries"
msgstr ""

#: ../utils/net_ads.c:2557
msgid "Issue LDAP search using filter"
msgstr ""

#: ../utils/net_ads.c:2558
msgid ""
"net ads search\n"
"    Issue LDAP search using filter"
msgstr ""

#: ../utils/net_ads.c:2565
msgid "Issue LDAP search by DN"
msgstr ""

#: ../utils/net_ads.c:2566
msgid ""
"net ads dn\n"
"    Issue LDAP search by DN"
msgstr ""

#: ../utils/net_ads.c:2573
msgid "Issue LDAP search by SID"
msgstr ""

#: ../utils/net_ads.c:2574
msgid ""
"net ads sid\n"
"    Issue LDAP search by SID"
msgstr ""

#: ../utils/net_ads.c:2581
msgid "Display workgroup name"
msgstr ""

#: ../utils/net_ads.c:2582
msgid ""
"net ads workgroup\n"
"    Display the workgroup name"
msgstr ""

#: ../utils/net_ads.c:2589
msgid "Perfom CLDAP query on DC"
msgstr ""

#: ../utils/net_ads.c:2590
msgid ""
"net ads lookup\n"
"    Find the ADS DC using CLDAP lookups"
msgstr ""

#: ../utils/net_ads.c:2597
msgid "Manage local keytab file"
msgstr ""

#: ../utils/net_ads.c:2598
msgid ""
"net ads keytab\n"
"    Manage local keytab file"
msgstr ""

#: ../utils/net_ads.c:2605
msgid "Manage group policy objects"
msgstr ""

#: ../utils/net_ads.c:2606
msgid ""
"net ads gpo\n"
"    Manage group policy objects"
msgstr ""

#: ../utils/net_ads.c:2613
msgid "Manage kerberos keytab"
msgstr ""

#: ../utils/net_ads.c:2614
msgid ""
"net ads kerberos\n"
"    Manage kerberos keytab"
msgstr ""

#: ../utils/net_ads.c:2627
msgid "ADS support not compiled in\n"
msgstr ""

#: ../utils/net_ads_gpo.c:40
msgid ""
"Usage:\n"
"net ads gpo refresh <username|machinename>\n"
"  Lists all GPOs assigned to an account and downloads them\n"
"    username\tUser to refresh GPOs for\n"
"    machinename\tMachine to refresh GPOs for\n"
msgstr ""

#: ../utils/net_ads_gpo.c:56
#, c-format
msgid "failed to connect AD server: %s\n"
msgstr ""

#: ../utils/net_ads_gpo.c:62
#, c-format
msgid "failed to find samaccount for %s\n"
msgstr ""

#: ../utils/net_ads_gpo.c:70
#, c-format
msgid ""
"\n"
"%s: '%s' has dn: '%s'\n"
"\n"
msgstr ""

#: ../utils/net_ads_gpo.c:71 ../utils/net_ads_gpo.c:328
#, fuzzy
msgid "machine"
msgstr "Entfernte Maschine"

#: ../utils/net_ads_gpo.c:71 ../utils/net_ads_gpo.c:328
#, fuzzy
msgid "user"
msgstr "Benutzer"

#: ../utils/net_ads_gpo.c:74
msgid "* fetching token "
msgstr ""

#: ../utils/net_ads_gpo.c:82 ../utils/net_ads_gpo.c:90 ../utils/net_ads_gpo.c:102 ../utils/net_ads_gpo.c:113 ../utils/net_ads_gpo.c:158
#, c-format
msgid "failed: %s\n"
msgstr ""

#: ../utils/net_ads_gpo.c:85 ../utils/net_ads_gpo.c:94 ../utils/net_ads_gpo.c:105 ../utils/net_ads_gpo.c:118 ../utils/net_ads_gpo.c:163
msgid "finished\n"
msgstr ""

#: ../utils/net_ads_gpo.c:87
msgid "* fetching GPO List "
msgstr ""

#: ../utils/net_ads_gpo.c:96
msgid "* Refreshing Group Policy Data "
msgstr ""

#: ../utils/net_ads_gpo.c:107
msgid "* storing GPO list to registry "
msgstr ""

#: ../utils/net_ads_gpo.c:122
msgid "* dumping GPO list\n"
msgstr ""

#: ../utils/net_ads_gpo.c:151
msgid "* re-reading GPO list from registry "
msgstr ""

#: ../utils/net_ads_gpo.c:167
msgid "* dumping GPO list from registry\n"
msgstr ""

#: ../utils/net_ads_gpo.c:226
msgid ""
"Usage:\n"
"net ads gpo listall\n"
"    List all GPOs on the DC\n"
msgstr ""

#: ../utils/net_ads_gpo.c:270
#, fuzzy, c-format
msgid "ads_parse_gpo failed: %s\n"
msgstr "Passwortverwaltung"

#: ../utils/net_ads_gpo.c:300
msgid ""
"Usage:\n"
"net ads gpo list <username|machinename>\n"
"  Lists all GPOs for machine/user\n"
"    username\tUser to list GPOs for\n"
"    machinename\tMachine to list GPOs for\n"
msgstr ""

#: ../utils/net_ads_gpo.c:327
#, c-format
msgid "%s: '%s' has dn: '%s'\n"
msgstr ""

#: ../utils/net_ads_gpo.c:451
msgid ""
"Usage:\n"
"net ads gpo linkget <container>\n"
"  Lists gPLink of a containter\n"
"    container\tContainer to get link for\n"
msgstr ""

#: ../utils/net_ads_gpo.c:470
#, c-format
msgid "get link for %s failed: %s\n"
msgstr ""

#: ../utils/net_ads_gpo.c:492
msgid ""
"Usage:\n"
"net ads gpo linkadd <linkdn> <gpodn> [options]\n"
"  Link a container to a GPO\n"
"    linkdn\tContainer to link to a GPO\n"
"    gpodn\tGPO to link container to\n"
msgstr ""

#: ../utils/net_ads_gpo.c:497
msgid ""
"note: DNs must be provided properly escaped.\n"
"See RFC 4514 for details\n"
msgstr ""

#: ../utils/net_ads_gpo.c:518
#, c-format
msgid "link add failed: %s\n"
msgstr ""

#: ../utils/net_ads_gpo.c:579
msgid ""
"Usage:\n"
"net ads gpo getgpo <gpo>\n"
"  List speciefied GPO\n"
"    gpo\t\tGPO to list\n"
msgstr ""

#: ../utils/net_ads_gpo.c:603
#, c-format
msgid "get gpo for [%s] failed: %s\n"
msgstr ""

#: ../utils/net_ads_gpo.c:634
msgid "List specified GPO"
msgstr ""

#: ../utils/net_ads_gpo.c:635
msgid ""
"net ads gpo getgpo\n"
"    List specified GPO"
msgstr ""

#: ../utils/net_ads_gpo.c:642
msgid "Link a container to a GPO"
msgstr ""

#: ../utils/net_ads_gpo.c:643
msgid ""
"net ads gpo linkadd\n"
"    Link a container to a GPO"
msgstr ""

#: ../utils/net_ads_gpo.c:660
msgid "Lists gPLink of containter"
msgstr ""

#: ../utils/net_ads_gpo.c:661
msgid ""
"net ads gpo linkget\n"
"    Lists gPLink of containter"
msgstr ""

#: ../utils/net_ads_gpo.c:668
msgid "Lists all GPOs for machine/user"
msgstr ""

#: ../utils/net_ads_gpo.c:669
msgid ""
"net ads gpo list\n"
"    Lists all GPOs for machine/user"
msgstr ""

#: ../utils/net_ads_gpo.c:676
msgid "Lists all GPOs on a DC"
msgstr ""

#: ../utils/net_ads_gpo.c:677
msgid ""
"net ads gpo listall\n"
"    Lists all GPOs on a DC"
msgstr ""

#: ../utils/net_ads_gpo.c:684
msgid "Lists all GPOs assigned to an account and downloads them"
msgstr ""

#: ../utils/net_ads_gpo.c:686
msgid ""
"net ads gpo refresh\n"
"    Lists all GPOs assigned to an account and downloads them"
msgstr ""

#: ../utils/net_afs.c:25
msgid ""
"  net afs key filename\n"
"\tImports a OpenAFS KeyFile into our secrets.tdb\n"
"\n"
msgstr ""

#: ../utils/net_afs.c:27
msgid ""
"  net afs impersonate <user> <cell>\n"
"\tCreates a token for user@cell\n"
"\n"
msgstr ""

#: ../utils/net_afs.c:38
msgid "usage: 'net afs key <keyfile> cell'\n"
msgstr ""

#: ../utils/net_afs.c:43
msgid "Could not open secrets.tdb\n"
msgstr ""

#: ../utils/net_afs.c:48
#, c-format
msgid "Could not open %s\n"
msgstr ""

#: ../utils/net_afs.c:53
msgid "Could not read keyfile\n"
msgstr ""

#: ../utils/net_afs.c:58
msgid "Could not write keyfile to secrets.tdb\n"
msgstr ""

#: ../utils/net_afs.c:71
#, c-format
msgid "Usage: net afs impersonate <user> <cell>\n"
msgstr ""

#: ../utils/net_afs.c:78
#, c-format
msgid "Could not create token\n"
msgstr ""

#: ../utils/net_afs.c:83
#, c-format
msgid "Could not set token into kernel\n"
msgstr ""

#: ../utils/net_afs.c:87
#, c-format
msgid "Success: %s@%s\n"
msgstr ""

#: ../utils/net_afs.c:98
msgid "Import an OpenAFS keyfile"
msgstr ""

#: ../utils/net_afs.c:99
msgid ""
"net afs key <filename>\n"
"    Import kefile from <filename>."
msgstr ""

#: ../utils/net_afs.c:106
msgid "Get a user token"
msgstr ""

#: ../utils/net_afs.c:107
msgid ""
"net afs impersonate <user> <cell>\n"
"    Create token for user@cell"
msgstr ""

#: ../utils/net_cache.c:74
#, c-format
msgid "Key: %s\t Timeout: %s\t Value: %s  %s\n"
msgstr ""

#: ../utils/net_cache.c:75
msgid "(expired)"
msgstr ""

#: ../utils/net_cache.c:84
#, c-format
msgid "Couldn't delete entry! key = %s\n"
msgstr ""

#: ../utils/net_cache.c:158
msgid ""
"\n"
"Usage:\n"
"net cache add <key string> <data string> <timeout>\n"
msgstr ""

#: ../utils/net_cache.c:170
msgid "Invalid timeout argument.\n"
msgstr ""

#: ../utils/net_cache.c:175
msgid "New cache entry stored successfully.\n"
msgstr ""

#: ../utils/net_cache.c:179
msgid "Entry couldn't be added. Perhaps there's already such a key.\n"
msgstr ""

#: ../utils/net_cache.c:195
msgid ""
"\n"
"Usage: net cache del <key string>\n"
msgstr ""

#: ../utils/net_cache.c:200
msgid "Entry deleted.\n"
msgstr ""

#: ../utils/net_cache.c:204
msgid "Couldn't delete specified entry\n"
msgstr ""

#: ../utils/net_cache.c:223
msgid ""
"\n"
"Usage: net cache get <key>\n"
msgstr ""

#: ../utils/net_cache.c:233
msgid "Failed to find entry\n"
msgstr ""

#: ../utils/net_cache.c:250
msgid "Usage: net cache search <pattern>\n"
msgstr ""

#: ../utils/net_cache.c:272
msgid ""
"Usage:\n"
"net cache list\n"
"    List all cache entries.\n"
msgstr ""

#: ../utils/net_cache.c:293 ../utils/net_cache.c:306
msgid ""
"Usage:\n"
"net cache flush\n"
"    Delete all cache entries.\n"
msgstr ""

#: ../utils/net_cache.c:331
msgid "Add new cache entry"
msgstr ""

#: ../utils/net_cache.c:332
msgid ""
"net cache add <key string> <data string> <timeout>\n"
"  Add new cache entry.\n"
"    key string\tKey string to add cache data under.\n"
"    data string\tData to store under given key.\n"
"    timeout\tTimeout for cache data."
msgstr ""

#: ../utils/net_cache.c:342
msgid "Delete existing cache entry by key"
msgstr ""

#: ../utils/net_cache.c:343
msgid ""
"net cache del <key string>\n"
"  Delete existing cache entry by key.\n"
"    key string\tKey string to delete."
msgstr ""

#: ../utils/net_cache.c:351
msgid "Get cache entry by key"
msgstr ""

#: ../utils/net_cache.c:352
msgid ""
"net cache get <key string>\n"
"  Get cache entry by key.\n"
"    key string\tKey string to look up cache entry for."
msgstr ""

#: ../utils/net_cache.c:361
msgid "Search entry by pattern"
msgstr ""

#: ../utils/net_cache.c:362
msgid ""
"net cache search <pattern>\n"
"  Search entry by pattern.\n"
"    pattern\tPattern to search for in cache."
msgstr ""

#: ../utils/net_cache.c:370
msgid "List all cache entries"
msgstr ""

#: ../utils/net_cache.c:371
msgid ""
"net cache list\n"
"  List all cache entries"
msgstr ""

#: ../utils/net_cache.c:378
#, fuzzy
msgid "Delete all cache entries"
msgstr "Lösche Drucker"

#: ../utils/net_cache.c:379
msgid ""
"net cache flush\n"
"  Delete all cache entries"
msgstr ""

#: ../utils/net_cache.c:386
msgid "Move transient cache content to stable storage"
msgstr ""

#: ../utils/net_cache.c:387
msgid ""
"net cache stabilize\n"
"  Move transient cache content to stable storage"
msgstr ""

#: ../utils/net_conf.c:42
msgid "USAGE: net conf list\n"
msgstr ""

#: ../utils/net_conf.c:49
msgid ""
"USAGE: net conf import [--test|-T] <filename> [<servicename>]\n"
"\t[--test|-T]    testmode - do not act, just print what would be done\n"
"\t<servicename>  only import service <servicename>, ignore the rest\n"
msgstr ""

#: ../utils/net_conf.c:61
msgid "USAGE: net conf listshares\n"
msgstr ""

#: ../utils/net_conf.c:68
msgid "USAGE: net conf drop\n"
msgstr ""

#: ../utils/net_conf.c:75
msgid "USAGE: net conf showshare <sharename>\n"
msgstr ""

#: ../utils/net_conf.c:82
msgid ""
"USAGE: net conf addshare <sharename> <path> [writeable={y|N} [guest_ok={y|N} [<comment>]]\n"
"\t<sharename>      the new share name.\n"
"\t<path>           the path on the filesystem to export.\n"
"\twriteable={y|N}  set \"writeable to \"yes\" or \"no\" (default) on this share.\n"
"\tguest_ok={y|N}   set \"guest ok\" to \"yes\" or \"no\" (default)   on this share.\n"
"\t<comment>        optional comment for the new share.\n"
msgstr ""

#: ../utils/net_conf.c:97
msgid "USAGE: net conf delshare <sharename>\n"
msgstr ""

#: ../utils/net_conf.c:104
msgid "USAGE: net conf setparm <section> <param> <value>\n"
msgstr ""

#: ../utils/net_conf.c:111
msgid "USAGE: net conf getparm <section> <param>\n"
msgstr ""

#: ../utils/net_conf.c:118
msgid "USAGE: net conf delparm <section> <param>\n"
msgstr ""

#: ../utils/net_conf.c:125
msgid "USAGE: net conf getincludes <section>\n"
msgstr ""

#: ../utils/net_conf.c:132
msgid "USAGE: net conf setincludes <section> [<filename>]*\n"
msgstr ""

#: ../utils/net_conf.c:139
msgid "USAGE: net conf delincludes <section>\n"
msgstr ""

#: ../utils/net_conf.c:251
#, c-format
msgid "Error getting config: %s\n"
msgstr ""

#: ../utils/net_conf.c:305 ../utils/net_conf.c:318 ../utils/net_conf.c:614 ../utils/net_conf.c:742 ../utils/net_conf.c:780 ../utils/net_conf.c:786 ../utils/net_conf.c:860 ../utils/net_conf.c:866 ../utils/net_conf.c:916 ../utils/net_conf.c:970
#: ../utils/net_conf.c:1010 ../utils/net_conf.c:1050
msgid "error: out of memory!\n"
msgstr ""

#: ../utils/net_conf.c:324
#, c-format
msgid "error loading file '%s': %s\n"
msgstr ""

#: ../utils/net_conf.c:330
msgid ""
"\n"
"TEST MODE - would import the following configuration:\n"
"\n"
msgstr ""

#: ../utils/net_conf.c:346 ../utils/net_conf.c:382 ../utils/net_conf.c:407 ../utils/net_conf.c:793
#, c-format
msgid "error starting transaction: %s\n"
msgstr ""

#: ../utils/net_conf.c:400 ../utils/net_conf.c:416 ../utils/net_conf.c:817
#, c-format
msgid "error committing transaction: %s\n"
msgstr ""

#: ../utils/net_conf.c:427 ../utils/net_conf.c:828
#, c-format
msgid "error cancelling transaction: %s\n"
msgstr ""

#: ../utils/net_conf.c:484
#, c-format
msgid "Error deleting configuration: %s\n"
msgstr ""

#: ../utils/net_conf.c:521
#, c-format
msgid "error getting share parameters: %s\n"
msgstr ""

#: ../utils/net_conf.c:630
#, c-format
msgid "ERROR: share name %s contains invalid characters (any of %s)\n"
msgstr ""

#: ../utils/net_conf.c:638
msgid "ERROR: 'global' is not a valid share name.\n"
msgstr ""

#: ../utils/net_conf.c:643
#, c-format
msgid "ERROR: share %s already exists.\n"
msgstr ""

#: ../utils/net_conf.c:652
#, c-format
msgid "Error: path '%s' is not an absolute path.\n"
msgstr ""

#: ../utils/net_conf.c:659
#, c-format
msgid ""
"ERROR: cannot stat path '%s' to ensure this is a directory.\n"
"Error was '%s'.\n"
msgstr ""

#: ../utils/net_conf.c:668
#, c-format
msgid "ERROR: path '%s' is not a directory.\n"
msgstr ""

#: ../utils/net_conf.c:679
#, c-format
msgid "Error creating share %s: %s\n"
msgstr ""

#: ../utils/net_conf.c:690 ../utils/net_conf.c:699 ../utils/net_conf.c:707 ../utils/net_conf.c:715
#, c-format
msgid "Error setting parameter %s: %s\n"
msgstr ""

#: ../utils/net_conf.c:748
#, c-format
msgid "Error deleting share %s: %s\n"
msgstr ""

#: ../utils/net_conf.c:801
#, c-format
msgid "Error creating share '%s': %s\n"
msgstr ""

#: ../utils/net_conf.c:810
#, c-format
msgid "Error setting value '%s': %s\n"
msgstr ""

#: ../utils/net_conf.c:874 ../utils/net_conf.c:930
#, c-format
msgid "Error: given service '%s' does not exist.\n"
msgstr ""

#: ../utils/net_conf.c:879 ../utils/net_conf.c:935
#, c-format
msgid "Error: given parameter '%s' is not set.\n"
msgstr ""

#: ../utils/net_conf.c:883
#, c-format
msgid "Error getting value '%s': %s.\n"
msgstr ""

#: ../utils/net_conf.c:939
#, c-format
msgid "Error deleting value '%s': %s.\n"
msgstr ""

#: ../utils/net_conf.c:977
#, c-format
msgid "error getting includes: %s\n"
msgstr ""

#: ../utils/net_conf.c:1023
#, c-format
msgid "error setting includes: %s\n"
msgstr ""

#: ../utils/net_conf.c:1056
#, c-format
msgid "error deleting includes: %s\n"
msgstr ""

#: ../utils/net_conf.c:1136 ../utils/net_help.c:36
msgid "Usage:\n"
msgstr ""

#: ../utils/net_conf.c:1160
msgid "Dump the complete configuration in smb.conf like format."
msgstr ""

#: ../utils/net_conf.c:1162
msgid ""
"net conf list\n"
"    Dump the complete configuration in smb.conf like format."
msgstr ""

#: ../utils/net_conf.c:1171
msgid "Import configuration from file in smb.conf format."
msgstr ""

#: ../utils/net_conf.c:1173
msgid ""
"net conf import\n"
"    Import configuration from file in smb.conf format."
msgstr ""

#: ../utils/net_conf.c:1181
msgid "List the share names."
msgstr ""

#: ../utils/net_conf.c:1182
msgid ""
"net conf listshares\n"
"    List the share names."
msgstr ""

#: ../utils/net_conf.c:1189
msgid "Delete the complete configuration."
msgstr ""

#: ../utils/net_conf.c:1190
msgid ""
"net conf drop\n"
"    Delete the complete configuration."
msgstr ""

#: ../utils/net_conf.c:1197
msgid "Show the definition of a share."
msgstr ""

#: ../utils/net_conf.c:1198
msgid ""
"net conf showshare\n"
"    Show the definition of a share."
msgstr ""

#: ../utils/net_conf.c:1205
#, fuzzy
msgid "Create a new share."
msgstr "Erstelle Freigabe"

#: ../utils/net_conf.c:1206
msgid ""
"net conf addshare\n"
"    Create a new share."
msgstr ""

#: ../utils/net_conf.c:1213
#, fuzzy
msgid "Delete a share."
msgstr "Lösche Freigabe"

#: ../utils/net_conf.c:1214
msgid ""
"net conf delshare\n"
"    Delete a share."
msgstr ""

#: ../utils/net_conf.c:1221
#, fuzzy
msgid "Store a parameter."
msgstr "Parameter der Freigabe"

#: ../utils/net_conf.c:1222
msgid ""
"net conf setparm\n"
"    Store a parameter."
msgstr ""

#: ../utils/net_conf.c:1229
msgid "Retrieve the value of a parameter."
msgstr ""

#: ../utils/net_conf.c:1230
msgid ""
"net conf getparm\n"
"    Retrieve the value of a parameter."
msgstr ""

#: ../utils/net_conf.c:1237
#, fuzzy
msgid "Delete a parameter."
msgstr "Lösche Drucker"

#: ../utils/net_conf.c:1238
msgid ""
"net conf delparm\n"
"    Delete a parameter."
msgstr ""

#: ../utils/net_conf.c:1245
msgid "Show the includes of a share definition."
msgstr ""

#: ../utils/net_conf.c:1246
msgid ""
"net conf getincludes\n"
"    Show the includes of a share definition."
msgstr ""

#: ../utils/net_conf.c:1253
msgid "Set includes for a share."
msgstr ""

#: ../utils/net_conf.c:1254
msgid ""
"net conf setincludes\n"
"    Set includes for a share."
msgstr ""

#: ../utils/net_conf.c:1261
msgid "Delete includes from a share definition."
msgstr ""

#: ../utils/net_conf.c:1262
msgid ""
"net conf setincludes\n"
"    Delete includes from a share definition."
msgstr ""

#: ../utils/net_dom.c:25
msgid ""
"usage: net dom join <domain=DOMAIN> <ou=OU> <account=ACCOUNT> <password=PASSWORD> <reboot>\n"
"  Join a remote machine\n"
msgstr ""

#: ../utils/net_dom.c:28
msgid ""
"usage: net dom unjoin <account=ACCOUNT> <password=PASSWORD> <reboot>\n"
"  Unjoin a remote machine\n"
msgstr ""

#: ../utils/net_dom.c:31
msgid ""
"usage: net dom renamecomputer <newname=NEWNAME> <account=ACCOUNT> <password=PASSWORD> <reboot>\n"
"  Rename joined computer\n"
msgstr ""

#: ../utils/net_dom.c:91
#, c-format
msgid "Failed to unjoin domain: %s\n"
msgstr ""

#: ../utils/net_dom.c:97 ../utils/net_dom.c:204
msgid "Shutting down due to a domain membership change"
msgstr ""

#: ../utils/net_dom.c:290
#, c-format
msgid "Failed to rename machine: "
msgstr ""

#: ../utils/net_dom.c:292
#, c-format
msgid "Computer is not joined to a Domain\n"
msgstr ""

#: ../utils/net_dom.c:301
msgid "Shutting down due to a computer rename"
msgstr ""

#: ../utils/net_dom.c:338
#, fuzzy
msgid "Join a remote machine"
msgstr "Entfernte Maschine"

#: ../utils/net_dom.c:339
msgid ""
"net dom join <domain=DOMAIN> <ou=OU> <account=ACCOUNT> <password=PASSWORD> <reboot>\n"
"  Join a remote machine"
msgstr ""

#: ../utils/net_dom.c:347
#, fuzzy
msgid "Unjoin a remote machine"
msgstr "Entfernte Maschine"

#: ../utils/net_dom.c:348
msgid ""
"net dom unjoin <account=ACCOUNT> <password=PASSWORD> <reboot>\n"
"  Unjoin a remote machine"
msgstr ""

#: ../utils/net_dom.c:356
msgid "Rename a computer that is joined to a domain"
msgstr ""

#: ../utils/net_dom.c:357
msgid ""
"net dom renamecomputer <newname=NEWNAME> <account=ACCOUNT> <password=PASSWORD> <reboot>\n"
"  Rename joined computer"
msgstr ""

#: ../utils/net_eventlog.c:46
msgid "usage: net eventlog dump <file.evt>\n"
msgstr ""

#: ../utils/net_eventlog.c:52 ../utils/net_eventlog.c:108
#, c-format
msgid "failed to load evt file: %s\n"
msgstr ""

#: ../utils/net_eventlog.c:59 ../utils/net_eventlog.c:129
#, fuzzy, c-format
msgid "evt pull failed: %s\n"
msgstr "Passwortverwaltung"

#: ../utils/net_eventlog.c:102
msgid "usage: net eventlog import <file> <eventlog>\n"
msgstr ""

#: ../utils/net_eventlog.c:116
#, fuzzy, c-format
msgid "evt header pull failed: %s\n"
msgstr "Passwortverwaltung"

#: ../utils/net_eventlog.c:122
msgid "input file is wrapped, cannot proceed\n"
msgstr ""

#: ../utils/net_eventlog.c:138 ../utils/net_eventlog.c:203
#, c-format
msgid "can't open the eventlog TDB (%s)\n"
msgstr ""

#: ../utils/net_eventlog.c:158
#, c-format
msgid "can't write to the eventlog: %s\n"
msgstr ""

#: ../utils/net_eventlog.c:164
#, c-format
msgid "wrote %d entries to tdb\n"
msgstr ""

#: ../utils/net_eventlog.c:197
msgid "usage: net eventlog export <file> <eventlog>\n"
msgstr ""

#: ../utils/net_eventlog.c:214
#, c-format
msgid "failed to save evt file: %s\n"
msgstr ""

#: ../utils/net_eventlog.c:243
msgid "Dump eventlog"
msgstr ""

#: ../utils/net_eventlog.c:244
msgid ""
"net eventlog dump\n"
"    Dump win32 *.evt eventlog file"
msgstr ""

#: ../utils/net_eventlog.c:251
#, fuzzy
msgid "Import eventlog"
msgstr "Wichtiger Hinweis:"

#: ../utils/net_eventlog.c:252
msgid ""
"net eventlog import\n"
"    Import win32 *.evt eventlog file"
msgstr ""

#: ../utils/net_eventlog.c:259
msgid "Export eventlog"
msgstr ""

#: ../utils/net_eventlog.c:260
msgid ""
"net eventlog export\n"
"    Export win32 *.evt eventlog file"
msgstr ""

#: ../utils/net_file.c:27
msgid ""
"net [<method>] file [misc. options] [targets]\n"
"\tlists all open files on file server\n"
msgstr ""

#: ../utils/net_file.c:29
msgid ""
"net [<method>] file USER <username> [misc. options] [targets]\n"
"\tlists all files opened by username on file server\n"
msgstr ""

#: ../utils/net_file.c:32
msgid ""
"net [<method>] file CLOSE <id> [misc. options] [targets]\n"
"\tcloses specified file on target server\n"
msgstr ""

#: ../utils/net_file.c:34
msgid ""
"net [rap] file INFO <id> [misc. options] [targets]\n"
"\tdisplays information about the specified open file\n"
msgstr ""

#: ../utils/net_group.c:27
msgid ""
"net [<method>] group [misc. options] [targets]\n"
"\tList user groups\n"
"\n"
msgstr ""

#: ../utils/net_group.c:29
msgid ""
"net rpc group LIST [global|local|builtin]* [misc. options]\n"
"\tList specific user groups\n"
"\n"
msgstr ""

#: ../utils/net_group.c:31
msgid ""
"net [<method>] group DELETE <name> [misc. options] [targets]\n"
"\tDelete specified group\n"
msgstr ""

#: ../utils/net_group.c:34
msgid ""
"\n"
"net [<method>] group ADD <name> [-C comment] [-c container] [misc. options] [targets]\n"
"\tCreate specified group\n"
msgstr ""

#: ../utils/net_group.c:37
msgid ""
"\n"
"net rpc group MEMBERS <name>\n"
"\tList Group Members\n"
"\n"
msgstr ""

#: ../utils/net_group.c:38
msgid ""
"\n"
"net rpc group ADDMEM <group> <member>\n"
"\tAdd Group Members\n"
"\n"
msgstr ""

#: ../utils/net_group.c:40
msgid ""
"\n"
"net rpc group DELMEM <group> <member>\n"
"\tDelete Group Members\n"
"\n"
msgstr ""

#: ../utils/net_group.c:44
msgid "\t-C or --comment=<comment>\tdescriptive comment (for add only)\n"
msgstr ""

#: ../utils/net_group.c:46
msgid "\t-c or --container=<container>\tLDAP container, defaults to cn=Users (for add in ADS only)\n"
msgstr ""

#: ../utils/net_group.c:48
msgid "\t-L or --localgroup\t\tWhen adding groups, create a local group (alias)\n"
msgstr ""

#: ../utils/net_groupmap.c:38
#, c-format
msgid "NT Group %s doesn't exist in mapping DB\n"
msgstr ""

#: ../utils/net_groupmap.c:46
#, c-format
msgid "converting sid %s from a string failed!\n"
msgstr ""

#: ../utils/net_groupmap.c:65
#, c-format
msgid "\tSID       : %s\n"
msgstr ""

#: ../utils/net_groupmap.c:66
#, c-format
msgid "\tUnix gid  : %u\n"
msgstr ""

#: ../utils/net_groupmap.c:67
#, c-format
msgid "\tUnix group: %s\n"
msgstr ""

#: ../utils/net_groupmap.c:68
#, c-format
msgid "\tGroup type: %s\n"
msgstr ""

#: ../utils/net_groupmap.c:70
#, c-format
msgid "\tComment   : %s\n"
msgstr ""

#: ../utils/net_groupmap.c:84
msgid ""
"net groupmap list [verbose] [ntgroup=NT group] [sid=SID]\n"
"    verbose\tPrint verbose list\n"
"    ntgroup\tNT group to list\n"
"    sid\tSID of group to list"
msgstr ""

#: ../utils/net_groupmap.c:91 ../utils/net_groupmap.c:271 ../utils/net_groupmap.c:356 ../utils/net_groupmap.c:412 ../utils/net_groupmap.c:495 ../utils/net_groupmap.c:522
#, fuzzy, c-format
msgid ""
"Usage:\n"
"%s\n"
msgstr "Benutzername"

#: ../utils/net_groupmap.c:106 ../utils/net_groupmap.c:213 ../utils/net_groupmap.c:220 ../utils/net_groupmap.c:365 ../utils/net_groupmap.c:372 ../utils/net_groupmap.c:504
msgid "must supply a name\n"
msgstr ""

#: ../utils/net_groupmap.c:113 ../utils/net_groupmap.c:227 ../utils/net_groupmap.c:511
msgid "must supply a SID\n"
msgstr ""

#: ../utils/net_groupmap.c:118 ../utils/net_groupmap.c:265 ../utils/net_groupmap.c:406 ../utils/net_groupmap.c:516
#, fuzzy, c-format
msgid "Bad option: %s\n"
msgstr "Basisoptionen"

#: ../utils/net_groupmap.c:139
msgid "Failure to local group SID in the database\n"
msgstr ""

#: ../utils/net_groupmap.c:181
msgid "net groupmap add {rid=<int>|sid=<string>} unixgroup=<string> [type=<domain|local|builtin>] [ntgroup=<string>] [comment=<string>]"
msgstr ""

#: ../utils/net_groupmap.c:195
#, fuzzy, c-format
msgid ""
"Usage\n"
"%s\n"
msgstr "Benutzername"

#: ../utils/net_groupmap.c:205
#, c-format
msgid "RID must be greater than %d\n"
msgstr ""

#: ../utils/net_groupmap.c:235 ../utils/net_groupmap.c:380
msgid "must supply a comment string\n"
msgstr ""

#: ../utils/net_groupmap.c:259
#, c-format
msgid "unknown group type %s\n"
msgstr ""

#: ../utils/net_groupmap.c:276
#, c-format
msgid "Can't lookup UNIX group %s\n"
msgstr ""

#: ../utils/net_groupmap.c:282
#, c-format
msgid "Unix group %s already mapped to SID %s\n"
msgstr ""

#: ../utils/net_groupmap.c:289
msgid "No rid or sid specified, choosing a RID\n"
msgstr ""

#: ../utils/net_groupmap.c:292
msgid "Could not get new RID\n"
msgstr ""

#: ../utils/net_groupmap.c:297
#, c-format
msgid "Got RID %d\n"
msgstr ""

#: ../utils/net_groupmap.c:328
#, c-format
msgid "adding entry for group %s failed!\n"
msgstr ""

#: ../utils/net_groupmap.c:332
#, c-format
msgid "Successfully added group %s to the mapping db as a %s\n"
msgstr ""

#: ../utils/net_groupmap.c:349
msgid "net groupmap modify {ntgroup=<string>|sid=<SID>} [comment=<string>] [unixgroup=<string>] [type=<domain|local>]"
msgstr ""

#: ../utils/net_groupmap.c:388
msgid "must supply a group name\n"
msgstr ""

#: ../utils/net_groupmap.c:434
msgid "Failed to find local group SID in the database\n"
msgstr ""

#: ../utils/net_groupmap.c:443
msgid "Can't map to an unknown group type.\n"
msgstr ""

#: ../utils/net_groupmap.c:449
msgid "You can only change between domain and local groups.\n"
msgstr ""

#: ../utils/net_groupmap.c:466
#, c-format
msgid "Unable to lookup UNIX group %s.  Make sure the group exists.\n"
msgstr ""

#: ../utils/net_groupmap.c:476
msgid "Could not update group database\n"
msgstr ""

#: ../utils/net_groupmap.c:480
#, c-format
msgid "Updated mapping entry for %s\n"
msgstr ""

#: ../utils/net_groupmap.c:491
msgid "net groupmap delete {ntgroup=<string>|sid=<SID>}"
msgstr ""

#: ../utils/net_groupmap.c:532
#, c-format
msgid "Unable to resolve group %s to a SID\n"
msgstr ""

#: ../utils/net_groupmap.c:539
#, c-format
msgid "Failed to remove group %s from the mapping db!\n"
msgstr ""

#: ../utils/net_groupmap.c:544
#, c-format
msgid "Sucessfully removed %s from the mapping db\n"
msgstr ""

#: ../utils/net_groupmap.c:557
msgid "Usage: net groupmap set \"NT Group\" [\"unix group\"] [-C \"comment\"] [-L] [-D]\n"
msgstr ""

#: ../utils/net_groupmap.c:563
msgid "Can only specify -L or -D, not both\n"
msgstr ""

#: ../utils/net_groupmap.c:573
#, c-format
msgid "Could not find unix group %s\n"
msgstr ""

#: ../utils/net_groupmap.c:594
#, c-format
msgid "Could not find group mapping for %s\n"
msgstr ""

#: ../utils/net_groupmap.c:605
msgid "Could not allocate new RID\n"
msgstr ""

#: ../utils/net_groupmap.c:622
#, c-format
msgid "Could not add mapping entry for %s\n"
msgstr ""

#: ../utils/net_groupmap.c:633
#, c-format
msgid "Can't change type of the BUILTIN group %s\n"
msgstr ""

#: ../utils/net_groupmap.c:660
#, c-format
msgid "Could not update group mapping for %s\n"
msgstr ""

#: ../utils/net_groupmap.c:674
msgid ""
"Usage:\n"
"net groupmap cleanup\n"
"    Delete all group mappings\n"
msgstr ""

#: ../utils/net_groupmap.c:682
msgid "Could not list group mappings\n"
msgstr ""

#: ../utils/net_groupmap.c:689
#, c-format
msgid "Group %s is not mapped\n"
msgstr ""

#: ../utils/net_groupmap.c:692
#, c-format
msgid "Deleting mapping for NT Group %s, sid %s\n"
msgstr ""

#: ../utils/net_groupmap.c:712
msgid "Usage: net groupmap addmem alias-sid member-sid\n"
msgstr ""

#: ../utils/net_groupmap.c:717
#, c-format
msgid "Could not add sid %s to alias %s\n"
msgstr ""

#: ../utils/net_groupmap.c:733
msgid "Usage: net groupmap delmem alias-sid member-sid\n"
msgstr ""

#: ../utils/net_groupmap.c:738
#, c-format
msgid "Could not delete sid %s from alias %s\n"
msgstr ""

#: ../utils/net_groupmap.c:755
msgid "Usage: net groupmap listmem alias-sid\n"
msgstr ""

#: ../utils/net_groupmap.c:764
#, c-format
msgid "Could not list members for sid %s\n"
msgstr ""

#: ../utils/net_groupmap.c:791
#, c-format
msgid "Could not list memberships for sid %s\n"
msgstr ""

#: ../utils/net_groupmap.c:814
msgid "Usage: net groupmap memberof sid\n"
msgstr ""

#: ../utils/net_groupmap.c:820 ../utils/net_idmap.c:345
msgid "talloc_init failed\n"
msgstr ""

#: ../utils/net_groupmap.c:827
msgid "Could not get domain sid\n"
msgstr ""

#: ../utils/net_groupmap.c:850
msgid "Create a new group mapping"
msgstr ""

#: ../utils/net_groupmap.c:851
msgid ""
"net groupmap add\n"
"    Create a new group mapping"
msgstr ""

#: ../utils/net_groupmap.c:858
msgid "Update a group mapping"
msgstr ""

#: ../utils/net_groupmap.c:859
msgid ""
"net groupmap modify\n"
"    Modify an existing group mapping"
msgstr ""

#: ../utils/net_groupmap.c:866
msgid "Remove a group mapping"
msgstr ""

#: ../utils/net_groupmap.c:867
msgid ""
"net groupmap delete\n"
"    Remove a group mapping"
msgstr ""

#: ../utils/net_groupmap.c:874
msgid "Set group mapping"
msgstr ""

#: ../utils/net_groupmap.c:875
msgid ""
"net groupmap set\n"
"    Set a group mapping"
msgstr ""

#: ../utils/net_groupmap.c:882
msgid "Remove foreign group mapping entries"
msgstr ""

#: ../utils/net_groupmap.c:883
msgid ""
"net groupmap cleanup\n"
"    Remove foreign group mapping entries"
msgstr ""

#: ../utils/net_groupmap.c:890
msgid "Add a foreign alias member"
msgstr ""

#: ../utils/net_groupmap.c:891
msgid ""
"net groupmap addmem\n"
"    Add a foreign alias member"
msgstr ""

#: ../utils/net_groupmap.c:898
msgid "Delete foreign alias member"
msgstr ""

#: ../utils/net_groupmap.c:899
msgid ""
"net groupmap delmem\n"
"    Delete foreign alias member"
msgstr ""

#: ../utils/net_groupmap.c:906
msgid "List foreign group members"
msgstr ""

#: ../utils/net_groupmap.c:907
msgid ""
"net groupmap listmem\n"
"    List foreign alias members"
msgstr ""

#: ../utils/net_groupmap.c:914
msgid "List foreign group memberships"
msgstr ""

#: ../utils/net_groupmap.c:915
msgid ""
"net groupmap memberships\n"
"    List foreign group memberships"
msgstr ""

#: ../utils/net_groupmap.c:922
msgid "List current group map"
msgstr ""

#: ../utils/net_groupmap.c:923
msgid ""
"net groupmap list\n"
"    List current group map"
msgstr ""

#: ../utils/net_help.c:39
#, c-format
msgid "net %s usage:\n"
msgstr ""

#: ../utils/net_help_common.c:25 ../utils/net_join.c:28
msgid "Valid methods: (auto-detected if not specified)\n"
msgstr ""

#: ../utils/net_help_common.c:26 ../utils/net_join.c:29
msgid "\tads\t\t\t\tActive Directory (LDAP/Kerberos)\n"
msgstr ""

#: ../utils/net_help_common.c:27 ../utils/net_join.c:30
msgid "\trpc\t\t\t\tDCE-RPC\n"
msgstr ""

#: ../utils/net_help_common.c:28
msgid "\trap\t\t\t\tRAP (older systems)\n"
msgstr ""

#: ../utils/net_help_common.c:35
msgid "Valid targets: choose one (none defaults to localhost)\n"
msgstr ""

#: ../utils/net_help_common.c:36
msgid "\t-S or --server=<server>\t\tserver name\n"
msgstr ""

#: ../utils/net_help_common.c:37
msgid "\t-I or --ipaddress=<ipaddr>\taddress of target server\n"
msgstr ""

#: ../utils/net_help_common.c:38
msgid "\t-w or --workgroup=<wg>\t\ttarget workgroup or domain\n"
msgstr ""

#: ../utils/net_help_common.c:41
#, fuzzy
msgid "Valid miscellaneous options are:\n"
msgstr "Sonstige Optionen"

#. misc options
#: ../utils/net_help_common.c:42
msgid "\t-p or --port=<port>\t\tconnection port on target\n"
msgstr ""

#: ../utils/net_help_common.c:43
msgid "\t-W or --myworkgroup=<wg>\tclient workgroup\n"
msgstr ""

#: ../utils/net_help_common.c:44
msgid "\t-d or --debuglevel=<level>\tdebug level (0-10)\n"
msgstr ""

#: ../utils/net_help_common.c:45
msgid "\t-n or --myname=<name>\t\tclient name\n"
msgstr ""

#: ../utils/net_help_common.c:46
msgid "\t-U or --user=<name>\t\tuser name\n"
msgstr ""

#: ../utils/net_help_common.c:47
msgid "\t-s or --configfile=<path>\tpathname of smb.conf file\n"
msgstr ""

#: ../utils/net_help_common.c:48
msgid "\t-l or --long\t\t\tDisplay full information\n"
msgstr ""

#: ../utils/net_help_common.c:49
msgid "\t-V or --version\t\t\tPrint samba version information\n"
msgstr ""

#: ../utils/net_help_common.c:50
msgid "\t-P or --machine-pass\t\tAuthenticate as machine account\n"
msgstr ""

#: ../utils/net_help_common.c:52
msgid "\t-e or --encrypt\t\t\tEncrypt SMB transport (UNIX extended servers only)\n"
msgstr ""

#: ../utils/net_help_common.c:54
msgid "\t-k or --kerberos\t\tUse kerberos (active directory) authentication\n"
msgstr ""

#: ../utils/net_idmap.c:25
msgid "Out of memory!\n"
msgstr ""

#: ../utils/net_idmap.c:39
#, c-format
msgid "USER HWM %d\n"
msgstr ""

#: ../utils/net_idmap.c:44
#, c-format
msgid "GROUP HWM %d\n"
msgstr ""

#: ../utils/net_idmap.c:63
msgid ""
"Usage:\n"
"net idmap dump <inputfile>\n"
"  Dump current ID mapping.\n"
"    inputfile\tTDB file to read mappings from.\n"
msgstr ""

#: ../utils/net_idmap.c:73
#, c-format
msgid "Could not open idmap: %s\n"
msgstr ""

#: ../utils/net_idmap.c:94
msgid ""
"Usage:\n"
"net idmap restore [inputfile]\n"
"  Restore ID mappings from file\n"
"    inputfile\tFile to load ID mappings from. If not given, load data from stdin.\n"
msgstr ""

#: ../utils/net_idmap.c:104
msgid "To use net idmap Winbindd must be running.\n"
msgstr ""

#: ../utils/net_idmap.c:142
#, c-format
msgid "Could not set USER HWM: %s\n"
msgstr ""

#: ../utils/net_idmap.c:151
#, c-format
msgid "Could not set GROUP HWM: %s\n"
msgstr ""

#: ../utils/net_idmap.c:156
#, c-format
msgid "ignoring invalid line [%s]\n"
msgstr ""

#: ../utils/net_idmap.c:163
#, c-format
msgid "ignoring invalid sid [%s]: %s\n"
msgstr ""

#: ../utils/net_idmap.c:175
#, c-format
msgid "Could not set mapping of %s %lu to sid %s: %s\n"
msgstr ""

#: ../utils/net_idmap.c:196 ../utils/net_idmap.c:202
msgid "Not Implemented yet\n"
msgstr ""

#: ../utils/net_idmap.c:240
msgid ""
"Usage:\n"
"net idmap secret {<DOMAIN>|alloc} <secret>\n"
"  Set the secret for the specified domain (or alloc module)\n"
"    DOMAIN\tDomain to set secret for.\n"
"    alloc\tSet secret for the alloc module\n"
"    secret\tNew secret to set.\n"
msgstr ""

#: ../utils/net_idmap.c:271
msgid "The only currently supported backend is LDAP\n"
msgstr ""

#: ../utils/net_idmap.c:281
#, c-format
msgid "Missing ldap_user_dn option for domain %s\n"
msgstr ""

#: ../utils/net_idmap.c:292
msgid "Missing ldap_user_dn option for alloc backend\n"
msgstr ""

#: ../utils/net_idmap.c:302
msgid "Failed to store secret\n"
msgstr ""

#: ../utils/net_idmap.c:307
msgid "Secret stored\n"
msgstr ""

#: ../utils/net_idmap.c:313
msgid ""
"net idmap dump <inputfile>\n"
"    Dump current id mapping\n"
msgstr ""

#: ../utils/net_idmap.c:316
msgid ""
"net idmap restore\n"
"    Restore entries from stdin\n"
msgstr ""

#. Deliberately *not* document net idmap delete
#: ../utils/net_idmap.c:321
msgid ""
"net idmap secret <DOMAIN>|alloc <secret>\n"
"    Set the secret for the specified DOMAIN (or the alloc module)\n"
msgstr ""

#: ../utils/net_idmap.c:339
msgid "usage: net idmap aclmapset <tdb> <src-sid> <dst-sid>\n"
msgstr ""

#: ../utils/net_idmap.c:351
#, fuzzy, c-format
msgid "db_open failed: %s\n"
msgstr "Passwortverwaltung"

#: ../utils/net_idmap.c:356 ../utils/net_idmap.c:361
#, c-format
msgid "%s is not a valid sid\n"
msgstr ""

#: ../utils/net_idmap.c:367
msgid "talloc_strdup failed\n"
msgstr ""

#: ../utils/net_idmap.c:373
msgid "could not fetch db record\n"
msgstr ""

#: ../utils/net_idmap.c:381
#, c-format
msgid "could not store record: %s\n"
msgstr ""

#: ../utils/net_idmap.c:402
msgid "Dump the current ID mappings"
msgstr ""

#: ../utils/net_idmap.c:403
msgid ""
"net idmap dump\n"
"  Dump the current ID mappings"
msgstr ""

#: ../utils/net_idmap.c:410
msgid "Restore entries from stdin"
msgstr ""

#: ../utils/net_idmap.c:411
msgid ""
"net idmap restore\n"
"  Restore entries from stdin"
msgstr ""

#: ../utils/net_idmap.c:418 ../utils/net_idmap.c:426
msgid "Not implemented yet"
msgstr ""

#: ../utils/net_idmap.c:419
msgid ""
"net idmap setmap\n"
"  Not implemented yet"
msgstr ""

#: ../utils/net_idmap.c:427
msgid ""
"net idmap delete\n"
"  Not implemented yet"
msgstr ""

#: ../utils/net_idmap.c:434
msgid "Set secret for specified domain"
msgstr ""

#: ../utils/net_idmap.c:435
msgid ""
"net idmap secret {<DOMAIN>|alloc} <secret>\n"
"  Set secret for specified domain or alloc module"
msgstr ""

#: ../utils/net_idmap.c:442
msgid "Set acl map"
msgstr ""

#: ../utils/net_idmap.c:443
msgid ""
"net idmap aclmapset\n"
"  Set acl map"
msgstr ""

#: ../utils/net_join.c:26
msgid ""
"\n"
"net [<method>] join [misc. options]\n"
"\tjoins this server to a domain\n"
msgstr ""

#: ../utils/net_join.c:47
msgid "ADS join did not work, falling back to RPC...\n"
msgstr ""

#: ../utils/net_lookup.c:25
msgid ""
"  net lookup [host] HOSTNAME[#<type>]\n"
"\tgives IP for a hostname\n"
"\n"
"  net lookup ldap [domain]\n"
"\tgives IP of domain's ldap server\n"
"\n"
"  net lookup kdc [realm]\n"
"\tgives IP of realm's kerberos KDC\n"
"\n"
"  net lookup pdc [domain|realm]\n"
"\tgives IP of realm's kerberos KDC\n"
"\n"
"  net lookup dc [domain]\n"
"\tgives IP of domains Domain Controllers\n"
"\n"
"  net lookup master [domain|wg]\n"
"\tgive IP of master browser\n"
"\n"
"  net lookup name [name]\n"
"\tLookup name's sid and type\n"
"\n"
"  net lookup sid [sid]\n"
"\tGive sid's name and type\n"
"\n"
"  net lookup dsgetdcname [name] [flags] [sitename]\n"
"\n"
msgstr ""

#: ../utils/net_lookup.c:112
msgid "net_lookup_ldap: talloc_init() failed!\n"
msgstr ""

#: ../utils/net_lookup.c:325
msgid "usage: net lookup name <name>\n"
msgstr ""

#: ../utils/net_lookup.c:331 ../utils/net_lookup.c:358
#, c-format
msgid "Could not lookup name %s\n"
msgstr ""

#: ../utils/net_lookup.c:347
msgid "usage: net lookup sid <sid>\n"
msgstr ""

#: ../utils/net_lookup.c:352
#, c-format
msgid "Could not convert %s to SID\n"
msgstr ""

#: ../utils/net_lookup.c:378
msgid "usage: net lookup dsgetdcname <name> <flags> <sitename>\n"
msgstr ""

#: ../utils/net_lookup.c:404
#, c-format
msgid "failed with: %s\n"
msgstr ""

#: ../utils/net_lookup.c:437
msgid ""
"\n"
"Usage: \n"
msgstr ""

#: ../utils/net_lua.c:60
msgid "connect: Expected IP-Address"
msgstr ""

#: ../utils/net_lua.c:65
msgid "connect: Expected port"
msgstr ""

#: ../utils/net_lua.c:84
#, fuzzy, c-format
msgid "connect failed: %s"
msgstr "Passwortverwaltung"

#: ../utils/net_lua.c:132
#, c-format
msgid "socket domain %s unknown"
msgstr ""

#: ../utils/net_lua.c:144
#, c-format
msgid "socket type %s unknown"
msgstr ""

#: ../utils/net_lua.c:155
#, fuzzy, c-format
msgid "socket() failed: %s"
msgstr "Passwortverwaltung"

#: ../utils/net_lua.c:278
msgid "evt_reference_thread failed\n"
msgstr ""

#: ../utils/net_lua.c:287
msgid "event_add_timed failed"
msgstr ""

#: ../utils/net_lua.c:300
msgid "event_once called from non-base thread"
msgstr ""

#: ../utils/net_lua.c:323
msgid "event_context_init failed"
msgstr ""

#: ../utils/net_lua.c:353
msgid "lua_newstate failed\n"
msgstr ""

#: ../utils/net_lua.c:371
msgid "luaL_dofile returned an error\n"
msgstr ""

#: ../utils/net_lua.c:376
msgid "luaL_dostring returned an error\n"
msgstr ""
