#!/bin/sh
# Copyright (C) 2003 TAKAHASHI Motonobu <monyo@samba.org>
# Copyright (C) 2009 Kai Blin  <kai@samba.org>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, see <http://www.gnu.org/licenses/>.
#
add_basedir_to_filelist() {
	BASEDIR="$1"
	shift;
	FILELIST="$@"
	FULL_LIST=""
	for file in ${FILELIST}; do
		FULL_LIST="${FULL_LIST} $BASEDIR/${file}"
	done
	echo ${FULL_LIST}
}

NET_FILES=`add_basedir_to_filelist ../utils net.c net_ads.c net_ads_gpo.c \
	   net_afs.c net_cache.c net_conf.c net_dom.c net_eventlog.c \
	   net_file.c net_group.c net_groupmap.c net_help.c net_help_common.c`

FILES="../web/swat.c ../web/statuspage.c ../param/loadparm.c ${NET_FILES}"
LANGS='en ja tr pl fr de it ru'

XGETTEXT=xgettext
MSGMERGE=msgmerge

WIDTH=256

$XGETTEXT --default-domain="i18n_swat" \
  --add-comments \
  --keyword=_ --keyword=N_  \
  --width=${WIDTH} \
  $FILES

for lang in $LANGS; do
  printf "%s" "$lang"
  mv ${lang}.msg ${lang}.msg.old
  $MSGMERGE --width=${WIDTH} ${lang}.msg.old i18n_swat.po -o ${lang}.msg
done

rm i18n_swat.po

