# Russian messages for international release of SWAT.
# Copyright (C) 2007 Yuri Kozlov <kozlov.y@gmail.com>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, see <http://www.gnu.org/licenses/>.
#
msgid ""
msgstr ""
"Project-Id-Version: swat\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-07-29 23:59+0200\n"
"PO-Revision-Date: 2007-06-27 22:00+0400\n"
"Last-Translator: Yuri Kozlov <kozlov.y@gmail.com>\n"
"Language-Team: Russian <debian-l10n-russian@lists.debian.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: KBabel 1.11.4\n"
"Plural-Forms:  nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"

#: ../web/swat.c:153
#, c-format
msgid "ERROR: Can't open %s"
msgstr "ОШИБКА: Не удалось открыть %s"

#: ../web/swat.c:241
msgid "Help"
msgstr "Справка"

#: ../web/swat.c:247 ../web/swat.c:272 ../web/swat.c:293 ../web/swat.c:302 ../web/swat.c:311 ../web/swat.c:317 ../web/swat.c:329 ../web/swat.c:343
msgid "Set Default"
msgstr "Установить по умолчанию"

#: ../web/swat.c:465
#, c-format
msgid "failed to open %s for writing"
msgstr "не удалось открыть %s для записи"

#: ../web/swat.c:488
#, c-format
msgid "Can't reload %s"
msgstr "Невозможно перезагрузить %s"

#: ../web/swat.c:561
#, c-format
msgid "Logged in as <b>%s</b>"
msgstr "Осуществлён вход под именем <b>%s</b>"

#: ../web/swat.c:565
msgid "Home"
msgstr "Главная"

#: ../web/swat.c:567
msgid "Globals"
msgstr "Глобальные"

#: ../web/swat.c:568
msgid "Shares"
msgstr "Ресурсы"

#: ../web/swat.c:569
msgid "Printers"
msgstr "Принтеры"

#: ../web/swat.c:570
msgid "Wizard"
msgstr "Помощник"

#: ../web/swat.c:574
msgid "Status"
msgstr "Состояние"

#: ../web/swat.c:575
msgid "View Config"
msgstr "Настройки"

#: ../web/swat.c:577
msgid "Password Management"
msgstr "Пароли"

#: ../web/swat.c:587
msgid "Current View Is"
msgstr "Текущий вид"

#: ../web/swat.c:588 ../web/swat.c:591
msgid "Basic"
msgstr "Простой"

#: ../web/swat.c:589 ../web/swat.c:592
msgid "Advanced"
msgstr "Сложный"

#: ../web/swat.c:590
msgid "Change View To"
msgstr "Сменить вид на"

#: ../web/swat.c:619
msgid "Current Config"
msgstr "Текущий файл конфигурации"

#: ../web/swat.c:623
msgid "Normal View"
msgstr "Обычный вид"

#: ../web/swat.c:625
msgid "Full View"
msgstr "Полный вид"

#. Here we first set and commit all the parameters that were selected
#. in the previous screen.
#: ../web/swat.c:644
msgid "Wizard Parameter Edit Page"
msgstr "Страница редактирования параметров помощника"

#: ../web/swat.c:673
msgid "Note: smb.conf file has been read and rewritten"
msgstr "Замечание: файл smb.conf был прочитан и перезаписан"

#. Here we go ...
#: ../web/swat.c:779
msgid "Samba Configuration Wizard"
msgstr "Помощник настройки Samba"

#: ../web/swat.c:783
msgid "The \"Rewrite smb.conf file\" button will clear the smb.conf file of all default values and of comments."
msgstr "По кнопке \"Перезаписать файл smb.conf\" в файл smb.conf записываются все значения по умолчанию с комментариями."

#: ../web/swat.c:784
msgid "The same will happen if you press the commit button."
msgstr "То же самое произойдёт при нажатии кнопки сохранения."

#: ../web/swat.c:787
msgid "Rewrite smb.conf file"
msgstr "Перезаписать файл smb.conf"

#: ../web/swat.c:788
msgid "Commit"
msgstr "Сохранить"

#: ../web/swat.c:789
msgid "Edit Parameter Values"
msgstr "Редактировать значения параметров"

#: ../web/swat.c:795
msgid "Server Type"
msgstr "Тип сервера"

#: ../web/swat.c:796
msgid "Stand Alone"
msgstr "Независимый"

#: ../web/swat.c:797
msgid "Domain Member"
msgstr "Член домена"

#: ../web/swat.c:798
msgid "Domain Controller"
msgstr "Контроллер домена"

#: ../web/swat.c:801
msgid "Unusual Type in smb.conf - Please Select New Mode"
msgstr "Необычный тип в smb.conf - Выберите новый режим"

#: ../web/swat.c:803
msgid "Configure WINS As"
msgstr "Настроить WINS как"

#: ../web/swat.c:804
msgid "Not Used"
msgstr "Не использовать"

#: ../web/swat.c:805
msgid "Server for client use"
msgstr "Сервер для клиентов"

#: ../web/swat.c:806
msgid "Client of another WINS server"
msgstr "Клиент другого сервера WINS"

#: ../web/swat.c:808
msgid "Remote WINS Server"
msgstr "Удалённый сервер WINS"

#: ../web/swat.c:819
msgid "Error: WINS Server Mode and WINS Support both set in smb.conf"
msgstr "Ошибка: в smb.conf установлены одновременно режим сервера WINS и поддержка WINS"

#: ../web/swat.c:820
msgid "Please Select desired WINS mode above."
msgstr "Выберите желаемый режим WINS."

#: ../web/swat.c:822
msgid "Expose Home Directories"
msgstr "Сделать доступными домашние каталоги"

#: ../web/swat.c:837
msgid "The above configuration options will set multiple parameters and will generally assist with rapid Samba deployment."
msgstr "Выбор параметров выше приводит к автоматической настройке большего числа параметров, и помогает в сокращении времени развёртывания Samba."

#: ../web/swat.c:850
msgid "Global Parameters"
msgstr "Глобальные параметры"

#: ../web/swat.c:878 ../web/swat.c:986 ../web/swat.c:1344
msgid "Commit Changes"
msgstr "Сохранить изменения"

#: ../web/swat.c:882 ../web/swat.c:989 ../web/swat.c:1346
msgid "Reset Values"
msgstr "Реинициализировать значения"

#: ../web/swat.c:908
msgid "Share Parameters"
msgstr "Параметры общих ресурсов"

#: ../web/swat.c:955
msgid "Choose Share"
msgstr "Выбрать ресурс"

#: ../web/swat.c:971
msgid "Delete Share"
msgstr "Удалить ресурс"

#: ../web/swat.c:978
msgid "Create Share"
msgstr "Создать ресурс"

#: ../web/swat.c:1014
msgid "password change in demo mode rejected"
msgstr "смена пароля в демо-режиме не работает"

#: ../web/swat.c:1028
msgid "Can't setup password database vectors."
msgstr "Не удалось настроить векторы базы данных паролей."

#: ../web/swat.c:1056
msgid " Must specify \"User Name\" "
msgstr " Должно быть указано \"Имя пользователя\" "

#: ../web/swat.c:1072
msgid " Must specify \"Old Password\" "
msgstr " Должен быть указан \"Старый пароль\" "

#: ../web/swat.c:1078
msgid " Must specify \"Remote Machine\" "
msgstr " Должна быть указана \"Удалённая машина\" "

#: ../web/swat.c:1085
msgid " Must specify \"New, and Re-typed Passwords\" "
msgstr "  Должен быть указан \"Новый пароль, введённый дважды\" "

#: ../web/swat.c:1091
msgid " Re-typed password didn't match new password "
msgstr " Повторно набранный новый пароль не совпадает с новым паролем "

#: ../web/swat.c:1124
#, c-format
msgid " The passwd for '%s' has been changed."
msgstr " Был изменён пароль для '%s'."

#: ../web/swat.c:1127
#, c-format
msgid " The passwd for '%s' has NOT been changed."
msgstr " Пароль для '%s' НЕ был изменён."

#: ../web/swat.c:1152
msgid "Server Password Management"
msgstr "Управление паролями сервера"

#.
#. * Create all the dialog boxes for data collection
#.
#: ../web/swat.c:1161 ../web/swat.c:1208
msgid "User Name"
msgstr "Имя пользователя"

#: ../web/swat.c:1164 ../web/swat.c:1210
msgid "Old Password"
msgstr "Старый пароль"

#: ../web/swat.c:1167 ../web/swat.c:1212
msgid "New Password"
msgstr "Новый пароль"

#: ../web/swat.c:1169 ../web/swat.c:1214
msgid "Re-type New Password"
msgstr "Новый пароль ещё раз"

#: ../web/swat.c:1177 ../web/swat.c:1225
msgid "Change Password"
msgstr "Сменить пароль"

#: ../web/swat.c:1180
msgid "Add New User"
msgstr "Добавить нового пользователя"

#: ../web/swat.c:1182
msgid "Delete User"
msgstr "Удалить пользователя"

#: ../web/swat.c:1184
msgid "Disable User"
msgstr "Заблокировать пользователя"

#: ../web/swat.c:1186
msgid "Enable User"
msgstr "Разблокировать пользователя"

#: ../web/swat.c:1199
msgid "Client/Server Password Management"
msgstr "Управление паролями в режиме клиент/сервер"

#: ../web/swat.c:1216
msgid "Remote Machine"
msgstr "Удалённая машина"

#: ../web/swat.c:1255
msgid "Printer Parameters"
msgstr "Параметры принтера"

#: ../web/swat.c:1257
msgid "Important Note:"
msgstr "Важное замечание:"

#: ../web/swat.c:1258
msgid "Printer names marked with [*] in the Choose Printer drop-down box "
msgstr "Имена принтеров, помеченные [*] в выпадающем списке принтеров, "

#: ../web/swat.c:1259
msgid "are autoloaded printers from "
msgstr "были автоматически загружены согласно параметру "

#: ../web/swat.c:1260
msgid "Printcap Name"
msgstr "Printcap Name"

#: ../web/swat.c:1261
msgid "Attempting to delete these printers from SWAT will have no effect."
msgstr ". Попытка удалить эти принтеры из SWAT ни к чему не приведёт."

#: ../web/swat.c:1310
msgid "Choose Printer"
msgstr "Выбрать принтер"

#: ../web/swat.c:1329
msgid "Delete Printer"
msgstr "Удалить принтер"

#: ../web/swat.c:1336
msgid "Create Printer"
msgstr "Создать принтер"

#: ../web/statuspage.c:151
msgid "RDWR       "
msgstr "RDWR       "

#: ../web/statuspage.c:153
msgid "WRONLY     "
msgstr "WRONLY     "

#: ../web/statuspage.c:155
msgid "RDONLY     "
msgstr "RDONLY     "

#: ../web/statuspage.c:329
msgid "Server Status"
msgstr "Состояние сервера"

#: ../web/statuspage.c:334
msgid "Auto Refresh"
msgstr "Включить автообновление"

#: ../web/statuspage.c:335 ../web/statuspage.c:340
msgid "Refresh Interval: "
msgstr "Интервал автообновления: "

#: ../web/statuspage.c:339
msgid "Stop Refreshing"
msgstr "Выключить автообновление"

#: ../web/statuspage.c:348
msgid "version:"
msgstr "версия:"

#: ../web/statuspage.c:351
msgid "smbd:"
msgstr "smbd:"

#: ../web/statuspage.c:351 ../web/statuspage.c:364 ../web/statuspage.c:378
msgid "running"
msgstr "работает"

#: ../web/statuspage.c:351 ../web/statuspage.c:364 ../web/statuspage.c:378
msgid "not running"
msgstr "не работает"

#: ../web/statuspage.c:355
msgid "Stop smbd"
msgstr "Остановить smbd"

#: ../web/statuspage.c:357
msgid "Start smbd"
msgstr "Запустить smbd"

#: ../web/statuspage.c:359
msgid "Restart smbd"
msgstr "Перезапустить smbd"

#: ../web/statuspage.c:364
msgid "nmbd:"
msgstr "nmbd:"

#: ../web/statuspage.c:368
msgid "Stop nmbd"
msgstr "Остановить nmbd"

#: ../web/statuspage.c:370
msgid "Start nmbd"
msgstr "Запустить nmbd"

#: ../web/statuspage.c:372
msgid "Restart nmbd"
msgstr "Перезапустить nmbd"

#: ../web/statuspage.c:378
msgid "winbindd:"
msgstr "winbindd:"

#: ../web/statuspage.c:382
msgid "Stop winbindd"
msgstr "Остановить winbindd"

#: ../web/statuspage.c:384
msgid "Start winbindd"
msgstr "Запустить winbindd"

#: ../web/statuspage.c:386
msgid "Restart winbindd"
msgstr "Перезапустить winbindd"

#. stop, restart all
#: ../web/statuspage.c:395
msgid "Stop All"
msgstr "Остановить всё"

#: ../web/statuspage.c:396
msgid "Restart All"
msgstr "Перезапустить всё"

#. start all
#: ../web/statuspage.c:400
msgid "Start All"
msgstr "Запустить всё"

#: ../web/statuspage.c:407
msgid "Active Connections"
msgstr "Активные подключения"

#: ../web/statuspage.c:409 ../web/statuspage.c:422 ../web/statuspage.c:431
msgid "PID"
msgstr "PID"

#: ../web/statuspage.c:409 ../web/statuspage.c:422
msgid "Client"
msgstr "Клиент"

#: ../web/statuspage.c:409
msgid "IP address"
msgstr "IP-адрес"

#: ../web/statuspage.c:409 ../web/statuspage.c:422 ../web/statuspage.c:431
msgid "Date"
msgstr "Дата"

#: ../web/statuspage.c:411
msgid "Kill"
msgstr "Отключить"

#: ../web/statuspage.c:419
msgid "Active Shares"
msgstr "Активные ресурсы"

#: ../web/statuspage.c:422
msgid "Share"
msgstr "Ресурс"

#: ../web/statuspage.c:422
msgid "User"
msgstr "Пользователь"

#: ../web/statuspage.c:422
msgid "Group"
msgstr "Группа"

#: ../web/statuspage.c:428
msgid "Open Files"
msgstr "Открытые файлы"

#: ../web/statuspage.c:431
#, fuzzy
msgid "UID"
msgstr "PID"

#: ../web/statuspage.c:431
msgid "Sharing"
msgstr "Ресурс"

#: ../web/statuspage.c:431
msgid "R/W"
msgstr "R/W"

#: ../web/statuspage.c:431
msgid "Oplock"
msgstr "Oplock"

#: ../web/statuspage.c:431
msgid "File"
msgstr "Файл"

#: ../web/statuspage.c:438
msgid "Show Client in col 1"
msgstr "Показать клиента в колонке 1"

#: ../web/statuspage.c:439
msgid "Show PID in col 1"
msgstr "Показать PID в колонке 1"

#: ../param/loadparm.c:907
msgid "Base Options"
msgstr "Основные параметры"

#: ../param/loadparm.c:1047
msgid "Security Options"
msgstr "Параметры безопасности"

#: ../param/loadparm.c:1800
msgid "Logging Options"
msgstr "Параметры журнала"

#: ../param/loadparm.c:1929
msgid "Protocol Options"
msgstr "Параметры протокола"

#: ../param/loadparm.c:2301
msgid "Tuning Options"
msgstr "Параметры детальной настройки"

#: ../param/loadparm.c:2538
msgid "Printing Options"
msgstr "Параметры печати"

#: ../param/loadparm.c:2858
msgid "Filename Handling"
msgstr "Обработка имён файлов"

#: ../param/loadparm.c:3088
msgid "Domain Options"
msgstr "Параметры домена"

#: ../param/loadparm.c:3100
msgid "Logon Options"
msgstr "Параметры входа"

#: ../param/loadparm.c:3273
msgid "Browse Options"
msgstr "Параметры обзора"

#: ../param/loadparm.c:3384
msgid "WINS Options"
msgstr "Параметры WINS"

#: ../param/loadparm.c:3432
msgid "Locking Options"
msgstr "Параметры блокировки"

#: ../param/loadparm.c:3552
msgid "Ldap Options"
msgstr "Параметры Ldap"

#: ../param/loadparm.c:3708
msgid "EventLog Options"
msgstr "Параметры EventLog"

#: ../param/loadparm.c:3720
msgid "Miscellaneous Options"
msgstr "Различные параметры"

#: ../param/loadparm.c:4301
msgid "VFS module options"
msgstr "Параметры модуля VFS"

#: ../param/loadparm.c:4323
#, fuzzy
msgid "MSDFS options"
msgstr "Параметры модуля VFS"

#: ../param/loadparm.c:4353
msgid "Winbind options"
msgstr "Параметры Winbind"

#: ../utils/net.c:103
msgid "Enter machine password: "
msgstr ""

#: ../utils/net.c:107
msgid "Unable to write the machine account password in the secrets database"
msgstr ""

#: ../utils/net.c:111
msgid "Modified trust account password in secrets database\n"
msgstr ""

#: ../utils/net.c:115
msgid ""
"Machine account password change requires the -f flag.\n"
"Do NOT use this function unless you know what it does!\n"
"This function will change the ADS Domain member machine account password in the secrets.tdb file!\n"
msgstr ""

#: ../utils/net.c:150 ../utils/net.c:228
#, c-format
msgid "Unable to open secrets.tdb.  Can't fetch domain SID for name: %s\n"
msgstr ""

#: ../utils/net.c:163 ../utils/net.c:251
#, c-format
msgid "SID for domain %s is: %s\n"
msgstr ""

#: ../utils/net.c:175
msgid "usage: net setlocalsid S-1-5-21-x-y-z\n"
msgstr ""

#: ../utils/net.c:195
msgid "usage: net setdomainsid S-1-5-21-x-y-z\n"
msgstr ""

#: ../utils/net.c:213
msgid "usage: net getdomainsid\n"
msgstr ""

#: ../utils/net.c:238
msgid "Could not fetch local SID\n"
msgstr ""

#: ../utils/net.c:242
#, c-format
msgid "SID for local machine %s is: %s\n"
msgstr ""

#: ../utils/net.c:246
msgid "Could not fetch domain SID\n"
msgstr ""

#: ../utils/net.c:263
#, c-format
msgid "get_maxrid: Could not search %s\n"
msgstr ""

#: ../utils/net.c:297
msgid "usage: net maxrid\n"
msgstr ""

#: ../utils/net.c:302
msgid "can't get current maximum rid\n"
msgstr ""

#: ../utils/net.c:306
#, c-format
msgid "Currently used maximum rid: %d\n"
msgstr ""

#: ../utils/net.c:317
msgid "Run functions using RPC transport"
msgstr ""

#: ../utils/net.c:318
msgid "  Use 'net help rpc' to get more extensive information about 'net rpc' commands."
msgstr ""

#: ../utils/net.c:325
msgid "Run functions using RAP transport"
msgstr ""

#: ../utils/net.c:326
msgid "  Use 'net help rap' to get more extensive information about 'net rap' commands."
msgstr ""

#: ../utils/net.c:333
msgid "Run functions using ADS transport"
msgstr ""

#: ../utils/net.c:334
msgid "  Use 'net help ads' to get more extensive information about 'net ads' commands."
msgstr ""

#: ../utils/net.c:343
msgid "Functions on remote opened files"
msgstr ""

#: ../utils/net.c:344
msgid "  Use 'net help file' to get more information about 'net file' commands."
msgstr ""

#: ../utils/net.c:351
msgid "Functions on shares"
msgstr ""

#: ../utils/net.c:352
msgid "  Use 'net help share' to get more information about 'net share' commands."
msgstr ""

#: ../utils/net.c:359
msgid "Manage sessions"
msgstr ""

#: ../utils/net.c:360
msgid "  Use 'net help session' to get more information about 'net session' commands."
msgstr ""

#: ../utils/net.c:367
msgid "List servers in workgroup"
msgstr ""

#: ../utils/net.c:368
msgid "  Use 'net help server' to get more information about 'net server' commands."
msgstr ""

#: ../utils/net.c:375
msgid "List domains/workgroups on network"
msgstr ""

#: ../utils/net.c:376
msgid "  Use 'net help domain' to get more information about 'net domain' commands."
msgstr ""

#: ../utils/net.c:383
msgid "Modify printer queue"
msgstr ""

#: ../utils/net.c:384
msgid "  Use 'net help printq' to get more information about 'net printq' commands."
msgstr ""

#: ../utils/net.c:391
#, fuzzy
msgid "Manage users"
msgstr "Разблокировать пользователя"

#: ../utils/net.c:392
msgid "  Use 'net help user' to get more information about 'net user' commands."
msgstr ""

#: ../utils/net.c:399
msgid "Manage groups"
msgstr ""

#: ../utils/net.c:400
msgid "  Use 'net help group' to get more information about 'net group' commands."
msgstr ""

#: ../utils/net.c:407
msgid "Manage group mappings"
msgstr ""

#: ../utils/net.c:408
msgid "  Use 'net help groupmap' to get more information about 'net groupmap' commands."
msgstr ""

#: ../utils/net.c:415
msgid "Functions on the SAM database"
msgstr ""

#: ../utils/net.c:416
msgid "  Use 'net help sam' to get more information about 'net sam' commands."
msgstr ""

#: ../utils/net.c:423
msgid "Validate username and password"
msgstr ""

#: ../utils/net.c:424
msgid "  Use 'net help validate' to get more information about 'net validate' commands."
msgstr ""

#: ../utils/net.c:431
msgid "Modify group memberships"
msgstr ""

#: ../utils/net.c:432
msgid "  Use 'net help groupmember' to get more information about 'net groupmember' commands."
msgstr ""

#: ../utils/net.c:438
msgid "Execute remote command on a remote OS/2 server"
msgstr ""

#: ../utils/net.c:439
msgid "  Use 'net help admin' to get more information about 'net admin' commands."
msgstr ""

#: ../utils/net.c:445
msgid "List/modify running services"
msgstr ""

#: ../utils/net.c:446
msgid "  Use 'net help service' to get more information about 'net service' commands."
msgstr ""

#: ../utils/net.c:453
#, fuzzy
msgid "Change user password on target server"
msgstr "Не удалось настроить векторы базы данных паролей."

#: ../utils/net.c:454
msgid "  Use 'net help password' to get more information about 'net password' commands."
msgstr ""

#: ../utils/net.c:460
#, fuzzy
msgid "Change the trust password"
msgstr "Сменить пароль"

#: ../utils/net.c:461
msgid "  Use 'net help changetrustpw' to get more information about 'net changetrustpw'."
msgstr ""

#: ../utils/net.c:467
#, fuzzy
msgid "Change the secret password"
msgstr "Сменить пароль"

#: ../utils/net.c:468
msgid ""
"  net [options] changesecretpw\n"
"    Change the ADS domain member machine account password in secrets.tdb.\n"
"    Do NOT use this function unless you know what it does.\n"
"    Requires the -f flag to work."
msgstr ""

#: ../utils/net.c:477
msgid "Show/set time"
msgstr ""

#: ../utils/net.c:478
msgid "  Use 'net help time' to get more information about 'net time' commands."
msgstr ""

#: ../utils/net.c:484
msgid "Look up host names/IP addresses"
msgstr ""

#: ../utils/net.c:485
msgid "  Use 'net help lookup' to get more information about 'net lookup' commands."
msgstr ""

#: ../utils/net.c:491
msgid "Join a domain/AD"
msgstr ""

#: ../utils/net.c:492
msgid "  Use 'net help join' to get more information about 'net join'."
msgstr ""

#: ../utils/net.c:498
msgid "Join/unjoin (remote) machines to/from a domain/AD"
msgstr ""

#: ../utils/net.c:499
msgid "  Use 'net help dom' to get more information about 'net dom' commands."
msgstr ""

#: ../utils/net.c:505
msgid "Operate on the cache tdb file"
msgstr ""

#: ../utils/net.c:506
msgid "  Use 'net help cache' to get more information about 'net cache' commands."
msgstr ""

#: ../utils/net.c:512
msgid "Get the SID for the local domain"
msgstr ""

#: ../utils/net.c:513
msgid "  net getlocalsid"
msgstr ""

#: ../utils/net.c:518
msgid "Set the SID for the local domain"
msgstr ""

#: ../utils/net.c:519
msgid "  net setlocalsid S-1-5-21-x-y-z"
msgstr ""

#: ../utils/net.c:524
msgid "Set domain SID on member servers"
msgstr ""

#: ../utils/net.c:525
msgid "  net setdomainsid S-1-5-21-x-y-z"
msgstr ""

#: ../utils/net.c:530
msgid "Get domain SID on member servers"
msgstr ""

#: ../utils/net.c:531
msgid "  net getdomainsid"
msgstr ""

#: ../utils/net.c:536
msgid "Display the maximul RID currently used"
msgstr ""

#: ../utils/net.c:537
msgid "  net maxrid"
msgstr ""

#: ../utils/net.c:542
#, fuzzy
msgid "IDmap functions"
msgstr "Параметры домена"

#: ../utils/net.c:543
msgid "  Use 'net help idmap to get more information about 'net idmap' commands."
msgstr ""

#: ../utils/net.c:549
#, fuzzy
msgid "Display server status"
msgstr "Состояние сервера"

#: ../utils/net.c:550
msgid "  Use 'net help status' to get more information about 'net status' commands."
msgstr ""

#: ../utils/net.c:556
msgid "Manage user-modifiable shares"
msgstr ""

#: ../utils/net.c:557
msgid "  Use 'net help usershare to get more information about 'net usershare' commands."
msgstr ""

#: ../utils/net.c:563
msgid "Display list of all users with SID"
msgstr ""

#: ../utils/net.c:564
msgid "  Use 'net help usersidlist' to get more information about 'net usersidlist'."
msgstr ""

#: ../utils/net.c:570
msgid "Manage Samba registry based configuration"
msgstr ""

#: ../utils/net.c:571
msgid "  Use 'net help conf' to get more information about 'net conf' commands."
msgstr ""

#: ../utils/net.c:577
msgid "Manage the Samba registry"
msgstr ""

#: ../utils/net.c:578
msgid "  Use 'net help registry' to get more information about 'net registry' commands."
msgstr ""

#: ../utils/net.c:584
msgid "Open a lua interpreter"
msgstr ""

#: ../utils/net.c:585
msgid "  Use 'net help lua' to get more information about 'net lua' commands."
msgstr ""

#: ../utils/net.c:591
msgid "Process Win32 *.evt eventlog files"
msgstr ""

#: ../utils/net.c:592
msgid "  Use 'net help eventlog' to get more information about 'net eventlog' commands."
msgstr ""

#: ../utils/net.c:600
msgid "Manage AFS tokens"
msgstr ""

#: ../utils/net.c:601
msgid "  Use 'net help afs' to get more information about 'net afs' commands."
msgstr ""

#: ../utils/net.c:609
msgid "Print usage information"
msgstr ""

#: ../utils/net.c:610
msgid "  Use 'net help help' to list usage information for 'net' commands."
msgstr ""

#: ../utils/net.c:639
msgid "Encrypt SMB transport (UNIX extended servers only)"
msgstr ""

#: ../utils/net.c:703
msgid ""
"\n"
"Invalid ip address specified\n"
msgstr ""

#: ../utils/net.c:718
#, c-format
msgid ""
"\n"
"Invalid option %s: %s\n"
msgstr ""

#: ../utils/net_ads.c:52 ../utils/net_ads.c:392
msgid "CLDAP query failed!\n"
msgstr ""

#: ../utils/net_ads.c:56
#, fuzzy, c-format
msgid ""
"Information for Domain Controller: %s\n"
"\n"
msgstr "Контроллер домена"

#: ../utils/net_ads.c:59
msgid "Response Type: "
msgstr ""

#: ../utils/net_ads.c:72
#, c-format
msgid "GUID: %s\n"
msgstr ""

#: ../utils/net_ads.c:74
#, c-format
msgid ""
"Flags:\n"
"\tIs a PDC:                                   %s\n"
"\tIs a GC of the forest:                      %s\n"
"\tIs an LDAP server:                          %s\n"
"\tSupports DS:                                %s\n"
"\tIs running a KDC:                           %s\n"
"\tIs running time services:                   %s\n"
"\tIs the closest DC:                          %s\n"
"\tIs writable:                                %s\n"
"\tHas a hardware clock:                       %s\n"
"\tIs a non-domain NC serviced by LDAP server: %s\n"
"\tIs NT6 DC that has some secrets:            %s\n"
"\tIs NT6 DC that has all secrets:             %s\n"
msgstr ""

#: ../utils/net_ads.c:87 ../utils/net_ads.c:88 ../utils/net_ads.c:89 ../utils/net_ads.c:90 ../utils/net_ads.c:91 ../utils/net_ads.c:92 ../utils/net_ads.c:93 ../utils/net_ads.c:94 ../utils/net_ads.c:95 ../utils/net_ads.c:96 ../utils/net_ads.c:97
#: ../utils/net_ads.c:98
msgid "yes"
msgstr ""

#: ../utils/net_ads.c:87 ../utils/net_ads.c:88 ../utils/net_ads.c:89 ../utils/net_ads.c:90 ../utils/net_ads.c:91 ../utils/net_ads.c:92 ../utils/net_ads.c:93 ../utils/net_ads.c:94 ../utils/net_ads.c:95 ../utils/net_ads.c:96 ../utils/net_ads.c:97
#: ../utils/net_ads.c:98
msgid "no"
msgstr ""

#: ../utils/net_ads.c:101
#, c-format
msgid "Forest:\t\t\t%s\n"
msgstr ""

#: ../utils/net_ads.c:102
#, c-format
msgid "Domain:\t\t\t%s\n"
msgstr ""

#: ../utils/net_ads.c:103
#, fuzzy, c-format
msgid "Domain Controller:\t%s\n"
msgstr "Контроллер домена"

#: ../utils/net_ads.c:105
#, c-format
msgid "Pre-Win2k Domain:\t%s\n"
msgstr ""

#: ../utils/net_ads.c:106
#, c-format
msgid "Pre-Win2k Hostname:\t%s\n"
msgstr ""

#: ../utils/net_ads.c:108
#, fuzzy, c-format
msgid "User name:\t%s\n"
msgstr "Имя пользователя"

#: ../utils/net_ads.c:110
#, fuzzy, c-format
msgid "Server Site Name :\t\t%s\n"
msgstr "Состояние сервера"

#: ../utils/net_ads.c:111
#, c-format
msgid "Client Site Name :\t\t%s\n"
msgstr ""

#: ../utils/net_ads.c:113
#, fuzzy, c-format
msgid "NT Version: %d\n"
msgstr "версия:"

#: ../utils/net_ads.c:114
#, c-format
msgid "LMNT Token: %.2x\n"
msgstr ""

#: ../utils/net_ads.c:115
#, c-format
msgid "LM20 Token: %.2x\n"
msgstr ""

#: ../utils/net_ads.c:130
msgid ""
"Usage:\n"
"net ads lookup\n"
"    Find the ADS DC using CLDAP lookup.\n"
msgstr ""

#: ../utils/net_ads.c:137 ../utils/net_ads.c:381
msgid "Didn't find the cldap server!\n"
msgstr ""

#: ../utils/net_ads.c:160
msgid ""
"Usage:\n"
"net ads info\n"
"    Display information about an Active Directory server.\n"
msgstr ""

#: ../utils/net_ads.c:168 ../utils/net_ads.c:173
msgid "Didn't find the ldap server!\n"
msgstr ""

#: ../utils/net_ads.c:182
msgid "Failed to get server's current time!\n"
msgstr ""

#: ../utils/net_ads.c:187
#, c-format
msgid "LDAP server: %s\n"
msgstr ""

#: ../utils/net_ads.c:188
#, c-format
msgid "LDAP server name: %s\n"
msgstr ""

#: ../utils/net_ads.c:189
#, c-format
msgid "Realm: %s\n"
msgstr ""

#: ../utils/net_ads.c:190
#, c-format
msgid "Bind Path: %s\n"
msgstr ""

#: ../utils/net_ads.c:191
#, c-format
msgid "LDAP port: %d\n"
msgstr ""

#: ../utils/net_ads.c:192
#, fuzzy, c-format
msgid "Server time: %s\n"
msgstr "Состояние сервера"

#: ../utils/net_ads.c:195
#, c-format
msgid "KDC server: %s\n"
msgstr ""

#: ../utils/net_ads.c:196
#, c-format
msgid "Server time offset: %d\n"
msgstr ""

#: ../utils/net_ads.c:374
msgid ""
"Usage:\n"
"net ads workgroup\n"
"    Print the workgroup name\n"
msgstr ""

#: ../utils/net_ads.c:397
#, c-format
msgid "Workgroup: %s\n"
msgstr ""

#: ../utils/net_ads.c:458
#, c-format
msgid "ads_user_add: %s\n"
msgstr ""

#: ../utils/net_ads.c:463
#, c-format
msgid "ads_user_add: User %s already exists\n"
msgstr ""

#: ../utils/net_ads.c:477
#, c-format
msgid "Could not add user %s: %s\n"
msgstr ""

#: ../utils/net_ads.c:484 ../utils/net_ads.c:497
#, fuzzy, c-format
msgid "User %s added\n"
msgstr "Имя пользователя"

#. password didn't set, delete account
#: ../utils/net_ads.c:503
#, c-format
msgid "Could not add user %s. Error setting password %s\n"
msgstr ""

#: ../utils/net_ads.c:551
#, c-format
msgid "ads_user_info: failed to escape user %s\n"
msgstr ""

#: ../utils/net_ads.c:569
#, c-format
msgid "ads_search: %s\n"
msgstr ""

#: ../utils/net_ads.c:575
msgid "ads_pull_uint32 failed\n"
msgstr ""

#: ../utils/net_ads.c:582
#, c-format
msgid "ads_domain_sid: %s\n"
msgstr ""

#: ../utils/net_ads.c:642
#, c-format
msgid "User %s does not exist.\n"
msgstr ""

#: ../utils/net_ads.c:652
#, c-format
msgid "User %s deleted\n"
msgstr ""

#: ../utils/net_ads.c:656
#, c-format
msgid "Error deleting user %s: %s\n"
msgstr ""

#: ../utils/net_ads.c:669
#, fuzzy
msgid "Add an AD user"
msgstr "Добавить нового пользователя"

#: ../utils/net_ads.c:670
msgid ""
"net ads user add\n"
"    Add an AD user"
msgstr ""

#: ../utils/net_ads.c:677
msgid "Display information about an AD user"
msgstr ""

#: ../utils/net_ads.c:678
msgid ""
"net ads user info\n"
"    Display information about an AD user"
msgstr ""

#: ../utils/net_ads.c:685
#, fuzzy
msgid "Delete an AD user"
msgstr "Удалить пользователя"

#: ../utils/net_ads.c:686
msgid ""
"net ads user delete\n"
"    Delete an AD user"
msgstr ""

#: ../utils/net_ads.c:699
msgid ""
"Usage:\n"
"net ads user\n"
"    List AD users\n"
msgstr ""

#: ../utils/net_ads.c:711
msgid ""
"\n"
"User name             Comment\n"
"-----------------------------\n"
msgstr ""

#: ../utils/net_ads.c:751
#, c-format
msgid "ads_group_add: %s\n"
msgstr ""

#: ../utils/net_ads.c:756
#, c-format
msgid "ads_group_add: Group %s already exists\n"
msgstr ""

#: ../utils/net_ads.c:769
#, c-format
msgid "Group %s added\n"
msgstr ""

#: ../utils/net_ads.c:772
#, c-format
msgid "Could not add group %s: %s\n"
msgstr ""

#: ../utils/net_ads.c:801
#, c-format
msgid "Group %s does not exist.\n"
msgstr ""

#: ../utils/net_ads.c:811
#, c-format
msgid "Group %s deleted\n"
msgstr ""

#: ../utils/net_ads.c:815
#, c-format
msgid "Error deleting group %s: %s\n"
msgstr ""

#: ../utils/net_ads.c:828
msgid "Add an AD group"
msgstr ""

#: ../utils/net_ads.c:829
msgid ""
"net ads group add\n"
"    Add an AD group"
msgstr ""

#: ../utils/net_ads.c:836
#, fuzzy
msgid "Delete an AD group"
msgstr "Удалить ресурс"

#: ../utils/net_ads.c:837
msgid ""
"net ads group delete\n"
"    Delete an AD group"
msgstr ""

#: ../utils/net_ads.c:850
msgid ""
"Usage:\n"
"net ads group\n"
"    List AD groups\n"
msgstr ""

#: ../utils/net_ads.c:862
msgid ""
"\n"
"Group name            Comment\n"
"-----------------------------\n"
msgstr ""

#: ../utils/net_ads.c:884
msgid ""
"Usage:\n"
"net ads status\n"
"    Display machine account details\n"
msgstr ""

#: ../utils/net_ads.c:896
#, c-format
msgid "ads_find_machine_acct: %s\n"
msgstr ""

#: ../utils/net_ads.c:902
#, c-format
msgid "No machine account for '%s' found\n"
msgstr ""

#: ../utils/net_ads.c:926
msgid ""
"Usage:\n"
"net ads leave\n"
"    Leave an AD domain\n"
msgstr ""

#: ../utils/net_ads.c:933
msgid "No realm set, are we joined ?\n"
msgstr ""

#: ../utils/net_ads.c:938 ../utils/net_ads.c:1260
msgid "Could not initialise talloc context.\n"
msgstr ""

#: ../utils/net_ads.c:948
msgid "Could not initialise unjoin context.\n"
msgstr ""

#: ../utils/net_ads.c:968
#, c-format
msgid "Failed to leave domain: %s\n"
msgstr ""

#: ../utils/net_ads.c:975
#, c-format
msgid "Deleted account for '%s' in realm '%s'\n"
msgstr ""

#: ../utils/net_ads.c:982
#, c-format
msgid "Disabled account for '%s' in realm '%s'\n"
msgstr ""

#. Based on what we requseted, we shouldn't get here, but if
#. we did, it means the secrets were removed, and therefore
#. we have left the domain
#: ../utils/net_ads.c:991
#, c-format
msgid "Machine '%s' Left domain '%s'\n"
msgstr ""

#: ../utils/net_ads.c:1035
msgid ""
"Usage:\n"
"net ads testjoin\n"
"    Test if the existing join is ok\n"
msgstr ""

#: ../utils/net_ads.c:1044
#, c-format
msgid "Join to domain is not valid: %s\n"
msgstr ""

#: ../utils/net_ads.c:1049
#, c-format
msgid "Join is OK\n"
msgstr ""

#: ../utils/net_ads.c:1060
msgid "Host is not configured as a member server.\n"
msgstr ""

#: ../utils/net_ads.c:1065
#, c-format
msgid "Our netbios name can be at most 15 chars long, \"%s\" is %u chars long\n"
msgstr ""

#: ../utils/net_ads.c:1072
#, c-format
msgid "realm must be set in in %s for ADS join to succeed.\n"
msgstr ""

#: ../utils/net_ads.c:1105
#, c-format
msgid "No DNS domain configured for %s. Unable to perform DNS Update.\n"
msgstr ""

#: ../utils/net_ads.c:1212
msgid ""
"net ads join [options]\n"
"Valid options:\n"
msgstr ""

#: ../utils/net_ads.c:1214
msgid ""
"   createupn[=UPN]    Set the userPrincipalName attribute during the join.\n"
"                      The deault UPN is in the form host/netbiosname@REALM.\n"
msgstr ""

#: ../utils/net_ads.c:1216
msgid ""
"   createcomputer=OU  Precreate the computer account in a specific OU.\n"
"                      The OU string read from top to bottom without RDNs and delimited by a '/'.\n"
"                      E.g. \"createcomputer=Computers/Servers/Unix\"\n"
"                      NB: A backslash '\\' is used as escape at multiple levels and may\n"
"                          need to be doubled or even quadrupled.  It is not used as a separator.\n"
msgstr ""

#: ../utils/net_ads.c:1221
msgid "   osName=string      Set the operatingSystem attribute during the join.\n"
msgstr ""

#: ../utils/net_ads.c:1222
msgid ""
"   osVer=string       Set the operatingSystemVersion attribute during the join.\n"
"                      NB: osName and osVer must be specified together for either to take effect.\n"
"                          Also, the operatingSystemService attribute is also set when along with\n"
"                          the two other attributes.\n"
msgstr ""

#: ../utils/net_ads.c:1254
msgid "Invalid configuration.  Exiting....\n"
msgstr ""

#: ../utils/net_ads.c:1283
msgid "Please supply a valid OU path.\n"
msgstr ""

#: ../utils/net_ads.c:1290
msgid "Please supply a operating system name.\n"
msgstr ""

#: ../utils/net_ads.c:1297
msgid "Please supply a valid operating system version.\n"
msgstr ""

#: ../utils/net_ads.c:1308
msgid "Please supply a valid domain name\n"
msgstr ""

#: ../utils/net_ads.c:1339
#, c-format
msgid ""
"The workgroup in %s does not match the short\n"
"domain name obtained from the server.\n"
"Using the name [%s] from the server.\n"
"You should set \"workgroup = %s\" in %s.\n"
msgstr ""

#: ../utils/net_ads.c:1347
#, c-format
msgid "Using short domain name -- %s\n"
msgstr ""

#: ../utils/net_ads.c:1350
#, c-format
msgid "Joined '%s' to realm '%s'\n"
msgstr ""

#: ../utils/net_ads.c:1353
#, c-format
msgid "Joined '%s' to domain '%s'\n"
msgstr ""

#: ../utils/net_ads.c:1377 ../utils/net_ads.c:1433
msgid "DNS update failed!\n"
msgstr ""

#. issue an overall failure message at the end.
#: ../utils/net_ads.c:1391
#, c-format
msgid "Failed to join domain: %s\n"
msgstr ""

#: ../utils/net_ads.c:1414
msgid ""
"Usage:\n"
"net ads dns register\n"
"    Register hostname with DNS\n"
msgstr ""

#: ../utils/net_ads.c:1421
msgid "Could not initialise talloc context\n"
msgstr ""

#: ../utils/net_ads.c:1439
msgid "Successfully registered hostname with DNS\n"
msgstr ""

#: ../utils/net_ads.c:1447
msgid "DNS update support not enabled at compile time!\n"
msgstr ""

#: ../utils/net_ads.c:1466
msgid ""
"Usage:\n"
"net ads dns gethostbyname <server> <name>\n"
"  Look up hostname from the AD\n"
"    server\tName server to use\n"
"    name\tName to look up\n"
msgstr ""

#: ../utils/net_ads.c:1476
#, c-format
msgid "do_gethostbyname returned %d\n"
msgstr ""

#: ../utils/net_ads.c:1488
msgid "Add host dns entry to AD"
msgstr ""

#: ../utils/net_ads.c:1489
msgid ""
"net ads dns register\n"
"    Add host dns entry to AD"
msgstr ""

#: ../utils/net_ads.c:1496
msgid "Look up host"
msgstr ""

#: ../utils/net_ads.c:1497
msgid ""
"net ads dns gethostbyname\n"
"    Look up host"
msgstr ""

#: ../utils/net_ads.c:1512
msgid ""
"\n"
"net ads printer search <printer>\n"
"\tsearch for a printer in the directory\n"
"\n"
"net ads printer info <printer> <server>\n"
"\tlookup info in directory for printer on server\n"
"\t(note: printer defaults to \"*\", server defaults to local)\n"
"\n"
"net ads printer publish <printername>\n"
"\tpublish printer in directory\n"
"\t(note: printer name is required)\n"
"\n"
"net ads printer remove <printername>\n"
"\tremove printer from directory\n"
"\t(note: printer name is required)\n"
msgstr ""

#: ../utils/net_ads.c:1536
msgid ""
"Usage:\n"
"net ads printer search\n"
"    List printers in the AD\n"
msgstr ""

#: ../utils/net_ads.c:1549
#, c-format
msgid "ads_find_printer: %s\n"
msgstr ""

#: ../utils/net_ads.c:1556
msgid "No results found\n"
msgstr ""

#: ../utils/net_ads.c:1576
msgid ""
"Usage:\n"
"net ads printer info [printername [servername]]\n"
"  Display printer info from AD\n"
"    printername\tPrinter name or wildcard\n"
"    servername\tName of the print server\n"
msgstr ""

#: ../utils/net_ads.c:1603
#, c-format
msgid "Server '%s' not found: %s\n"
msgstr ""

#: ../utils/net_ads.c:1611 ../utils/net_ads.c:1794
#, c-format
msgid "Printer '%s' not found\n"
msgstr ""

#: ../utils/net_ads.c:1640
msgid ""
"Usage:\n"
"net ads printer publish <printername> [servername]\n"
"  Publish printer in AD\n"
"    printername\tName of the printer\n"
"    servername\tName of the print server\n"
msgstr ""

#: ../utils/net_ads.c:1675
#, c-format
msgid "Unable to open a connnection to %s to obtain data for %s\n"
msgstr ""

#: ../utils/net_ads.c:1688
#, c-format
msgid "Could not find machine account for server %s\n"
msgstr ""

#: ../utils/net_ads.c:1704 ../utils/net_ads.c:1713
msgid "Internal error, out of memory!"
msgstr ""

#: ../utils/net_ads.c:1724
#, c-format
msgid "Unable to open a connnection to the spoolss pipe on %s\n"
msgstr ""

#: ../utils/net_ads.c:1766
msgid ""
"Usage:\n"
"net ads printer remove <printername> [servername]\n"
"  Remove a printer from the AD\n"
"    printername\tName of the printer\n"
"    servername\tName of the print server\n"
msgstr ""

#: ../utils/net_ads.c:1787
#, c-format
msgid "ads_find_printer_on_server: %s\n"
msgstr ""

#: ../utils/net_ads.c:1806
#, c-format
msgid "ads_del_dn: %s\n"
msgstr ""

#: ../utils/net_ads.c:1822
msgid "Search for a printer"
msgstr ""

#: ../utils/net_ads.c:1823
msgid ""
"net ads printer search\n"
"    Search for a printer"
msgstr ""

#: ../utils/net_ads.c:1830
msgid "Display printer information"
msgstr ""

#: ../utils/net_ads.c:1831
msgid ""
"net ads printer info\n"
"    Display printer information"
msgstr ""

#: ../utils/net_ads.c:1838
msgid "Publish a printer"
msgstr ""

#: ../utils/net_ads.c:1839
msgid ""
"net ads printer publish\n"
"    Publish a printer"
msgstr ""

#: ../utils/net_ads.c:1846
#, fuzzy
msgid "Delete a printer"
msgstr "Удалить принтер"

#: ../utils/net_ads.c:1847
msgid ""
"net ads printer remove\n"
"    Delete a printer"
msgstr ""

#: ../utils/net_ads.c:1869
msgid ""
"Usage:\n"
"net ads password <username>\n"
"  Change password for user\n"
"    username\tName of user to change password for\n"
msgstr ""

#: ../utils/net_ads.c:1877
msgid "You must supply an administrator username/password\n"
msgstr ""

#: ../utils/net_ads.c:1883
msgid "ERROR: You must say which username to change password for\n"
msgstr ""

#: ../utils/net_ads.c:1915
msgid "Didn't find the kerberos server!\n"
msgstr ""

#: ../utils/net_ads.c:1923
#, c-format
msgid "Enter new password for %s:"
msgstr ""

#: ../utils/net_ads.c:1933 ../utils/net_ads.c:1982
#, fuzzy, c-format
msgid "Password change failed: %s\n"
msgstr "Пароли"

#: ../utils/net_ads.c:1938
#, fuzzy, c-format
msgid "Password change for %s completed.\n"
msgstr "смена пароля в демо-режиме не работает"

#: ../utils/net_ads.c:1952
msgid ""
"Usage:\n"
"net ads changetrustpw\n"
"    Change the machine account's trust password\n"
msgstr ""

#: ../utils/net_ads.c:1977
#, c-format
msgid "Changing password for principal: %s\n"
msgstr ""

#: ../utils/net_ads.c:1988
#, c-format
msgid "Password change for principal %s succeeded.\n"
msgstr ""

#: ../utils/net_ads.c:1991
msgid "Attempting to update system keytab with new password.\n"
msgstr ""

#: ../utils/net_ads.c:1993
msgid "Failed to update system keytab.\n"
msgstr ""

#: ../utils/net_ads.c:2009
msgid ""
"\n"
"net ads search <expression> <attributes...>\n"
"\n"
"Perform a raw LDAP search on a ADS server and dump the results.\n"
"The expression is a standard LDAP search expression, and the\n"
"attributes are a list of LDAP fields to show in the results.\n"
"\n"
"Example: net ads search '(objectCategory=group)' sAMAccountName\n"
"\n"
msgstr ""

#: ../utils/net_ads.c:2046 ../utils/net_ads.c:2107 ../utils/net_ads.c:2171 ../utils/net_ads_gpo.c:250
#, c-format
msgid "search failed: %s\n"
msgstr ""

#: ../utils/net_ads.c:2051 ../utils/net_ads.c:2176 ../utils/net_ads_gpo.c:256
#, c-format
msgid ""
"Got %d replies\n"
"\n"
msgstr ""

#: ../utils/net_ads.c:2069
msgid ""
"\n"
"net ads dn <dn> <attributes...>\n"
"\n"
"perform a raw LDAP search on a ADS server and dump the results\n"
"The DN standard LDAP DN, and the attributes are a list of LDAP fields \n"
"to show in the results\n"
"\n"
"Example: net ads dn 'CN=administrator,CN=Users,DC=my,DC=domain' sAMAccountName\n"
"\n"
"Note: the DN must be provided properly escaped. See RFC 4514 for details\n"
"\n"
msgstr ""

#: ../utils/net_ads.c:2129
msgid ""
"\n"
"net ads sid <sid> <attributes...>\n"
"\n"
"perform a raw LDAP search on a ADS server and dump the results\n"
"The SID is in string format, and the attributes are a list of LDAP fields \n"
"to show in the results\n"
"\n"
"Example: net ads sid 'S-1-5-32' distinguishedName\n"
"\n"
msgstr ""

#: ../utils/net_ads.c:2164
msgid "could not convert sid\n"
msgstr ""

#: ../utils/net_ads.c:2193
msgid ""
"Usage:\n"
"net ads keytab flush\n"
"    Delete the whole keytab\n"
msgstr ""

#: ../utils/net_ads.c:2214
msgid ""
"Usage:\n"
"net ads keytab add <principal> [principal ...]\n"
"  Add principals to local keytab\n"
"    principal\tKerberos principal to add to keytab\n"
msgstr ""

#: ../utils/net_ads.c:2222
msgid "Processing principals to add...\n"
msgstr ""

#: ../utils/net_ads.c:2239
msgid ""
"Usage:\n"
"net ads keytab create\n"
"    Create new default keytab\n"
msgstr ""

#: ../utils/net_ads.c:2258
msgid ""
"Usage:\n"
"net ads keytab list [keytab]\n"
"  List a local keytab\n"
"    keytab\tKeytab to list\n"
msgstr ""

#: ../utils/net_ads.c:2280
msgid "Add a service principal"
msgstr ""

#: ../utils/net_ads.c:2281
msgid ""
"net ads keytab add\n"
"    Add a service principal"
msgstr ""

#: ../utils/net_ads.c:2288
#, fuzzy
msgid "Create a fresh keytab"
msgstr "Создать ресурс"

#: ../utils/net_ads.c:2289
msgid ""
"net ads keytab create\n"
"    Create a fresh keytab"
msgstr ""

#: ../utils/net_ads.c:2296
msgid "Remove all keytab entries"
msgstr ""

#: ../utils/net_ads.c:2297
msgid ""
"net ads keytab flush\n"
"    Remove all keytab entries"
msgstr ""

#: ../utils/net_ads.c:2304
msgid "List a keytab"
msgstr ""

#: ../utils/net_ads.c:2305
msgid ""
"net ads keytab list\n"
"    List a keytab"
msgstr ""

#: ../utils/net_ads.c:2312
msgid ""
"\n"
"Warning: \"kerberos method\" must be set to a keytab method to use keytab functions.\n"
msgstr ""

#: ../utils/net_ads.c:2324
msgid ""
"Usage:\n"
"net ads kerberos renew\n"
"    Renew TGT from existing credential cache\n"
msgstr ""

#: ../utils/net_ads.c:2332
#, c-format
msgid "failed to renew kerberos ticket: %s\n"
msgstr ""

#: ../utils/net_ads.c:2347
msgid ""
"Usage:\n"
"net ads kerberos pac\n"
"    Dump the Kerberos PAC\n"
msgstr ""

#: ../utils/net_ads.c:2372
#, c-format
msgid "failed to query kerberos PAC: %s\n"
msgstr ""

#: ../utils/net_ads.c:2381
#, c-format
msgid "The Pac: %s\n"
msgstr ""

#: ../utils/net_ads.c:2397
msgid ""
"Usage:\n"
"net ads kerberos kinit\n"
"    Get Ticket Granting Ticket (TGT) for the user\n"
msgstr ""

#: ../utils/net_ads.c:2421
#, c-format
msgid "failed to kinit password: %s\n"
msgstr ""

#: ../utils/net_ads.c:2435
msgid "Retrieve Ticket Granting Ticket (TGT)"
msgstr ""

#: ../utils/net_ads.c:2436
msgid ""
"net ads kerberos kinit\n"
"    Receive Ticket Granting Ticket (TGT)"
msgstr ""

#: ../utils/net_ads.c:2443
msgid "Renew Ticket Granting Ticket from credential cache"
msgstr ""

#: ../utils/net_ads.c:2444
msgid ""
"net ads kerberos renew\n"
"    Renew Ticket Granting Ticket (TGT) from credential cache"
msgstr ""

#: ../utils/net_ads.c:2452
msgid "Dump Kerberos PAC"
msgstr ""

#: ../utils/net_ads.c:2453
msgid ""
"net ads kerberos pac\n"
"    Dump Kerberos PAC"
msgstr ""

#: ../utils/net_ads.c:2469
msgid "Display details on remote ADS server"
msgstr ""

#: ../utils/net_ads.c:2470
msgid ""
"net ads info\n"
"    Display details on remote ADS server"
msgstr ""

#: ../utils/net_ads.c:2477
msgid "Join the local machine to ADS realm"
msgstr ""

#: ../utils/net_ads.c:2478
msgid ""
"net ads join\n"
"    Join the local machine to ADS realm"
msgstr ""

#: ../utils/net_ads.c:2485
msgid "Validate machine account"
msgstr ""

#: ../utils/net_ads.c:2486
msgid ""
"net ads testjoin\n"
"    Validate machine account"
msgstr ""

#: ../utils/net_ads.c:2493
msgid "Remove the local machine from ADS"
msgstr ""

#: ../utils/net_ads.c:2494
msgid ""
"net ads leave\n"
"    Remove the local machine from ADS"
msgstr ""

#: ../utils/net_ads.c:2501
msgid "Display machine account details"
msgstr ""

#: ../utils/net_ads.c:2502
msgid ""
"net ads status\n"
"    Display machine account details"
msgstr ""

#: ../utils/net_ads.c:2509
msgid "List/modify users"
msgstr ""

#: ../utils/net_ads.c:2510
msgid ""
"net ads user\n"
"    List/modify users"
msgstr ""

#: ../utils/net_ads.c:2517
msgid "List/modify groups"
msgstr ""

#: ../utils/net_ads.c:2518
msgid ""
"net ads group\n"
"    List/modify groups"
msgstr ""

#: ../utils/net_ads.c:2525
msgid "Issue dynamic DNS update"
msgstr ""

#: ../utils/net_ads.c:2526
msgid ""
"net ads dns\n"
"    Issue dynamic DNS update"
msgstr ""

#: ../utils/net_ads.c:2533
#, fuzzy
msgid "Change user passwords"
msgstr "Сменить пароль"

#: ../utils/net_ads.c:2534
msgid ""
"net ads password\n"
"    Change user passwords"
msgstr ""

#: ../utils/net_ads.c:2541
#, fuzzy
msgid "Change trust account password"
msgstr "Сменить пароль"

#: ../utils/net_ads.c:2542
msgid ""
"net ads changetrustpw\n"
"    Change trust account password"
msgstr ""

#: ../utils/net_ads.c:2549
msgid "List/modify printer entries"
msgstr ""

#: ../utils/net_ads.c:2550
msgid ""
"net ads printer\n"
"    List/modify printer entries"
msgstr ""

#: ../utils/net_ads.c:2557
msgid "Issue LDAP search using filter"
msgstr ""

#: ../utils/net_ads.c:2558
msgid ""
"net ads search\n"
"    Issue LDAP search using filter"
msgstr ""

#: ../utils/net_ads.c:2565
msgid "Issue LDAP search by DN"
msgstr ""

#: ../utils/net_ads.c:2566
msgid ""
"net ads dn\n"
"    Issue LDAP search by DN"
msgstr ""

#: ../utils/net_ads.c:2573
msgid "Issue LDAP search by SID"
msgstr ""

#: ../utils/net_ads.c:2574
msgid ""
"net ads sid\n"
"    Issue LDAP search by SID"
msgstr ""

#: ../utils/net_ads.c:2581
msgid "Display workgroup name"
msgstr ""

#: ../utils/net_ads.c:2582
msgid ""
"net ads workgroup\n"
"    Display the workgroup name"
msgstr ""

#: ../utils/net_ads.c:2589
msgid "Perfom CLDAP query on DC"
msgstr ""

#: ../utils/net_ads.c:2590
msgid ""
"net ads lookup\n"
"    Find the ADS DC using CLDAP lookups"
msgstr ""

#: ../utils/net_ads.c:2597
msgid "Manage local keytab file"
msgstr ""

#: ../utils/net_ads.c:2598
msgid ""
"net ads keytab\n"
"    Manage local keytab file"
msgstr ""

#: ../utils/net_ads.c:2605
msgid "Manage group policy objects"
msgstr ""

#: ../utils/net_ads.c:2606
msgid ""
"net ads gpo\n"
"    Manage group policy objects"
msgstr ""

#: ../utils/net_ads.c:2613
msgid "Manage kerberos keytab"
msgstr ""

#: ../utils/net_ads.c:2614
msgid ""
"net ads kerberos\n"
"    Manage kerberos keytab"
msgstr ""

#: ../utils/net_ads.c:2627
msgid "ADS support not compiled in\n"
msgstr ""

#: ../utils/net_ads_gpo.c:40
msgid ""
"Usage:\n"
"net ads gpo refresh <username|machinename>\n"
"  Lists all GPOs assigned to an account and downloads them\n"
"    username\tUser to refresh GPOs for\n"
"    machinename\tMachine to refresh GPOs for\n"
msgstr ""

#: ../utils/net_ads_gpo.c:56
#, c-format
msgid "failed to connect AD server: %s\n"
msgstr ""

#: ../utils/net_ads_gpo.c:62
#, c-format
msgid "failed to find samaccount for %s\n"
msgstr ""

#: ../utils/net_ads_gpo.c:70
#, c-format
msgid ""
"\n"
"%s: '%s' has dn: '%s'\n"
"\n"
msgstr ""

#: ../utils/net_ads_gpo.c:71 ../utils/net_ads_gpo.c:328
#, fuzzy
msgid "machine"
msgstr "Удалённая машина"

#: ../utils/net_ads_gpo.c:71 ../utils/net_ads_gpo.c:328
#, fuzzy
msgid "user"
msgstr "Пользователь"

#: ../utils/net_ads_gpo.c:74
msgid "* fetching token "
msgstr ""

#: ../utils/net_ads_gpo.c:82 ../utils/net_ads_gpo.c:90 ../utils/net_ads_gpo.c:102 ../utils/net_ads_gpo.c:113 ../utils/net_ads_gpo.c:158
#, c-format
msgid "failed: %s\n"
msgstr ""

#: ../utils/net_ads_gpo.c:85 ../utils/net_ads_gpo.c:94 ../utils/net_ads_gpo.c:105 ../utils/net_ads_gpo.c:118 ../utils/net_ads_gpo.c:163
msgid "finished\n"
msgstr ""

#: ../utils/net_ads_gpo.c:87
msgid "* fetching GPO List "
msgstr ""

#: ../utils/net_ads_gpo.c:96
msgid "* Refreshing Group Policy Data "
msgstr ""

#: ../utils/net_ads_gpo.c:107
msgid "* storing GPO list to registry "
msgstr ""

#: ../utils/net_ads_gpo.c:122
msgid "* dumping GPO list\n"
msgstr ""

#: ../utils/net_ads_gpo.c:151
msgid "* re-reading GPO list from registry "
msgstr ""

#: ../utils/net_ads_gpo.c:167
msgid "* dumping GPO list from registry\n"
msgstr ""

#: ../utils/net_ads_gpo.c:226
msgid ""
"Usage:\n"
"net ads gpo listall\n"
"    List all GPOs on the DC\n"
msgstr ""

#: ../utils/net_ads_gpo.c:270
#, fuzzy, c-format
msgid "ads_parse_gpo failed: %s\n"
msgstr "Пароли"

#: ../utils/net_ads_gpo.c:300
msgid ""
"Usage:\n"
"net ads gpo list <username|machinename>\n"
"  Lists all GPOs for machine/user\n"
"    username\tUser to list GPOs for\n"
"    machinename\tMachine to list GPOs for\n"
msgstr ""

#: ../utils/net_ads_gpo.c:327
#, c-format
msgid "%s: '%s' has dn: '%s'\n"
msgstr ""

#: ../utils/net_ads_gpo.c:451
msgid ""
"Usage:\n"
"net ads gpo linkget <container>\n"
"  Lists gPLink of a containter\n"
"    container\tContainer to get link for\n"
msgstr ""

#: ../utils/net_ads_gpo.c:470
#, c-format
msgid "get link for %s failed: %s\n"
msgstr ""

#: ../utils/net_ads_gpo.c:492
msgid ""
"Usage:\n"
"net ads gpo linkadd <linkdn> <gpodn> [options]\n"
"  Link a container to a GPO\n"
"    linkdn\tContainer to link to a GPO\n"
"    gpodn\tGPO to link container to\n"
msgstr ""

#: ../utils/net_ads_gpo.c:497
msgid ""
"note: DNs must be provided properly escaped.\n"
"See RFC 4514 for details\n"
msgstr ""

#: ../utils/net_ads_gpo.c:518
#, c-format
msgid "link add failed: %s\n"
msgstr ""

#: ../utils/net_ads_gpo.c:579
msgid ""
"Usage:\n"
"net ads gpo getgpo <gpo>\n"
"  List speciefied GPO\n"
"    gpo\t\tGPO to list\n"
msgstr ""

#: ../utils/net_ads_gpo.c:603
#, c-format
msgid "get gpo for [%s] failed: %s\n"
msgstr ""

#: ../utils/net_ads_gpo.c:634
msgid "List specified GPO"
msgstr ""

#: ../utils/net_ads_gpo.c:635
msgid ""
"net ads gpo getgpo\n"
"    List specified GPO"
msgstr ""

#: ../utils/net_ads_gpo.c:642
msgid "Link a container to a GPO"
msgstr ""

#: ../utils/net_ads_gpo.c:643
msgid ""
"net ads gpo linkadd\n"
"    Link a container to a GPO"
msgstr ""

#: ../utils/net_ads_gpo.c:660
msgid "Lists gPLink of containter"
msgstr ""

#: ../utils/net_ads_gpo.c:661
msgid ""
"net ads gpo linkget\n"
"    Lists gPLink of containter"
msgstr ""

#: ../utils/net_ads_gpo.c:668
msgid "Lists all GPOs for machine/user"
msgstr ""

#: ../utils/net_ads_gpo.c:669
msgid ""
"net ads gpo list\n"
"    Lists all GPOs for machine/user"
msgstr ""

#: ../utils/net_ads_gpo.c:676
msgid "Lists all GPOs on a DC"
msgstr ""

#: ../utils/net_ads_gpo.c:677
msgid ""
"net ads gpo listall\n"
"    Lists all GPOs on a DC"
msgstr ""

#: ../utils/net_ads_gpo.c:684
msgid "Lists all GPOs assigned to an account and downloads them"
msgstr ""

#: ../utils/net_ads_gpo.c:686
msgid ""
"net ads gpo refresh\n"
"    Lists all GPOs assigned to an account and downloads them"
msgstr ""

#: ../utils/net_afs.c:25
msgid ""
"  net afs key filename\n"
"\tImports a OpenAFS KeyFile into our secrets.tdb\n"
"\n"
msgstr ""

#: ../utils/net_afs.c:27
msgid ""
"  net afs impersonate <user> <cell>\n"
"\tCreates a token for user@cell\n"
"\n"
msgstr ""

#: ../utils/net_afs.c:38
msgid "usage: 'net afs key <keyfile> cell'\n"
msgstr ""

#: ../utils/net_afs.c:43
msgid "Could not open secrets.tdb\n"
msgstr ""

#: ../utils/net_afs.c:48
#, c-format
msgid "Could not open %s\n"
msgstr ""

#: ../utils/net_afs.c:53
msgid "Could not read keyfile\n"
msgstr ""

#: ../utils/net_afs.c:58
msgid "Could not write keyfile to secrets.tdb\n"
msgstr ""

#: ../utils/net_afs.c:71
#, c-format
msgid "Usage: net afs impersonate <user> <cell>\n"
msgstr ""

#: ../utils/net_afs.c:78
#, c-format
msgid "Could not create token\n"
msgstr ""

#: ../utils/net_afs.c:83
#, c-format
msgid "Could not set token into kernel\n"
msgstr ""

#: ../utils/net_afs.c:87
#, c-format
msgid "Success: %s@%s\n"
msgstr ""

#: ../utils/net_afs.c:98
msgid "Import an OpenAFS keyfile"
msgstr ""

#: ../utils/net_afs.c:99
msgid ""
"net afs key <filename>\n"
"    Import kefile from <filename>."
msgstr ""

#: ../utils/net_afs.c:106
msgid "Get a user token"
msgstr ""

#: ../utils/net_afs.c:107
msgid ""
"net afs impersonate <user> <cell>\n"
"    Create token for user@cell"
msgstr ""

#: ../utils/net_cache.c:74
#, c-format
msgid "Key: %s\t Timeout: %s\t Value: %s  %s\n"
msgstr ""

#: ../utils/net_cache.c:75
msgid "(expired)"
msgstr ""

#: ../utils/net_cache.c:84
#, c-format
msgid "Couldn't delete entry! key = %s\n"
msgstr ""

#: ../utils/net_cache.c:158
msgid ""
"\n"
"Usage:\n"
"net cache add <key string> <data string> <timeout>\n"
msgstr ""

#: ../utils/net_cache.c:170
msgid "Invalid timeout argument.\n"
msgstr ""

#: ../utils/net_cache.c:175
msgid "New cache entry stored successfully.\n"
msgstr ""

#: ../utils/net_cache.c:179
msgid "Entry couldn't be added. Perhaps there's already such a key.\n"
msgstr ""

#: ../utils/net_cache.c:195
msgid ""
"\n"
"Usage: net cache del <key string>\n"
msgstr ""

#: ../utils/net_cache.c:200
msgid "Entry deleted.\n"
msgstr ""

#: ../utils/net_cache.c:204
msgid "Couldn't delete specified entry\n"
msgstr ""

#: ../utils/net_cache.c:223
msgid ""
"\n"
"Usage: net cache get <key>\n"
msgstr ""

#: ../utils/net_cache.c:233
msgid "Failed to find entry\n"
msgstr ""

#: ../utils/net_cache.c:250
msgid "Usage: net cache search <pattern>\n"
msgstr ""

#: ../utils/net_cache.c:272
msgid ""
"Usage:\n"
"net cache list\n"
"    List all cache entries.\n"
msgstr ""

#: ../utils/net_cache.c:293 ../utils/net_cache.c:306
msgid ""
"Usage:\n"
"net cache flush\n"
"    Delete all cache entries.\n"
msgstr ""

#: ../utils/net_cache.c:331
msgid "Add new cache entry"
msgstr ""

#: ../utils/net_cache.c:332
msgid ""
"net cache add <key string> <data string> <timeout>\n"
"  Add new cache entry.\n"
"    key string\tKey string to add cache data under.\n"
"    data string\tData to store under given key.\n"
"    timeout\tTimeout for cache data."
msgstr ""

#: ../utils/net_cache.c:342
msgid "Delete existing cache entry by key"
msgstr ""

#: ../utils/net_cache.c:343
msgid ""
"net cache del <key string>\n"
"  Delete existing cache entry by key.\n"
"    key string\tKey string to delete."
msgstr ""

#: ../utils/net_cache.c:351
msgid "Get cache entry by key"
msgstr ""

#: ../utils/net_cache.c:352
msgid ""
"net cache get <key string>\n"
"  Get cache entry by key.\n"
"    key string\tKey string to look up cache entry for."
msgstr ""

#: ../utils/net_cache.c:361
msgid "Search entry by pattern"
msgstr ""

#: ../utils/net_cache.c:362
msgid ""
"net cache search <pattern>\n"
"  Search entry by pattern.\n"
"    pattern\tPattern to search for in cache."
msgstr ""

#: ../utils/net_cache.c:370
msgid "List all cache entries"
msgstr ""

#: ../utils/net_cache.c:371
msgid ""
"net cache list\n"
"  List all cache entries"
msgstr ""

#: ../utils/net_cache.c:378
#, fuzzy
msgid "Delete all cache entries"
msgstr "Удалить принтер"

#: ../utils/net_cache.c:379
msgid ""
"net cache flush\n"
"  Delete all cache entries"
msgstr ""

#: ../utils/net_cache.c:386
msgid "Move transient cache content to stable storage"
msgstr ""

#: ../utils/net_cache.c:387
msgid ""
"net cache stabilize\n"
"  Move transient cache content to stable storage"
msgstr ""
