#!/usr/bin/env python

bld.SAMBA3_SUBSYSTEM('notifyd',
		     source='notifyd.c',
                     deps='util_tdb TDB_LIB messages_util')

bld.SAMBA3_BINARY('notifyd-tests',
                  source='tests.c',
                  install=False,
                  deps='''
                       smbconf
                  ''')

bld.SAMBA3_BINARY('notifydd',
                  source='notifydd.c',
                  install=False,
                  deps='''notifyd
                       smbconf
                  ''')
