/* Generated from /home/data/samba/samba4/svn/source/heimdal/lib/hx509/hx509_err.et */
/* $Id: hx509_err.et,v 1.19 2006/12/30 23:05:39 lha Exp $ */

#include <stddef.h>
#include <com_err.h>
#include "hx509_err.h"

static const char *hx_error_strings[] = {
	/* 000 */ "ASN.1 failed call to system time library",
	/* 001 */ "Extension not found",
	/* 002 */ "Certification path not found",
	/* 003 */ "Parent certificate is not a CA",
	/* 004 */ "CA path too deep",
	/* 005 */ "Signature algorithm not supported",
	/* 006 */ "Signature algorithm doesn't match certificate key",
	/* 007 */ "Certificate used before it became valid",
	/* 008 */ "Certificate used after it became invalid",
	/* 009 */ "Private key required for the operation is missing",
	/* 010 */ "Algorithm not supported",
	/* 011 */ "Issuer couldn't be found",
	/* 012 */ "Error verifing constraints",
	/* 013 */ "Number too large",
	/* 014 */ "Error while verifing name constraints",
	/* 015 */ "Path is too long, failed to find valid anchor",
	/* 016 */ "Required keyusage for this certificate is missing",
	/* 017 */ "Certificate not found",
	/* 018 */ "Unknown lock command",
	/* 019 */ "Parent certificate is a CA",
	/* 020 */ "Extra data was found after the structure",
	/* 021 */ "Proxy certificate is invalid",
	/* 022 */ "Proxy certificate name is wrong",
	/* 023 */ "Name is malformated",
	/* 024 */ "Certificate is malformated",
	/* 025 */ "Certificate is missing a required EKU",
	/* 026 */ "Proxy certificate not canonicalize",
	/* 027 */ "Reserved hx error (27)",
	/* 028 */ "Reserved hx error (28)",
	/* 029 */ "Reserved hx error (29)",
	/* 030 */ "Reserved hx error (30)",
	/* 031 */ "Reserved hx error (31)",
	/* 032 */ "Failed to create signature",
	/* 033 */ "Missing signer data",
	/* 034 */ "Couldn't find signers certificate",
	/* 035 */ "No data to perform the operation on",
	/* 036 */ "Data in the message is invalid",
	/* 037 */ "Padding in the message invalid",
	/* 038 */ "Couldn't find recipient certificate",
	/* 039 */ "Mismatch bewteen signed type and unsigned type",
	/* 040 */ "Reserved hx error (40)",
	/* 041 */ "Reserved hx error (41)",
	/* 042 */ "Reserved hx error (42)",
	/* 043 */ "Reserved hx error (43)",
	/* 044 */ "Reserved hx error (44)",
	/* 045 */ "Reserved hx error (45)",
	/* 046 */ "Reserved hx error (46)",
	/* 047 */ "Reserved hx error (47)",
	/* 048 */ "Reserved hx error (48)",
	/* 049 */ "Reserved hx error (49)",
	/* 050 */ "Reserved hx error (50)",
	/* 051 */ "Reserved hx error (51)",
	/* 052 */ "Reserved hx error (52)",
	/* 053 */ "Reserved hx error (53)",
	/* 054 */ "Reserved hx error (54)",
	/* 055 */ "Reserved hx error (55)",
	/* 056 */ "Reserved hx error (56)",
	/* 057 */ "Reserved hx error (57)",
	/* 058 */ "Reserved hx error (58)",
	/* 059 */ "Reserved hx error (59)",
	/* 060 */ "Reserved hx error (60)",
	/* 061 */ "Reserved hx error (61)",
	/* 062 */ "Reserved hx error (62)",
	/* 063 */ "Reserved hx error (63)",
	/* 064 */ "Internal error in the crypto engine",
	/* 065 */ "External error in the crypto engine",
	/* 066 */ "Signature missing for data",
	/* 067 */ "Signature is not valid",
	/* 068 */ "Sigature doesn't provide confidentiality",
	/* 069 */ "Invalid format on signature",
	/* 070 */ "Mismatch bewteen oids",
	/* 071 */ "No prompter function defined",
	/* 072 */ "Signature require signer, but non available",
	/* 073 */ "RSA public encyption failed",
	/* 074 */ "RSA public encyption failed",
	/* 075 */ "RSA private decryption failed",
	/* 076 */ "RSA private decryption failed",
	/* 077 */ "Reserved hx error (77)",
	/* 078 */ "Reserved hx error (78)",
	/* 079 */ "Reserved hx error (79)",
	/* 080 */ "Reserved hx error (80)",
	/* 081 */ "Reserved hx error (81)",
	/* 082 */ "Reserved hx error (82)",
	/* 083 */ "Reserved hx error (83)",
	/* 084 */ "Reserved hx error (84)",
	/* 085 */ "Reserved hx error (85)",
	/* 086 */ "Reserved hx error (86)",
	/* 087 */ "Reserved hx error (87)",
	/* 088 */ "Reserved hx error (88)",
	/* 089 */ "Reserved hx error (89)",
	/* 090 */ "Reserved hx error (90)",
	/* 091 */ "Reserved hx error (91)",
	/* 092 */ "Reserved hx error (92)",
	/* 093 */ "Reserved hx error (93)",
	/* 094 */ "Reserved hx error (94)",
	/* 095 */ "Reserved hx error (95)",
	/* 096 */ "CRL used before it became valid",
	/* 097 */ "CRL used after it became invalid",
	/* 098 */ "CRL have invalid format",
	/* 099 */ "Certificate is included in CRL",
	/* 100 */ "No revoke status found for certificates",
	/* 101 */ "Unknown extension",
	/* 102 */ "Got wrong CRL/OCSP data from server",
	/* 103 */ "Doesn't have same parent as other certificaes",
	/* 104 */ "Reserved hx error (104)",
	/* 105 */ "Reserved hx error (105)",
	/* 106 */ "Reserved hx error (106)",
	/* 107 */ "Reserved hx error (107)",
	/* 108 */ "No local key attribute",
	/* 109 */ "Failed to parse key",
	/* 110 */ "Unsupported operation",
	/* 111 */ "Unimplemented operation",
	/* 112 */ "Failed to parse name",
	/* 113 */ "Reserved hx error (113)",
	/* 114 */ "Reserved hx error (114)",
	/* 115 */ "Reserved hx error (115)",
	/* 116 */ "Reserved hx error (116)",
	/* 117 */ "Reserved hx error (117)",
	/* 118 */ "Reserved hx error (118)",
	/* 119 */ "Reserved hx error (119)",
	/* 120 */ "Reserved hx error (120)",
	/* 121 */ "Reserved hx error (121)",
	/* 122 */ "Reserved hx error (122)",
	/* 123 */ "Reserved hx error (123)",
	/* 124 */ "Reserved hx error (124)",
	/* 125 */ "Reserved hx error (125)",
	/* 126 */ "Reserved hx error (126)",
	/* 127 */ "Reserved hx error (127)",
	/* 128 */ "No smartcard reader/device found",
	/* 129 */ "No smartcard in reader",
	/* 130 */ "No supported mech(s)",
	/* 131 */ "Token or slot failed in inconsistent way",
	/* 132 */ "Failed to open session to slot",
	/* 133 */ "Failed to login to slot",
	/* 134 */ "Failed to load PKCS module",
	NULL
};

#define num_errors 135

void initialize_hx_error_table_r(struct et_list **list)
{
    initialize_error_table_r(list, hx_error_strings, num_errors, ERROR_TABLE_BASE_hx);
}

void initialize_hx_error_table(void)
{
    init_error_table(hx_error_strings, ERROR_TABLE_BASE_hx, num_errors);
}
