#!/usr/bin/env python

def configure(conf):
    conf.CHECK_FUNCS_IN('openpty', 'util', checklibc=True, headers='pty.h util.h libutil.h')

def build(bld):
    bld.SAMBA_BINARY('texpect', 'texpect.c', deps='popt util', install=False)
