.\" $Id$
.\"
.Dd September 27, 1996
.Dt KX 1
.Os KTH-KRB
.Sh NAME
.Nm kx
.Nd
securely forward X conections
.Sh SYNOPSIS
.Ar kx
.Op Fl d
.Op Fl l Ar username
.Ar host
.Sh DESCRIPTION
The
.Nm
program forwards a X connection from a remote client to a local screen
through an authenticated and encrypted stream.  Options supported by
.Nm kx :
.Bl -tag -width Ds
.It Fl l
Log in on remote host as user
.Ar username
.It Fl d
Do not fork.
.El
.Pp
This program is used by
.Nm rxtelnet
and
.Nm rxterm
and you should not need to run it directly.
.Pp
It connects to a
.Nm kxd
on the host
.Ar host
and then will relay the traffic from the remote X clients to the local
server.  When started, it prints the display and Xauthority-file to be
used on host
.Ar host
and then goes to the background, waiting for connections from the
remote
.Nm kxd.
.Sh SEE ALSO
.Xr rxtelnet 1 ,
.Xr rxterm 1 ,
.Xr kxd 8
