/* header auto-generated by pidl */

struct dfs_Exist {
	struct {
	} in;

	struct {
		uint32 *exist_flag;
	} out;

};

struct dfs_Add {
	struct {
		const char *path;
		const char *server;
		const char *share;
		const char *comment;
		uint32 flags;
	} in;

	struct {
		NTSTATUS result;
	} out;

};

struct dfs_Remove {
	struct {
		const char *path;
		const char *server;
		const char *share;
	} in;

	struct {
		NTSTATUS result;
	} out;

};

struct dfs_UNKNOWN3 {
	struct {
	} in;

	struct {
		NTSTATUS result;
	} out;

};

struct dfs_Info {
	struct {
		const char *path;
		const char *server;
		const char *share;
		uint16 level;
	} in;

	struct {
		NTSTATUS result;
	} out;

};

struct dfs_String {
	const char *str;
};

struct dfs_Enum1 {
	uint32 count;
	struct dfs_String *s;
};

union dfs_EnumInfo {
/* [case(1)] */ struct dfs_Enum1 *enum1;
};

struct dfs_EnumStruct {
	uint32 level;
	union dfs_EnumInfo e;
};

struct dfs_Enum {
	struct {
		uint32 level;
		uint32 bufsize;
		struct dfs_EnumStruct *info;
		uint32 *unknown;
		uint32 *total;
	} in;

	struct {
		struct dfs_EnumStruct *info;
		uint32 *total;
		NTSTATUS result;
	} out;

};

#define DCERPC_DFS_EXIST 0
#define DCERPC_DFS_ADD 1
#define DCERPC_DFS_REMOVE 2
#define DCERPC_DFS_UNKNOWN3 3
#define DCERPC_DFS_INFO 4
#define DCERPC_DFS_ENUM 5
