#!/usr/bin/env python


bld.SAMBA_LIBRARY('cli_smb_common',
	source='smb_seal.c smb2_create_blob.c smb2_signing.c util.c read_smb.c',
	autoproto='smb_common_proto.h',
	deps='LIBCRYPTO errors gssapi gensec KRB5_WRAP LIBASYNC_REQ',
	public_deps='talloc samba-util',
	private_library=True,
	public_headers='''smb_common.h smb2_constants.h smb_constants.h
			smb_seal.h
			smb2_create_blob.h smb2_signing.h smb_util.h smb_unix_ext.h
			read_smb.h
	''',
	)
