# Polish messages for international release of SWAT.
# Copyright (C) 2001 Rafal Szczesniak <mimir@spin.ict.pwr.wroc.pl>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
msgid ""
msgstr ""
"Project-Id-Version: i18n_swat \n"
"POT-Creation-Date: 2001-09-20 20:29+0900\n"
"PO-Revision-Date: 2001-08-15 22:45+02:00\n"
"Last-Translator: Rafal Szczesniak <mimir@spin.ict.pwr.wroc.pl>\n"
"Language-Team: pl\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=iso-8859-2\n"
"Content-Transfer-Encoding: \n"

#: web/swat.c:120
#, c-format
msgid "ERROR: Can't open %s\n"
msgstr "B£¡D: Nie mo¿na otworzyæ %s\n"

#.
#. str = stripspace(parm->label);
#. strlower (str); //monyo
#. d_printf("<tr><td><A HREF=\"/swat/help/smb.conf.5.html#%s\" target=\"docs\">%s</A>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; %s</td><td>",
#. str, _("Help"), parm->label);
#.
#: web/swat.c:211
msgid "Help"
msgstr "Pomoc"

#: web/swat.c:217 web/swat.c:231 web/swat.c:246 web/swat.c:254 web/swat.c:263
#: web/swat.c:272 web/swat.c:278 web/swat.c:284 web/swat.c:297
msgid "Set Default"
msgstr "Ustaw domy¶lnie"

#: web/swat.c:502
#, c-format
msgid "Logged in as <b>%s</b><p>\n"
msgstr "Zalogowany jako <b>%s</b><p>\n"

#: web/swat.c:505
msgid "Home"
msgstr "Strona domowa"

#: web/swat.c:507
msgid "Globals"
msgstr "Ustawienia globalne"

#: web/swat.c:508
msgid "Shares"
msgstr "Wspó³udzia³y"

#: web/swat.c:509
msgid "Printers"
msgstr "Drukarki"

#: web/swat.c:512
msgid "Status"
msgstr "Status"

#: web/swat.c:513
msgid "View Config"
msgstr "Przejrzyj Konfiguracjê"

#: web/swat.c:515
msgid "Password Management"
msgstr "Zarz±dzanie Has³ami"

#: web/swat.c:539
msgid "Current Config"
msgstr "Bie¿±ca Konfiguracja"

#: web/swat.c:543
msgid "Normal View"
msgstr "Normalny Widok"

#: web/swat.c:545
msgid "Full View"
msgstr "Pe³ny Widok"

#: web/swat.c:561
msgid "Global Variables"
msgstr "Zmienne Globalne"

#: web/swat.c:575 web/swat.c:671 web/swat.c:1014
msgid "Commit Changes"
msgstr "Potwierd¼ Zmiany"

#: web/swat.c:579 web/swat.c:674 web/swat.c:1016
msgid "Reset Values"
msgstr "Zresetuj Warto¶ci"

#: web/swat.c:581 web/swat.c:676 web/swat.c:1018
msgid "Advanced View"
msgstr "Widok Zaawansowany"

#: web/swat.c:583 web/swat.c:678 web/swat.c:1020
msgid "Basic View"
msgstr "Widok Podstawowy"

#: web/swat.c:613
msgid "Share Parameters"
msgstr "Parametry Wspó³udzia³u"

#: web/swat.c:642
msgid "Choose Share"
msgstr "Wybierz Wspó³udzia³"

#: web/swat.c:656
msgid "Delete Share"
msgstr "Usuñ Wspó³udzia³"

#: web/swat.c:663
msgid "Create Share"
msgstr "Utwórz Wspó³udzia³"

#: web/swat.c:708
msgid "password change in demo mode rejected\n"
msgstr "zmiana has³a w trybie demo odrzucona\n"

#: web/swat.c:747
msgid " Must specify \"User Name\" \n"
msgstr " Musisz podaæ \"Nazwê U¿ytkownika\" \n"

#: web/swat.c:763
msgid " Must specify \"Old Password\" \n"
msgstr " Musisz podaæ \"Stare Has³o\" \n"

#: web/swat.c:769
msgid " Must specify \"Remote Machine\" \n"
msgstr " Musisz podaæ \"Zdaln± Maszynê\" \n"

#: web/swat.c:776
msgid " Must specify \"New, and Re-typed Passwords\" \n"
msgstr " Musisz podaæ \"Nowe Has³o, i ponownie wpisane Nowe Has³o\" \n"

#: web/swat.c:782
msgid " Re-typed password didn't match new password\n"
msgstr " Ponownie wpisane has³o nie pasuje do nowego has³a\n"

#: web/swat.c:812
#, c-format
msgid " The passwd for '%s' has been changed. \n"
msgstr " Has³o dla '%s' zosta³o zmienione. \n"

#: web/swat.c:814
#, c-format
msgid " The passwd for '%s' has NOT been changed. \n"
msgstr " Has³o dla '%s' NIE zosta³o zmienione. \n"

#: web/swat.c:838
msgid "Server Password Management"
msgstr "Zarz±dzanie Has³ami na Serwerze"

#.
#. * Create all the dialog boxes for data collection
#.
#: web/swat.c:847 web/swat.c:894
msgid " User Name : "
msgstr " Nazwa U¿ytkownika : "

#: web/swat.c:850 web/swat.c:896
msgid " Old Password : "
msgstr " Stare Has³o : "

#: web/swat.c:853 web/swat.c:898
msgid " New Password : "
msgstr " Nowe Has³o : "

#: web/swat.c:855 web/swat.c:900
msgid " Re-type New Password : "
msgstr " Ponownie wpisz Nowe Has³o : "

#: web/swat.c:863 web/swat.c:911
msgid "Change Password"
msgstr "Zmieñ Has³o"

#: web/swat.c:866
msgid "Add New User"
msgstr "Dodaj Nowego U¿ytkownika"

#: web/swat.c:868
msgid "Delete User"
msgstr "Usuñ U¿ytkownika"

#: web/swat.c:870
msgid "Disable User"
msgstr "Zablokuj U¿ytkownika"

#: web/swat.c:872
msgid "Enable User"
msgstr "Odblokuj U¿ytkownika"

#: web/swat.c:885
msgid "Client/Server Password Management"
msgstr "Zarz±dzanie Has³ami Klient/Serwer"

#: web/swat.c:902
msgid " Remote Machine : "
msgstr " Zdalna Maszyna : "

#: web/swat.c:940
msgid "Printer Parameters"
msgstr "Parametry Drukarki"

#: web/swat.c:942
msgid "Important Note:"
msgstr "Wa¿na Informacja:"

#: web/swat.c:943
msgid "Printer names marked with [*] in the Choose Printer drop-down box "
msgstr "Nazwy Drukarek zaznaczone [*] w rozwijanym polu Wybierz Drukarkê "

#: web/swat.c:944
msgid "are autoloaded printers from "
msgstr "s± drukarkami automatycznie ³adowanymi z "

#: web/swat.c:945
msgid "Printcap Name"
msgstr "Nazwa Printcap"

#: web/swat.c:946
msgid "Attempting to delete these printers from SWAT will have no effect.\n"
msgstr "Próby usuniêcia tych drukarek ze SWAT nie przynios± efektu.\n"

#: web/swat.c:980
msgid "Choose Printer"
msgstr "Wybierz Drukarkê"

#: web/swat.c:999
msgid "Delete Printer"
msgstr "Usuñ Drukarkê"

#: web/swat.c:1006
msgid "Create Printer"
msgstr "Utwórz Drukarkê"

#: web/statuspage.c:40
msgid "DENY_NONE"
msgstr ""

#: web/statuspage.c:41
msgid "DENY_ALL   "
msgstr ""

#: web/statuspage.c:42
msgid "DENY_DOS   "
msgstr ""

#: web/statuspage.c:43
msgid "DENY_READ  "
msgstr ""

#: web/statuspage.c:44
msgid "DENY_WRITE "
msgstr ""

#: web/statuspage.c:50
msgid "RDONLY     "
msgstr ""

#: web/statuspage.c:51
msgid "WRONLY     "
msgstr ""

#: web/statuspage.c:52
msgid "RDWR       "
msgstr ""

#: web/statuspage.c:60
msgid "EXCLUSIVE+BATCH "
msgstr ""

#: web/statuspage.c:62
msgid "EXCLUSIVE       "
msgstr ""

#: web/statuspage.c:64
msgid "BATCH           "
msgstr ""

#: web/statuspage.c:66
msgid "LEVEL_II        "
msgstr ""

#: web/statuspage.c:68
msgid "NONE            "
msgstr ""

#: web/statuspage.c:195
msgid "Server Status"
msgstr "Status Serwera"

#: web/statuspage.c:200
msgid "Auto Refresh"
msgstr "Automatyczne Od¶wie¿anie"

#: web/statuspage.c:201 web/statuspage.c:206
msgid "Refresh Interval: "
msgstr "Interwa³ Od¶wie¿ania: "

#: web/statuspage.c:205
msgid "Stop Refreshing"
msgstr "Zatrzymaj Od¶wie¿anie"

#: web/statuspage.c:220
msgid "version:"
msgstr "wersja:"

#: web/statuspage.c:223
msgid "smbd:"
msgstr ""

#: web/statuspage.c:223 web/statuspage.c:235
msgid "running"
msgstr "dzia³a"

#: web/statuspage.c:223 web/statuspage.c:235
msgid "not running"
msgstr "nie dzia³a"

#: web/statuspage.c:226
msgid "Stop smbd"
msgstr "Zatrzymaj smbd"

#: web/statuspage.c:228
msgid "Start smbd"
msgstr "Uruchom smbd"

#: web/statuspage.c:230
msgid "Restart smbd"
msgstr "Zrestartuj smbd"

#: web/statuspage.c:235
msgid "nmbd:"
msgstr ""

#: web/statuspage.c:238
msgid "Stop nmbd"
msgstr "Zatrzymaj nmbd"

#: web/statuspage.c:240
msgid "Start nmbd"
msgstr "Uruchom nmbd"

#: web/statuspage.c:242
msgid "Restart nmbd"
msgstr "Zrestartuj nmbd"

#: web/statuspage.c:249
msgid "Active Connections"
msgstr "Aktywne Po³±czenia"

#: web/statuspage.c:251 web/statuspage.c:264 web/statuspage.c:272
msgid "PID"
msgstr ""

#: web/statuspage.c:251 web/statuspage.c:264
msgid "Client"
msgstr "Klient"

#: web/statuspage.c:251
msgid "IP address"
msgstr "adres IP"

#: web/statuspage.c:251 web/statuspage.c:264 web/statuspage.c:272
msgid "Date"
msgstr "Data"

#: web/statuspage.c:253
msgid "Kill"
msgstr "Zatrzymaj"

#: web/statuspage.c:261
msgid "Active Shares"
msgstr "Aktywne Wspó³udzia³y"

#: web/statuspage.c:264
msgid "Share"
msgstr "Wspó³udzia³"

#: web/statuspage.c:264
msgid "User"
msgstr "U¿ytkownik"

#: web/statuspage.c:264
msgid "Group"
msgstr "Grupa"

#: web/statuspage.c:270
msgid "Open Files"
msgstr "Otwarte Pliki"

#: web/statuspage.c:272
msgid "Sharing"
msgstr "Wspó³dzielenie"

#: web/statuspage.c:272
msgid "R/W"
msgstr ""

#: web/statuspage.c:272
msgid "Oplock"
msgstr ""

#: web/statuspage.c:272
msgid "File"
msgstr "Plik"

#: param/loadparm.c:641
msgid "Base Options"
msgstr "Bazowe Opcje"

#: param/loadparm.c:643
#, fuzzy
msgid "dos charset"
msgstr "Wybierz Wspó³udzia³"

#: param/loadparm.c:644
msgid "unix charset"
msgstr ""

#: param/loadparm.c:645
msgid "display charset"
msgstr ""

#: param/loadparm.c:646
msgid "comment"
msgstr ""

#: param/loadparm.c:647
msgid "path"
msgstr ""

#: param/loadparm.c:648
msgid "directory"
msgstr ""

#: param/loadparm.c:649
msgid "workgroup"
msgstr ""

#: param/loadparm.c:650
msgid "netbios name"
msgstr ""

#: param/loadparm.c:651
msgid "netbios aliases"
msgstr ""

#: param/loadparm.c:652
msgid "netbios scope"
msgstr ""

#: param/loadparm.c:653
msgid "server string"
msgstr ""

#: param/loadparm.c:654
#, fuzzy
msgid "interfaces"
msgstr "Drukarki"

#: param/loadparm.c:655
msgid "bind interfaces only"
msgstr ""

#: param/loadparm.c:657
msgid "Security Options"
msgstr "Opcje Zabezpieczeñ"

#: param/loadparm.c:659
msgid "security"
msgstr ""

#: param/loadparm.c:660
msgid "encrypt passwords"
msgstr ""

#: param/loadparm.c:661
msgid "update encrypted"
msgstr ""

#: param/loadparm.c:662
msgid "allow trusted domains"
msgstr ""

#: param/loadparm.c:663
msgid "alternate permissions"
msgstr ""

#: param/loadparm.c:664
msgid "hosts equiv"
msgstr ""

#: param/loadparm.c:665
msgid "min passwd length"
msgstr ""

#: param/loadparm.c:666
msgid "min password length"
msgstr ""

#: param/loadparm.c:667
msgid "map to guest"
msgstr ""

#: param/loadparm.c:668
#, fuzzy
msgid "null passwords"
msgstr "Zmieñ Has³o"

#: param/loadparm.c:669
msgid "obey pam restrictions"
msgstr ""

#: param/loadparm.c:670
msgid "password server"
msgstr ""

#: param/loadparm.c:671
msgid "smb passwd file"
msgstr ""

#: param/loadparm.c:672
msgid "private dir"
msgstr ""

#: param/loadparm.c:673
msgid "passdb module path"
msgstr ""

#: param/loadparm.c:674
msgid "root directory"
msgstr ""

#: param/loadparm.c:675
msgid "root dir"
msgstr ""

#: param/loadparm.c:676
msgid "root"
msgstr ""

#: param/loadparm.c:678
#, fuzzy
msgid "pam password change"
msgstr "Zarz±dzanie Has³ami"

#: param/loadparm.c:679
msgid "passwd program"
msgstr ""

#: param/loadparm.c:680
msgid "passwd chat"
msgstr ""

#: param/loadparm.c:681
msgid "passwd chat debug"
msgstr ""

#: param/loadparm.c:682
msgid "username map"
msgstr ""

#: param/loadparm.c:683
#, fuzzy
msgid "password level"
msgstr "Zarz±dzanie Has³ami"

#: param/loadparm.c:684
msgid "username level"
msgstr ""

#: param/loadparm.c:685
msgid "unix password sync"
msgstr ""

#: param/loadparm.c:686
msgid "restrict anonymous"
msgstr ""

#: param/loadparm.c:687
msgid "lanman auth"
msgstr ""

#: param/loadparm.c:688
msgid "ntlm auth"
msgstr ""

#: param/loadparm.c:689
msgid "plaintext to smbpasswd"
msgstr ""

#: param/loadparm.c:690
msgid "use rhosts"
msgstr ""

#: param/loadparm.c:692
msgid "username"
msgstr ""

#: param/loadparm.c:693
#, fuzzy
msgid "user"
msgstr "U¿ytkownik"

#: param/loadparm.c:694
#, fuzzy
msgid "users"
msgstr "U¿ytkownik"

#: param/loadparm.c:696
msgid "guest account"
msgstr ""

#: param/loadparm.c:697
msgid "invalid users"
msgstr ""

#: param/loadparm.c:698
msgid "valid users"
msgstr ""

#: param/loadparm.c:699
msgid "admin users"
msgstr ""

#: param/loadparm.c:700
msgid "read list"
msgstr ""

#: param/loadparm.c:701
msgid "write list"
msgstr ""

#: param/loadparm.c:702
msgid "printer admin"
msgstr ""

#: param/loadparm.c:703
msgid "force user"
msgstr ""

#: param/loadparm.c:704
msgid "force group"
msgstr ""

#: param/loadparm.c:705
#, fuzzy
msgid "group"
msgstr "Grupa"

#: param/loadparm.c:707
msgid "read only"
msgstr ""

#: param/loadparm.c:708
msgid "write ok"
msgstr ""

#: param/loadparm.c:709
msgid "writeable"
msgstr ""

#: param/loadparm.c:710
msgid "writable"
msgstr ""

#: param/loadparm.c:712
#, fuzzy
msgid "create mask"
msgstr "Utwórz Wspó³udzia³"

#: param/loadparm.c:713
#, fuzzy
msgid "create mode"
msgstr "Utwórz Wspó³udzia³"

#: param/loadparm.c:714
msgid "force create mode"
msgstr ""

#: param/loadparm.c:715
#, fuzzy
msgid "security mask"
msgstr "Opcje Zabezpieczeñ"

#: param/loadparm.c:716
msgid "force security mode"
msgstr ""

#: param/loadparm.c:717
msgid "directory mask"
msgstr ""

#: param/loadparm.c:718
msgid "directory mode"
msgstr ""

#: param/loadparm.c:719
msgid "force directory mode"
msgstr ""

#: param/loadparm.c:720
msgid "directory security mask"
msgstr ""

#: param/loadparm.c:721
msgid "force directory security mode"
msgstr ""

#: param/loadparm.c:722
msgid "inherit permissions"
msgstr ""

#: param/loadparm.c:723
msgid "guest only"
msgstr ""

#: param/loadparm.c:724
msgid "only guest"
msgstr ""

#: param/loadparm.c:726
msgid "guest ok"
msgstr ""

#: param/loadparm.c:727
msgid "public"
msgstr ""

#: param/loadparm.c:729
#, fuzzy
msgid "only user"
msgstr "Odblokuj U¿ytkownika"

#: param/loadparm.c:730
msgid "hosts allow"
msgstr ""

#: param/loadparm.c:731
msgid "allow hosts"
msgstr ""

#: param/loadparm.c:732
msgid "hosts deny"
msgstr ""

#: param/loadparm.c:733
msgid "deny hosts"
msgstr ""

#: param/loadparm.c:736
msgid "Secure Socket Layer Options"
msgstr "Opcje SSL"

#: param/loadparm.c:737
msgid "ssl"
msgstr ""

#: param/loadparm.c:739
msgid "ssl hosts"
msgstr ""

#: param/loadparm.c:740
msgid "ssl hosts resign"
msgstr ""

#: param/loadparm.c:741
msgid "ssl CA certDir"
msgstr ""

#: param/loadparm.c:742
msgid "ssl CA certFile"
msgstr ""

#: param/loadparm.c:743
msgid "ssl server cert"
msgstr ""

#: param/loadparm.c:744
msgid "ssl server key"
msgstr ""

#: param/loadparm.c:745
msgid "ssl client cert"
msgstr ""

#: param/loadparm.c:746
msgid "ssl client key"
msgstr ""

#: param/loadparm.c:747
msgid "ssl require clientcert"
msgstr ""

#: param/loadparm.c:748
msgid "ssl require servercert"
msgstr ""

#: param/loadparm.c:749
msgid "ssl ciphers"
msgstr ""

#: param/loadparm.c:750
#, fuzzy
msgid "ssl version"
msgstr "wersja:"

#: param/loadparm.c:751
msgid "ssl compatibility"
msgstr ""

#: param/loadparm.c:754
#, fuzzy
msgid "Logging Options"
msgstr "Opcje Blokowania"

#: param/loadparm.c:755
msgid "log level"
msgstr ""

#: param/loadparm.c:756
msgid "debuglevel"
msgstr ""

#: param/loadparm.c:757
msgid "syslog"
msgstr ""

#: param/loadparm.c:758
msgid "syslog only"
msgstr ""

#: param/loadparm.c:759
msgid "log file"
msgstr ""

#: param/loadparm.c:761
msgid "max log size"
msgstr ""

#: param/loadparm.c:762
msgid "timestamp logs"
msgstr ""

#: param/loadparm.c:763
msgid "debug timestamp"
msgstr ""

#: param/loadparm.c:764
msgid "debug hires timestamp"
msgstr ""

#: param/loadparm.c:765
msgid "debug pid"
msgstr ""

#: param/loadparm.c:766
msgid "debug uid"
msgstr ""

#: param/loadparm.c:768
msgid "Protocol Options"
msgstr "Opcje Protoko³u"

#: param/loadparm.c:770
msgid "protocol"
msgstr ""

#: param/loadparm.c:771
msgid "large readwrite"
msgstr ""

#: param/loadparm.c:772
msgid "max protocol"
msgstr ""

#: param/loadparm.c:773
msgid "min protocol"
msgstr ""

#: param/loadparm.c:774
msgid "unicode"
msgstr ""

#: param/loadparm.c:775
msgid "read bmpx"
msgstr ""

#: param/loadparm.c:776
msgid "read raw"
msgstr ""

#: param/loadparm.c:777
msgid "write raw"
msgstr ""

#: param/loadparm.c:779
msgid "nt smb support"
msgstr ""

#: param/loadparm.c:780
msgid "nt pipe support"
msgstr ""

#: param/loadparm.c:781
msgid "nt acl support"
msgstr ""

#: param/loadparm.c:782
msgid "announce version"
msgstr ""

#: param/loadparm.c:783
msgid "announce as"
msgstr ""

#: param/loadparm.c:784
msgid "max mux"
msgstr ""

#: param/loadparm.c:785
msgid "max xmit"
msgstr ""

#: param/loadparm.c:787
msgid "name resolve order"
msgstr ""

#: param/loadparm.c:788
msgid "max packet"
msgstr ""

#: param/loadparm.c:789
msgid "packet size"
msgstr ""

#: param/loadparm.c:790
msgid "max ttl"
msgstr ""

#: param/loadparm.c:791
msgid "max wins ttl"
msgstr ""

#: param/loadparm.c:792
msgid "min wins ttl"
msgstr ""

#: param/loadparm.c:793
msgid "time server"
msgstr ""

#: param/loadparm.c:795
msgid "Tuning Options"
msgstr "Opcje Dostrajaj±ce"

#: param/loadparm.c:797
msgid "change notify timeout"
msgstr ""

#: param/loadparm.c:798
msgid "deadtime"
msgstr ""

#: param/loadparm.c:799
msgid "getwd cache"
msgstr ""

#: param/loadparm.c:800
msgid "keepalive"
msgstr ""

#: param/loadparm.c:802
msgid "lpq cache time"
msgstr ""

#: param/loadparm.c:803
msgid "max smbd processes"
msgstr ""

#: param/loadparm.c:804
#, fuzzy
msgid "max connections"
msgstr "Aktywne Po³±czenia"

#: param/loadparm.c:805
msgid "paranoid server security"
msgstr ""

#: param/loadparm.c:806
msgid "max disk size"
msgstr ""

#: param/loadparm.c:807
#, fuzzy
msgid "max open files"
msgstr "Otwarte Pliki"

#: param/loadparm.c:808
msgid "min print space"
msgstr ""

#: param/loadparm.c:809
msgid "read size"
msgstr ""

#: param/loadparm.c:811
#, fuzzy
msgid "socket options"
msgstr "Bazowe Opcje"

#: param/loadparm.c:812
msgid "stat cache size"
msgstr ""

#: param/loadparm.c:813
msgid "strict allocate"
msgstr ""

#: param/loadparm.c:814
msgid "strict sync"
msgstr ""

#: param/loadparm.c:815
msgid "sync always"
msgstr ""

#: param/loadparm.c:816
msgid "use mmap"
msgstr ""

#: param/loadparm.c:817
msgid "hostname lookups"
msgstr ""

#: param/loadparm.c:818
msgid "write cache size"
msgstr ""

#: param/loadparm.c:820
msgid "Printing Options"
msgstr "Opcje Drukowania"

#: param/loadparm.c:822
msgid "total print jobs"
msgstr ""

#: param/loadparm.c:823
msgid "max print jobs"
msgstr ""

#: param/loadparm.c:824
#, fuzzy
msgid "load printers"
msgstr "Drukarki"

#: param/loadparm.c:825
#, fuzzy
msgid "printcap name"
msgstr "Nazwa Printcap"

#: param/loadparm.c:826
#, fuzzy
msgid "printcap"
msgstr "Nazwa Printcap"

#: param/loadparm.c:827
msgid "printable"
msgstr ""

#: param/loadparm.c:828
msgid "print ok"
msgstr ""

#: param/loadparm.c:829
msgid "postscript"
msgstr ""

#: param/loadparm.c:830
#, fuzzy
msgid "printing"
msgstr "dzia³a"

#: param/loadparm.c:831
msgid "print command"
msgstr ""

#: param/loadparm.c:832
msgid "disable spoolss"
msgstr ""

#: param/loadparm.c:833
msgid "lpq command"
msgstr ""

#: param/loadparm.c:834
msgid "lprm command"
msgstr ""

#: param/loadparm.c:835
msgid "lppause command"
msgstr ""

#: param/loadparm.c:836
msgid "lpresume command"
msgstr ""

#: param/loadparm.c:837
msgid "queuepause command"
msgstr ""

#: param/loadparm.c:838
msgid "queueresume command"
msgstr ""

#: param/loadparm.c:840
msgid "enumports command"
msgstr ""

#: param/loadparm.c:841
msgid "addprinter command"
msgstr ""

#: param/loadparm.c:842
#, fuzzy
msgid "deleteprinter command"
msgstr "Usuñ Drukarkê"

#: param/loadparm.c:843
msgid "show add printer wizard"
msgstr ""

#: param/loadparm.c:844
msgid "os2 driver map"
msgstr ""

#: param/loadparm.c:846
#, fuzzy
msgid "printer name"
msgstr "Parametry Drukarki"

#: param/loadparm.c:847
#, fuzzy
msgid "printer"
msgstr "Drukarki"

#: param/loadparm.c:848
msgid "use client driver"
msgstr ""

#: param/loadparm.c:849
#, fuzzy
msgid "printer driver"
msgstr "Parametry Drukarki"

#: param/loadparm.c:850
msgid "printer driver file"
msgstr ""

#: param/loadparm.c:851
msgid "printer driver location"
msgstr ""

#: param/loadparm.c:853
msgid "Filename Handling"
msgstr "Obs³uga Nazw Plików"

#: param/loadparm.c:854
msgid "strip dot"
msgstr ""

#: param/loadparm.c:856
msgid "mangled stack"
msgstr ""

#: param/loadparm.c:857
msgid "default case"
msgstr ""

#: param/loadparm.c:858
msgid "case sensitive"
msgstr ""

#: param/loadparm.c:859
msgid "casesignames"
msgstr ""

#: param/loadparm.c:860
msgid "preserve case"
msgstr ""

#: param/loadparm.c:861
msgid "short preserve case"
msgstr ""

#: param/loadparm.c:862
msgid "mangle case"
msgstr ""

#: param/loadparm.c:863
msgid "mangling char"
msgstr ""

#: param/loadparm.c:864
msgid "hide dot files"
msgstr ""

#: param/loadparm.c:865
msgid "hide unreadable"
msgstr ""

#: param/loadparm.c:866
msgid "delete veto files"
msgstr ""

#: param/loadparm.c:867
#, fuzzy
msgid "veto files"
msgstr "Otwarte Pliki"

#: param/loadparm.c:868
#, fuzzy
msgid "hide files"
msgstr "Otwarte Pliki"

#: param/loadparm.c:869
msgid "veto oplock files"
msgstr ""

#: param/loadparm.c:870
msgid "map system"
msgstr ""

#: param/loadparm.c:871
msgid "map hidden"
msgstr ""

#: param/loadparm.c:872
msgid "map archive"
msgstr ""

#: param/loadparm.c:873
msgid "mangled names"
msgstr ""

#: param/loadparm.c:874
msgid "mangled map"
msgstr ""

#: param/loadparm.c:875
msgid "stat cache"
msgstr ""

#: param/loadparm.c:877
msgid "Domain Options"
msgstr "Opcje Domeny"

#: param/loadparm.c:879
msgid "domain admin group"
msgstr ""

#: param/loadparm.c:880
msgid "domain guest group"
msgstr ""

#: param/loadparm.c:883
msgid "groupname map"
msgstr ""

#: param/loadparm.c:886
msgid "machine password timeout"
msgstr ""

#: param/loadparm.c:888
msgid "Logon Options"
msgstr "Opcje Logowania"

#: param/loadparm.c:890
msgid "add user script"
msgstr ""

#: param/loadparm.c:891
#, fuzzy
msgid "delete user script"
msgstr "Usuñ U¿ytkownika"

#: param/loadparm.c:892
msgid "add group script"
msgstr ""

#: param/loadparm.c:893
msgid "delete group script"
msgstr ""

#: param/loadparm.c:894
msgid "add user to group script"
msgstr ""

#: param/loadparm.c:895
msgid "delete user from group script"
msgstr ""

#: param/loadparm.c:896
msgid "add machine script"
msgstr ""

#: param/loadparm.c:897
msgid "shutdown script"
msgstr ""

#: param/loadparm.c:898
msgid "abort shutdown script"
msgstr ""

#: param/loadparm.c:900
msgid "logon script"
msgstr ""

#: param/loadparm.c:901
#, fuzzy
msgid "logon path"
msgstr "Opcje Logowania"

#: param/loadparm.c:902
msgid "logon drive"
msgstr ""

#: param/loadparm.c:903
msgid "logon home"
msgstr ""

#: param/loadparm.c:904
#, fuzzy
msgid "domain logons"
msgstr "Opcje Domeny"

#: param/loadparm.c:906
msgid "Browse Options"
msgstr "Opcje Przegl±dania"

#: param/loadparm.c:908
msgid "os level"
msgstr ""

#: param/loadparm.c:909
msgid "lm announce"
msgstr ""

#: param/loadparm.c:910
msgid "lm interval"
msgstr ""

#: param/loadparm.c:911
msgid "preferred master"
msgstr ""

#: param/loadparm.c:912
msgid "prefered master"
msgstr ""

#: param/loadparm.c:913
msgid "local master"
msgstr ""

#: param/loadparm.c:914
msgid "domain master"
msgstr ""

#: param/loadparm.c:915
#, fuzzy
msgid "browse list"
msgstr "Opcje Przegl±dania"

#: param/loadparm.c:916
msgid "browseable"
msgstr ""

#: param/loadparm.c:917
msgid "browsable"
msgstr ""

#: param/loadparm.c:918
msgid "enhanced browsing"
msgstr ""

#: param/loadparm.c:920
msgid "WINS Options"
msgstr "Opcje WINS"

#: param/loadparm.c:921
msgid "dns proxy"
msgstr ""

#: param/loadparm.c:922
msgid "wins proxy"
msgstr ""

#: param/loadparm.c:924
msgid "wins server"
msgstr ""

#: param/loadparm.c:925
msgid "wins support"
msgstr ""

#: param/loadparm.c:926
msgid "wins hook"
msgstr ""

#: param/loadparm.c:928
msgid "Locking Options"
msgstr "Opcje Blokowania"

#: param/loadparm.c:930
#, fuzzy
msgid "blocking locks"
msgstr "Opcje Blokowania"

#: param/loadparm.c:931
msgid "fake oplocks"
msgstr ""

#: param/loadparm.c:932
msgid "kernel oplocks"
msgstr ""

#: param/loadparm.c:933
msgid "locking"
msgstr ""

#: param/loadparm.c:935
msgid "oplocks"
msgstr ""

#: param/loadparm.c:936
msgid "level2 oplocks"
msgstr ""

#: param/loadparm.c:937
msgid "oplock break wait time"
msgstr ""

#: param/loadparm.c:938
msgid "oplock contention limit"
msgstr ""

#: param/loadparm.c:939
msgid "posix locking"
msgstr ""

#: param/loadparm.c:940
msgid "strict locking"
msgstr ""

#: param/loadparm.c:941
msgid "share modes"
msgstr ""

#: param/loadparm.c:944
msgid "Ldap Options"
msgstr "Opcje Ldap"

#: param/loadparm.c:946
msgid "ldap server"
msgstr ""

#: param/loadparm.c:947
msgid "ldap port"
msgstr ""

#: param/loadparm.c:948
msgid "ldap suffix"
msgstr ""

#: param/loadparm.c:949
msgid "ldap filter"
msgstr ""

#: param/loadparm.c:950
msgid "ldap root"
msgstr ""

#: param/loadparm.c:951
msgid "ldap root passwd"
msgstr ""

#: param/loadparm.c:954
msgid "Miscellaneous Options"
msgstr "Pozosta³e Opcje"

#: param/loadparm.c:955
msgid "add share command"
msgstr ""

#: param/loadparm.c:956
msgid "change share command"
msgstr ""

#: param/loadparm.c:957
#, fuzzy
msgid "delete share command"
msgstr "Usuñ Wspó³udzia³"

#: param/loadparm.c:959
msgid "config file"
msgstr ""

#: param/loadparm.c:960
msgid "preload"
msgstr ""

#: param/loadparm.c:961
#, fuzzy
msgid "auto services"
msgstr "Automatyczne Od¶wie¿anie"

#: param/loadparm.c:962
msgid "lock dir"
msgstr ""

#: param/loadparm.c:963
msgid "lock directory"
msgstr ""

#: param/loadparm.c:965
msgid "utmp directory"
msgstr ""

#: param/loadparm.c:966
msgid "wtmp directory"
msgstr ""

#: param/loadparm.c:967
msgid "utmp"
msgstr ""

#: param/loadparm.c:970
msgid "default service"
msgstr ""

#: param/loadparm.c:971
#, fuzzy
msgid "default"
msgstr "Ustaw domy¶lnie"

#: param/loadparm.c:972
msgid "message command"
msgstr ""

#: param/loadparm.c:973
msgid "dfree command"
msgstr ""

#: param/loadparm.c:974
msgid "remote announce"
msgstr ""

#: param/loadparm.c:975
msgid "remote browse sync"
msgstr ""

#: param/loadparm.c:976
#, fuzzy
msgid "socket address"
msgstr "adres IP"

#: param/loadparm.c:977
msgid "homedir map"
msgstr ""

#: param/loadparm.c:978
msgid "time offset"
msgstr ""

#: param/loadparm.c:979
msgid "NIS homedir"
msgstr ""

#: param/loadparm.c:980
msgid "-valid"
msgstr ""

#: param/loadparm.c:982
msgid "copy"
msgstr ""

#: param/loadparm.c:983
msgid "include"
msgstr ""

#: param/loadparm.c:984
msgid "exec"
msgstr ""

#: param/loadparm.c:985
msgid "preexec"
msgstr ""

#: param/loadparm.c:987
msgid "preexec close"
msgstr ""

#: param/loadparm.c:988
msgid "postexec"
msgstr ""

#: param/loadparm.c:989
msgid "root preexec"
msgstr ""

#: param/loadparm.c:990
msgid "root preexec close"
msgstr ""

#: param/loadparm.c:991
msgid "root postexec"
msgstr ""

#: param/loadparm.c:992
msgid "available"
msgstr ""

#: param/loadparm.c:993
#, fuzzy
msgid "volume"
msgstr "Strona domowa"

#: param/loadparm.c:994
msgid "fstype"
msgstr ""

#: param/loadparm.c:995
msgid "set directory"
msgstr ""

#: param/loadparm.c:996
msgid "source environment"
msgstr ""

#: param/loadparm.c:997
msgid "wide links"
msgstr ""

#: param/loadparm.c:998
msgid "follow symlinks"
msgstr ""

#: param/loadparm.c:999
msgid "dont descend"
msgstr ""

#: param/loadparm.c:1000
msgid "magic script"
msgstr ""

#: param/loadparm.c:1001
msgid "magic output"
msgstr ""

#: param/loadparm.c:1002
msgid "delete readonly"
msgstr ""

#: param/loadparm.c:1003
msgid "dos filemode"
msgstr ""

#: param/loadparm.c:1004
msgid "dos filetimes"
msgstr ""

#: param/loadparm.c:1005
msgid "dos filetime resolution"
msgstr ""

#: param/loadparm.c:1007
msgid "fake directory create times"
msgstr ""

#: param/loadparm.c:1008
msgid "panic action"
msgstr ""

#: param/loadparm.c:1009
msgid "hide local users"
msgstr ""

#: param/loadparm.c:1012
#, fuzzy
msgid "VFS options"
msgstr "Opcje WINS"

#: param/loadparm.c:1014
msgid "vfs object"
msgstr ""

#: param/loadparm.c:1015
#, fuzzy
msgid "vfs options"
msgstr "Bazowe Opcje"

#: param/loadparm.c:1018
msgid "msdfs root"
msgstr ""

#: param/loadparm.c:1019
msgid "host msdfs"
msgstr ""

#: param/loadparm.c:1021
#, fuzzy
msgid "Winbind options"
msgstr "Opcje Drukowania"

#: param/loadparm.c:1023
msgid "winbind uid"
msgstr ""

#: param/loadparm.c:1024
msgid "winbind gid"
msgstr ""

#: param/loadparm.c:1025
msgid "template homedir"
msgstr ""

#: param/loadparm.c:1026
msgid "template shell"
msgstr ""

#: param/loadparm.c:1027
msgid "winbind separator"
msgstr ""

#: param/loadparm.c:1028
msgid "winbind cache time"
msgstr ""

#: param/loadparm.c:1029
msgid "winbind enum users"
msgstr ""

#: param/loadparm.c:1030
msgid "winbind enum groups"
msgstr ""

#~ msgid "failed to open %s for writing\n"
#~ msgstr "nie uda³o siê otworzyæ %s do zapisu\n"

#~ msgid "Can't reload %s\n"
#~ msgstr "Nie mogê prze³adowaæ %s\n"

#~ msgid "Can't setup password database vectors.\n"
#~ msgstr "Nie mo¿na ustawiæ wektorów bazy hase³.\n"

#~ msgid "You need to have status=yes in your smb config file\n"
#~ msgstr "Musisz mieæ status=yes w swoim pliku konfiguracyjnym smb\n"
