#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('CREDENTIALS',
	source='credentials.c',
	autoproto='credentials_proto.h',
	public_headers='credentials.h',
	deps='LIBCRYPTO errors events LIBCLI_AUTH security',
	)

bld.SAMBA_SUBSYSTEM('CREDENTIALS_KRB5',
	source='credentials_krb5.c',
	deps='KERBEROS_UTIL gssapi CREDENTIALS',
	public_deps='com_err KERBEROS',
	)

bld.SAMBA_SUBSYSTEM('CREDENTIALS_SECRETS',
	source='credentials_secrets.c',
	deps='SECRETS CREDENTIALS_KRB5 CREDENTIALS_NTLM ldb',
	)

bld.SAMBA_SUBSYSTEM('CREDENTIALS_NTLM',
	source='credentials_ntlm.c',
	deps='CREDENTIALS')

bld.SAMBA_PYTHON('pycredentials',
	source='pycredentials.c',
	public_deps='CREDENTIALS LIBCMDLINE_CREDENTIALS pytalloc-util pyparam_util CREDENTIALS_KRB5 CREDENTIALS_SECRETS',
	realname='samba/credentials.so'
	)

