#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('CREDENTIALS',
	source='credentials.c credentials_files.c credentials_ntlm.c credentials_krb5.c ../kerberos/kerberos_util.c',
	autoproto='credentials_proto.h',
	public_deps='LIBCLI_AUTH SECRETS LIBCRYPTO KERBEROS UTIL_LDB HEIMDAL_GSSAPI',
	public_headers='credentials.h',
	deps='SECRETS SAMDB'
	)


bld.SAMBA_PYTHON('pycredentials',
	source='pycredentials.c',
	public_deps='CREDENTIALS LIBCMDLINE_CREDENTIALS PYTALLOC pyparam_util',
	realname='samba/credentials.so'
	)

