#!/bin/sh
# event script for 'make test'

. "${CTDB_BASE}/functions"

ctdb_check_args "$@"

event="$1"
shift

case "$event" in
    monitor)
	echo "monitor event"
	echo "monitor event stderr" >&2
	exit 0
	;;

     startrecovery)
	echo "ctdb startrecovery event"
	exit 0;	
	;;

     init)
	echo "ctdb init event"
	exit 0;
	;;
     setup)
	echo "ctdb setup event"
	exit 0;
	;;
     startup)
	echo "ctdb startup event"
	IFACES=`ctdb ifaces -X | grep -v '^|Name|LinkStatus|References|'`
	for I in $IFACES; do
		IFACE=`echo -n "$I" | cut -d '|' -f2`
		ctdb setifacelink $IFACE up
	done
	exit 0;
	;;
	
     takeip)
	echo "ctdb takeip event for $1 $2 $3"
	exit 0;
	;;

     releaseip)
	echo "ctdb releaseip event for $1 $2 $3"
	exit 0
	;;

     updateip)
	echo "ctdb updateip event for $1"
	exit 0
	;;

     recovered)
	echo "ctdb recovered event"
	exit 0
	;;

     ipreallocated)
	echo "ctdb ipreallocated event"
	exit 0
	;;


     shutdown)
	echo "ctdb shutdown event"
	exit 0
	;;

     stopped)
	echo "ctdb stopped event"
	exit 0
	;;
esac
