#! /bin/sh

echo "fixing distribution in $1..."

cd $1

ver=`sed -n 's/AM_INIT_AUTOMAKE(.*,\(.*\))/\1/p' configure.in`
echo "*************************************************************"
echo "*                                                           *"
echo "* Hej $USER!                                                *"
echo "* Har du uppdaterat versionsnummret? Detta är version $ver. *"
echo "*                                                           *"
echo "*************************************************************"

ed -s configure.in << END
/test -z/s,^,#,
w
q
END
aclocal -I cf
autoconf
autoheader
automake
(cd doc; makeinfo heimdal.texi)
(cd lib/krb5; perl ../../cf/make-proto.pl `perl -e '
	do { 
		$_ = <>; 
	} until(/libkrb5_la_SOURCES/); 
	while(/\\\\\s*$/s){ 
		$_ = $_ . <>;
	} 
	s/\n//g; 
	s/\\\\//g; 
	s/.*=//; 
	s/\s+/ /g; 
	print;' Makefile.in` > krb5-protos.h)
rm fix-export make-release make-release.el
find . -name .cvsignore -print | xargs rm
