#! /bin/sh

echo "fixing distribution in $1..."

cd $1
aclocal
autoconf
autoheader
automake
(cd doc; makeinfo heimdal.texi)
(cd lib/krb5; perl ../../aux/make-proto.pl `perl -e '
	do { 
		$_ = <>; 
	} until(/libkrb5_a_SOURCES/); 
	while(/\\\\\s*$/s){ 
		$_ = $_ . <>;
	} 
	s/\n//g; 
	s/\\\\//g; 
	s/.*=//; 
	s/\s+/ /g; 
	print;' Makefile.in` > krb5-protos.h)
rm fix-export make-release make-release.el
