#!/usr/bin/env python

bld.SAMBA3_SUBSYSTEM('NDR_LIBNETAPI',
        cflags="-D SKIP_NDR_TABLE_libnetapi",
	source='gen_ndr/ndr_libnetapi.c',
	public_deps='ndr',
	allow_warnings=True
	)

bld.SAMBA3_SUBSYSTEM('NDR_LIBNET_JOIN',
	source='gen_ndr/ndr_libnet_join.c',
	public_deps='ndr krb5samba'
	)

bld.SAMBA3_SUBSYSTEM('NDR_OPEN_FILES',
	source='gen_ndr/ndr_open_files.c',
	public_deps='ndr NDR_SERVER_ID NDR_FILE_ID NDR_SECURITY NDR_SMB2_LEASE_STRUCT'
	)

bld.SAMBA3_SUBSYSTEM('NDR_SMBXSRV',
	source='gen_ndr/ndr_smbXsrv.c',
	public_deps='ndr NDR_SERVER_ID NDR_SECURITY NDR_AUTH'
	)

bld.SAMBA3_SUBSYSTEM('NDR_LEASES_DB',
	source='gen_ndr/ndr_leases_db.c',
	public_deps='ndr NDR_SMB2_LEASE_STRUCT NDR_FILE_ID'
	)

bld.SAMBA3_SUBSYSTEM('NDR_SECRETS',
	source='gen_ndr/ndr_secrets.c',
	public_deps='ndr NDR_SAMR NDR_LSA NDR_NETLOGON NDR_SECURITY'
	)

bld.SAMBA3_SUBSYSTEM('NDR_PERFCOUNT',
	source='gen_ndr/ndr_perfcount.c',
	public_deps='ndr'
	)

