[
	uuid("ecec0d70-a603-11d0-96b1-00a0c91ece30"),
	version(1.0),
	pointer_default(unique),
	helpstring("Backup support for Active Directory")
] interface ad_backup
{
	void HrRBackupPrepare();
	void HrRBackupEnd();
	void HrRBackupGetAttachmentInformation();
	void HrRBackupOpenFile();
	void HrRBackupRead();
	void HrRBackupClose();
	void HrRBackupGetBackupLogs();
	void HrRBackupTruncateLogs();
	void HrRBackupPing();
}

[
	uuid("16e0cf3a-a604-11d0-96b1-00a0c91ece30"),
	version(1.0),
    	pointer_default(unique),
	helpstring("Restoring Active Directory backups")
] interface ad_restore
{
	void HrRIsNTDSOnline();
	void HrRRestorePrepare();
	void HrRRestoreRegister();
	void HrRRestoreRegisterComplete();
	void HrRRestoreGetDatabaseLocations();
	void HrRRestoreEnd();
	void HrRRestoreSetCurrentLogNumber();
	void HrRRestoreCheckLogsForBackup();
}
