#include "idl_types.h"

/*
  dssetup interface definition
*/

[
	uuid("3919286a-b10c-11d0-9ba8-00c04fd92ef5"),
	version(0.0),
	endpoint("ncacn_np:[\\pipe\\lsarpc]","ncacn_np:[\\pipe\\lsass]"),
	pointer_default(unique),
	helpstring("Active Directory Setup")
] interface dssetup
{
	/**********************************************/
	/* Function 0x00                              */

	typedef struct {
		uint16    role;
		uint32    flags;
		unistr    *domain;
		unistr    *dns_domain;
		unistr    *forest;
		GUID domain_guid;
	} ds_DomainBasicInformation;
	
	typedef union {
		[case(1)] ds_DomainBasicInformation basic;
	} ds_DomainInformation;

	WERROR ds_RolerGetPrimaryDomainInformation(
		[in] uint16 level,
		[out,switch_is(level)] ds_DomainInformation *info
		);


	WERROR ds_RolerDnsNameToFlatName();
	WERROR ds_RolerDcAsDc();
	WERROR ds_RolerDcAsReplica();
	WERROR ds_RolerDemoteDc();
	WERROR ds_RolerGetDcOperationProgress();
	WERROR ds_RolerGetDcOperationResults();
	WERROR ds_RolerCancel();
	WERROR ds_RolerServerSaveStateForUpgrade();
	WERROR ds_RolerUpgradeDownlevelServer();
	WERROR ds_RolerAbortDownlevelServerUpgrade();
}
