#include "idl_types.h"

import "misc.idl";

[
  uuid("d049b186-814f-11d1-9a3c-00c04fc9b232"),
  version(1.1),
  endpoint("ncacn_ip_tcp:", "ncalrpc:"),
  helpstring("File Replication API"),
  pointer_default(unique)
]
interface frsapi
{
	/****************/
	/* Function 0x00 */
	void FRSAPI_VERIFY_PROMOTION();

	/****************/
	/* Function 0x01 */
	void FRSAPI_PROMOTION_STATUS();

	/****************/
	/* Function 0x02 */
	void FRSAPI_START_DEMOTION();

	/****************/
	/* Function 0x03 */
	void FRSAPI_COMMIT_DEMOTION();

	/****************/
	/* Function 0x04 */
	WERROR frsapi_SetDsPollingIntervalW(
		[in] uint32 CurrentInterval,
		[in] uint32 DsPollingLongInterval,
		[in] uint32 DsPollingShortInterval
	);

        /****************/
        /* Function 0x05 */
	WERROR frsapi_GetDsPollingIntervalW(
		[out] uint32 *CurrentInterval,
		[out] uint32 *DsPollingLongInterval,
		[out] uint32 *DsPollingShortInterval
	);

	/****************/
	/* Function 0x06 */
	void FRSAPI_VERIFY_PROMOTION_W();

	/****************/
	/* Function 0x07 */

	typedef enum {
		FRSAPI_INFO_VERSION	= 0,
		FRSAPI_INFO_SETS	= 1,
		FRSAPI_INFO_DS		= 2,
		FRSAPI_INFO_MEMORY	= 3,
		FRSAPI_INFO_IDTABLE	= 4,
		FRSAPI_INFO_OUTLOG	= 5,
		FRSAPI_INFO_INLOG	= 6,
		FRSAPI_INFO_THREADS	= 7,
		FRSAPI_INFO_STAGE	= 8,
		FRSAPI_INFO_CONFIGTABLE	= 9
	} frsapi_InfoEnum;

	void FRSAPI_INFO_W();

	/****************/
	/* Function 0x08 */
	WERROR frsapi_IsPathReplicated(
		[in,unique] [string,charset(UTF16)] uint16 *path,
		[in] uint32 unknown,
		[out] uint32 *unknown1,
		[out] uint32 *unknown2,
		[out] uint32 *unknown3,
		[out] GUID *guid
	);

	/****************/
	/* Function 0x09 */
	void FRSAPI_WRITER_COMMAND();
}
