#include "idl_types.h"

/*
   IDL structures for messaging code
*/

[
  pointer_default(unique)
]
interface messaging
{
	/* messaging struct sent across the sockets and stored in the tdb */

	typedef [public] struct {
		uint32 msg_version;
		uint32 msg_type;
		server_id dest;
		server_id src;
		DATA_BLOB buf;
	} messaging_rec;

	typedef [public] struct {
		uint32 num_messages;
		messaging_rec messages[num_messages];
	} messaging_array;
}
