#include "idl_types.h"

/*
   IDL structures for messaging code
*/

[
  pointer_default(unique)
]
interface messaging
{
	/* messaging struct sent across the sockets and stored in the tdb */

	typedef [public] struct {
		uint32 msg_version;
		uint32 msg_type;
		server_id dest;
		server_id src;
		DATA_BLOB buf;
	} messaging_rec;

	typedef [public] struct {
		uint32 num_messages;
		messaging_rec messages[num_messages];
	} messaging_array;

	/*
	 * struct used for change notify messages
	 * in the dbwrap_tdb2 code
	 */
	typedef [public] struct {
		[charset(DOS),value("TDB2")] uint8 magic_string[4];
		[value(1)] uint32 magic_version;
		[charset(UTF8),string] uint8 name[];
		uint32 old_seqnum;
		uint32 new_seqnum;
		uint32 num_changes;
		uint32 num_keys;
		DATA_BLOB keys[num_keys];
	} dbwrap_tdb2_changes;
}
