#include "idl_types.h"

/*
  miscellaneous IDL structures
*/

interface misc
{
	/* server roles */
	typedef enum {
		ROLE_STANDALONE    = 0,
		ROLE_DOMAIN_MEMBER = 1,
		ROLE_DOMAIN_BDC    = 2,
		ROLE_DOMAIN_PDC    = 3
	} samr_Role;


	typedef [public,noprint,gensize] struct {
		uint32 time_low;
		uint16 time_mid;
		uint16 time_hi_and_version;
		uint8  clock_seq[2];
		uint8  node[6];
	} GUID;

	typedef [public] struct {
		uint32 handle_type;
		GUID   uuid;
	} policy_handle;

	typedef [public, flag(NDR_PAHEX)] struct {
		uint8 hash[16];
	} samr_Password;

	typedef [public, flag(NDR_PAHEX)] struct {
		uint8 data[8];
	} netr_Credential;

	typedef [public] struct {
		netr_Credential cred;
		time_t timestamp;
	} netr_Authenticator;

}
