/*
  plug and play services
*/

[
  uuid("8d9f4e40-a03d-11ce-8f69-08003e30051b"),
  version(1.0),
  helpstring("Plug and Play services")
]
interface ntsvcs
{
	[todo] void PNP_Disconnect();
	[todo] void PNP_Connect();
	[todo] void PNP_GetVersion();
	[todo] void PNP_GetGlobalState();
	[todo] void PNP_InitDetection();
	[todo] void PNP_ReportLogOn();
	[todo] void PNP_ValidateDeviceInstance();
	[todo] void PNP_GetRootDeviceInstance();
	[todo] void PNP_GetRelatedDeviceInstance();
	[todo] void PNP_EnumerateSubKeys();
	[todo] void PNP_GetDeviceList();
	[todo] void PNP_GetDeviceListSize();
	[todo] void PNP_GetDepth();
	[todo] void PNP_GetDeviceRegProp();
	[todo] void PNP_SetDeviceRegProp();
	[todo] void PNP_GetClassInstance();
	[todo] void PNP_CreateKey();
	[todo] void PNP_DeleteRegistryKey();
	[todo] void PNP_GetClassCount();
	[todo] void PNP_GetClassName();
	[todo] void PNP_DeleteClassKey();
	[todo] void PNP_GetInterfaceDeviceAlias();
	[todo] void PNP_GetInterfaceDeviceList();
	[todo] void PNP_GetInterfaceDeviceListSize();
	[todo] void PNP_RegisterDeviceClassAssociation();
	[todo] void PNP_UnregisterDeviceClassAssociation();
	[todo] void PNP_GetClassRegProp();
	[todo] void PNP_SetClassRegProp();
	[todo] void PNP_CreateDevInst();
	[todo] void PNP_DeviceInstanceAction();
	[todo] void PNP_GetDeviceStatus();
	[todo] void PNP_SetDeviceProblem();
	[todo] void PNP_DisableDevInst();
	[todo] void PNP_UninstallDevInst();
	[todo] void PNP_AddID();
	[todo] void PNP_RegisterDriver();
	[todo] void PNP_QueryRemove();
	[todo] void PNP_RequestDeviceEject();
	[todo] void PNP_IsDockStationPresent();
	[todo] void PNP_RequestEjectPC();
	[todo] void PNP_HwProfFlags();
	[todo] void PNP_GetHwProfInfo();
	[todo] void PNP_AddEmptyLogConf();
	[todo] void PNP_FreeLogConf();
	[todo] void PNP_GetFirstLogConf();
	[todo] void PNP_GetNextLogConf();
	[todo] void PNP_GetLogConfPriority();
	[todo] void PNP_AddResDes();
	[todo] void PNP_FreeResDes();
	[todo] void PNP_GetNextResDes();
	[todo] void PNP_GetResDesData();
	[todo] void PNP_GetResDesDataSize();
	[todo] void PNP_ModifyResDes();
	[todo] void PNP_DetectResourceLimit();
	[todo] void PNP_QueryResConfList();
	[todo] void PNP_SetHwProf();
	[todo] void PNP_QueryArbitratorFreeData();
	[todo] void PNP_QueryArbitratorFreeSize();
	[todo] void PNP_RunDetection();
	[todo] void PNP_RegisterNotification();
	[todo] void PNP_UnregisterNotification();
	[todo] void PNP_GetCustomDevProp();
	[todo] void PNP_GetVersionInternal();
	[todo] void PNP_GetBlockedDriverInfo();
	[todo] void PNP_GetServerSideDeviceInstallFlags();
}
