/*
  wkssvc interface definitions
*/

[ uuid(6bffd098-a112-3610-9833-46c3f87e345a),
  version(1.0),
  pointer_default(unique)
] interface wkssvc
{
	/******************/
	/* Function: 0x00 */
	typedef struct {
		uint32 platform_id;
		unistr *server;
		unistr *domain;
		uint32 ver_major;
		uint32 ver_minor;
	} wks_Info100;

	typedef struct {
		uint32 platform_id;
		unistr *server;
		unistr *domain;
		uint32 ver_major;
		uint32 ver_minor;
		unistr *unknown;
	} wks_Info101;

	typedef struct {
		uint32 platform_id;
		unistr *server;
		unistr *domain;
		uint32 ver_major;
		uint32 ver_minor;
		unistr *unknown;
		uint32 unknown2;
	} wks_Info102;

	typedef union {
		case (100) wks_Info100 *info100;
		case (101) wks_Info101 *info101;
		case (102) wks_Info102 *info102;
	} wks_Info;

	NTSTATUS wks_QueryInfo(
		[in]   unistr *server_name,
		[in]   uint32 level,
		[out,switch_is(level)]  wks_Info info
		);

}
