/*
  windows zero-configuration service
*/

[
  uuid(378e52b0-c0a9-11cf-822d-00aa0051e40f),
  version(1.0)
]
interface wzcsvc
{

	/*****************/
	/* Function 0x00 */
	WERROR wzcsvc_Unknown0();

	/*****************/
	/* Function 0x01 */
	WERROR wzcsvc_Unknown1();

	/*****************/
	/* Function 0x02 */
	WERROR wzcsvc_Unknown2();

	/*****************/
	/* Function 0x03 */
	WERROR wzcsvc_Unknown3();

}
