.TH DEBUG2HTML 1 "09 Apr 2000" "debug2html TNG-prealpha"
.PP 
.SH "NAME" 
debug2html \- Samba DEBUG to HTML translation filter
.PP 
.SH "SYNOPSIS" 
.PP 
debug2html [input-file [output-file]]
.PP 
.SH "DESCRIPTION" 
.PP 
This program is part of the \fBSamba\fP suite\&.
.PP 
\fBdebug2html\fP generates HTML files from Samba log files\&.  Log files
produced by \fBnmbd\fP(8) or \fBsmbd\fP(8) may then be viewed by a web
browser\&.  The output conforms to the HTML 3\&.2 specification\&. 
.PP 
The filenames specified on the command line are optional\&.  If the
output-file is ommitted, output will go to \fBstdout\fP\&.  If the input-file
is ommitted, \fBdebug2html\fP will read from \fBstdin\fP\&.  The filename "-" 
can be used to indicate that input should be read from \fBstdin\fP\&.  For
example:
.PP 
\f(CWcat /usr/local/samba/var/log\&.nmb | debug2html - nmblog\&.html\fP 
.br 
.PP 
.SH "VERSION" 
.PP 
This man page is correct for version 2\&.0 of the Samba suite\&.
.PP 
.SH "SEE ALSO" 
.PP 
\fBnmbd\fP(8), \fBsmbd\fP(8),
\fBsamba\fP(7)\&.
.PP 
.SH "AUTHOR" 
.PP 
The original Samba software and related utilities were created by
Andrew Tridgell \fIsamba-bugs@samba\&.org\fP\&. Samba is now developed
by the Samba Team as an Open Source project similar to the way the
Linux kernel is developed\&.
.PP 
The original Samba man pages were written by Karl Auer\&. The man page
sources were converted to YODL format (another excellent piece of Open
Source software, available at
\fBftp://ftp\&.icce\&.rug\&.nl/pub/unix/\fP)
and updated for the Samba2\&.0 release by Jeremy Allison\&.
\fIsamba-bugs@samba\&.org\fP\&.
.PP 
\fBdebug2html\fP was added by Chris Hertel\&.
.PP 
See \fBsamba\fP(7) to find out how to get a full
list of contributors and details on how to submit bug reports,
comments etc\&.
