.TH "smbcacls " "1" "3 Dec 2000" "Samba" "SAMBA" 
.PP 
.SH "NAME" 
smbcacls \- Set or get ACLs on an NT file or directory 
.PP 
.SH "SYNOPSIS" 
.PP 
\fBsmbcacls\fP //server/share filename -U username
[-A acls] [-M acls] 
[-D acls] [-S acls] 
[-n] [-h]
.PP 
.SH "DESCRIPTION" 
.PP 
The \fBsmbcacls\fP program manipulates NT Access Control Lists (ACLs) on
SMB file shares\&.
.PP 
.SH "OPTIONS" 
.PP 
The following options are available to the \fBsmbcacls\fP program\&.  The
format of ACLs is described in the section ACL FORMAT
.PP 
.IP 
.IP "\fB-A acls\fP" 
.IP 
Add the ACLs specified to the ACL list\&.  Existing access control entries
are unchanged\&.
.IP 
.IP "\fB-M acls\fP" 
.IP 
Modify the mask value (permissions) for the ACLs specified on the command
line\&.  An error will be printed for each ACL specified that was not already
present in the ACL list\&.
.IP 
.IP "\fB-D acls\fP" 
.IP 
Delete any ACLs specfied on the command line\&.  An error will be printed for
each ACL specified that was not already present in the ACL list\&.
.IP 
.IP "\fB-S acls\fP" 
.IP 
This command sets the ACLs on the file with only the ones specified on the
command line\&.  All other ACLs are erased\&.  Note that the ACL specified must
contain at least a revision, type, owner and group for the call to succeed\&.
.IP 
.IP "\fB-U username\fP" 
.IP 
Specifies a username used to connect to the specified service\&.  The
username may be of the form \f(CWusername\fP in which case the user is
prompted to enter in a password and the workgroup specified in the
\fBsmb\&.conf\fP file is used, or \f(CWusername%password\fP
or \f(CWDOMAIN\eusername%password\fP and the password and workgroup names are
used as provided\&.
.IP 
.IP "\fB-n\fP" 
.IP 
This option displays all ACL information in numeric format\&.  The default is
to convert SIDs to names and ACE types and masks to a readable string
format\&. 
.IP 
.IP "\fB-h\fP" 
.IP 
Print usage information on the \fBsmbcacls\fP program
.IP 
.PP 
.SH "ACL FORMAT" 
.PP 
The format of an ACL is one or more ACL entries separated by either spaces,
commas or newlines\&.  An ACL entry is one of the following:
.PP 

.nf 
 

REVISION:<revision number>
OWNER:<sid or name>
GROUP:<sid or name>
ACL:<sid or name>:<type>/<flags>/<mask>
.fi 
 

.PP 
The revision of the ACL specifies the internal Windows NT ACL revision for
the security descriptor\&.  If not specified it defaults to 1\&.
.PP 
The owner and group specify the owner and group sids for the object\&.  If a
SID in the format \f(CWS-1-x-y-z\fP is specified this is used, otherwise
the name specified is resolved using the server on which the file or
directory resides\&. 
.PP 
ACLs specify permissions granted to the SID\&.  This SID again can be
specified in \f(CWS-1-x-y-z\fP format or as a name in which case it is resolved
against the server on which the file or directory resides\&.  The type, flags
and mask values determine the type of access granted to the SID\&.
.PP 
The type can be either 0 or 1 corresponding to ALLOWED or DENIED access to
the SID\&.  The flags values are generally zero for file ACLs and either 9 or
2 for directory ACLs\&.  Some common flags are:
.PP 

.nf 
 

#define SEC_ACE_FLAG_OBJECT_INHERIT     	0x1
#define SEC_ACE_FLAG_CONTAINER_INHERIT  	0x2
#define SEC_ACE_FLAG_NO_PROPAGATE_INHERIT       0x4
#define SEC_ACE_FLAG_INHERIT_ONLY       	0x8
.fi 
 

.PP 
The mask is a value which expresses the access right granted to
the SID\&.  It can be given as a hexadecimal value or by using one of the
following text strings which map to the NT file permissions of the same
name\&. 
.PP 
.IP 
.IP "" 
\f(CWR\fP 	Allow read access
.IP 
.IP "" 
\f(CWW\fP 	Allow write access
.IP 
.IP "" 
\f(CWX\fP 	Execute permission on the object
.IP 
.IP "" 
\f(CWD\fP 	Delete the object
.IP 
.IP "" 
\f(CWP\fP 	Change permissions
.IP 
.IP "" 
\f(CWO\fP	Take ownership
.IP 
.PP 
The following combined permissions can be specified:
.PP 
.IP 
.IP "" 
\f(CWREAD\fP	 Equivalent to \f(CWRX\fP permissions
.IP "" 
\f(CWCHANGE\fP Equivalent to \f(CWRXWD\fP permissions
.IP "" 
\f(CWFULL\fP   Equivalent to \f(CWRWXDPO\fP permissions
.IP 
.PP 
.SH "EXIT STATUS" 
.PP 
.SH "AUTHOR" 
.PP 
The original Samba software and related utilities were created by
Andrew Tridgell\&. Samba is now developed by the Samba Team as an Open
Source project\&.
.PP 
\fBsmbcacls\fP was written by Andrew Tridgell and Tim Potter\&.
