.TH SMBMOUNT 8 01/05/1998 smbmount smbmount
.SH NAME
smbmount \- mount smb file system
.SH SYNOPSIS
.B smbmount
[
.B options
]

.SH DESCRIPTION
.B smbmount 
is a stripped down smbclient program. It only contains the mount
command that itself calls the
.B smbmnt(8)
program to do the actual mount.
.B smbmount
itself accepts nearly the same options as
.B smbclient(1)
does. See the smbclient manpage for details.

To mount an smb file system I suggest to use the option
.B -c
for smbclient. For example, use

smbmount "\\\\server\\tmp" -c 'mount /mnt -u 123 -g 456'

to mount the tmp share of server on /mnt, giving it a local uid 123
and a local gid 456.

.SH SEE ALSO
.B smbmnt(8), smbclient(1)

