#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('SMB_PROTOCOL',
	source='receive.c negprot.c nttrans.c reply.c request.c search.c service.c sesssetup.c srvtime.c trans2.c signing.c',
	autoproto='smb_proto.h',
	deps='dfs_server_ad',
	public_deps='ntvfs LIBPACKET samba-credentials samba_server_gensec',
	enabled=bld.AD_DC_BUILD_IS_ENABLED()
	)

