#!/usr/bin/env python

bld.SAMBA_MODULE('net_drs',
	source='drs/net_drs.c drs/net_drs_bind.c drs/net_drs_kcc.c drs/net_drs_replicate.c drs/net_drs_showrepl.c',
	autoproto='drs/net_drs_proto.h',
	subsystem='net',
	deps='LIBCLI_DRSUAPI ldb LDBSAMBA',
	internal_module=True
	)


bld.SAMBA_BINARY('net',
	source='net.c net_password.c net_join.c net_vampire.c net_gpo.c',
	autoproto='net_proto.h',
	deps='LIBSAMBA-HOSTCONFIG LIBSAMBA-UTIL LIBSAMBA-NET popt POPT_SAMBA POPT_CREDENTIALS net_drs policy auth',
        needs_python=True
	)

