# very crude Makefile to run waf
WAF=WAFCACHE=$(HOME)/.wafcache ../buildtools/waf

all:
	$(WAF) build

install:
	$(WAF) install

uninstall:
	$(WAF) uninstall

test:
	$(WAF) test

quicktest:
	$(WAF) test --quick

clean:
	$(WAF) clean

distclean:
	rm -rf bin

# some compatibility make targets
everything: all

testsuite: all

check: test

torture: all

# this should do an install as well, once install is finished
installcheck: test

