#!/usr/bin/env python

bld.SAMBA_PYTHON('LIBPYTHON',
                 source='modules.c',
                 public_deps='EXT_LIB_PYTHON',
                 init_function_sentinal='{NULL,NULL}',
                 deps='PYTALLOC',
	)


bld.SAMBA_PYTHON('PYTALLOC',
                 source='../../../lib/talloc/pytalloc.c',
                 public_deps='EXT_LIB_PYTHON talloc'
                 )


bld.SAMBA_PYTHON('python_uuid',
                 source='uuidmodule.c',
                 deps='LIBNDR',
                 realname='uuid.so'
                 )


bld.SAMBA_PYTHON('python_glue',
                 source='pyglue.c',
                 deps='LIBNDR ldb SAMDB CREDENTIALS pyldb python_dcerpc_misc python_dcerpc_security pyauth pyldb_util pyparam_util',
                 realname='samba/_glue.so'
	)


# create a dummy subsystem for EXT_LIB_PYTHON
bld.SAMBA_SUBSYSTEM('EXT_LIB_PYTHON', '')


# install out various python scripts for use by make test
bld.SAMBA_SCRIPT('samba_python',
                 pattern='samba/**/*.py',
                 installdir='python')

bld.INSTALL_WILDCARD('${PYTHONDIR}', 'samba/**/*.py', flat=False)
