#!/usr/bin/env python

bld.SAMBA_LIBRARY('samba_python',
	source=[],
	deps='LIBPYTHON PYTALLOC pyrpc_util',
	grouping_library=True,
	private_library=True,
	pyext=True)

bld.SAMBA_SUBSYSTEM('LIBPYTHON',
	source='modules.c',
	public_deps='EXT_LIB_PYTHON',
	init_function_sentinal='{NULL,NULL}',
	deps='talloc',
	pyext=True,
	)


bld.SAMBA_SUBSYSTEM('PYTALLOC',
	source='../../../lib/talloc/pytalloc.c',
	public_deps='EXT_LIB_PYTHON talloc',
	pyext=True,
	)


bld.SAMBA_PYTHON('python_uuid',
	source='uuidmodule.c',
	deps='ndr',
	realname='uuid.so',
	enabled = float(bld.env.PYTHON_VERSION) <= 2.4
	)


bld.SAMBA_PYTHON('python_glue',
	source='pyglue.c',
	deps='pyparam_util samba-util netif PYTALLOC',
	realname='samba/_glue.so'
	)


# create a dummy subsystem for EXT_LIB_PYTHON
bld.SAMBA_SUBSYSTEM('EXT_LIB_PYTHON', '')


# install out various python scripts for use by make test
bld.SAMBA_SCRIPT('samba_python',
                 pattern='samba/**/*.py',
                 installdir='python')

bld.INSTALL_WILDCARD('${PYTHONDIR}', 'samba/**/*.py', flat=False)
