#include "idl_types.h"

/*
  protected_storage interface definitions
*/

[ uuid(e3514235-4b06-11d1-ab04-00c04fc2dcd2),
  version(4.0),
  pointer_default(unique)
] interface protected_storage
{
	/*****************************/
	/* Function        0x00      */
	WERROR ps_XXX ();
}
