Import('hostenv')
tdbenv = hostenv.Copy()
tdbenv.Append(CPPPATH=['include'])
tdb = tdbenv.StaticLibrary('tdb',
	['common/tdb.c','common/dump.c','common/io.c','common/lock.c',
	 'common/open.c','common/traverse.c','common/freelist.c',
	 'common/error.c','common/tdbutil.c'])

tdbtool = tdbenv.Program('tdbtool', ['tools/tdbtool.c',tdb])
tdbtorture = tdbenv.Program('tdbtorture', ['tools/tdbtorture.c',tdb])
tdbdump = tdbenv.Program('tdbdump', ['tools/tdbdump.c',tdb])
tdbbackup = tdbenv.Program('tdbbackup', ['tools/tdbbackup.c',tdb])
Default(tdbtool,tdbtorture,tdbdump,tdbbackup)
