#!/usr/bin/env python

bld.SAMBA_LIBRARY('netif',
                  source='interface.c',
                  deps='samba-util interfaces samba-hostconfig',
                  private_library=True,
                  autoproto='netif_proto.h'
                  )

bld.SAMBA_MODULE('socket_ip',
    source='socket_ip.c',
    subsystem='samba_socket',
    deps='samba-errors',
    internal_module=True
    )

bld.SAMBA_MODULE('socket_unix',
    source='socket_unix.c',
    subsystem='samba_socket',
    deps='talloc',
    internal_module=True
    )

bld.SAMBA_SUBSYSTEM('samba_socket',
    source='socket.c access.c connect_multi.c connect.c',
    public_deps='talloc LIBTSOCKET',
    deps='cli_composite LIBCLI_RESOLVE socket_ip socket_unix access'
    )

