#!/usr/bin/env python

bld.SAMBA_LIBRARY('auth_sam_reply',
                  source='auth_sam_reply.c wbc_auth_util.c',
                  deps='talloc samba-security samba-util',
                  private_library=True
                  )

bld.RECURSE('gensec')
bld.RECURSE('ntlmssp')
bld.RECURSE('credentials')
