#!/usr/bin/env python


bld.SAMBA_SUBSYSTEM('LIBSECURITY_COMMON',
	source='dom_sid.c display_sec.c secace.c secacl.c security_descriptor.c sddl.c privileges.c security_token.c',
	deps='talloc LIBNDR'
	)

