#!/usr/bin/env python


bld.SAMBA_LIBRARY('samba-security',
                  source=['dom_sid.c',
                          'display_sec.c', 'secace.c', 'secacl.c',
                          'security_descriptor.c', 'sddl.c', 'privileges.c',
                          'security_token.c', 'access_check.c',
                          'object_tree.c', 'create_descriptor.c',
                          'util_sid.c', 'session.c', 'secdesc.c',
                          'conditional_ace.c', 'sddl_conditional_ace.c',
                          'claims-conversions.c',
                          'claims_transformation.l',
                          'claims_transformation.y',
                  ],
                  private_library=True,
                  deps='stable_sort talloc ndr NDR_SECURITY NDR_CONDITIONAL_ACE')

bld.SAMBA_LIBRARY('samba-security-trusts',
                  source='''
                      trust_forest_info.c
                  ''',
                  deps='''
                      talloc
                      samba-util
                      samba-security
                      ndr-samba
                  ''',
                  private_library=True)

pytalloc_util = bld.pyembed_libname('pytalloc-util')
pyrpc_util = bld.pyembed_libname('pyrpc_util')
bld.SAMBA_PYTHON('pysecurity',
                 source='pysecurity.c',
                 deps='samba-security %s %s' % (pytalloc_util, pyrpc_util),
                 realname='samba/security.so'
                 )

bld.SAMBA_BINARY(
    'test_sddl_conditional_ace',
    source='tests/test_sddl_conditional_ace.c',
    deps='''
        cmocka
        talloc
        samba-util
        asn1util
        NDR_SECURITY
        samba-security
    ''',
    for_selftest=True
)

bld.SAMBA_BINARY(
    'test_run_conditional_ace',
    source='tests/test_run_conditional_ace.c',
    deps='''
        cmocka
        talloc
        samba-util
        asn1util
        NDR_SECURITY
        samba-security
    ''',
    for_selftest=True
)

bld.SAMBA_BINARY(
    'test_claim_conversion',
    source='tests/test_claim_conversion.c',
    deps='''
        cmocka
        talloc
        samba-util
        asn1util
        NDR_SECURITY
        NDR_CLAIMS
        samba-security
    ''',
    for_selftest=True
)
