#!/usr/bin/env python

bld.SAMBA_MODULE('KDC',
	source='kdc.c kpasswdd.c',
	subsystem='service',
	init_function='server_service_kdc_init',
	deps='HEIMDAL_KDC HDB_SAMBA4 WDC_SAMBA4 LIBSAMBA-HOSTCONFIG LIBTSOCKET LIBSAMBA_TSOCKET',
        local_include=False
	)


bld.SAMBA_SUBSYSTEM('HDB_SAMBA4',
	source='hdb-samba4.c',
	deps='ldb auth_sam auth_sam_reply CREDENTIALS HEIMDAL_HDB DB_GLUE LIBSAMBA-HOSTCONFIG',
        includes='../heimdal/kdc',
        local_include=False
	)


bld.SAMBA_SUBSYSTEM('WDC_SAMBA4',
	source='wdc-samba4.c',
        local_include_first=False,
        includes='../heimdal/kdc',
	deps='ldb auth_sam auth_sam_reply CREDENTIALS HEIMDAL_HDB PAC_GLUE LIBSAMBA-HOSTCONFIG'
	)


bld.SAMBA_SUBSYSTEM('PAC_GLUE',
	source='pac-glue.c',
        local_include_first=False,
        includes='../heimdal/kdc',
	deps='ldb auth_sam auth_sam_reply CREDENTIALS HEIMDAL_HDB LIBSAMBA-HOSTCONFIG'
	)


bld.SAMBA_SUBSYSTEM('DB_GLUE',
	source='db-glue.c',
        local_include=False,
	deps='ldb auth_sam auth_sam_reply CREDENTIALS HEIMDAL_HDB LIBSAMBA-HOSTCONFIG'
	)


bld.SAMBA_SUBSYSTEM('MIT_SAMBA',
	source='mit_samba.c',
        local_include=False,
	deps='ldb auth_sam auth_sam_reply CREDENTIALS HEIMDAL_HDB DB_GLUE PAC_GLUE LIBSAMBA-HOSTCONFIG'
	)


bld.SAMBA_LIBRARY('mit_samba',
                  source='',
                  deps='MIT_SAMBA',
                  external_library=True,
                  realname='mit_samba.so'
                  )

