#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('LIBWINBIND-CLIENT',
                    source='wb_common.c',
                    deps='replace',
                    cflags='-DSOCKET_WRAPPER_DISABLE=1'
                    )


bld.SAMBA_BINARY('nsstest',
	source='nsstest.c',
	deps='LIBSAMBA-UTIL LIBSAMBA-HOSTCONFIG NSS_WRAPPER'
	)


bld.SAMBA_BINARY('wbinfo',
	source='wbinfo.c',
	deps='LIBSAMBA-UTIL LIBCLI_AUTH popt POPT_SAMBA LIBWINBIND-CLIENT LIBWBCLIENT tevent UTIL_TEVENT LIBASYNC_REQ UID_WRAPPER'
	)

