#!/usr/bin/env python

bld.SAMBA_LIBRARY('winbind-client',
	source='wb_common.c',
	deps='replace',
	cflags='-DSOCKET_WRAPPER_DISABLE=1 -DWINBINDD_SOCKET_DIR=\"%s\"' % bld.env.WINBINDD_SOCKET_DIR,
	private_library=True
	)


bld.SAMBA_BINARY('nsstest',
	source='nsstest.c',
	deps='libsamba-util libsamba-hostconfig'
	)


bld.SAMBA_BINARY('wbinfo',
	source='wbinfo.c',
	deps='libsamba-util LIBCLI_AUTH popt POPT_SAMBA winbind-client wbclient tevent UTIL_TEVENT LIBASYNC_REQ libsecurity LIBNDR NDR_SECURITY'
	)

bld.SAMBA_LIBRARY('nss_winbind',
	source='../nsswitch/winbind_nss_linux.c',
	deps='winbind-client',
	realname='libnss_winbind.so.2',
	vnum='2')

if bld.CONFIG_SET('HAVE_PAM_START'):
	bld.SAMBA_LIBRARY('pamwinbind',
		source='../nsswitch/pam_winbind.c',
		deps='talloc wbclient winbind-client LIBINIPARSER pam',
		cflags='-DLOCALEDIR=\"%s/locale\"' % bld.env.DATADIR,
		realname='pam_winbind.so',
		)
