#!/usr/bin/env python

bld.SAMBA_MODULE('TORTURE_LIBNETAPI',
	source='libnetapi.c libnetapi_user.c libnetapi_group.c libnetapi_server.c',
	autoproto='proto.h',
	subsystem='smbtorture',
	init_function='torture_libnetapi_init',
	deps='netapi CMDLINE_S4',
	internal_module=True,
	)

