#!/bin/env python
names = [ ("init", range(1, 4)),
          ("fstat", range(1, 6)),
          ("open", range(1, 5)), 
          ("unlink", range(1, 12)),
          ("chown", range(1)), 
          ("close", range(1,2)),
          ("opendir", range(1, 4)),
          ("closedir", range(1, 4)),
          ("rename", range(1, 14)),
          ("lseek", range(1, 8)),
          ("lseekdir", range(1, 6)),
          ("stat", range(1, 6)),
          ("getdents", range(1, 5)),
          ("creat", range(1, 3)),
          ("mkdir", range(1, 4)),
          ("readdir", range(1, 5)),
          ("rmdir", range(1, 6)),
          ("write", range(1, 13)),
          ("read", range(1, 13)),
          ("chmod", range(1)),
          ("telldir", range(1, 5)),
          ("print_file", range(1, 4)),
          ("open_print_job", range(1, 2)),
          ("list_print_jobs", range(1, 7)),
          ("unlink_print_job", range(1, 5)) ]

for pattern in names:
    (name, suffixes) = pattern
    for suffix in map(lambda x: x + 1, suffixes):
        bld.SAMBA_BINARY('%s_%s' % (name, suffix),
                 source='%s/%s_%s.c' % (name, name, suffix),
                 deps='smbclient',
                 install=False)

bld.SAMBA_BINARY('stat_k', 
                 source='stat/stat_k.c',
                 deps='smbclient',
                 install=False)
