Import('hostenv')
#            tastes like -*- python -*-

Import('dynconfig')
param = StaticLibrary('loadparm',['loadparm.c','params.c',dynconfig])
Export('param')
generic = StaticLibrary('generic',['generic.c'])
Export('generic')
