#            tastes like -*- python -*-

Import('hostenv')
Import('dynconfig')
param = hostenv.StaticLibrary('loadparm',['loadparm.c','params.c',dynconfig])
Export('param')
generic = hostenv.StaticLibrary('generic',['generic.c'])
Export('generic')
