#!/usr/bin/env python

bld.SAMBA_LIBRARY('LIBSAMBA-HOSTCONFIG',
	source='loadparm.c generic.c util.c',
	pc_files='samba-hostconfig.pc',
	vnum='0.0.1',
	deps='DYNCONFIG CHARSET',
	public_deps='LIBSAMBA-UTIL',
	public_headers='param.h',
	autoproto='param_proto.h',
	)


bld.SAMBA_SUBSYSTEM('PROVISION',
	source='provision.c pyparam.c',
	deps='LIBPYTHON pyparam_util ldb PYTALLOC',
	pyext=True,
	)


bld.SAMBA_SUBSYSTEM('share',
	source='share.c',
	public_headers='share.h',
	deps='LIBSAMBA-UTIL'
	)


bld.SAMBA_MODULE('share_classic',
	source='share_classic.c',
	subsystem='share',
	init_function='share_classic_init',
	deps='LIBSAMBA-UTIL'
	)


bld.SAMBA_MODULE('share_ldb',
	source='share_ldb.c',
	subsystem='share',
	init_function='share_ldb_init',
	deps='LDBSAMBA'
	)


bld.SAMBA_SUBSYSTEM('SECRETS',
	source='secrets.c',
	deps='ldb TDB_WRAP UTIL_TDB NDR_SECURITY tevent LDBSAMBA'
	)


bld.SAMBA_PYTHON('param',
	source='pyparam.c',
	deps='LIBSAMBA-HOSTCONFIG PYTALLOC',
	realname='samba/param.so'
	)


bld.SAMBA_SUBSYSTEM('pyparam_util',
	source='pyparam_util.c',
	deps='LIBPYTHON LIBSAMBA-HOSTCONFIG',
	pyext=True,
	)

bld.SAMBA_LIBRARY('libshares',
                  source=[],
                  deps='share share_classic share_ldb',
                  grouping_library=True,
                  private_library=True)
