#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('PROVISION',
	source='provision.c pyparam.c',
	deps='LIBPYTHON pyparam_util ldb pytalloc-util pyldb-util',
	pyext=True,
	)


bld.SAMBA_SUBSYSTEM('share',
	source='share.c',
	public_headers='share.h',
	deps='samba-util samba-modules'
	)


bld.SAMBA_MODULE('share_classic',
	source='share_classic.c',
	subsystem='share',
	init_function='share_classic_init',
	deps='samba-util'
	)


bld.SAMBA_MODULE('share_ldb',
	source='share_ldb.c',
	subsystem='share',
	init_function='share_ldb_init',
	deps='ldbsamba auth_system_session'
	)


bld.SAMBA_SUBSYSTEM('SECRETS',
	source='secrets.c',
	deps='ldb tdb-wrap util_tdb NDR_SECURITY tevent ldbwrap'
	)


bld.SAMBA_PYTHON('pyparam',
	source='pyparam.c',
	deps='samba-hostconfig pytalloc-util',
	realname='samba/param.so'
	)

bld.SAMBA_SUBSYSTEM('param_options',
	source='loadparm.c',
	deps='samba-hostconfig')


bld.SAMBA_SUBSYSTEM('pyparam_util',
	source='pyparam_util.c',
	deps='LIBPYTHON samba-hostconfig',
	pyext=True,
	)

bld.SAMBA_LIBRARY('shares',
                  source=[],
                  deps='share',
                  grouping_library=True,
                  private_library=True)
