Import('hostenv')
hostenv.StaticLibrary('tls', ['tls.c', 'tlscert.c'])

if hostenv['configure']:
    conf = hostenv.Configure()
    conf.CheckLibWithHeader('gnutls', 'gnutls/gnutls.h', 'c', 'gnutls_global_init()')
    conf.Finish()
