#!/usr/bin/env python

bld.SAMBA3_LIBRARY('gpext',
                   source='''gpext/gpext.c gpo_util.c gpo_ldap.c gpo_ini.c
                           gpo_fetch.c gpo_filesync.c
                           gpo_sec.c gpo_reg.c''',
                   deps='talloc ads TOKEN_UTIL auth',
                   private_library=True)

for env in bld.gen_python_environments():
    bld.SAMBA3_PYTHON('python_samba_libgpo', 'pygpo.c',
                     deps='''pyparam_util gpext talloc ads TOKEN_UTIL
                     auth pyrpc_util''',
                     realname='samba/gpo.so')
