#!/usr/bin/env python

LIBGPO_SRC = '''gpo_ldap.c gpo_ini.c gpo_util.c gpo_fetch.c gpo_filesync.c
                gpo_sec.c gpo_reg.c gpext/gpext.c'''

bld.SAMBA3_LIBRARY('gpo',
                   source='${LIBGPO_SRC}',
                   deps='talloc ads TOKEN_UTIL auth',
                   vars=locals(),
                   private_library=True)

bld.SAMBA3_LIBRARY('gpext',
                   source='''gpext/gpext.c''',
                   deps='talloc ads TOKEN_UTIL auth gpo',
                   private_library=True)

pyparam_util = bld.pyembed_libname('pyparam_util')
pyrpc_util = bld.pyembed_libname('pyrpc_util')
bld.SAMBA3_PYTHON('python_samba_libgpo', 'pygpo.c',
                  deps='%s gpext talloc ads TOKEN_UTIL auth %s' % (pyparam_util, pyrpc_util),
                  realname='samba/gpo.so')

if bld.AD_DC_BUILD_IS_ENABLED():
    bld.RECURSE('admx')
