.\" Copyright (c) 2003 Kungliga Tekniska Högskolan
.\" (Royal Institute of Technology, Stockholm, Sweden).
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" 3. Neither the name of the Institute nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE INSTITUTE AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE INSTITUTE OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $Id$
.\"
.Dd August 17, 2003
.Dt KRB5_GET_INIT_CREDS 3
.Os HEIMDAL
.Sh NAME
.Nm krb5_get_init_creds_opt ,
.Nm krb5_get_init_creds_opt_init ,
.Nm krb5_get_init_creds_opt_set_default_flags ,
.Nm krb5_get_init_creds_opt_set_tkt_life ,
.Nm krb5_get_init_creds_opt_set_rewew_life ,
.Nm krb5_get_init_creds_opt_set_forwardable ,
.Nm krb5_get_init_creds_opt_set_proxiable ,
.Nm krb5_get_init_creds_opt_set_etype_list ,
.Nm krb5_get_init_creds_opt_set_address_list ,
.Nm krb5_get_init_creds_opt_set_preauth_list ,
.Nm krb5_get_init_creds_opt_set_salt ,
.Nm krb5_get_init_creds_opt_set_anonymous ,
.Nm krb5_get_init_creds ,
.Nm krb5_get_init_creds_keytab
.Sh LIBRARY
Kerberos 5 Library (libkrb5, -lkrb5)
.Sh SYNOPSIS
.In krb5.h
.Pp
.Ft krb5_get_init_creds_opt;
.Pp
.Ft void
.Fo krb5_get_init_creds_opt_init
.Fa "krb5_get_init_creds_opt *opt"
.Fc
.Ft void
.Fo krb5_get_init_creds_opt_set_default_flags
.Fa "krb5_context context"
.Fa "const char *appname"
.Fa "krb5_const_realm realm"
.Fa "krb5_get_init_creds_opt *opt"
.Fc
.Ft void
.Fo krb5_get_init_creds_opt_set_tkt_life
.Fa "krb5_get_init_creds_opt *opt"
.Fa "krb5_deltat tkt_life"
.Fc
.Ft void
.Fo krb5_get_init_creds_opt_set_rewew_life
.Fa "krb5_get_init_creds_opt *opt"
.Fa "krb5_deltat renew_life"
.Fc
.Ft void
.Fo krb5_get_init_creds_opt_set_forwardable
.Fa "krb5_get_init_creds_opt *opt"
.Fa "int forwardable"
.Fc
.Ft void
.Fo krb5_get_init_creds_opt_set_proxiable
.Fa "krb5_get_init_creds_opt *opt"
.Fa "int proxiable"
.Fc
.Ft void
.Fo krb5_get_init_creds_opt_set_etype_list
.Fa "krb5_get_init_creds_opt *opt"
.Fa "krb5_enctype *etype_list"
.Fa int etype_list_length"
.Fc
.Ft void
.Fo krb5_get_init_creds_opt_set_address_list
.Fa "krb5_get_init_creds_opt *opt"
.Fa "krb5_addresses *addresses"
.Fc
.Ft void
.Fo krb5_get_init_creds_opt_set_preauth_list
.Fa "krb5_get_init_creds_opt *opt"
.Fa "krb5_preauthtype *preauth_list"
.Fa "int preauth_list_length"
.Fc
.Ft void
.Fo krb5_get_init_creds_opt_set_salt
.Fa "krb5_get_init_creds_opt *opt"
.Fa "krb5_data *salt"
.Fc
.Ft void
.Fo krb5_get_init_creds_opt_set_anonymous
.Fa "krb5_get_init_creds_opt *opt"
.Fa "int anonymous"
.Fc
.Ft krb5_error_code
.Fo krb5_get_init_creds
.Fa "krb5_context context"
.Fa "krb5_creds *creds"
.Fa "krb5_principal client"
.Fa "char *password"
.Fa "const char *password"
.Fa "krb5_prompter_fct prompter"
.Fa "void *data"
.Fa "krb5_deltat start_time"
.Fa "const char *in_tkt_service"
.Fa "krb5_get_init_creds_opt *options"
.Fc
.Ft krb5_error_code
.Fo krb5_get_init_creds_keytab
.Fa "krb5_context context"
.Fa "krb5_creds *creds"
.Fa "krb5_principal client"
.Fa "krb5_keytab keytab"
.Fa "krb5_deltat start_time"
.Fa "const char *in_tkt_service"
.Fa "krb5_get_init_creds_opt *options"
.Fc
.Sh DESCRIPTION
Getting initial credential ticket for a principal.
This interface that replaces the deprecated
.Fa krb5_in_tkt
and 
.Fa krb5_in_cred
functions.
.Pp
If you only to verify a user and password, consider using
.Xr krb5_verify_user 3
instead, since it also verifies that initial credentials with using a
keytab to make sure the response was from the KDC.
.Sh SEE ALSO
.Xr krb5 3 ,
.Xr krb5_verify_user 3 ,
.Xr krb5.conf 5 ,
.Xr kerberos 8
