Import('hostenv')

hostenv.Library('ntvfs_cifs',['cifs/vfs_cifs.c'])
hostenv.Library('ntvfs_simple',['simple/vfs_simple.c','simple/svfs_util.c'])
hostenv.Library('ntvfs_print',['print/vfs_print.c'])
hostenv.Library('ntvfs_ipc',['ipc/vfs_ipc.c','ipc/ipc_rap.c','ipc/rap_server.c'])
hostenv.Library('ntvfs_nbench',['nbench/vfs_nbench.c'])
hostenv.Library('ntvfs_common',['common/brlock.c','common/opendb.c','common/sidmap.c'])
hostenv.Library('ntvfs',['ntvfs_base.c','ntvfs_generic.c','ntvfs_interface.c','ntvfs_util.c'])

SConscript(dirs=['unixuid','posix'],exports='hostenv')
