#!/bin/sh
#
# $Id: swat.postinst,v 1.3 2003/06/01 07:12:51 peloy Exp $
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin

case "$1" in
	configure)
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0
		;;
	*)
		echo "$0: Unknown action \"$1\""
		exit 0
		;;
esac

# Set up swat, turned off by default.
update-inetd --group OTHER --add \
 '#<off># swat\t\tstream\ttcp\tnowait.400\troot\t/usr/sbin/tcpd\t/usr/sbin/swat'

#DEBHELPER#
