#include "idl_types.h"

import "misc.idl";
import "smb2_lease_struct.idl";
import "file_id.idl";

[
	pointer_default(unique)
]
interface leases_db
{
	typedef [public] struct {
		GUID client_guid;
		smb2_lease_key lease_key;
	} leases_db_key;

	typedef [public] struct {
		file_id id;
		[string,charset(UTF8)] char *servicepath;
		[string,charset(UTF8)] char *base_name;
		[string,charset(UTF8)] char *stream_name;
	} leases_db_file;

	typedef [public] struct {
		uint32 num_files;
		[size_is(num_files)] leases_db_file files[];
	} leases_db_value;
}
