#!/usr/bin/env python

bld.INSTALL_WILDCARD('${SETUPDIR}', 'ad-schema/*.txt')
bld.INSTALL_WILDCARD('${SETUPDIR}', 'display-specifiers/*.txt')

O755 = 493
bld.INSTALL_FILES('${SBINDIR}','provision', chmod=O755, python_fixup=True)

bld.INSTALL_FILES('${SETUPDIR}', 'dns_update_list')
bld.INSTALL_FILES('${SETUPDIR}', 'spn_update_list')

for p in '''schema-map-* DB_CONFIG *.inf *.ldif *.reg *.zone *.conf *.php *.txt
            named.conf named.conf.update provision.smb.conf.dc provision.smb.conf.member
            provision.smb.conf.standalone'''.split():
    bld.INSTALL_WILDCARD('${SETUPDIR}', p)

