#!/usr/bin/env python

bld.INSTALL_WILDCARD('${SETUPDIR}', 'ad-schema/*.txt')
bld.INSTALL_WILDCARD('${SETUPDIR}', 'ad-schema/*.ldf')
bld.INSTALL_WILDCARD('${SETUPDIR}', 'display-specifiers/*.txt')
bld.INSTALL_WILDCARD('${SETUPDIR}', 'adprep/*.ldf')
bld.INSTALL_WILDCARD('${SETUPDIR}', 'adprep/WindowsServerDocs/Schema-Updates.md')
bld.INSTALL_WILDCARD('${SETUPDIR}', 'adprep/WindowsServerDocs/Forest-Wide-Updates.md')
bld.INSTALL_WILDCARD('${SETUPDIR}', 'adprep/WindowsServerDocs/*.diff')

bld.INSTALL_FILES('${SETUPDIR}', 'dns_update_list')
bld.INSTALL_FILES('${SETUPDIR}', 'spn_update_list')

for p in '''*.inf *.ldif *.reg *.zone *.conf *.php *.txt
            named.conf.update named.conf.dlz'''.split():
    bld.INSTALL_WILDCARD('${SETUPDIR}', p)

