#!/usr/bin/env python
bld.SAMBA_SUBSYSTEM('KRB5_PAC',
                    source='gssapi_pac.c kerberos_pac.c',
                    allow_warnings=True,
                    deps='gssapi_krb5 ndr-krb5pac krb5samba')
