#!/usr/bin/env python

# The remaining task is to build the gtk example, but we first need to find the gtk libs
# netdomjoin-gui/netdomjoin-gui.c

names = [	   
    ("getdc", "getdc"),
    ("dsgetdc", "dsgetdc"),	
    ("join", "netdomjoin"),
    ("join", "getjoinableous"),
    ("join", "getjoininformation"),
    ("join", "rename_machine"),
    ("user", "user_add"),
    ("user", "user_del"),
    ("user", "user_enum"),
    ("user", "user_dispinfo"),
    ("user", "user_chgpwd"),
    ("user", "user_getinfo"),
    ("user", "user_setinfo"),
    ("user", "user_modalsget"),
    ("user", "user_modalsset"),
    ("user", "user_getgroups"),
    ("user", "user_setgroups"),
    ("user", "user_getlocalgroups"),
    ("group", "group_add"),
    ("group", "group_del"),
    ("group", "group_enum"),
    ("group", "group_setinfo"),
    ("group", "group_getinfo"),
    ("group", "group_adduser"),
    ("group", "group_deluser"),
    ("group", "group_getusers"),
    ("group", "group_setusers"),
    ("localgroup", "localgroup_add"),
    ("localgroup", "localgroup_del"),
    ("localgroup", "localgroup_getinfo"),
    ("localgroup", "localgroup_setinfo"),
    ("localgroup", "localgroup_enum"),
    ("localgroup", "localgroup_addmembers"),
    ("localgroup", "localgroup_delmembers"),
    ("localgroup", "localgroup_setmembers"),
    ("localgroup", "localgroup_getmembers"),
    ("server", "remote_tod"),
    ("server", "server_getinfo"),
    ("share", "share_add"),
    ("share", "share_del"),
    ("share", "share_enum"),
    ("share", "share_getinfo"),
    ("share", "share_setinfo"),
    ("file", "file_close"),
    ("file", "file_getinfo"),
    ("file", "file_enum"),
    ("shutdown", "shutdown_init"),
    ("shutdown", "shutdown_abort"),
    ("netlogon", "netlogon_control"),
    ("netlogon", "netlogon_control2"),
    ("netlogon", "nltest")]


bld.SAMBA_SUBSYSTEM('LIBNETAPI_EXAMPLES_COMMON',
                    source='common.c',
                    deps='netapi popt')

for pattern in names:
    (subdir, name) = pattern
    bld.SAMBA_BINARY('%s/%s' % (subdir, name),
                     source='%s/%s.c' % (subdir, name),
                     deps='netapi popt LIBNETAPI_EXAMPLES_COMMON',
                     install=False)
