#!/usr/bin/env python

RPC_LSARPC_SRC = '''srv_lsa_nt.c ../../librpc/gen_ndr/srv_lsa.c'''
RPC_NETLOGON_SRC = '''srv_netlog_nt.c ../../librpc/gen_ndr/srv_netlogon.c'''
RPC_SAMR_SRC = '''srv_samr_nt.c
               srv_samr_util.c
               srv_samr_chgpasswd.c
               ../../librpc/gen_ndr/srv_samr.c'''
RPC_INITSHUTDOWN_SRC = '''srv_initshutdown_nt.c ../../librpc/gen_ndr/srv_initshutdown.c'''
RPC_WINREG_SRC = '''srv_winreg_nt.c ../../librpc/gen_ndr/srv_winreg.c'''
RPC_DSSETUP_SRC = '''srv_dssetup_nt.c ../../librpc/gen_ndr/srv_dssetup.c'''
RPC_SRVSVC_SRC = '''srv_srvsvc_nt.c ../../librpc/gen_ndr/srv_srvsvc.c'''
RPC_WKSSVC_SRC = '''srv_wkssvc_nt.c ../../librpc/gen_ndr/srv_wkssvc.c'''
RPC_SVCCTL_SRC = '''srv_svcctl_nt.c ../../librpc/gen_ndr/srv_svcctl.c'''
RPC_NTSVCS_SRC = '''srv_ntsvcs_nt.c ../../librpc/gen_ndr/srv_ntsvcs.c'''
RPC_NETDFS_SRC = '''srv_dfs_nt.c ../../librpc/gen_ndr/srv_dfs.c'''
RPC_SPOOLSS_SRC = '''srv_spoolss_nt.c ../../librpc/gen_ndr/srv_spoolss.c
                     srv_spoolss_util.c'''
RPC_EVENTLOG_SRC = '''srv_eventlog_nt.c ../../librpc/gen_ndr/srv_eventlog.c'''
RPC_RPCECHO_SRC = '''srv_echo_nt.c ../../librpc/gen_ndr/srv_echo.c'''

bld.SAMBA_SUBSYSTEM('rpc',
                    source='',
                    deps='RPC_PIPE_REGISTER',
                    vars=locals())

bld.SAMBA_SUBSYSTEM('RPC_NCACN_NP',
                    source='rpc_ncacn_np.c rpc_handles.c')

bld.SAMBA_SUBSYSTEM('RPC_SERVICE',
                    source='rpc_server.c')

bld.SAMBA_SUBSYSTEM('RPC_CRYPTO',
                    source='dcesrv_ntlmssp.c dcesrv_gssapi.c dcesrv_spnego.c')

bld.SAMBA_SUBSYSTEM('RPC_PIPE_REGISTER',
                    source='srv_pipe_register.c')

bld.SAMBA_SUBSYSTEM('RPC_SAMR',
                    source=RPC_SAMR_SRC,
                    deps='PLAINTEXT_AUTH',
                    vars=locals())

bld.SAMBA_SUBSYSTEM('RPC_LSARPC',
                    source=RPC_LSARPC_SRC,
                    vars=locals())

bld.SAMBA_SUBSYSTEM('RPC_WINREG',
                    source=RPC_WINREG_SRC,
                    deps='REGFIO REG_API_REGF NDR_PERFCOUNT',
                    vars=locals())

bld.SAMBA_SUBSYSTEM('RPC_INITSHUTDOWN',
                    source=RPC_INITSHUTDOWN_SRC,
                    vars=locals())

bld.SAMBA_SUBSYSTEM('RPC_DSSETUP',
                    source=RPC_DSSETUP_SRC,
                    vars=locals())

bld.SAMBA_SUBSYSTEM('RPC_WKSSVC',
                    source=RPC_WKSSVC_SRC,
                    deps='LIBNET',
                    vars=locals())

bld.SAMBA_SUBSYSTEM('RPC_SVCCTL',
                    source=RPC_SVCCTL_SRC,
                    deps='SERVICES',
                    vars=locals())

bld.SAMBA_SUBSYSTEM('RPC_NTSVCS',
                    source=RPC_NTSVCS_SRC,
                    vars=locals())

bld.SAMBA_SUBSYSTEM('RPC_NETLOGON',
                    source=RPC_NETLOGON_SRC,
                    vars=locals())

bld.SAMBA_SUBSYSTEM('RPC_NETDFS',
                    source=RPC_NETDFS_SRC,
                    vars=locals())

bld.SAMBA_SUBSYSTEM('RPC_SRVSVC',
                    source=RPC_SRVSVC_SRC,
                    vars=locals())

bld.SAMBA_SUBSYSTEM('RPC_SPOOLSS',
                    source=RPC_SPOOLSS_SRC,
                    deps='cups PRINTING PRINTBACKEND RPC_NDR_WINREG',
                    vars=locals())

bld.SAMBA_SUBSYSTEM('RPC_EVENTLOG',
                    source=RPC_EVENTLOG_SRC,
                    deps='LIBEVENTLOG',
                    vars=locals())

bld.SAMBA_SUBSYSTEM('RPC_RPCECHO',
                    source=RPC_RPCECHO_SRC,
                    vars=locals())

bld.SAMBA_SUBSYSTEM('RPC_SERVER',
                    source='srv_pipe_hnd.c srv_pipe.c',
                    deps='''RPC_NCACN_NP RPC_SERVICE RPC_CRYPTO
                          RPC_SAMR RPC_LSARPC RPC_WINREG RPC_INITSHUTDOWN
                          RPC_DSSETUP RPC_WKSSVC RPC_SVCCTL RPC_NTSVCS
                          RPC_NETLOGON RPC_NETDFS RPC_SRVSVC RPC_SPOOLSS
                          RPC_EVENTLOG RPC_RPCECHO RPC_SERVER''')
