##############################
# Start SUBSYSTEM LIBCMDLINE_CREDENTIALS
[SUBSYSTEM::LIBCMDLINE_CREDENTIALS]
OBJ_FILES = getsmbpass.o \
		credentials.o
REQUIRED_SUBSYSTEMS = CREDENTIALS
# End SUBSYSTEM LIBCMDLINE_CREDENTIALS
##############################
