#!/usr/bin/env python

bld.SAMBA_LIBRARY('SOCKET_WRAPPER',
                  source='socket_wrapper.c',
                  group='base_libraries',
                  private_library=True,
                  deps='replace')

