#!/usr/bin/env python

if bld.env.WITH_PTHREADPOOL:
    bld.SAMBA_SUBSYSTEM('PTHREADPOOL',
                         source='''pthreadpool.c
                                   pthreadpool_pipe.c
                                   pthreadpool_tevent.c
                                ''',
                         deps='pthread rt replace tevent-util')
else:
    bld.SAMBA_SUBSYSTEM('PTHREADPOOL',
                         source='''pthreadpool_sync.c
                                   pthreadpool_pipe.c
                                   pthreadpool_tevent.c
                                ''',
                         deps='replace tevent-util')


bld.SAMBA_BINARY('pthreadpooltest',
                  source='tests.c',
                  deps='PTHREADPOOL',
                  enabled=bld.env.WITH_PTHREADPOOL,
                  install=False)
