#!/usr/bin/env python

bld.SAMBA_MODULE('TORTURE_LIBCLI_ECHO',
        source='echo.c',
        subsystem='smbtorture',
        init_function='torture_libcli_echo_init',
        deps='LIBTSOCKET tevent-util LIBCLI_ECHO',
        internal_module=True);
