#!/usr/bin/env python


bld.SAMBA_LIBRARY('SMBPASSWD',
                  source='smbpasswd.c',
                  deps='CHARSET LIBSAMBA-UTIL',
                  private_library=True
                  )

