# French messages for international release of SWAT.
# Copyright (C) 2001 François Le Lay <fanch@tuxfamily.org>

msgid ""
msgstr ""
"Project-Id-Version: i18n_swat \n"
"POT-Creation-Date: 2001-09-20 14:05+0100\n"
"PO-Revision-Date: 2000-02-08 14:45+0100\n"
"Last-Translator: François Le Lay <fanch@tuxfamily.org>\n"
"Language-Team: (Samba Team) <samba-technical@samba.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=US-ASCII\n"
"Content-Transfer-Encoding: \n"

#: web/swat.c:120
#, c-format
msgid "ERROR: Can't open %s\n"
msgstr "ERREUR: Impossible d'ouvrir %s\n"

#.
#. str = stripspace(parm->label);
#. strlower (str); //monyo
#. d_printf("<tr><td><A HREF=\"/swat/help/smb.conf.5.html#%s\" target=\"docs\">%s</A>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; %s</td><td>",
#. str, _("Help"), parm->label);
#.
#: web/swat.c:211
msgid "Help"
msgstr "Aide"

#: web/swat.c:217 web/swat.c:231 web/swat.c:246 web/swat.c:254 web/swat.c:263
#: web/swat.c:272 web/swat.c:278 web/swat.c:284 web/swat.c:297
msgid "Set Default"
msgstr "Définir par défaut"

#: web/swat.c:502
#, c-format
msgid "Logged in as <b>%s</b><p>\n"
msgstr "Connecté en tant que <b>%s</b><p>\n"

#: web/swat.c:505
msgid "Home"
msgstr "Home"

#: web/swat.c:507
msgid "Globals"
msgstr "Paramètres Généraux"

#: web/swat.c:508
msgid "Shares"
msgstr "Partages"

#: web/swat.c:509
msgid "Printers"
msgstr "Imprimantes"

#: web/swat.c:512
msgid "Status"
msgstr "Statut"

#: web/swat.c:513
msgid "View Config"
msgstr "Voir Configuration"

#: web/swat.c:515
msgid "Password Management"
msgstr "Gestion des mots de passe"

#: web/swat.c:539
msgid "Current Config"
msgstr "Configuration Actuelle"

#: web/swat.c:543
msgid "Normal View"
msgstr "Vue Normale"

#: web/swat.c:545
msgid "Full View"
msgstr "Vue Complète"

#: web/swat.c:561
msgid "Global Variables"
msgstr "Variables Globales"

#: web/swat.c:575 web/swat.c:671 web/swat.c:1014
msgid "Commit Changes"
msgstr "Sauver les modifications"

#: web/swat.c:579 web/swat.c:674 web/swat.c:1016
msgid "Reset Values"
msgstr "Réinitialiser Valeurs"

#: web/swat.c:581 web/swat.c:676 web/swat.c:1018
msgid "Advanced View"
msgstr "Vue Détaillée"

#: web/swat.c:583 web/swat.c:678 web/swat.c:1020
msgid "Basic View"
msgstr "Vue Basique"

#: web/swat.c:613
msgid "Share Parameters"
msgstr "Paramètres de partage"

#: web/swat.c:642
msgid "Choose Share"
msgstr "Choisir un partage"

#: web/swat.c:656
msgid "Delete Share"
msgstr "Supprimer un partage"

#: web/swat.c:663
msgid "Create Share"
msgstr "Créer un partage"

#: web/swat.c:708
msgid "password change in demo mode rejected\n"
msgstr "changement de mot de passe en mode démo rejeté"

#: web/swat.c:747
msgid " Must specify \"User Name\" \n"
msgstr "  Le champ \"Nom d'utilisateur\" doit être spécifié\n"

#: web/swat.c:763
msgid " Must specify \"Old Password\" \n"
msgstr " Le champ  \"Ancien mot de passe\" doît être spécifié\n"

#: web/swat.c:769
msgid " Must specify \"Remote Machine\" \n"
msgstr "  Le champ \"Machine Distante\" doît être spécifié\n"

#: web/swat.c:776
msgid " Must specify \"New, and Re-typed Passwords\" \n"
msgstr " Les champs \"Nouveau mot de passe\" et  \"Confirmation du nouveau mot de passe\" doivent être spécifiés \n"

#: web/swat.c:782
msgid " Re-typed password didn't match new password\n"
msgstr " Echec de la confirmation du nouveau mot de passe\n"

#: web/swat.c:812
#, c-format
msgid " The passwd for '%s' has been changed. \n"
msgstr " Le mot de passe de '%s' a été modifié. \n"

#: web/swat.c:814
#, c-format
msgid " The password for '%s' has NOT been changed. \n"
msgstr " Le mot de passe de '%s' n'a PAS été modifié. \n"

#: web/swat.c:838
msgid "Server Password Management"
msgstr "Gestion des mots de passe serveur"

#.
#. * Create all the dialog boxes for data collection
#.
#: web/swat.c:847 web/swat.c:894
msgid " User Name : "
msgstr " Nom d'utilisateur : "

#: web/swat.c:850 web/swat.c:896
msgid " Old Password : "
msgstr " Ancien mot de passe : "

#: web/swat.c:853 web/swat.c:898
msgid " New Password : "
msgstr " Nouveau mot de passe : "

#: web/swat.c:855 web/swat.c:900
msgid " Re-type New Password : "
msgstr " Confirmation du nouveau mot de passe : "

#: web/swat.c:863 web/swat.c:911
msgid "Change Password"
msgstr "Modifier le mot de passe"

#: web/swat.c:866
msgid "Add New User"
msgstr "Nouvel Utilisateur"

#: web/swat.c:868
msgid "Delete User"
msgstr "Supprimer Utilisateur"

#: web/swat.c:870
msgid "Disable User"
msgstr "Désactiver Utilisateur"

#: web/swat.c:872
msgid "Enable User"
msgstr "Activer Utilisateur"

#: web/swat.c:885
msgid "Client/Server Password Management"
msgstr "Gestion des mots de passe Client/Serveur"

#: web/swat.c:902
msgid " Remote Machine : "
msgstr " Machine distante : "

#: web/swat.c:940
msgid "Printer Parameters"
msgstr "Paramètres Imprimantes"

#: web/swat.c:942
msgid "Important Note:"
msgstr "Note Importante:"

#: web/swat.c:943
msgid "Printer names marked with [*] in the Choose Printer drop-down box "
msgstr "Les Noms d'imprimantes marqués du signe [*] dans le menu déroulant Choisir Imprimante"

#: web/swat.c:944
msgid "are autoloaded printers from "
msgstr "désignent des imprimantes automatiquement chargées depuis le "

#: web/swat.c:945
msgid "Printcap Name"
msgstr "Nom Printcap"

#: web/swat.c:946
msgid "Attempting to delete these printers from SWAT will have no effect.\n"
msgstr "Essayer de supprimer ces imprimantes depuis SWAT n'aura aucun effet.\n"

#: web/swat.c:980
msgid "Choose Printer"
msgstr "Choisir Imprimante"

#: web/swat.c:999
msgid "Delete Printer"
msgstr "Supprimer Imprimante"

#: web/swat.c:1006
msgid "Create Printer"
msgstr "Créer Imprimante"

#: web/statuspage.c:40
msgid "DENY_NONE"
msgstr ""

#: web/statuspage.c:41
msgid "DENY_ALL   "
msgstr ""

#: web/statuspage.c:42
msgid "DENY_DOS   "
msgstr ""

#: web/statuspage.c:43
msgid "DENY_READ  "
msgstr ""

#: web/statuspage.c:44
msgid "DENY_WRITE "
msgstr ""

#: web/statuspage.c:50
msgid "RDONLY     "
msgstr ""

#: web/statuspage.c:51
msgid "WRONLY     "
msgstr ""

#: web/statuspage.c:52
msgid "RDWR       "
msgstr ""

#: web/statuspage.c:60
msgid "EXCLUSIVE+BATCH "
msgstr ""

#: web/statuspage.c:62
msgid "EXCLUSIVE       "
msgstr ""

#: web/statuspage.c:64
msgid "BATCH           "
msgstr ""

#: web/statuspage.c:66
msgid "LEVEL_II        "
msgstr ""

#: web/statuspage.c:68
msgid "NONE            "
msgstr ""

#: web/statuspage.c:195
msgid "Server Status"
msgstr "Statut du Serveur"

#: web/statuspage.c:200
msgid "Auto Refresh"
msgstr "Rafraîchissement Automatique"

#: web/statuspage.c:201 web/statuspage.c:206
msgid "Refresh Interval: "
msgstr "Intervalle de rafraîchissement: "

#: web/statuspage.c:205
msgid "Stop Refreshing"
msgstr "Stopper Rafraîchissement"

#: web/statuspage.c:220
msgid "version:"
msgstr "version:"

#: web/statuspage.c:223
msgid "smbd:"
msgstr ""

#: web/statuspage.c:223 web/statuspage.c:235
msgid "running"
msgstr "actif"

#: web/statuspage.c:223 web/statuspage.c:235
msgid "not running"
msgstr "non actif"

#: web/statuspage.c:226
msgid "Stop smbd"
msgstr "Stopper smbd"

#: web/statuspage.c:228
msgid "Start smbd"
msgstr "Lancer smbd"

#: web/statuspage.c:230
msgid "Restart smbd"
msgstr "Relancer smbd"

#: web/statuspage.c:235
msgid "nmbd:"
msgstr ""

#: web/statuspage.c:238
msgid "Stop nmbd"
msgstr "Stopper nmbd"

#: web/statuspage.c:240
msgid "Start nmbd"
msgstr "Lancer nmbd"

#: web/statuspage.c:242
msgid "Restart nmbd"
msgstr "Relancer nmbd"

#: web/statuspage.c:249
msgid "Active Connections"
msgstr "Connections Actives"

#: web/statuspage.c:251 web/statuspage.c:264 web/statuspage.c:272
msgid "PID"
msgstr ""

#: web/statuspage.c:251 web/statuspage.c:264
msgid "Client"
msgstr ""

#: web/statuspage.c:251
msgid "IP address"
msgstr "adresse IP"

#: web/statuspage.c:251 web/statuspage.c:264 web/statuspage.c:272
msgid "Date"
msgstr "Date"

#: web/statuspage.c:253
msgid "Kill"
msgstr "Terminer"

#: web/statuspage.c:261
msgid "Active Shares"
msgstr "Partages Actifs"

#: web/statuspage.c:264
msgid "Share"
msgstr "Partager"

#: web/statuspage.c:264
msgid "User"
msgstr "Utilisateur"

#: web/statuspage.c:264
msgid "Group"
msgstr "Groupe"

#: web/statuspage.c:270
msgid "Open Files"
msgstr "Fichiers Ouverts"

#: web/statuspage.c:272
msgid "Sharing"
msgstr ""

#: web/statuspage.c:272
msgid "R/W"
msgstr ""

#: web/statuspage.c:272
msgid "Oplock"
msgstr ""

#: web/statuspage.c:272
msgid "File"
msgstr "Fichier"

#: param/loadparm.c:641
msgid "Base Options"
msgstr "Options de base"

#: param/loadparm.c:643
msgid "dos charset"
msgstr "caractères dos"

#: param/loadparm.c:644
msgid "unix charset"
msgstr "caractères unix"

#: param/loadparm.c:645
msgid "display charset"
msgstr "caractères display"

#: param/loadparm.c:646
msgid "comment"
msgstr "commentaire"

#: param/loadparm.c:647
msgid "path"
msgstr "chemin"

#: param/loadparm.c:648
msgid "directory"
msgstr "répertoire"

#: param/loadparm.c:649
msgid "workgroup"
msgstr "groupe de travail"

#: param/loadparm.c:650
msgid "netbios name"
msgstr "nom netbios"

#: param/loadparm.c:651
msgid "netbios aliases"
msgstr "alias netbios"

#: param/loadparm.c:652
msgid "netbios scope"
msgstr ""

#: param/loadparm.c:653
msgid "server string"
msgstr ""

#: param/loadparm.c:654
msgid "interfaces"
msgstr ""

#: param/loadparm.c:655
msgid "bind interfaces only"
msgstr "lier uniquement les interfaces"

#: param/loadparm.c:657
msgid "Security Options"
msgstr "Options de Sécurité"

#: param/loadparm.c:659
msgid "security"
msgstr "sécurité"

#: param/loadparm.c:660
msgid "encrypt passwords"
msgstr "crypter les mots de passe"

#: param/loadparm.c:661
msgid "update encrypted"
msgstr "mise à jour cryptés"

#: param/loadparm.c:662
msgid "allow trusted domains"
msgstr "autoriser les domaines de confiance"

#: param/loadparm.c:663
msgid "alternate permissions"
msgstr "permissions alternatives"

#: param/loadparm.c:664
msgid "hosts equiv"
msgstr ""

#: param/loadparm.c:665
msgid "min passwd length"
msgstr "taille minimale des mots de passe"

#: param/loadparm.c:666
msgid "min password length"
msgstr "taille minimale des mots de passe"

#: param/loadparm.c:667
msgid "map to guest"
msgstr "associer à un invité"

#: param/loadparm.c:668
msgid "null passwords"
msgstr "mots de passe null"

#: param/loadparm.c:669
msgid "obey pam restrictions"
msgstr "utiliser les restrictions pam"

#: param/loadparm.c:670
msgid "password server"
msgstr "serveur de mots de passe"

#: param/loadparm.c:671
msgid "smb passwd file"
msgstr "fichier passwd de smb"

#: param/loadparm.c:672
msgid "private dir"
msgstr "répertoire privé"

#: param/loadparm.c:673
msgid "passdb module path"
msgstr "chemin du module passdb"

#: param/loadparm.c:674
msgid "root directory"
msgstr "répertoire root"

#: param/loadparm.c:675
msgid "root dir"
msgstr "répertoire root"

#: param/loadparm.c:676
msgid "root"
msgstr ""

#: param/loadparm.c:678
msgid "pam password change"
msgstr "modification de mot de passe pam"

#: param/loadparm.c:679
msgid "passwd program"
msgstr "programme passwd"

#: param/loadparm.c:680
msgid "passwd chat"
msgstr ""

#: param/loadparm.c:681
msgid "passwd chat debug"
msgstr ""

#: param/loadparm.c:682
msgid "username map"
msgstr ""

#: param/loadparm.c:683
msgid "password level"
msgstr "niveau mot de passe"

#: param/loadparm.c:684
msgid "username level"
msgstr "niveau nom d'utilisateur"

#: param/loadparm.c:685
msgid "unix password sync"
msgstr "synchroniser avec mots de passe unix"

#: param/loadparm.c:686
msgid "restrict anonymous"
msgstr "limiter anonyme"

#: param/loadparm.c:687
msgid "lanman auth"
msgstr ""

#: param/loadparm.c:688
msgid "ntlm auth"
msgstr ""

#: param/loadparm.c:689
msgid "plaintext to smbpasswd"
msgstr "texte brut vers smbpasswd"

#: param/loadparm.c:690
msgid "use rhosts"
msgstr "utiliser rhosts"

#: param/loadparm.c:692
msgid "username"
msgstr "nom d'utilisateur"

#: param/loadparm.c:693
msgid "user"
msgstr "utilisateur"

#: param/loadparm.c:694
msgid "users"
msgstr "utilisateurs"

#: param/loadparm.c:696
msgid "guest account"
msgstr "compte invité"

#: param/loadparm.c:697
msgid "invalid users"
msgstr "utilisateurs non-valides"

#: param/loadparm.c:698
msgid "valid users"
msgstr "utilisateurs valides"

#: param/loadparm.c:699
msgid "admin users"
msgstr "utilisateurs administrateurs"

#: param/loadparm.c:700
msgid "read list"
msgstr ""

#: param/loadparm.c:701
msgid "write list"
msgstr ""

#: param/loadparm.c:702
msgid "printer admin"
msgstr "administrateur d'imprimante"

#: param/loadparm.c:703
msgid "force user"
msgstr "forcer utilisateur"

#: param/loadparm.c:704
msgid "force group"
msgstr "forcer le groupe"

#: param/loadparm.c:705
msgid "group"
msgstr "groupe"

#: param/loadparm.c:707
msgid "read only"
msgstr "lecture seule"

#: param/loadparm.c:708
msgid "write ok"
msgstr "écriture ok"

#: param/loadparm.c:709
msgid "writeable"
msgstr "écriture possible"

#: param/loadparm.c:710
msgid "writable"
msgstr "écriture possible"

#: param/loadparm.c:712
msgid "create mask"
msgstr ""

#: param/loadparm.c:713
msgid "create mode"
msgstr "mode création"

#: param/loadparm.c:714
msgid "force create mode"
msgstr "forcer le mode création"

#: param/loadparm.c:715
msgid "security mask"
msgstr ""

#: param/loadparm.c:716
msgid "force security mode"
msgstr "forcer le mode sécurité"

#: param/loadparm.c:717
msgid "directory mask"
msgstr "masque de répertoire"

#: param/loadparm.c:718
msgid "directory mode"
msgstr "mode répertoire"

#: param/loadparm.c:719
msgid "force directory mode"
msgstr "forcer le mode répertoire"

#: param/loadparm.c:720
msgid "directory security mask"
msgstr "masque de sécurité répertoire"

#: param/loadparm.c:721
msgid "force directory security mode"
msgstr "forcer le mode sécurité répertoire"

#: param/loadparm.c:722
msgid "inherit permissions"
msgstr "héritage de permissions"

#: param/loadparm.c:723
msgid "guest only"
msgstr "invité seulement"

#: param/loadparm.c:724
msgid "only guest"
msgstr "invité seulement"

#: param/loadparm.c:726
msgid "guest ok"
msgstr "invité ok"

#: param/loadparm.c:727
msgid "public"
msgstr "public"

#: param/loadparm.c:729
msgid "only user"
msgstr "utilisateur seulement"

#: param/loadparm.c:730
msgid "hosts allow"
msgstr "autoriser hosts"

#: param/loadparm.c:731
msgid "allow hosts"
msgstr "autoriser hosts"

#: param/loadparm.c:732
msgid "hosts deny"
msgstr "refuser hosts"

#: param/loadparm.c:733
msgid "deny hosts"
msgstr "refuser hosts"

#: param/loadparm.c:736
msgid "Secure Socket Layer Options"
msgstr "Options Secure Socket Layer"

#: param/loadparm.c:737
msgid "ssl"
msgstr ""

#: param/loadparm.c:739
msgid "ssl hosts"
msgstr ""

#: param/loadparm.c:740
msgid "ssl hosts resign"
msgstr ""

#: param/loadparm.c:741
msgid "ssl CA certDir"
msgstr ""

#: param/loadparm.c:742
msgid "ssl CA certFile"
msgstr ""

#: param/loadparm.c:743
msgid "ssl server cert"
msgstr "certificat ssl serveur"

#: param/loadparm.c:744
msgid "ssl server key"
msgstr "clé ssl serveur"

#: param/loadparm.c:745
msgid "ssl client cert"
msgstr "certificat ssl client"

#: param/loadparm.c:746
msgid "ssl client key"
msgstr "clé ssl client"

#: param/loadparm.c:747
msgid "ssl require clientcert"
msgstr "ssl requiert un certificat client"

#: param/loadparm.c:748
msgid "ssl require servercert"
msgstr "ssl requiert un certificat serveur"

#: param/loadparm.c:749
msgid "ssl ciphers"
msgstr "chiffres ssl"

#: param/loadparm.c:750
msgid "ssl version"
msgstr "ssl version"

#: param/loadparm.c:751
msgid "ssl compatibility"
msgstr "compatibilité ssl"

#: param/loadparm.c:754
msgid "Logging Options"
msgstr "Options de Logging"

#: param/loadparm.c:755
msgid "log level"
msgstr "niveau log"

#: param/loadparm.c:756
msgid "debuglevel"
msgstr "niveau debug"

#: param/loadparm.c:757
msgid "syslog"
msgstr ""

#: param/loadparm.c:758
msgid "syslog only"
msgstr "syslog seulement"

#: param/loadparm.c:759
msgid "log file"
msgstr "fichier log"

#: param/loadparm.c:761
msgid "max log size"
msgstr "taille maxi de la log"

#: param/loadparm.c:762
msgid "timestamp logs"
msgstr ""

#: param/loadparm.c:763
msgid "debug timestamp"
msgstr ""

#: param/loadparm.c:764
msgid "debug hires timestamp"
msgstr ""

#: param/loadparm.c:765
msgid "debug pid"
msgstr ""

#: param/loadparm.c:766
msgid "debug uid"
msgstr ""

#: param/loadparm.c:768
msgid "Protocol Options"
msgstr "Options de Protocole"

#: param/loadparm.c:770
msgid "protocol"
msgstr "protocole"

#: param/loadparm.c:771
msgid "large readwrite"
msgstr ""

#: param/loadparm.c:772
msgid "max protocol"
msgstr "protocole maxi"

#: param/loadparm.c:773
msgid "min protocol"
msgstr "protocole mini"

#: param/loadparm.c:774
msgid "unicode"
msgstr ""

#: param/loadparm.c:775
msgid "read bmpx"
msgstr ""

#: param/loadparm.c:776
msgid "read raw"
msgstr ""

#: param/loadparm.c:777
msgid "write raw"
msgstr ""

#: param/loadparm.c:779
msgid "nt smb support"
msgstr "support smb nt"

#: param/loadparm.c:780
msgid "nt pipe support"
msgstr "support pipe nt"

#: param/loadparm.c:781
msgid "nt acl support"
msgstr "support acl nt"

#: param/loadparm.c:782
msgid "announce version"
msgstr "annoncer la version"

#: param/loadparm.c:783
msgid "announce as"
msgstr "annoncer comme"

#: param/loadparm.c:784
msgid "max mux"
msgstr "mux maxi"

#: param/loadparm.c:785
msgid "max xmit"
msgstr "xmit maxi"

#: param/loadparm.c:787
msgid "name resolve order"
msgstr "ordre de résolution des noms"

#: param/loadparm.c:788
msgid "max packet"
msgstr "paquet maxi"

#: param/loadparm.c:789
msgid "packet size"
msgstr "taille de paquet"

#: param/loadparm.c:790
msgid "max ttl"
msgstr "ttl maxi"

#: param/loadparm.c:791
msgid "max wins ttl"
msgstr "wins ttl maxi"

#: param/loadparm.c:792
msgid "min wins ttl"
msgstr "wins ttl mini"

#: param/loadparm.c:793
msgid "time server"
msgstr ""

#: param/loadparm.c:795
msgid "Tuning Options"
msgstr "Options de réglage"

#: param/loadparm.c:797
msgid "change notify timeout"
msgstr ""

#: param/loadparm.c:798
msgid "deadtime"
msgstr ""

#: param/loadparm.c:799
msgid "getwd cache"
msgstr ""

#: param/loadparm.c:800
msgid "keepalive"
msgstr ""

#: param/loadparm.c:802
msgid "lpq cache time"
msgstr ""

#: param/loadparm.c:803
msgid "max smbd processes"
msgstr "nombre maxi de processus smbd"

#: param/loadparm.c:804
msgid "max connections"
msgstr "connections maxi"

#: param/loadparm.c:805
msgid "paranoid server security"
msgstr ""

#: param/loadparm.c:806
msgid "max disk size"
msgstr "taille maxi de disque"

#: param/loadparm.c:807
msgid "max open files"
msgstr "nombre maxi de fichiers ouverts"

#: param/loadparm.c:808
msgid "min print space"
msgstr "espace d'impression mini"

#: param/loadparm.c:809
msgid "read size"
msgstr ""

#: param/loadparm.c:811
msgid "socket options"
msgstr "options de socket"

#: param/loadparm.c:812
msgid "stat cache size"
msgstr "taille du cache stat"

#: param/loadparm.c:813
msgid "strict allocate"
msgstr "allocation stricte"

#: param/loadparm.c:814
msgid "strict sync"
msgstr "synchronisation stricte"

#: param/loadparm.c:815
msgid "sync always"
msgstr "toujours synchroniser"

#: param/loadparm.c:816
msgid "use mmap"
msgstr "utiliser mmap"

#: param/loadparm.c:817
msgid "hostname lookups"
msgstr ""

#: param/loadparm.c:818
msgid "write cache size"
msgstr "taille du cache d'écriture"

#: param/loadparm.c:820
msgid "Printing Options"
msgstr "Options d'impression"

#: param/loadparm.c:822
msgid "total print jobs"
msgstr "total jobs d'impression"

#: param/loadparm.c:823
msgid "max print jobs"
msgstr "max jobs d'impression"

#: param/loadparm.c:824
msgid "load printers"
msgstr "charger imprimantes"

#: param/loadparm.c:825
msgid "printcap name"
msgstr "nom printcap"

#: param/loadparm.c:826
msgid "printcap"
msgstr ""

#: param/loadparm.c:827
msgid "printable"
msgstr "imprimable"

#: param/loadparm.c:828
msgid "print ok"
msgstr "imprimante ok"

#: param/loadparm.c:829
msgid "postscript"
msgstr ""

#: param/loadparm.c:830
msgid "printing"
msgstr "impression"

#: param/loadparm.c:831
msgid "print command"
msgstr "commande d'impression"

#: param/loadparm.c:832
msgid "disable spoolss"
msgstr "désactiver spoolss"

#: param/loadparm.c:833
msgid "lpq command"
msgstr "commande lpq"

#: param/loadparm.c:834
msgid "lprm command"
msgstr "commande lprm"

#: param/loadparm.c:835
msgid "lppause command"
msgstr "commande lppause"

#: param/loadparm.c:836
msgid "lpresume command"
msgstr "commande lpresume"

#: param/loadparm.c:837
msgid "queuepause command"
msgstr "commande queuepause"

#: param/loadparm.c:838
msgid "queueresume command"
msgstr "commande queueresume"

#: param/loadparm.c:840
msgid "enumports command"
msgstr "commande enumports"

#: param/loadparm.c:841
msgid "addprinter command"
msgstr "commande addprinter"

#: param/loadparm.c:842
msgid "deleteprinter command"
msgstr "commande deleteprinter"

#: param/loadparm.c:843
msgid "show add printer wizard"
msgstr "Voir l'assistant d'ajout d'imprimante"

#: param/loadparm.c:844
msgid "os2 driver map"
msgstr ""

#: param/loadparm.c:846
msgid "printer name"
msgstr "nom d'imprimante"

#: param/loadparm.c:847
msgid "printer"
msgstr "imprimante"

#: param/loadparm.c:848
msgid "use client driver"
msgstr "utiliser le pilote client"

#: param/loadparm.c:849
msgid "printer driver"
msgstr "pilote d'imprimante"

#: param/loadparm.c:850
msgid "printer driver file"
msgstr "fichier de pilote d'imprimante"

#: param/loadparm.c:851
msgid "printer driver location"
msgstr "adresse du pilote d'imprimante"

#: param/loadparm.c:853
msgid "Filename Handling"
msgstr "Gestion des noms de fichier"

#: param/loadparm.c:854
msgid "strip dot"
msgstr ""

#: param/loadparm.c:856
msgid "mangled stack"
msgstr ""

#: param/loadparm.c:857
msgid "default case"
msgstr "casse par défaut"

#: param/loadparm.c:858
msgid "case sensitive"
msgstr "sensible à la casse"

#: param/loadparm.c:859
msgid "casesignames"
msgstr ""

#: param/loadparm.c:860
msgid "preserve case"
msgstr "garder la casse"

#: param/loadparm.c:861
msgid "short preserve case"
msgstr ""

#: param/loadparm.c:862
msgid "mangle case"
msgstr ""

#: param/loadparm.c:863
msgid "mangling char"
msgstr ""

#: param/loadparm.c:864
msgid "hide dot files"
msgstr ""

#: param/loadparm.c:865
msgid "hide unreadable"
msgstr ""

#: param/loadparm.c:866
msgid "delete veto files"
msgstr "supprimer les fichiers veto"

#: param/loadparm.c:867
msgid "veto files"
msgstr "fichiers veto"

#: param/loadparm.c:868
msgid "hide files"
msgstr "cacher les fichiers"

#: param/loadparm.c:869
msgid "veto oplock files"
msgstr ""

#: param/loadparm.c:870
msgid "map system"
msgstr "map système"

#: param/loadparm.c:871
msgid "map hidden"
msgstr "map caché"

#: param/loadparm.c:872
msgid "map archive"
msgstr ""

#: param/loadparm.c:873
msgid "mangled names"
msgstr ""

#: param/loadparm.c:874
msgid "mangled map"
msgstr ""

#: param/loadparm.c:875
msgid "stat cache"
msgstr "cache stat"

#: param/loadparm.c:877
msgid "Domain Options"
msgstr "Options de Domaine"

#: param/loadparm.c:879
msgid "domain admin group"
msgstr "groupe d'administration du domaine"

#: param/loadparm.c:880
msgid "domain guest group"
msgstr "groupe invité du domaine"

#: param/loadparm.c:883
msgid "groupname map"
msgstr "map noms de groupe"

#: param/loadparm.c:886
msgid "machine password timeout"
msgstr ""

#: param/loadparm.c:888
msgid "Logon Options"
msgstr "Options de Logon"

#: param/loadparm.c:890
msgid "add user script"
msgstr "ajouter script utilisateur"

#: param/loadparm.c:891
msgid "delete user script"
msgstr "supprimer script utilisateur"

#: param/loadparm.c:892
msgid "add group script"
msgstr "ajouter script de groupe"

#: param/loadparm.c:893
msgid "delete group script"
msgstr "supprimer script de groupe"

#: param/loadparm.c:894
msgid "add user to group script"
msgstr "ajouter un utilisateur à un script de groupe"

#: param/loadparm.c:895
msgid "delete user from group script"
msgstr "supprimer un utilisateur d'un script de groupe"

#: param/loadparm.c:896
msgid "add machine script"
msgstr "ajouter un script machine"

#: param/loadparm.c:897
msgid "shutdown script"
msgstr "script shutdown"

#: param/loadparm.c:898
msgid "abort shutdown script"
msgstr "annuler script shutdown"

#: param/loadparm.c:900
msgid "logon script"
msgstr "script de logon"

#: param/loadparm.c:901
msgid "logon path"
msgstr ""

#: param/loadparm.c:902
msgid "logon drive"
msgstr ""

#: param/loadparm.c:903
msgid "logon home"
msgstr ""

#: param/loadparm.c:904
msgid "domain logons"
msgstr ""

#: param/loadparm.c:906
msgid "Browse Options"
msgstr "Options de Navigation"

#: param/loadparm.c:908
msgid "os level"
msgstr "niveau os"

#: param/loadparm.c:909
msgid "lm announce"
msgstr "annonce lm"

#: param/loadparm.c:910
msgid "lm interval"
msgstr "intervalle lm"

#: param/loadparm.c:911
msgid "preferred master"
msgstr "master préféré"

#: param/loadparm.c:912
msgid "prefered master"
msgstr "master préféré"

#: param/loadparm.c:913
msgid "local master"
msgstr "master local"

#: param/loadparm.c:914
msgid "domain master"
msgstr "master de domaine"

#: param/loadparm.c:915
msgid "browse list"
msgstr "parcourir la liste"

#: param/loadparm.c:916
msgid "browseable"
msgstr "navigable"

#: param/loadparm.c:917
msgid "browsable"
msgstr "navigable"

#: param/loadparm.c:918
msgid "enhanced browsing"
msgstr "navigation améliorée"

#: param/loadparm.c:920
msgid "WINS Options"
msgstr "Options WINS"

#: param/loadparm.c:921
msgid "dns proxy"
msgstr ""

#: param/loadparm.c:922
msgid "wins proxy"
msgstr ""

#: param/loadparm.c:924
msgid "wins server"
msgstr ""

#: param/loadparm.c:925
msgid "wins support"
msgstr ""

#: param/loadparm.c:926
msgid "wins hook"
msgstr ""

#: param/loadparm.c:928
msgid "Locking Options"
msgstr "Options de Verrouillage"

#: param/loadparm.c:930
msgid "blocking locks"
msgstr "verrous bloquants"

#: param/loadparm.c:931
msgid "fake oplocks"
msgstr ""

#: param/loadparm.c:932
msgid "kernel oplocks"
msgstr ""

#: param/loadparm.c:933
msgid "locking"
msgstr "verrouillage"

#: param/loadparm.c:935
msgid "oplocks"
msgstr ""

#: param/loadparm.c:936
msgid "level2 oplocks"
msgstr ""

#: param/loadparm.c:937
msgid "oplock break wait time"
msgstr ""

#: param/loadparm.c:938
msgid "oplock contention limit"
msgstr ""

#: param/loadparm.c:939
msgid "posix locking"
msgstr "verrouillage posix"

#: param/loadparm.c:940
msgid "strict locking"
msgstr "verrouillage strict"

#: param/loadparm.c:941
msgid "share modes"
msgstr "modes de partage"

#: param/loadparm.c:944
msgid "Ldap Options"
msgstr "Options Ldap"

#: param/loadparm.c:946
msgid "ldap server"
msgstr "serveur ldap"

#: param/loadparm.c:947
msgid "ldap port"
msgstr "port ldap"

#: param/loadparm.c:948
msgid "ldap suffix"
msgstr "suffixe ldap"

#: param/loadparm.c:949
msgid "ldap filter"
msgstr "filtre ldap"

#: param/loadparm.c:950
msgid "ldap root"
msgstr ""

#: param/loadparm.c:951
msgid "ldap root passwd"
msgstr ""

#: param/loadparm.c:954
msgid "Miscellaneous Options"
msgstr "Options Diverses"

#: param/loadparm.c:955
msgid "add share command"
msgstr "ajouter une commande de partage"

#: param/loadparm.c:956
msgid "change share command"
msgstr "modifier une commande de partage"

#: param/loadparm.c:957
msgid "delete share command"
msgstr "supprimer une commande de partage"

#: param/loadparm.c:959
msgid "config file"
msgstr "fichier de configuration"

#: param/loadparm.c:960
msgid "preload"
msgstr "pré-chargement"

#: param/loadparm.c:961
msgid "auto services"
msgstr ""

#: param/loadparm.c:962
msgid "lock dir"
msgstr ""

#: param/loadparm.c:963
msgid "lock directory"
msgstr ""

#: param/loadparm.c:965
msgid "utmp directory"
msgstr ""

#: param/loadparm.c:966
msgid "wtmp directory"
msgstr ""

#: param/loadparm.c:967
msgid "utmp"
msgstr ""

#: param/loadparm.c:970
msgid "default service"
msgstr "service par défaut"

#: param/loadparm.c:971
msgid "default"
msgstr "par défaut"

#: param/loadparm.c:972
msgid "message command"
msgstr "commande message"

#: param/loadparm.c:973
msgid "dfree command"
msgstr "commande dfree"

#: param/loadparm.c:974
msgid "remote announce"
msgstr "annonce distante"

#: param/loadparm.c:975
msgid "remote browse sync"
msgstr "synchronisation de navigation distante"

#: param/loadparm.c:976
msgid "socket address"
msgstr "adresse de socket"

#: param/loadparm.c:977
msgid "homedir map"
msgstr ""

#: param/loadparm.c:978
msgid "time offset"
msgstr ""

#: param/loadparm.c:979
msgid "NIS homedir"
msgstr ""

#: param/loadparm.c:980
msgid "-valid"
msgstr ""

#: param/loadparm.c:982
msgid "copy"
msgstr ""

#: param/loadparm.c:983
msgid "include"
msgstr ""

#: param/loadparm.c:984
msgid "exec"
msgstr ""

#: param/loadparm.c:985
msgid "preexec"
msgstr ""

#: param/loadparm.c:987
msgid "preexec close"
msgstr ""

#: param/loadparm.c:988
msgid "postexec"
msgstr ""

#: param/loadparm.c:989
msgid "root preexec"
msgstr ""

#: param/loadparm.c:990
msgid "root preexec close"
msgstr ""

#: param/loadparm.c:991
msgid "root postexec"
msgstr ""

#: param/loadparm.c:992
msgid "available"
msgstr "disponible"

#: param/loadparm.c:993
msgid "volume"
msgstr ""

#: param/loadparm.c:994
msgid "fstype"
msgstr ""

#: param/loadparm.c:995
msgid "set directory"
msgstr ""

#: param/loadparm.c:996
msgid "source environment"
msgstr ""

#: param/loadparm.c:997
msgid "wide links"
msgstr ""

#: param/loadparm.c:998
msgid "follow symlinks"
msgstr ""

#: param/loadparm.c:999
msgid "dont descend"
msgstr "ne pas descendre"

#: param/loadparm.c:1000
msgid "magic script"
msgstr ""

#: param/loadparm.c:1001
msgid "magic output"
msgstr ""

#: param/loadparm.c:1002
msgid "delete readonly"
msgstr "supprimer lecture seule"

#: param/loadparm.c:1003
msgid "dos filemode"
msgstr ""

#: param/loadparm.c:1004
msgid "dos filetimes"
msgstr ""

#: param/loadparm.c:1005
msgid "dos filetime resolution"
msgstr ""

#: param/loadparm.c:1007
msgid "fake directory create times"
msgstr ""

#: param/loadparm.c:1008
msgid "panic action"
msgstr ""

#: param/loadparm.c:1009
msgid "hide local users"
msgstr "cacher les utilisateurs locaux"

#: param/loadparm.c:1012
msgid "VFS options"
msgstr "Options VFS"

#: param/loadparm.c:1014
msgid "vfs object"
msgstr ""

#: param/loadparm.c:1015
msgid "vfs options"
msgstr ""

#: param/loadparm.c:1018
msgid "msdfs root"
msgstr ""

#: param/loadparm.c:1019
msgid "host msdfs"
msgstr ""

#: param/loadparm.c:1021
msgid "Winbind options"
msgstr "Options Winbind"

#: param/loadparm.c:1023
msgid "winbind uid"
msgstr ""

#: param/loadparm.c:1024
msgid "winbind gid"
msgstr ""

#: param/loadparm.c:1025
msgid "template homedir"
msgstr ""

#: param/loadparm.c:1026
msgid "template shell"
msgstr ""

#: param/loadparm.c:1027
msgid "winbind separator"
msgstr ""

#: param/loadparm.c:1028
msgid "winbind cache time"
msgstr ""

#: param/loadparm.c:1029
msgid "winbind enum users"
msgstr ""

#: param/loadparm.c:1030
msgid "winbind enum groups"
msgstr ""


