# SOME DESCRIPTIVE TITLE.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2000-05-30 12:14+0900\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: zh <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=GB2312\n"
"Content-Transfer-Encoding: \n"

#: web/swat.c:125
#, c-format
msgid "ERROR: Can't open %s\n"
msgstr ""

#: web/swat.c:214
msgid "Help"
msgstr "Help(zh)"

#: web/swat.c:221 web/swat.c:233 web/swat.c:245 web/swat.c:254 web/swat.c:263
#: web/swat.c:269 web/swat.c:275 web/swat.c:285
msgid "Set Default"
msgstr ""

#: web/swat.c:396
#, c-format
msgid "failed to open %s for writing\n"
msgstr ""

#: web/swat.c:408
#, c-format
msgid "Can't reload %s\n"
msgstr ""

#: web/swat.c:486
#, c-format
msgid "Logged in as <b>%s</b><p>\n"
msgstr ""

#: web/swat.c:489
msgid "Home"
msgstr ""

#: web/swat.c:491
msgid "Globals"
msgstr ""

#: web/swat.c:492
msgid "Shares"
msgstr ""

#: web/swat.c:493
msgid "Printers"
msgstr ""

#: web/swat.c:496
msgid "Status"
msgstr ""

#: web/swat.c:497
msgid "View Config"
msgstr ""

#: web/swat.c:499
msgid "Password Management"
msgstr ""

#: web/swat.c:523
msgid "Current Config"
msgstr ""

#: web/swat.c:527
msgid "Normal View"
msgstr ""

#: web/swat.c:529
msgid "Full View"
msgstr ""

#: web/swat.c:545
msgid "Global Variables"
msgstr ""

#: web/swat.c:559 web/swat.c:667 web/swat.c:1022
msgid "Commit Changes"
msgstr ""

#: web/swat.c:563 web/swat.c:670 web/swat.c:1024
msgid "Reset Values"
msgstr ""

#: web/swat.c:565 web/swat.c:672 web/swat.c:1026
msgid "Advanced View"
msgstr ""

#: web/swat.c:567 web/swat.c:674 web/swat.c:1028
msgid "Basic View"
msgstr ""

#: web/swat.c:601
msgid "Share Parameters"
msgstr ""

#: web/swat.c:637
msgid "Choose Share"
msgstr ""

#: web/swat.c:652
msgid "Delete Share"
msgstr ""

#: web/swat.c:659
msgid "Create Share"
msgstr ""

#: web/swat.c:704
msgid "password change in demo mode rejected\n"
msgstr ""

#: web/swat.c:717
msgid "Can't setup password database vectors.\n"
msgstr ""

#: web/swat.c:743
msgid " Must specify \"User Name\" \n"
msgstr ""

#: web/swat.c:759
msgid " Must specify \"Old Password\" \n"
msgstr ""

#: web/swat.c:765
msgid " Must specify \"Remote Machine\" \n"
msgstr ""

#: web/swat.c:772
msgid " Must specify \"New, and Re-typed Passwords\" \n"
msgstr ""

#: web/swat.c:778
msgid " Re-typed password didn't match new password\n"
msgstr ""

#: web/swat.c:807
#, c-format
msgid " The passwd for '%s' has been changed. \n"
msgstr ""

#: web/swat.c:809
#, c-format
msgid " The passwd for '%s' has NOT been changed. \n"
msgstr ""

#: web/swat.c:833
msgid "Server Password Management"
msgstr ""

#.
#. * Create all the dialog boxes for data collection
#.
#: web/swat.c:842 web/swat.c:889
msgid " User Name : "
msgstr ""

#: web/swat.c:845 web/swat.c:891
msgid " Old Password : "
msgstr ""

#: web/swat.c:848 web/swat.c:893
msgid " New Password : "
msgstr ""

#: web/swat.c:850 web/swat.c:895
msgid " Re-type New Password : "
msgstr ""

#: web/swat.c:858 web/swat.c:906
msgid "Change Password"
msgstr ""

#: web/swat.c:861
msgid "Add New User"
msgstr ""

#: web/swat.c:863
msgid "Delete User"
msgstr ""

#: web/swat.c:865
msgid "Disable User"
msgstr ""

#: web/swat.c:867
msgid "Enable User"
msgstr ""

#: web/swat.c:880
msgid "Client/Server Password Management"
msgstr ""

#: web/swat.c:897
msgid " Remote Machine : "
msgstr ""

#: web/swat.c:941
msgid "Printer Parameters"
msgstr ""

#: web/swat.c:943
msgid "Important Note:"
msgstr ""

#: web/swat.c:944
msgid "Printer names marked with [*] in the Choose Printer drop-down box "
msgstr ""

#: web/swat.c:945
msgid "are autoloaded printers from "
msgstr ""

#: web/swat.c:946
msgid "Printcap Name"
msgstr ""

#: web/swat.c:947
msgid "Attempting to delete these printers from SWAT will have no effect.\n"
msgstr ""

#: web/swat.c:987
msgid "Choose Printer"
msgstr ""

#: web/swat.c:1007
msgid "Delete Printer"
msgstr ""

#: web/swat.c:1014
msgid "Create Printer"
msgstr ""

#: web/statuspage.c:38
msgid "DENY_NONE"
msgstr ""

#: web/statuspage.c:39
msgid "DENY_ALL   "
msgstr ""

#: web/statuspage.c:40
msgid "DENY_DOS   "
msgstr ""

#: web/statuspage.c:41
msgid "DENY_READ  "
msgstr ""

#: web/statuspage.c:42
msgid "DENY_WRITE "
msgstr ""

#: web/statuspage.c:48
msgid "RDONLY     "
msgstr ""

#: web/statuspage.c:49
msgid "WRONLY     "
msgstr ""

#: web/statuspage.c:50
msgid "RDWR       "
msgstr ""

#: web/statuspage.c:58
msgid "EXCLUSIVE+BATCH "
msgstr ""

#: web/statuspage.c:60
msgid "EXCLUSIVE       "
msgstr ""

#: web/statuspage.c:62
msgid "BATCH           "
msgstr ""

#: web/statuspage.c:64
msgid "LEVEL_II        "
msgstr ""

#: web/statuspage.c:66
msgid "NONE            "
msgstr ""

#: web/statuspage.c:145
msgid "Server Status"
msgstr ""

#: web/statuspage.c:150
msgid "Auto Refresh"
msgstr ""

#: web/statuspage.c:151 web/statuspage.c:156
msgid "Refresh Interval: "
msgstr ""

#: web/statuspage.c:155
msgid "Stop Refreshing"
msgstr ""

#: web/statuspage.c:167
msgid "You need to have status=yes in your smb config file\n"
msgstr ""

#: web/statuspage.c:173
msgid "version:"
msgstr ""

#: web/statuspage.c:176
msgid "smbd:"
msgstr ""

#: web/statuspage.c:176 web/statuspage.c:188
msgid "running"
msgstr ""

#: web/statuspage.c:176 web/statuspage.c:188
msgid "not running"
msgstr ""

#: web/statuspage.c:179
msgid "Stop smbd"
msgstr ""

#: web/statuspage.c:181
msgid "Start smbd"
msgstr ""

#: web/statuspage.c:183
msgid "Restart smbd"
msgstr ""

#: web/statuspage.c:188
msgid "nmbd:"
msgstr ""

#: web/statuspage.c:191
msgid "Stop nmbd"
msgstr ""

#: web/statuspage.c:193
msgid "Start nmbd"
msgstr ""

#: web/statuspage.c:195
msgid "Restart nmbd"
msgstr ""

#: web/statuspage.c:202
msgid "Active Connections"
msgstr ""

#: web/statuspage.c:204 web/statuspage.c:235 web/statuspage.c:254
msgid "PID"
msgstr ""

#: web/statuspage.c:204 web/statuspage.c:235
msgid "Client"
msgstr ""

#: web/statuspage.c:204
msgid "IP address"
msgstr ""

#: web/statuspage.c:204 web/statuspage.c:235 web/statuspage.c:254
msgid "Date"
msgstr ""

#: web/statuspage.c:206
msgid "Kill"
msgstr ""

#: web/statuspage.c:232
msgid "Active Shares"
msgstr ""

#: web/statuspage.c:235
msgid "Share"
msgstr ""

#: web/statuspage.c:235
msgid "User"
msgstr ""

#: web/statuspage.c:235
msgid "Group"
msgstr ""

#: web/statuspage.c:252
msgid "Open Files"
msgstr ""

#: web/statuspage.c:254
msgid "Sharing"
msgstr ""

#: web/statuspage.c:254
msgid "R/W"
msgstr ""

#: web/statuspage.c:254
msgid "Oplock"
msgstr ""

#: web/statuspage.c:254
msgid "File"
msgstr ""

#: param/loadparm.c:557
msgid "Base Options"
msgstr ""

#: param/loadparm.c:558
msgid "coding system"
msgstr ""

#: param/loadparm.c:559
msgid "client code page"
msgstr ""

#: param/loadparm.c:560
msgid "comment"
msgstr ""

#: param/loadparm.c:561
msgid "path"
msgstr ""

#: param/loadparm.c:562
msgid "directory"
msgstr ""

#: param/loadparm.c:563
msgid "workgroup"
msgstr ""

#: param/loadparm.c:564
msgid "netbios name"
msgstr ""

#: param/loadparm.c:565
msgid "netbios aliases"
msgstr ""

#: param/loadparm.c:566
msgid "netbios scope"
msgstr ""

#: param/loadparm.c:567
msgid "server string"
msgstr ""

#: param/loadparm.c:568
msgid "interfaces"
msgstr ""

#: param/loadparm.c:569
msgid "bind interfaces only"
msgstr ""

#: param/loadparm.c:571
msgid "Security Options"
msgstr ""

#: param/loadparm.c:572
msgid "security"
msgstr ""

#: param/loadparm.c:573
msgid "encrypt passwords"
msgstr ""

#: param/loadparm.c:574
msgid "update encrypted"
msgstr ""

#: param/loadparm.c:575
msgid "allow trusted domains"
msgstr ""

#: param/loadparm.c:576
msgid "alternate permissions"
msgstr ""

#: param/loadparm.c:577
msgid "hosts equiv"
msgstr ""

#: param/loadparm.c:578
msgid "min password length"
msgstr ""

#: param/loadparm.c:579
msgid "min passwd length"
msgstr ""

#: param/loadparm.c:580
msgid "map to guest"
msgstr ""

#: param/loadparm.c:581
msgid "null passwords"
msgstr ""

#: param/loadparm.c:582
msgid "password server"
msgstr ""

#: param/loadparm.c:583
msgid "smb passwd file"
msgstr ""

#: param/loadparm.c:584
msgid "root directory"
msgstr ""

#: param/loadparm.c:585
msgid "root dir"
msgstr ""

#: param/loadparm.c:586
msgid "root"
msgstr ""

#: param/loadparm.c:587
msgid "passwd program"
msgstr ""

#: param/loadparm.c:588
msgid "passwd chat"
msgstr ""

#: param/loadparm.c:589
msgid "passwd chat debug"
msgstr ""

#: param/loadparm.c:590
msgid "username map"
msgstr ""

#: param/loadparm.c:591
msgid "password level"
msgstr ""

#: param/loadparm.c:592
msgid "username level"
msgstr ""

#: param/loadparm.c:593
msgid "unix password sync"
msgstr ""

#: param/loadparm.c:594
msgid "restrict anonymous"
msgstr ""

#: param/loadparm.c:595
msgid "revalidate"
msgstr ""

#: param/loadparm.c:596
msgid "use rhosts"
msgstr ""

#: param/loadparm.c:597
msgid "username"
msgstr ""

#: param/loadparm.c:598
msgid "user"
msgstr ""

#: param/loadparm.c:599
msgid "users"
msgstr ""

#: param/loadparm.c:600
msgid "guest account"
msgstr ""

#: param/loadparm.c:601
msgid "invalid users"
msgstr ""

#: param/loadparm.c:602
msgid "valid users"
msgstr ""

#: param/loadparm.c:603
msgid "admin users"
msgstr ""

#: param/loadparm.c:604
msgid "read list"
msgstr ""

#: param/loadparm.c:605
msgid "write list"
msgstr ""

#: param/loadparm.c:606
msgid "force user"
msgstr ""

#: param/loadparm.c:607
msgid "force group"
msgstr ""

#: param/loadparm.c:608
msgid "group"
msgstr ""

#: param/loadparm.c:609
msgid "writeable"
msgstr ""

#: param/loadparm.c:610
msgid "write ok"
msgstr ""

#: param/loadparm.c:611
msgid "writable"
msgstr ""

#: param/loadparm.c:612
msgid "read only"
msgstr ""

#: param/loadparm.c:613
msgid "create mask"
msgstr ""

#: param/loadparm.c:614
msgid "create mode"
msgstr ""

#: param/loadparm.c:615
msgid "force create mode"
msgstr ""

#: param/loadparm.c:616
msgid "security mask"
msgstr ""

#: param/loadparm.c:617
msgid "force security mode"
msgstr ""

#: param/loadparm.c:618
msgid "directory mask"
msgstr ""

#: param/loadparm.c:619
msgid "directory mode"
msgstr ""

#: param/loadparm.c:620
msgid "force directory mode"
msgstr ""

#: param/loadparm.c:621
msgid "directory security mask"
msgstr ""

#: param/loadparm.c:622
msgid "force directory security mode"
msgstr ""

#: param/loadparm.c:623
msgid "inherit permissions"
msgstr ""

#: param/loadparm.c:624
msgid "guest only"
msgstr ""

#: param/loadparm.c:625
msgid "only guest"
msgstr ""

#: param/loadparm.c:626
msgid "guest ok"
msgstr ""

#: param/loadparm.c:627
msgid "public"
msgstr ""

#: param/loadparm.c:628
msgid "only user"
msgstr ""

#: param/loadparm.c:629
msgid "hosts allow"
msgstr ""

#: param/loadparm.c:630
msgid "allow hosts"
msgstr ""

#: param/loadparm.c:631
msgid "hosts deny"
msgstr ""

#: param/loadparm.c:632
msgid "deny hosts"
msgstr ""

#: param/loadparm.c:635
msgid "Secure Socket Layer Options"
msgstr ""

#: param/loadparm.c:636
msgid "ssl"
msgstr ""

#: param/loadparm.c:637
msgid "ssl hosts"
msgstr ""

#: param/loadparm.c:638
msgid "ssl hosts resign"
msgstr ""

#: param/loadparm.c:639
msgid "ssl CA certDir"
msgstr ""

#: param/loadparm.c:640
msgid "ssl CA certFile"
msgstr ""

#: param/loadparm.c:641
msgid "ssl server cert"
msgstr ""

#: param/loadparm.c:642
msgid "ssl server key"
msgstr ""

#: param/loadparm.c:643
msgid "ssl client cert"
msgstr ""

#: param/loadparm.c:644
msgid "ssl client key"
msgstr ""

#: param/loadparm.c:645
msgid "ssl require clientcert"
msgstr ""

#: param/loadparm.c:646
msgid "ssl require servercert"
msgstr ""

#: param/loadparm.c:647
msgid "ssl ciphers"
msgstr ""

#: param/loadparm.c:648
msgid "ssl version"
msgstr ""

#: param/loadparm.c:649
msgid "ssl compatibility"
msgstr ""

#: param/loadparm.c:652
msgid "Logging Options"
msgstr ""

#: param/loadparm.c:653
msgid "debug level"
msgstr ""

#: param/loadparm.c:654
msgid "log level"
msgstr ""

#: param/loadparm.c:655
msgid "syslog"
msgstr ""

#: param/loadparm.c:656
msgid "syslog only"
msgstr ""

#: param/loadparm.c:657
msgid "log file"
msgstr ""

#: param/loadparm.c:658
msgid "max log size"
msgstr ""

#: param/loadparm.c:659
msgid "debug timestamp"
msgstr ""

#: param/loadparm.c:660
msgid "timestamp logs"
msgstr ""

#: param/loadparm.c:661
msgid "debug hires timestamp"
msgstr ""

#: param/loadparm.c:662
msgid "debug pid"
msgstr ""

#: param/loadparm.c:663
msgid "debug uid"
msgstr ""

#: param/loadparm.c:664
msgid "status"
msgstr ""

#: param/loadparm.c:666
msgid "Protocol Options"
msgstr ""

#: param/loadparm.c:667
msgid "protocol"
msgstr ""

#: param/loadparm.c:668
msgid "read bmpx"
msgstr ""

#: param/loadparm.c:669
msgid "read raw"
msgstr ""

#: param/loadparm.c:670
msgid "write raw"
msgstr ""

#: param/loadparm.c:671
msgid "nt smb support"
msgstr ""

#: param/loadparm.c:672
msgid "nt pipe support"
msgstr ""

#: param/loadparm.c:673
msgid "nt acl support"
msgstr ""

#: param/loadparm.c:674
msgid "announce version"
msgstr ""

#: param/loadparm.c:675
msgid "announce as"
msgstr ""

#: param/loadparm.c:676
msgid "max mux"
msgstr ""

#: param/loadparm.c:677
msgid "max xmit"
msgstr ""

#: param/loadparm.c:678
msgid "name resolve order"
msgstr ""

#: param/loadparm.c:679
msgid "packet size"
msgstr ""

#: param/loadparm.c:680
msgid "max packet"
msgstr ""

#: param/loadparm.c:681
msgid "max ttl"
msgstr ""

#: param/loadparm.c:682
msgid "max wins ttl"
msgstr ""

#: param/loadparm.c:683
msgid "min wins ttl"
msgstr ""

#: param/loadparm.c:684
msgid "time server"
msgstr ""

#: param/loadparm.c:686
msgid "Tuning Options"
msgstr ""

#: param/loadparm.c:687
msgid "change notify timeout"
msgstr ""

#: param/loadparm.c:688
msgid "deadtime"
msgstr ""

#: param/loadparm.c:689
msgid "getwd cache"
msgstr ""

#: param/loadparm.c:690
msgid "keepalive"
msgstr ""

#: param/loadparm.c:691
msgid "lpq cache time"
msgstr ""

#: param/loadparm.c:692
msgid "max connections"
msgstr ""

#: param/loadparm.c:693
msgid "max disk size"
msgstr ""

#: param/loadparm.c:694
msgid "max open files"
msgstr ""

#: param/loadparm.c:695
msgid "min print space"
msgstr ""

#: param/loadparm.c:696
msgid "read prediction"
msgstr ""

#: param/loadparm.c:697
msgid "read size"
msgstr ""

#: param/loadparm.c:698
msgid "shared mem size"
msgstr ""

#: param/loadparm.c:699
msgid "socket options"
msgstr ""

#: param/loadparm.c:700
msgid "stat cache size"
msgstr ""

#: param/loadparm.c:701
msgid "strict sync"
msgstr ""

#: param/loadparm.c:702
msgid "sync always"
msgstr ""

#: param/loadparm.c:703
msgid "write cache size"
msgstr ""

#: param/loadparm.c:705
msgid "Printing Options"
msgstr ""

#: param/loadparm.c:706
msgid "load printers"
msgstr ""

#: param/loadparm.c:707
msgid "printcap name"
msgstr ""

#: param/loadparm.c:708
msgid "printcap"
msgstr ""

#: param/loadparm.c:709
msgid "printer driver file"
msgstr ""

#: param/loadparm.c:710
msgid "printable"
msgstr ""

#: param/loadparm.c:711
msgid "print ok"
msgstr ""

#: param/loadparm.c:712
msgid "postscript"
msgstr ""

#: param/loadparm.c:713
msgid "printing"
msgstr ""

#: param/loadparm.c:714
msgid "print command"
msgstr ""

#: param/loadparm.c:715
msgid "lpq command"
msgstr ""

#: param/loadparm.c:716
msgid "lprm command"
msgstr ""

#: param/loadparm.c:717
msgid "lppause command"
msgstr ""

#: param/loadparm.c:718
msgid "lpresume command"
msgstr ""

#: param/loadparm.c:719
msgid "queuepause command"
msgstr ""

#: param/loadparm.c:720
msgid "queueresume command"
msgstr ""

#: param/loadparm.c:722
msgid "printer"
msgstr ""

#: param/loadparm.c:723
msgid "printer name"
msgstr ""

#: param/loadparm.c:724
msgid "printer driver"
msgstr ""

#: param/loadparm.c:725
msgid "printer driver location"
msgstr ""

#: param/loadparm.c:728
msgid "Filename Handling"
msgstr ""

#: param/loadparm.c:729
msgid "strip dot"
msgstr ""

#: param/loadparm.c:730
msgid "character set"
msgstr ""

#: param/loadparm.c:731
msgid "mangled stack"
msgstr ""

#: param/loadparm.c:732
msgid "default case"
msgstr ""

#: param/loadparm.c:733
msgid "case sensitive"
msgstr ""

#: param/loadparm.c:734
msgid "casesignames"
msgstr ""

#: param/loadparm.c:735
msgid "preserve case"
msgstr ""

#: param/loadparm.c:736
msgid "short preserve case"
msgstr ""

#: param/loadparm.c:737
msgid "mangle case"
msgstr ""

#: param/loadparm.c:738
msgid "mangling char"
msgstr ""

#: param/loadparm.c:739
msgid "hide dot files"
msgstr ""

#: param/loadparm.c:740
msgid "delete veto files"
msgstr ""

#: param/loadparm.c:741
msgid "veto files"
msgstr ""

#: param/loadparm.c:742
msgid "hide files"
msgstr ""

#: param/loadparm.c:743
msgid "veto oplock files"
msgstr ""

#: param/loadparm.c:744
msgid "map system"
msgstr ""

#: param/loadparm.c:745
msgid "map hidden"
msgstr ""

#: param/loadparm.c:746
msgid "map archive"
msgstr ""

#: param/loadparm.c:747
msgid "mangled names"
msgstr ""

#: param/loadparm.c:748
msgid "mangled map"
msgstr ""

#: param/loadparm.c:749
msgid "stat cache"
msgstr ""

#: param/loadparm.c:751
msgid "Domain Options"
msgstr ""

#: param/loadparm.c:752
msgid "domain groups"
msgstr ""

#: param/loadparm.c:753
msgid "domain admin group"
msgstr ""

#: param/loadparm.c:754
msgid "domain guest group"
msgstr ""

#: param/loadparm.c:755
msgid "domain admin users"
msgstr ""

#: param/loadparm.c:756
msgid "domain guest users"
msgstr ""

#: param/loadparm.c:758
msgid "groupname map"
msgstr ""

#: param/loadparm.c:760
msgid "machine password timeout"
msgstr ""

#: param/loadparm.c:762
msgid "Logon Options"
msgstr ""

#: param/loadparm.c:763
msgid "add user script"
msgstr ""

#: param/loadparm.c:764
msgid "delete user script"
msgstr ""

#: param/loadparm.c:765
msgid "logon script"
msgstr ""

#: param/loadparm.c:766
msgid "logon path"
msgstr ""

#: param/loadparm.c:767
msgid "logon drive"
msgstr ""

#: param/loadparm.c:768
msgid "logon home"
msgstr ""

#: param/loadparm.c:769
msgid "domain logons"
msgstr ""

#: param/loadparm.c:771
msgid "Browse Options"
msgstr ""

#: param/loadparm.c:772
msgid "os level"
msgstr ""

#: param/loadparm.c:773
msgid "lm announce"
msgstr ""

#: param/loadparm.c:774
msgid "lm interval"
msgstr ""

#: param/loadparm.c:775
msgid "preferred master"
msgstr ""

#: param/loadparm.c:776
msgid "prefered master"
msgstr ""

#: param/loadparm.c:777
msgid "local master"
msgstr ""

#: param/loadparm.c:778
msgid "domain master"
msgstr ""

#: param/loadparm.c:779
msgid "browse list"
msgstr ""

#: param/loadparm.c:780
msgid "browseable"
msgstr ""

#: param/loadparm.c:781
msgid "browsable"
msgstr ""

#: param/loadparm.c:783
msgid "WINS Options"
msgstr ""

#: param/loadparm.c:784
msgid "dns proxy"
msgstr ""

#: param/loadparm.c:785
msgid "wins proxy"
msgstr ""

#: param/loadparm.c:786
msgid "wins server"
msgstr ""

#: param/loadparm.c:787
msgid "wins support"
msgstr ""

#: param/loadparm.c:788
msgid "wins hook"
msgstr ""

#: param/loadparm.c:790
msgid "Locking Options"
msgstr ""

#: param/loadparm.c:791
msgid "blocking locks"
msgstr ""

#: param/loadparm.c:792
msgid "fake oplocks"
msgstr ""

#: param/loadparm.c:793
msgid "kernel oplocks"
msgstr ""

#: param/loadparm.c:794
msgid "locking"
msgstr ""

#: param/loadparm.c:796
msgid "utmp"
msgstr ""

#: param/loadparm.c:798
msgid "ole locking compatibility"
msgstr ""

#: param/loadparm.c:799
msgid "oplocks"
msgstr ""

#: param/loadparm.c:800
msgid "level2 oplocks"
msgstr ""

#: param/loadparm.c:801
msgid "oplock break wait time"
msgstr ""

#: param/loadparm.c:802
msgid "oplock contention limit"
msgstr ""

#: param/loadparm.c:803
msgid "strict locking"
msgstr ""

#: param/loadparm.c:804
msgid "share modes"
msgstr ""

#: param/loadparm.c:807
msgid "Ldap Options"
msgstr ""

#: param/loadparm.c:808
msgid "ldap server"
msgstr ""

#: param/loadparm.c:809
msgid "ldap port"
msgstr ""

#: param/loadparm.c:810
msgid "ldap suffix"
msgstr ""

#: param/loadparm.c:811
msgid "ldap filter"
msgstr ""

#: param/loadparm.c:812
msgid "ldap root"
msgstr ""

#: param/loadparm.c:813
msgid "ldap root passwd"
msgstr ""

#: param/loadparm.c:817
msgid "Miscellaneous Options"
msgstr ""

#: param/loadparm.c:818
msgid "smbrun"
msgstr ""

#: param/loadparm.c:819
msgid "config file"
msgstr ""

#: param/loadparm.c:820
msgid "auto services"
msgstr ""

#: param/loadparm.c:821
msgid "preload"
msgstr ""

#: param/loadparm.c:822
msgid "lock directory"
msgstr ""

#: param/loadparm.c:823
msgid "lock dir"
msgstr ""

#: param/loadparm.c:825
msgid "utmp directory"
msgstr ""

#: param/loadparm.c:826
msgid "utmp dir"
msgstr ""

#: param/loadparm.c:827
msgid "wtmp directory"
msgstr ""

#: param/loadparm.c:828
msgid "wtmp dir"
msgstr ""

#: param/loadparm.c:829
msgid "utmp hostname"
msgstr ""

#: param/loadparm.c:830
msgid "utmp consolidate"
msgstr ""

#: param/loadparm.c:832
msgid "default service"
msgstr ""

#: param/loadparm.c:833
msgid "default"
msgstr ""

#: param/loadparm.c:834
msgid "message command"
msgstr ""

#: param/loadparm.c:835
msgid "dfree command"
msgstr ""

#: param/loadparm.c:836
msgid "valid chars"
msgstr ""

#: param/loadparm.c:837
msgid "remote announce"
msgstr ""

#: param/loadparm.c:838
msgid "remote browse sync"
msgstr ""

#: param/loadparm.c:839
msgid "socket address"
msgstr ""

#: param/loadparm.c:840
msgid "homedir map"
msgstr ""

#: param/loadparm.c:841
msgid "time offset"
msgstr ""

#: param/loadparm.c:842
msgid "unix realname"
msgstr ""

#: param/loadparm.c:843
msgid "NIS homedir"
msgstr ""

#: param/loadparm.c:844
msgid "-valid"
msgstr ""

#: param/loadparm.c:845
msgid "copy"
msgstr ""

#: param/loadparm.c:846
msgid "include"
msgstr ""

#: param/loadparm.c:847
msgid "preexec"
msgstr ""

#: param/loadparm.c:848
msgid "exec"
msgstr ""

#: param/loadparm.c:849
msgid "preexec close"
msgstr ""

#: param/loadparm.c:850
msgid "postexec"
msgstr ""

#: param/loadparm.c:851
msgid "root preexec"
msgstr ""

#: param/loadparm.c:852
msgid "root preexec close"
msgstr ""

#: param/loadparm.c:853
msgid "root postexec"
msgstr ""

#: param/loadparm.c:854
msgid "available"
msgstr ""

#: param/loadparm.c:855
msgid "volume"
msgstr ""

#: param/loadparm.c:856
msgid "fstype"
msgstr ""

#: param/loadparm.c:857
msgid "set directory"
msgstr ""

#: param/loadparm.c:858
msgid "source environment"
msgstr ""

#: param/loadparm.c:859
msgid "wide links"
msgstr ""

#: param/loadparm.c:860
msgid "follow symlinks"
msgstr ""

#: param/loadparm.c:861
msgid "dont descend"
msgstr ""

#: param/loadparm.c:862
msgid "magic script"
msgstr ""

#: param/loadparm.c:863
msgid "magic output"
msgstr ""

#: param/loadparm.c:864
msgid "delete readonly"
msgstr ""

#: param/loadparm.c:865
msgid "dos filetimes"
msgstr ""

#: param/loadparm.c:866
msgid "dos filetime resolution"
msgstr ""

#: param/loadparm.c:868
msgid "fake directory create times"
msgstr ""

#: param/loadparm.c:869
msgid "panic action"
msgstr ""
