/* header auto-generated by pidl */

#include <stdint.h>

#include "libcli/util/ntstatus.h"

#ifndef _HEADER_misc
#define _HEADER_misc

struct GUID {
	uint32_t time_low;
	uint16_t time_mid;
	uint16_t time_hi_and_version;
	uint8_t clock_seq[2];
	uint8_t node[6];
}/* [noprint,gensize,public] */;

struct ndr_syntax_id {
	struct GUID uuid;
	uint32_t if_version;
}/* [public] */;

struct policy_handle {
	uint32_t handle_type;
	struct GUID uuid;
}/* [public] */;

enum netr_SchannelType
#ifndef USE_UINT_ENUMS
 {
	SEC_CHAN_NULL=0,
	SEC_CHAN_WKSTA=2,
	SEC_CHAN_DNS_DOMAIN=3,
	SEC_CHAN_DOMAIN=4,
	SEC_CHAN_BDC=6
}
#else
 { __donnot_use_enum_netr_SchannelType=0x7FFFFFFF}
#define SEC_CHAN_NULL ( 0 )
#define SEC_CHAN_WKSTA ( 2 )
#define SEC_CHAN_DNS_DOMAIN ( 3 )
#define SEC_CHAN_DOMAIN ( 4 )
#define SEC_CHAN_BDC ( 6 )
#endif
;

struct KRB5_EDATA_NTSTATUS {
	NTSTATUS ntstatus;
	uint32_t unknown1;
	uint32_t unknown2;
}/* [public] */;

#endif /* _HEADER_misc */
