#!/usr/bin/env python

bld.SAMBA_GENERATOR('param_functions.c',
                    source= '../../script/generate_param.py ../../docs-xml/smbdotconf/parameters.all.xml',
                    target='param_functions.c',
                    group='build_source',
                    rule='${PYTHON} ${SRC[0].abspath(env)} --file ${SRC[1].abspath(env)} --output ${TGT}')

bld.SAMBA_GENERATOR('param_local_h',
                    source= '../../script/mkparamdefs.pl loadparm.c param_functions.c ',
                    target='param_local.h',
                    group='build_source',
                    rule='${PERL} ${SRC[0].abspath(env)} ${SRC[1].abspath(env)} ${SRC[2].abspath(env)} --file ${TGT} --generate-scope=LOCAL')


bld.SAMBA_GENERATOR('s3_param_h',
                    source= ' ../../script/mks3param.pl loadparm.c param_functions.c',
                    target='s3_param.h',
                    group='build_source',
                    rule='${PERL} ${SRC[0].abspath(env)} ${SRC[1].abspath(env)} ${SRC[2].abspath(env)} --file ${TGT}')


bld.SAMBA_GENERATOR('param_global_h',
                    source= '../../script/mkparamdefs.pl loadparm.c param_functions.c',
                    target='param_global.h',
                    group='build_source',
                    rule='${PERL} ${SRC[0].abspath(env)} ${SRC[1].abspath(env)}  ${SRC[2].abspath(env)} --file ${TGT} --generate-scope=GLOBAL')

bld.SAMBA_LIBRARY('server-role',
                  source='loadparm_server_role.c',
                  deps='samba-util',
                  private_library=True)

bld.SAMBA_LIBRARY('samba-hostconfig',
	source='loadparm.c generic.c util.c',
	pc_files='samba-hostconfig.pc',
	vnum='0.0.1',
	deps='DYNCONFIG server-role',
	public_deps='samba-util param_local_h',
	public_headers='param.h',
	autoproto='param_proto.h',
	autoproto_extra_source='param_functions.c'
	)


