################################################
# Start SUBSYSTEM LIBNDR
[LIBRARY::LIBNDR]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION = Network Data Representation Core Library
PUBLIC_HEADERS = ndr/libndr.h
PUBLIC_PROTO_HEADER = ndr/libndr_proto.h
OBJ_FILES = \
		ndr/ndr.o \
		ndr/ndr_basic.o \
		ndr/ndr_string.o \
		ndr/ndr_obfuscate.o \
		ndr/ndr_misc.o
REQUIRED_SUBSYSTEMS = LIBCLI_UTILS LIBTALLOC LIBBASIC
# End SUBSYSTEM LIBNDR
################################################

################################################
# Start SUBSYSTEM NDR_COMPRESSION
[LIBRARY::NDR_COMPRESSION]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION = NDR support for compressed subcontexts
PRIVATE_PROTO_HEADER = ndr/ndr_compression.h
OBJ_FILES = \
		ndr/ndr_compression.o
REQUIRED_SUBSYSTEMS = LIBCOMPRESSION
# End SUBSYSTEM NDR_COMPRESSION
################################################

[SUBSYSTEM::NDR_SECURITY_HELPER]
PRIVATE_PROTO_HEADER = ndr/ndr_sec.h
OBJ_FILES = ndr/ndr_sec_helper.o ndr/ndr_sec.o

[LIBRARY::NDR_SECURITY]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_security.o
PUBLIC_HEADERS = gen_ndr/security.h
REQUIRED_SUBSYSTEMS = NDR_MISC NDR_SECURITY_HELPER

[LIBRARY::NDR_AUDIOSRV]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_audiosrv.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_DNSSERVER]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_dnsserver.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_WINSTATION]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_winstation.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_ECHO]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_echo.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_IRPC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_irpc.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_EXCHANGE]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_exchange.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_DSBACKUP]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_dsbackup.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_EFS]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_efs.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_MISC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_misc.o
PUBLIC_HEADERS = gen_ndr/misc.h gen_ndr/ndr_misc.h
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_ROT]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_rot.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_LSA]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_lsa.o
PUBLIC_HEADERS = gen_ndr/lsa.h
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_DFS]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_dfs.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_DRSUAPI]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_drsuapi.o
REQUIRED_SUBSYSTEMS = LIBNDR NDR_DRSUAPI_PRINT NDR_COMPRESSION NDR_SECURITY

[SUBSYSTEM::NDR_DRSUAPI_PRINT]
PRIVATE_PROTO_HEADER = ndr/ndr_drsuapi.h
OBJ_FILES = ndr/ndr_drsuapi.o

[LIBRARY::NDR_DRSBLOBS]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_drsblobs.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_SASL_HELPERS]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_sasl_helpers.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_POLICYAGENT]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_policyagent.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_UNIXINFO]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_unixinfo.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_SAMR]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_samr.o
PUBLIC_HEADERS = gen_ndr/samr.h
REQUIRED_SUBSYSTEMS = LIBNDR NDR_MISC NDR_LSA NDR_SECURITY

[LIBRARY::NDR_SPOOLSS]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_spoolss.o
REQUIRED_SUBSYSTEMS = LIBNDR NDR_SPOOLSS_BUF

[SUBSYSTEM::NDR_SPOOLSS_BUF]
PRIVATE_PROTO_HEADER = ndr/ndr_spoolss_buf.h
OBJ_FILES = ndr/ndr_spoolss_buf.o

[LIBRARY::NDR_WKSSVC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_wkssvc.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_SRVSVC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_srvsvc.o
REQUIRED_SUBSYSTEMS = LIBNDR NDR_SVCCTL

[LIBRARY::NDR_SVCCTL]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_svcctl.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_ATSVC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_atsvc.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_EVENTLOG]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_eventlog.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_EPMAPPER]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_epmapper.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_DBGIDL]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_dbgidl.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_DSSETUP]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_dssetup.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_MSGSVC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_msgsvc.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_WINS]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_wins.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_WINREG]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_winreg.o
REQUIRED_SUBSYSTEMS = LIBNDR NDR_INITSHUTDOWN

[LIBRARY::NDR_INITSHUTDOWN]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_initshutdown.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_MGMT]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_mgmt.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_PROTECTED_STORAGE]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_protected_storage.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_DCOM]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_dcom.o
REQUIRED_SUBSYSTEMS = LIBNDR NDR_ORPC

[SUBSYSTEM::NDR_ORPC_MANUAL]
PRIVATE_PROTO_HEADER = ndr/ndr_orpc.h
OBJ_FILES = ndr/ndr_orpc.o 

[LIBRARY::NDR_ORPC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_orpc.o
REQUIRED_SUBSYSTEMS = LIBNDR NDR_ORPC_MANUAL

[LIBRARY::NDR_OXIDRESOLVER]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_oxidresolver.o
REQUIRED_SUBSYSTEMS = LIBNDR NDR_ORPC

[LIBRARY::NDR_REMACT]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_remact.o
REQUIRED_SUBSYSTEMS = LIBNDR NDR_ORPC

[LIBRARY::NDR_WZCSVC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_wzcsvc.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_BROWSER]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_browser.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_W32TIME]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_w32time.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_SCERPC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_scerpc.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_NTSVCS]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_ntsvcs.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_NETLOGON]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_netlogon.o
PUBLIC_HEADERS = gen_ndr/netlogon.h
REQUIRED_SUBSYSTEMS = LIBNDR NDR_SAMR NDR_LSA

[LIBRARY::NDR_TRKWKS]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_trkwks.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_KEYSVC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_keysvc.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_KRB5PAC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_krb5pac.o
REQUIRED_SUBSYSTEMS = LIBNDR NDR_KRB5PAC_UTIL NDR_NETLOGON

[SUBSYSTEM::NDR_KRB5PAC_UTIL]
PRIVATE_PROTO_HEADER = ndr/ndr_krb5pac.h
OBJ_FILES = ndr/ndr_krb5pac.o

[LIBRARY::NDR_XATTR]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_xattr.o
REQUIRED_SUBSYSTEMS = LIBNDR NDR_SECURITY

[LIBRARY::NDR_OPENDB]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_opendb.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_SCHANNEL]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_schannel.o
REQUIRED_SUBSYSTEMS = LIBNDR

[LIBRARY::NDR_NBT]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_nbt.o
REQUIRED_SUBSYSTEMS = LIBNDR NDR_MISC NDR_NBT_BUF NDR_SVCCTL

[LIBRARY::NDR_WINSREPL]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_winsrepl.o
REQUIRED_SUBSYSTEMS = LIBNDR NDR_NBT

librpc/gen_ndr/tables.c: $(IDL_NDR_HEADER_FILES)
	@$(PERL) $(srcdir)/librpc/tables.pl --output=librpc/gen_ndr/tables.c $(IDL_NDR_HEADER_FILES)

[SUBSYSTEM::NDR_IFACE_TABLE]
OBJ_FILES = gen_ndr/tables.o

[LIBRARY::NDR_TABLE]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = rpc/table.o 
PRIVATE_PROTO_HEADER = rpc/dcerpc_table.h
REQUIRED_SUBSYSTEMS = \
	NDR_IFACE_TABLE \
	NDR_AUDIOSRV NDR_ECHO NDR_DCERPC NDR_EXCHANGE \
	NDR_DSBACKUP NDR_EFS NDR_MISC NDR_LSA NDR_DFS NDR_DRSUAPI \
	NDR_POLICYAGENT NDR_UNIXINFO NDR_SAMR NDR_SPOOLSS NDR_WKSSVC NDR_SRVSVC NDR_ATSVC \
	NDR_EVENTLOG NDR_EPMAPPER NDR_DBGIDL NDR_DSSETUP NDR_MSGSVC NDR_WINS \
	NDR_WINREG NDR_MGMT NDR_PROTECTED_STORAGE NDR_OXIDRESOLVER \
	NDR_REMACT NDR_WZCSVC NDR_BROWSER NDR_W32TIME NDR_SCERPC NDR_NTSVCS \
	NDR_NETLOGON NDR_TRKWKS NDR_KEYSVC NDR_KRB5PAC NDR_XATTR NDR_SCHANNEL \
	NDR_ROT NDR_DRSBLOBS NDR_SVCCTL NDR_NBT NDR_WINSREPL NDR_SECURITY \
	NDR_INITSHUTDOWN NDR_DNSSERVER NDR_WINSTATION NDR_IRPC NDR_DCOM NDR_OPENDB \
	NDR_SASL_HELPERS

[LIBRARY::RPC_NDR_ROT]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_rot_c.o
REQUIRED_SUBSYSTEMS = NDR_ROT dcerpc

[LIBRARY::RPC_NDR_AUDIOSRV]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_audiosrv_c.o
REQUIRED_SUBSYSTEMS = NDR_AUDIOSRV dcerpc

[LIBRARY::RPC_NDR_ECHO]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_echo_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_ECHO

[LIBRARY::RPC_NDR_EXCHANGE]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_exchange_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_EXCHANGE

[LIBRARY::RPC_NDR_DSBACKUP]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_dsbackup_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_DSBACKUP

[LIBRARY::RPC_NDR_EFS]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_efs_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_EFS

[LIBRARY::RPC_NDR_LSA]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_lsa_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_LSA

[LIBRARY::RPC_NDR_DFS]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_dfs_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_DFS

[LIBRARY::RPC_NDR_DRSUAPI]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_drsuapi_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_DRSUAPI

[LIBRARY::RPC_NDR_POLICYAGENT]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_policyagent_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_POLICYAGENT

[LIBRARY::RPC_NDR_UNIXINFO]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_unixinfo_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_UNIXINFO

[LIBRARY::RPC_NDR_SAMR]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_samr_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_SAMR

[LIBRARY::RPC_NDR_SPOOLSS]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_spoolss_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_SPOOLSS

[LIBRARY::RPC_NDR_WKSSVC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_wkssvc_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_WKSSVC

[LIBRARY::RPC_NDR_SRVSVC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_srvsvc_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_SRVSVC

[LIBRARY::RPC_NDR_SVCCTL]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_svcctl_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_SVCCTL

[LIBRARY::RPC_NDR_ATSVC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_atsvc_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_ATSVC

[LIBRARY::RPC_NDR_EVENTLOG]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_eventlog_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_EVENTLOG

[LIBRARY::RPC_NDR_EPMAPPER]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_epmapper_c.o
REQUIRED_SUBSYSTEMS = NDR_EPMAPPER

[LIBRARY::RPC_NDR_DBGIDL]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_dbgidl_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_DBGIDL

[LIBRARY::RPC_NDR_DSSETUP]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_dssetup_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_DSSETUP

[LIBRARY::RPC_NDR_MSGSVC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_msgsvc_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_MSGSVC

[LIBRARY::RPC_NDR_WINS]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_wins_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_WINS

[LIBRARY::RPC_NDR_WINREG]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_winreg_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_WINREG

[LIBRARY::RPC_NDR_INITSHUTDOWN]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_initshutdown_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_INITSHUTDOWN

[LIBRARY::RPC_NDR_MGMT]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_mgmt_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_MGMT

[LIBRARY::RPC_NDR_PROTECTED_STORAGE]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_protected_storage_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_PROTECTED_STORAGE

[LIBRARY::DCOM_PROXY_DCOM]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_dcom_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_DCOM

[LIBRARY::RPC_NDR_OXIDRESOLVER]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_oxidresolver_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_OXIDRESOLVER

[LIBRARY::RPC_NDR_REMACT]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_remact_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_REMACT

[LIBRARY::RPC_NDR_WZCSVC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_wzcsvc_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_WZCSVC

[LIBRARY::RPC_NDR_W32TIME]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_w32time_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_W32TIME

[LIBRARY::RPC_NDR_SCERPC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_scerpc_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_SCERPC

[LIBRARY::RPC_NDR_NTSVCS]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_ntsvcs_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_NTSVCS

[LIBRARY::RPC_NDR_NETLOGON]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_netlogon_c.o
REQUIRED_SUBSYSTEMS = NDR_NETLOGON

[LIBRARY::RPC_NDR_TRKWKS]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_trkwks_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_TRKWKS

[LIBRARY::RPC_NDR_KEYSVC]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION =
OBJ_FILES = gen_ndr/ndr_keysvc_c.o
REQUIRED_SUBSYSTEMS = dcerpc NDR_KEYSVC

[SUBSYSTEM::NDR_DCERPC]
OBJ_FILES = gen_ndr/ndr_dcerpc.o
REQUIRED_SUBSYSTEMS = LIBNDR NDR_MISC
PUBLIC_HEADERS = gen_ndr/dcerpc.h gen_ndr/ndr_dcerpc.h

################################################
# Start SUBSYSTEM dcerpc
[LIBRARY::dcerpc]
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION = DCE/RPC client library
PUBLIC_HEADERS = rpc/dcerpc.h
PUBLIC_PROTO_HEADER = rpc/dcerpc_proto.h
OBJ_FILES = \
		rpc/dcerpc.o \
		rpc/dcerpc_auth.o \
		rpc/dcerpc_schannel.o \
		rpc/dcerpc_util.o \
		rpc/dcerpc_error.o \
		rpc/dcerpc_smb.o \
		rpc/dcerpc_smb2.o \
		rpc/dcerpc_sock.o \
		rpc/dcerpc_connect.o
REQUIRED_SUBSYSTEMS = \
		SOCKET LIBSMB \
		LIBNDR NDR_DCERPC \
		RPC_NDR_EPMAPPER \
		NDR_SCHANNEL RPC_NDR_NETLOGON \
		gensec
# End SUBSYSTEM dcerpc
################################################

[MODULE::RPC_EJS_ECHO]
INIT_FUNCTION = ejs_init_rpcecho
OBJ_FILES = gen_ndr/ndr_echo_ejs.o
SUBSYSTEM = smbcalls
REQUIRED_SUBSYSTEMS = dcerpc NDR_ECHO EJSRPC

[MODULE::RPC_EJS_MISC]
INIT_FUNCTION = ejs_init_misc
OBJ_FILES = gen_ndr/ndr_misc_ejs.o
SUBSYSTEM = smbcalls
REQUIRED_SUBSYSTEMS = dcerpc NDR_MISC EJSRPC

[MODULE::RPC_EJS_SAMR]
INIT_FUNCTION = ejs_init_samr
OBJ_FILES = gen_ndr/ndr_samr_ejs.o
SUBSYSTEM = smbcalls
REQUIRED_SUBSYSTEMS = dcerpc NDR_SAMR EJSRPC

[MODULE::RPC_EJS_SECURITY]
INIT_FUNCTION = ejs_init_security
OBJ_FILES = gen_ndr/ndr_security_ejs.o
SUBSYSTEM = smbcalls
REQUIRED_SUBSYSTEMS = dcerpc NDR_SECURITY EJSRPC

[MODULE::RPC_EJS_LSA]
INIT_FUNCTION = ejs_init_lsarpc
OBJ_FILES = gen_ndr/ndr_lsa_ejs.o
SUBSYSTEM = smbcalls
REQUIRED_SUBSYSTEMS = dcerpc NDR_LSA EJSRPC

[MODULE::RPC_EJS_DFS]
INIT_FUNCTION = ejs_init_netdfs
OBJ_FILES = gen_ndr/ndr_dfs_ejs.o
SUBSYSTEM = smbcalls
REQUIRED_SUBSYSTEMS = dcerpc NDR_DFS EJSRPC

[MODULE::RPC_EJS_DRSUAPI]
INIT_FUNCTION = ejs_init_drsuapi
OBJ_FILES = gen_ndr/ndr_drsuapi_ejs.o
SUBSYSTEM = smbcalls
REQUIRED_SUBSYSTEMS = dcerpc NDR_DRSUAPI EJSRPC

[MODULE::RPC_EJS_SPOOLSS]
INIT_FUNCTION = ejs_init_spoolss
OBJ_FILES = gen_ndr/ndr_spoolss_ejs.o
SUBSYSTEM = smbcalls
ENABLE = NO
REQUIRED_SUBSYSTEMS = dcerpc NDR_SPOOLSS EJSRPC

[MODULE::RPC_EJS_WKSSVC]
INIT_FUNCTION = ejs_init_wkssvc
OBJ_FILES = gen_ndr/ndr_wkssvc_ejs.o
SUBSYSTEM = smbcalls
REQUIRED_SUBSYSTEMS = dcerpc NDR_WKSSVC EJSRPC

[MODULE::RPC_EJS_SRVSVC]
INIT_FUNCTION = ejs_init_srvsvc
OBJ_FILES = gen_ndr/ndr_srvsvc_ejs.o
SUBSYSTEM = smbcalls
REQUIRED_SUBSYSTEMS = dcerpc NDR_SRVSVC EJSRPC

[MODULE::RPC_EJS_EVENTLOG]
INIT_FUNCTION = ejs_init_eventlog
OBJ_FILES = gen_ndr/ndr_eventlog_ejs.o
SUBSYSTEM = smbcalls
REQUIRED_SUBSYSTEMS = dcerpc NDR_EVENTLOG EJSRPC

[MODULE::RPC_EJS_WINREG]
INIT_FUNCTION = ejs_init_winreg
OBJ_FILES = gen_ndr/ndr_winreg_ejs.o
SUBSYSTEM = smbcalls
REQUIRED_SUBSYSTEMS = dcerpc NDR_WINREG EJSRPC

[MODULE::RPC_EJS_INITSHUTDOWN]
INIT_FUNCTION = ejs_init_initshutdown
OBJ_FILES = gen_ndr/ndr_initshutdown_ejs.o
SUBSYSTEM = smbcalls
REQUIRED_SUBSYSTEMS = dcerpc NDR_INITSHUTDOWN EJSRPC

[MODULE::RPC_EJS_NETLOGON]
INIT_FUNCTION = ejs_init_netlogon
OBJ_FILES = gen_ndr/ndr_netlogon_ejs.o
SUBSYSTEM = smbcalls
REQUIRED_SUBSYSTEMS = dcerpc NDR_NETLOGON EJSRPC

[MODULE::RPC_EJS_SVCCTL]
INIT_FUNCTION = ejs_init_svcctl
OBJ_FILES = gen_ndr/ndr_svcctl_ejs.o
SUBSYSTEM = smbcalls
REQUIRED_SUBSYSTEMS = dcerpc NDR_SVCCTL EJSRPC

[MODULE::RPC_EJS_IRPC]
INIT_FUNCTION = ejs_init_irpc
OBJ_FILES = gen_ndr/ndr_irpc_ejs.o
SUBSYSTEM = smbcalls
REQUIRED_SUBSYSTEMS = dcerpc NDR_IRPC EJSRPC
