#include "idl_types.h"

import "misc.idl";
import "security.idl";
import "frsrpc.idl";
import "bkupblobs.idl";
import "fscc.idl";
/* frs related blobs decoding. Used for debug/dump of FRS related structures */

[
	pointer_default(unique),
	helpstring("bkup blobs"),
	uuid("12345777-1234-abcd-0001-00000004")
]

interface frsblobs
{

	void  decode_nt_backup_file(
		[in] bkup_NTBackupFile file
	);

	void decode_frsrpc_StageHeader(
		[in] frsrpc_StageHeader header,
		[in] bkup_NTBackupFile data
	);

	void decode_FileNetworkOpenInformation(
		[in] fscc_FileNetworkOpenInformation data
	);
}
