#include "idl_types.h"
/*
  miscellaneous IDL structures
*/

import "netlogon.idl";

[
	pointer_default(unique)
]
interface named_pipe_auth
{
	const char *NAMED_PIPE_AUTH_MAGIC = "NPAM";

	typedef [switch_type(uint32)] union {
		[case(0)] ;/* anonymous */
		[case(1)] netr_SamInfo3 info1;
	} named_pipe_auth_req_info;

	typedef [public,gensize] struct {
		[flag(NDR_BIG_ENDIAN),
		 value(ndr_size_named_pipe_auth_req(r,ndr->iconv_convenience,ndr->flags)-4)]
			uint32 length;
		[charset(DOS),value(NAMED_PIPE_AUTH_MAGIC)] uint8 magic[4];
		uint32 level;
		[switch_is(level)] named_pipe_auth_req_info info;
	} named_pipe_auth_req;

	typedef [switch_type(uint32)] union {
		[case(0)] ;
		[case(1)] ;
	} named_pipe_auth_rep_info;

	typedef [public,gensize] struct {
		[flag(NDR_BIG_ENDIAN),
		 value(ndr_size_named_pipe_auth_rep(r,ndr->iconv_convenience,ndr->flags)-4)]
			uint32 length;
		[charset(DOS),value(NAMED_PIPE_AUTH_MAGIC)] uint8 magic[4];
		uint32 level;
		[switch_is(level)] named_pipe_auth_rep_info info;
		NTSTATUS status;
	} named_pipe_auth_rep;
}

