#!/usr/bin/env python

bld.SAMBA_PIDL_LIST('PIDL',
                    '''atsvc.idl drsuapi.idl epmapper.idl initshutdown.idl
                       misc.idl ntlmssp.idl protected_storage.idl schannel.idl trkwks.idl
                       audiosrv.idl dfsblobs.idl dsbackup.idl eventlog.idl keysvc.idl
                       msgsvc.idl ntsvcs.idl remact.idl security.idl unixinfo.idl wzcsvc.idl
                       browser.idl dfs.idl dssetup.idl frsapi.idl krb5pac.idl
                       named_pipe_auth.idl orpc.idl rot.idl spoolss.idl w32time.idl xattr.idl
                       dbgidl.idl dnsserver.idl echo.idl frsrpc.idl lsa.idl nbt.idl
                       oxidresolver.idl samr.idl srvsvc.idl winreg.idl dcerpc.idl
                       drsblobs.idl efs.idl frstrans.idl mgmt.idl netlogon.idl
                       policyagent.idl scerpc.idl svcctl.idl wkssvc.idl''',
                    options='--header --ndr-parser --samba3-ndr-server --samba3-ndr-client --server --client --python',
                    output_dir='../gen_ndr')

bld.SAMBA_PIDL_LIST('PIDL',
                    'wmi.idl dcom.idl',
                    options='--header --ndr-parser --samba3-ndr-server --samba3-ndr-client --server --client --python --dcom-proxy --com-header',
                    output_dir='../gen_ndr')

bld.SAMBA_PIDL_LIST('PIDL',
                    'rap.idl idmap.idl',
                    options='--header --ndr-parser',
                    output_dir='../gen_ndr')
