# Unix SMB/CIFS implementation.
#
# Enums and flag types for models.
#
# Copyright (C) Catalyst.Net Ltd. 2023
#
# Written by Rob van der Linde <rob@catalyst.net.nz>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from enum import IntFlag

from samba.dsdb import (
    ATYPE_SECURITY_GLOBAL_GROUP,
    ATYPE_SECURITY_LOCAL_GROUP,
    ATYPE_NORMAL_ACCOUNT,
    ATYPE_DISTRIBUTION_GLOBAL_GROUP,
    ATYPE_DISTRIBUTION_LOCAL_GROUP,
    ATYPE_WORKSTATION_TRUST,
    ATYPE_INTERDOMAIN_TRUST,
    SYSTEM_FLAG_CR_NTDS_NC,
    SYSTEM_FLAG_CR_NTDS_DOMAIN,
    SYSTEM_FLAG_CR_NTDS_NOT_GC_REPLICATED,
    SYSTEM_FLAG_ATTR_IS_RDN,
    SYSTEM_FLAG_CONFIG_ALLOW_LIMITED_MOVE,
    SYSTEM_FLAG_CONFIG_ALLOW_MOVE,
    SYSTEM_FLAG_CONFIG_ALLOW_RENAME,
    SYSTEM_FLAG_DISALLOW_DELETE,
    SYSTEM_FLAG_DISALLOW_MOVE_ON_DELETE,
    SYSTEM_FLAG_DOMAIN_DISALLOW_MOVE,
    SYSTEM_FLAG_DOMAIN_DISALLOW_RENAME
)


class AccountType(IntFlag):
    SECURITY_GLOBAL_GROUP = ATYPE_SECURITY_GLOBAL_GROUP
    SECURITY_LOCAL_GROUP = ATYPE_SECURITY_LOCAL_GROUP
    NORMAL_ACCOUNT = ATYPE_NORMAL_ACCOUNT
    DISTRIBUTION_GLOBAL_GROUP = ATYPE_DISTRIBUTION_GLOBAL_GROUP
    DISTRIBUTION_LOCAL_GROUP = ATYPE_DISTRIBUTION_LOCAL_GROUP
    WORKSTATION_TRUST = ATYPE_WORKSTATION_TRUST
    INTERDOMAIN_TRUST = ATYPE_INTERDOMAIN_TRUST


class SystemFlags(IntFlag):
    CR_NTDS_NC = SYSTEM_FLAG_CR_NTDS_NC
    CR_NTDS_DOMAIN = SYSTEM_FLAG_CR_NTDS_DOMAIN
    CR_NTDS_NOT_GC_REPLICATED = SYSTEM_FLAG_CR_NTDS_NOT_GC_REPLICATED
    ATTR_IS_RDN = SYSTEM_FLAG_ATTR_IS_RDN
    CONFIG_ALLOW_LIMITED_MOVE = SYSTEM_FLAG_CONFIG_ALLOW_LIMITED_MOVE
    CONFIG_ALLOW_MOVE = SYSTEM_FLAG_CONFIG_ALLOW_MOVE
    CONFIG_ALLOW_RENAME = SYSTEM_FLAG_CONFIG_ALLOW_RENAME
    DISALLOW_DELETE = SYSTEM_FLAG_DISALLOW_DELETE
    DISALLOW_MOVE_ON_DELETE = SYSTEM_FLAG_DISALLOW_MOVE_ON_DELETE
    DOMAIN_DISALLOW_MOVE = SYSTEM_FLAG_DOMAIN_DISALLOW_MOVE
    DOMAIN_DISALLOW_RENAME = SYSTEM_FLAG_DOMAIN_DISALLOW_RENAME
