/*
  dnsserver interface definition
*/

#include "idl_types.h"

[ uuid("50abc2a4-574d-40b3-9d66-ee4fd5fba076"),
  version(5.0),
  pointer_default(unique),
  pointer_default_top(unique),
  helpstring("DNS Server")
] interface dnsserver
{
	void foo();
}
