[
	pointer_default(unique)
]
interface server_id
{
	/* id used to identify a endpoint, possibly in a cluster */
	typedef [public] struct {
		hyper pid;
		uint32 task_id;
		uint32 vnn;
		udlong unique_id;
	} server_id;
}
