/*
  winbind IRPC interface
*/

#include "idl_types.h"

import "netlogon.idl";

[
  uuid("b875118e-47a3-4210-b5f7-c240cce656b2"),
  version(1.0),
  pointer_default(unique)
]
interface winbind
{
	typedef [switch_type(uint16)] union netr_LogonLevel netr_LogonLevel;
	typedef [switch_type(uint16)] union netr_Validation netr_Validation;

	/*
	 * do a netr_LogonSamLogon() against the right DC
	 */
	NTSTATUS winbind_SamLogon(
		[in]  uint16 logon_level,
		[in]  [switch_is(logon_level)] netr_LogonLevel logon,
		[in]  uint16 validation_level,
		[out] [switch_is(validation_level)] netr_Validation validation,
		[out] uint8 authoritative
	);

	NTSTATUS winbind_DsrUpdateReadOnlyServerDnsRecords(
		[in,unique] [string,charset(UTF16)] uint16 *site_name,
		[in] uint32 dns_ttl,
		[in,out,ref] NL_DNS_NAME_INFO_ARRAY *dns_names
		);
}
