Import('hostenv')


hostenv.StaticLibrary('modules/timestamps.c')
hostenv.StaticLibrary('modules/rdn_name.c')
hostenv.StaticLibrary('modules/schema.c')
hostenv.StaticLibrary('ldb_ildap/ldb_ildap.c')
hostenv.StaticLibrary('modules/ldb_map.c')
hostenv.StaticLibrary('ldb_sqlite3/ldb_sqlite3.c')
hostenv.StaticLibrary('ldb_tdb',
	['ldb_tdb/ldb_tdb.c','ldb_tdb/ldb_search.c','ldb_tdb/ldb_pack.c',
	 'ldb_tdb/ldb_index.c','ldb_tdb/ldb_cache.c','ldb_tdb/ldb_tdb_wrap.c'])

hostenv.StaticLibrary('ldb', 
	['common/ldb.c','common/ldb_ldif.c','common/ldb_parse.c',
	 'common/ldb_parse.c','common/ldb_msg.c','common/ldb_utf8.c',
	 'common/ldb_debug.c','common/ldb_modules.c','common/ldb_match.c',
	 'common/attrib_handlers.c','common/ldb_dn.c'])

hostenv.StaticLibrary('samba/ldif_handlers.c')
hostenv.StaticLibrary('ldb_cmdline', 'tools/cmdline.c')

hostenv.Program('ldbadd',['tools/ldbadd.c'])
hostenv.Program('ldbdel',['tools/ldbdel.c'])
hostenv.Program('ldbmodify',['tools/ldbmodify.c'])
hostenv.Program('ldbsearch',['tools/ldbsearch.c'])
hostenv.Program('ldbrename',['tools/ldbrename.c'])
hostenv.Program('ldbtest',['tools/ldbtest.c'])
hostenv.Program('oLschema2ldif',['tools/oLschema2ldif.c'])
