#!/usr/bin/env python

names = ['testsmbc',
         'testacl',
         'testacl2',
         'testacl3',
         'testbrowse',
         'testbrowse2',
         'testnotify',
         'teststat',
         'teststat2',
         'teststat3',
         'teststatvfs',
         'testfstatvfs',
         'testtruncate',
         'testchmod',
         'testutime',
         'testread',
         'testwrite',
         'testctx']

for name in names:
    bld.SAMBA_BINARY(name,
                     source='%s.c' % name,
                     deps='popt smbclient',
                     install=False)
