#!/bin/sh

usage ()
{
    echo "usage: df -kP <mount-point>"
    exit 1
}

if [ "$1" != "-kP" ] ; then
    usage
fi

shift
if [ -z "$1" ] ; then
    usage
fi

fs="$1"

# Anything starting with CTDB_DBDIR gets canonicalised to CTDB_DBDIR.
# This helps with the setting of defaults for the filesystem checks.
if [ "${fs#${CTDB_DBDIR}}" != "$fs" ] ; then
    fs="$CTDB_DBDIR"
fi

# A default, for tests that don't initialise this...
if [ -z "$FAKE_FS_USE" ] ; then
    FAKE_FS_USE=10
fi

echo "Filesystem             1024-blocks      Used Available Capacity Mounted on"

blocks="1000000"
used=$(($blocks * $FAKE_FS_USE / 100))
available=$(($blocks - $used))

printf "%-36s %10d %10d %10d %10d%% %s\n" \
       "/dev/sda1" "$blocks" "$used" "$available" "$FAKE_FS_USE" "$fs"
