#!/usr/bin/env python

from samba_utils import *

TDB_LIB_SRC = '''lib/util_tdb.c ../lib/util/util_tdb.c
          lib/dbwrap.c lib/dbwrap_tdb.c
          lib/dbwrap_ctdb.c
          lib/g_lock.c
          lib/dbwrap_rbt.c'''

TDB_VALIDATE_SRC = '''lib/tdb_validate.c'''

SMBLDAP = bld.env.SMBLDAP or ""
SMBLDAPUTIL = bld.env.SMBLDAPUTIL or ""

SMBLDAP_SRC = '''${SMBLDAP} ${SMBLDAPUTIL}'''

VERSION_SRC = '''lib/version.c'''

WBCOMMON_SRC = '../nsswitch/wb_common.c'

AFS_SRC = 'lib/afs.c'

AFS_SETTOKEN_SRC = 'lib/afs_settoken.c'

AVAHI_SRC = 'lib/avahi.c smbd/avahi_register.c'

SERVER_MUTEX_SRC = 'lib/server_mutex.c'

PASSCHANGE_SRC = '''libsmb/passchange.c'''

LIBNDR_DRSUAPI_SRC = '''../librpc/ndr/ndr_drsuapi.c
                     ../librpc/ndr/ndr_compression.c
                     ../librpc/gen_ndr/ndr_drsuapi.c
                     ../librpc/ndr/ndr_drsblobs.c
                     ../librpc/gen_ndr/ndr_drsblobs.c'''

COMPRESSION_SRC = '../lib/compression/mszip.c ../lib/compression/lzxpress.c'

DRSUAPI_SRC = '''${LIBNDR_DRSUAPI_SRC}
              ${COMPRESSION_SRC}'''

LIBNDR_NTLMSSP_SRC = '''../librpc/gen_ndr/ndr_ntlmssp.c
                     ../librpc/ndr/ndr_ntlmssp.c'''

LIBNDR_SRC = '''../librpc/ndr/ndr_basic.c
             ../librpc/ndr/ndr.c
             ../librpc/ndr/ndr_misc.c
             ../librpc/gen_ndr/ndr_misc.c
             ../librpc/gen_ndr/ndr_security.c
             ../librpc/ndr/ndr_sec_helper.c
             ../librpc/ndr/ndr_string.c
             ../librpc/ndr/uuid.c
             librpc/ndr/util.c
             ../librpc/gen_ndr/ndr_dcerpc.c'''

RPCCLIENT_NDR_SRC = '''rpc_client/ndr.c'''

LIBNDR_GEN_SRC0 = '''../librpc/gen_ndr/ndr_samr.c
                  ../librpc/gen_ndr/ndr_lsa.c'''

LIBNDR_NETLOGON_SRC = '''../librpc/gen_ndr/ndr_netlogon.c
                  ../librpc/ndr/ndr_netlogon.c'''

LIBNDR_SCHANNEL_SRC = '''../librpc/gen_ndr/ndr_schannel.c
                  ../librpc/ndr/ndr_schannel.c'''

LIBNDR_SPOOLSS_SRC = '''../librpc/gen_ndr/ndr_spoolss.c
                  ../librpc/ndr/ndr_spoolss_buf.c'''

LIBNDR_XATTR_SRC = '''../librpc/gen_ndr/ndr_xattr.c
                  ../librpc/ndr/ndr_xattr.c'''

LIBNDR_GEN_SRC = '''../librpc/gen_ndr/ndr_wkssvc.c
                 ${LIBNDR_GEN_SRC0}
                 ../librpc/gen_ndr/ndr_dfs.c
                 ../librpc/gen_ndr/ndr_echo.c
                 ../librpc/gen_ndr/ndr_winreg.c
                 ../librpc/gen_ndr/ndr_initshutdown.c
                 ../librpc/gen_ndr/ndr_srvsvc.c
                 ../librpc/gen_ndr/ndr_eventlog.c
                 ${LIBNDR_NETLOGON_SRC}
                 ../librpc/gen_ndr/ndr_dssetup.c
                 librpc/gen_ndr/ndr_notify.c
                 ${LIBNDR_XATTR_SRC}
                 ../librpc/gen_ndr/ndr_epmapper.c
                 ../librpc/gen_ndr/ndr_named_pipe_auth.c
                 ../librpc/gen_ndr/ndr_ntsvcs.c
                 ${LIBNDR_SPOOLSS_SRC}'''

# this includes only the low level parse code, not stuff
# that requires knowledge of security contexts
REG_PARSE_PRS_SRC = '''registry/reg_parse_prs.c'''

RPC_PARSE_SRC2 = '''rpc_client/init_netlogon.c
                 rpc_client/init_lsa.c'''

LIBREPLACE_SRC = '''${LIBREPLACE_SRCS}'''

SOCKET_WRAPPER_SRC = '''${SOCKET_WRAPPER_SRCS}'''
NSS_WRAPPER_SRC = '''${NSS_WRAPPER_SRCS}'''

LIBSAMBAUTIL_SRC = '''
                ${LIBREPLACE_SRC}
                ${SOCKET_WRAPPER_SRC}
                ${NSS_WRAPPER_SRC}'''

UTIL_SRC = '''../lib/util/rbtree.c ../lib/util/signal.c ../lib/util/time.c
                   ../lib/util/xfile.c ../lib/util/util_strlist.c
                   ../lib/util/util_file.c ../lib/util/data_blob.c
                   ../lib/util/util.c ../lib/util/fsusage.c
                   ../lib/util/params.c ../lib/util/talloc_stack.c
                   ../lib/util/genrand.c ../lib/util/util_net.c
                   ../lib/util/become_daemon.c ../lib/util/system.c
                   ../lib/util/tevent_unix.c ../lib/util/tevent_ntstatus.c
                   ../lib/util/smb_threads.c ../lib/util/util_id.c
                   ../lib/util/blocking.c ../lib/util/rfc1738.c '''

CRYPTO_SRC = '''../lib/crypto/crc32.c ../lib/crypto/md5.c
                         ../lib/crypto/hmacmd5.c ../lib/crypto/arcfour.c
                         ../lib/crypto/md4.c
                         ../lib/crypto/sha256.c ../lib/crypto/hmacsha256.c
                         ../lib/crypto/aes.c ../lib/crypto/rijndael-alg-fst.c'''

LIBTEVENT_SRC0 = ''

PTHREADPOOL_SRC = ''

LIBREPLACE_SRCS = ''

SOCKET_WRAPPER_SRCS = ''

NSS_WRAPPER_SRCS = ''

ZLIB_SRCS = ''

LIB_SRC = '''${LIBSAMBAUTIL_SRC} ${UTIL_SRC} ${CRYPTO_SRC}
          lib/messages.c librpc/gen_ndr/ndr_messaging.c lib/messages_local.c
          lib/messages_ctdbd.c lib/packet.c lib/ctdbd_conn.c
          lib/interfaces.c lib/memcache.c
          lib/talloc_dict.c
          lib/util_sconn.c
          lib/serverid.c
          lib/util_transfer_file.c ../lib/async_req/async_sock.c
          ${TDB_LIB_SRC}
          ${VERSION_SRC} lib/charcnv.c lib/debug.c lib/fault.c
          lib/interface.c lib/pidfile.c
          lib/system.c lib/sendfile.c lib/recvfile.c lib/time.c
          lib/username.c
          ../libds/common/flag_mapping.c
          lib/util_pw.c lib/access.c lib/smbrun.c
          lib/bitmap.c lib/dprintf.c ${UTIL_REG_SRC}
          lib/wins_srv.c
          lib/util_str.c lib/clobber.c lib/util_sid.c lib/util_uuid.c
          lib/util_unistr.c lib/util_file.c lib/util_names.c
          lib/util.c lib/util_sock.c lib/sock_exec.c lib/util_sec.c
          lib/substitute.c lib/dbwrap_util.c
          lib/ms_fnmatch.c lib/select.c lib/errmap_unix.c
          lib/tallocmsg.c lib/dmallocmsg.c
          libsmb/clisigning.c libsmb/smb_signing.c
          lib/iconv.c lib/pam_errors.c intl/lang_tdb.c
          lib/conn_tdb.c lib/adt_tree.c lib/gencache.c
          lib/sessionid_tdb.c
          lib/module.c lib/events.c ${LIBTEVENT_SRC0}
          lib/server_contexts.c
          lib/ldap_escape.c ${CHARSET_STATIC}
          lib/secdesc.c lib/util_seaccess.c ../libcli/security/secace.c
          ../libcli/security/sddl.c
          ../libcli/security/secacl.c ${PTHREADPOOL_SRC}
          lib/fncall.c
          libads/krb5_errs.c lib/system_smbd.c lib/audit.c ${LIBNDR_SRC}
          lib/file_id.c lib/idmap_cache.c
          ../libcli/security/dom_sid.c ../libcli/security/security_descriptor.c'''

LIB_DUMMY_SRC = '''lib/dummysmbd.c lib/dummyroot.c'''
LIB_NONSMBD_SRC = '''${LIB_DUMMY_SRC}'''

READLINE_SRC = '''lib/readline.c'''

POPT_LIB_SRC = '''lib/popt_common.c'''

PARAM_WITHOUT_REG_SRC = '''param/loadparm.c param/util.c param/loadparm_server_role.c
                           lib/sharesec.c lib/ldap_debug_handler.c'''
PARAM_REG_ADD_SRC = '''${REG_SMBCONF_SRC} ${LIBSMBCONF_SRC} ${PRIVILEGES_BASIC_SRC}'''
PARAM_SRC = '''${PARAM_REG_ADD_SRC}'''

KRBCLIENT_SRC = '''libads/kerberos.c libads/ads_status.c'''

LIBADDNS_SRC0 = '''libaddns/dnsrecord.c libaddns/dnsutils.c  libaddns/dnssock.c
               libaddns/dnsgss.c libaddns/dnsmarshall.c'''
LIBADDNS_SRC = '''${LIBADDNS_SRC0} ${SOCKET_WRAPPER_SRC}'''

GPEXT_STATIC = ''
GPEXT_REGISTRY_SRC = 'libgpo/gpext/registry.c'
GPEXT_SCRIPTS_SRC = 'libgpo/gpext/scripts.c'
GPEXT_SECURITY_SRC = 'libgpo/gpext/security.c'

GPEXT_SRC = '''../libgpo/gpext/gpext.c ${GPEXT_STATIC}'''

LIBGPO_SRC0 = '''../libgpo/gpo_ldap.c ../libgpo/gpo_ini.c ../libgpo/gpo_util.c
              ../libgpo/gpo_fetch.c libgpo/gpo_filesync.c ../libgpo/gpo_sec.c
              libgpo/gpo_reg.c
              ${GPEXT_SRC}'''
LIBGPO_SRC = '''${LIBGPO_SRC0}'''

LIBADS_SRC = '''libads/ldap.c libads/ldap_printer.c
             libads/sasl.c libads/sasl_wrapping.c
             libads/krb5_setpw.c libads/ldap_user.c
             libads/ads_struct.c libads/kerberos_keytab.c
             libads/disp_sec.c libads/ads_utils.c libads/ldap_utils.c
             libads/ldap_schema.c libads/util.c libads/ndr.c'''

LIBADS_SERVER_SRC = '''libads/kerberos_verify.c libads/authdata.c
                    ../librpc/ndr/ndr_krb5pac.c
                    ../librpc/gen_ndr/ndr_krb5pac.c'''

LIBNBT_SRC = '''../libcli/nbt/nbtname.c
             ../libcli/netlogon.c
             ../libcli/ndr_netlogon.c
             ../librpc/gen_ndr/ndr_nbt.c
             ../librpc/gen_ndr/ndr_svcctl.c
             ../librpc/ndr/ndr_svcctl.c'''

LIBNMB_SRC = '''libsmb/unexpected.c libsmb/namecache.c libsmb/nmblib.c
             libsmb/namequery.c ../libcli/nbt/lmhosts.c libsmb/conncache.c
             libads/dns.c libads/sitename_cache.c'''

NTERR_SRC = '''libsmb/nterr.c libsmb/smberr.c'''
DOSERR_SRC = '../libcli/util/doserr.c'
ERRORMAP_SRC = 'libsmb/errormap.c'
DCE_RPC_ERR_SRC = '../librpc/rpc/dcerpc_error.c'

LIBSMB_ERR_SRC0 = '''${NTERR_SRC} ${DOSERR_SRC} ${ERRORMAP_SRC} ${DCE_RPC_ERR_SRC}'''

LIBSMB_ERR_SRC1 = '''../libcli/auth/smbdes.c ../libcli/auth/smbencrypt.c ../libcli/auth/msrpc_parse.c ../libcli/auth/session.c'''

LIBSMB_ERR_SRC = '${LIBSMB_ERR_SRC0} ${LIBSMB_ERR_SRC1} ${REG_PARSE_PRS_SRC}'

LIBSMB_SRC0 = '''
               ../libcli/auth/ntlm_check.c
               libsmb/ntlmssp.c
               ../libcli/auth/ntlmssp.c
               ../libcli/auth/ntlmssp_sign.c
               ${LIBNDR_NTLMSSP_SRC}
               ../libcli/auth/ntlmssp_ndr.c'''

LIBSAMBA_SRC = '${LIBSMB_SRC0}'

LIBCLI_LDAP_MESSAGE_SRC = '''../libcli/ldap/ldap_message.c'''
LIBCLI_LDAP_NDR_SRC = '''../libcli/ldap/ldap_ndr.c'''

CLDAP_SRC = '''libads/cldap.c
        ../libcli/cldap/cldap.c lib/ldb_compat.c
        ../lib/util/idtree.c
        ${LIBCLI_LDAP_MESSAGE_SRC} ${LIBCLI_LDAP_NDR_SRC}'''

TLDAP_SRC = '''lib/tldap.c lib/tldap_util.c lib/util_tsock.c'''

SCHANNEL_SRC = '''../libcli/auth/credentials.c
               ../libcli/auth/schannel_sign.c
               ../libcli/auth/schannel_state_tdb.c
               ${LIBNDR_SCHANNEL_SRC}'''

LIBSMB_SRC = '''libsmb/clientgen.c libsmb/cliconnect.c libsmb/clifile.c
             libsmb/clikrb5.c libsmb/clispnego.c
             ../libcli/auth/spnego_parse.c
             libsmb/clirap.c libsmb/clierror.c libsmb/climessage.c
             libsmb/clireadwrite.c libsmb/clilist.c libsmb/cliprint.c
             libsmb/clitrans.c libsmb/clisecdesc.c libsmb/clidgram.c
             libsmb/clistr.c libsmb/cliquota.c libsmb/clifsinfo.c libsmb/clidfs.c
             libsmb/clioplock.c libsmb/clirap2.c
             libsmb/smb_seal.c libsmb/async_smb.c
             ${LIBNMB_SRC}
             ${LIBNBT_SRC}
             ${CLDAP_SRC}
             ${DRSUAPI_SRC}'''

RPC_CLIENT_SRC1 = '''rpc_client/cli_netlogon.c
                  ${SCHANNEL_SRC}'''

LIBMSRPC_SRC = '''rpc_client/cli_lsarpc.c rpc_client/cli_samr.c
               ${RPC_CLIENT_SRC1}
               ${RPC_CLIENT_SRC}
               rpc_client/cli_spoolss.c
               rpc_client/init_spoolss.c
               rpc_client/init_samr.c
                   ../librpc/rpc/binding.c'''

LIBMSRPC_GEN_SRC = '''../librpc/gen_ndr/cli_lsa.c
                   ../librpc/gen_ndr/cli_dfs.c
                   ../librpc/gen_ndr/cli_echo.c
                   ../librpc/gen_ndr/cli_srvsvc.c
                   ../librpc/gen_ndr/cli_svcctl.c
                   ../librpc/gen_ndr/cli_winreg.c
                   ../librpc/gen_ndr/cli_initshutdown.c
                   ../librpc/gen_ndr/cli_eventlog.c
                   ../librpc/gen_ndr/cli_wkssvc.c
                   ../librpc/gen_ndr/cli_netlogon.c
                   ../librpc/gen_ndr/cli_samr.c
                   ../librpc/gen_ndr/cli_dssetup.c
                   ../librpc/gen_ndr/cli_ntsvcs.c
                   ../librpc/gen_ndr/cli_epmapper.c
                   ../librpc/gen_ndr/cli_drsuapi.c
                   ../librpc/gen_ndr/cli_spoolss.c
                   ../librpc/rpc/dcerpc_util.c
                   librpc/rpc/dcerpc_helpers.c
                   ${LIBNDR_GEN_SRC}
                   ${RPCCLIENT_NDR_SRC}'''

#
# registry-related objects
#
UTIL_REG_SRC = '''../libcli/registry/util_reg.c'''

REG_INIT_BASIC_SRC = '''registry/reg_init_basic.c'''
REG_INIT_SMBCONF_SRC = '''registry/reg_init_smbconf.c'''
REG_INIT_FULL_SRC = '''registry/reg_init_full.c'''

REGFIO_SRC = '''registry/regfio.c'''

REGSRCS_SRC = '''registry/reg_objects.c'''

REG_BACKENDS_BASE_SRC = '''registry/reg_backend_db.c'''

REG_BACKENDS_SMBCONF_SRC = '''registry/reg_backend_smbconf.c'''

REG_BACKENDS_EXTRA_SRC = '''registry/reg_backend_printing.c
                         registry/reg_backend_shares.c
                         registry/reg_backend_netlogon_params.c
                         registry/reg_backend_prod_options.c
                         registry/reg_backend_tcpip_params.c
                         registry/reg_backend_hkpt_params.c
                         registry/reg_backend_current_version.c
                         registry/reg_backend_perflib.c'''

REG_BASE_SRC = '''registry/reg_api.c
               registry/reg_dispatcher.c
               registry/reg_cachehook.c
               ${REGFIO_SRC}
               ${REGSRCS_SRC}
               registry/reg_util_internal.c
               lib/util_nttoken.c
               ${REG_BACKENDS_BASE_SRC}
               ${REG_INIT_BASIC_SRC}'''

REG_SMBCONF_SRC = '''${REG_BASE_SRC}
                  ${REG_BACKENDS_SMBCONF_SRC}
                  ${REG_INIT_SMBCONF_SRC}
		  registry/reg_util_token.c'''

REG_FULL_SRC = '''${REG_SMBCONF_SRC}
               ${REG_BACKENDS_EXTRA_SRC}
               ${REG_INIT_FULL_SRC}
               registry/reg_eventlog.c
               registry/reg_perfcount.c
               librpc/gen_ndr/ndr_perfcount.c
               registry/reg_util_legacy.c'''

LIB_EVENTLOG_SRC = '''lib/eventlog/eventlog.c'''

RPC_STATIC = ''

RPC_LSA_SRC = '''rpc_server/srv_lsa_nt.c ../librpc/gen_ndr/srv_lsa.c'''

RPC_NETLOG_SRC = '''rpc_server/srv_netlog_nt.c
                 ../librpc/gen_ndr/srv_netlogon.c'''

RPC_SAMR_SRC = '''rpc_server/srv_samr_nt.c
               rpc_server/srv_samr_util.c
	       rpc_server/srv_samr_chgpasswd.c
               ../librpc/gen_ndr/srv_samr.c'''

RPC_INITSHUTDOWN_SRC = ''' ../librpc/gen_ndr/srv_initshutdown.c rpc_server/srv_initshutdown_nt.c'''

RPC_REG_SRC = ''' rpc_server/srv_winreg_nt.c
               ../librpc/gen_ndr/srv_winreg.c'''

RPC_DSSETUP_SRC = ''' rpc_server/srv_dssetup_nt.c ../librpc/gen_ndr/srv_dssetup.c'''

RPC_SVC_SRC = '''rpc_server/srv_srvsvc_nt.c
              ../librpc/gen_ndr/srv_srvsvc.c'''

RPC_WKS_SRC = ''' ../librpc/gen_ndr/srv_wkssvc.c rpc_server/srv_wkssvc_nt.c'''

RPC_SVCCTL_SRC = ''' rpc_server/srv_svcctl_nt.c
                  ../librpc/gen_ndr/srv_svcctl.c
                  services/svc_spoolss.c services/svc_rcinit.c services/services_db.c
                  services/svc_netlogon.c services/svc_winreg.c
                  services/svc_wins.c'''

RPC_NTSVCS_SRC = '''rpc_server/srv_ntsvcs_nt.c
                 ../librpc/gen_ndr/srv_ntsvcs.c'''

RPC_DFS_SRC = ''' ../librpc/gen_ndr/srv_dfs.c rpc_server/srv_dfs_nt.c'''

RPC_SPOOLSS_SRC = '''rpc_server/srv_spoolss_nt.c
                     rpc_server/srv_spoolss_util.c
                  ../librpc/gen_ndr/srv_spoolss.c'''

RPC_EVENTLOG_SRC = '''rpc_server/srv_eventlog_nt.c
                   ${LIB_EVENTLOG_SRC} ../librpc/gen_ndr/srv_eventlog.c'''

NPA_TSTREAM_SRC = '''../libcli/named_pipe_auth/npa_tstream.c'''

RPC_NCACN_NP_INTERNAL = '''rpc_server/srv_pipe_register.c rpc_server/rpc_ncacn_np_internal.c
                        rpc_server/rpc_handles.c'''

RPC_PIPE_SRC = '''rpc_server/srv_pipe_hnd.c rpc_server/srv_pipe.c
               ${RPC_NCACN_NP_INTERNAL}'''

RPC_ECHO_SRC = '''rpc_server/srv_echo_nt.c ../librpc/gen_ndr/srv_echo.c'''

#TODO: RPC_SERVER_SRC used to include RPC_STATIC modules
RPC_SERVER_SRC = '''${RPC_PIPE_SRC} ${NPA_TSTREAM_SRC}'''

RPC_PARSE_SRC = '''${RPC_PARSE_SRC2}'''

RPC_CLIENT_SRC = '''rpc_client/cli_pipe.c librpc/rpc/rpc_common.c
                    rpc_client/rpc_transport_np.c
		    rpc_client/rpc_transport_sock.c
		    rpc_client/rpc_transport_smbd.c'''

LOCKING_SRC = '''locking/locking.c locking/brlock.c locking/posix.c'''

PRIVILEGES_BASIC_SRC = '''lib/privileges_basic.c'''

PRIVILEGES_SRC = '''lib/privileges.c'''

PASSDB_GET_SET_SRC = '''passdb/pdb_get_set.c'''

PDB_STATIC =        ''
PDB_TDBSAM_SRC =    'passdb/pdb_tdb.c'
PDB_LDAP_SRC =      'passdb/pdb_ldap.c'
PDB_ADS_SRC =       'passdb/pdb_ads.c'
PDB_SMBPASSWD_SRC = 'passdb/pdb_smbpasswd.c'
PDB_WBC_SAM_SRC =   'passdb/pdb_wbc_sam.c'

SECRETS_SRC = '''passdb/secrets.c passdb/machine_account_secrets.c
                 passdb/machine_sid.c librpc/gen_ndr/ndr_secrets.c'''

PASSDB_SRC = '''${PASSDB_GET_SET_SRC} passdb/passdb.c passdb/pdb_interface.c
                passdb/util_wellknown.c passdb/util_builtin.c passdb/pdb_compat.c
                passdb/util_unixsids.c passdb/lookup_sid.c
                passdb/login_cache.c ${PDB_STATIC}
                passdb/account_pol.c ${PRIVILEGES_SRC}
                lib/util_nscd.c lib/winbind_util.c ${SERVER_MUTEX_SRC}'''
#FIXME: lib/winbind_util.c probably is not part of PASSDB_SRC

CHARSET_STATIC = ''
CHARSET_WEIRD_SRC = 'modules/weird.c'
CHARSET_CP850_SRC = 'modules/CP850.c'
CHARSET_CP437_SRC = 'modules/CP437.c'
CHARSET_MACOSXFS_SRC = 'modules/charset_macosxfs.c'

GROUPDB_SRC = '''groupdb/mapping.c groupdb/mapping_tdb.c'''

PROFILE_SRC = '''profile/profile.c'''
PROFILES_SRC = '''utils/profiles.c
               ${LIBSMB_ERR_SRC}
               ${PARAM_SRC}
               ${LIB_SRC} ${LIB_DUMMY_SRC}'''

OPLOCK_SRC = '''smbd/oplock.c smbd/oplock_irix.c smbd/oplock_linux.c
             smbd/oplock_onefs.c'''

NOTIFY_SRC = '''smbd/notify.c smbd/notify_inotify.c smbd/notify_internal.c'''

FNAME_UTIL_SRC = '''smbd/filename_util.c'''

VFS_STATIC = ''
VFS_DEFAULT_SRC = '''modules/vfs_default.c'''
VFS_AUDIT_SRC = '''modules/vfs_audit.c'''
VFS_EXTD_AUDIT_SRC = '''modules/vfs_extd_audit.c'''
VFS_FULL_AUDIT_SRC = '''modules/vfs_full_audit.c'''
VFS_FAKE_PERMS_SRC = '''modules/vfs_fake_perms.c'''
VFS_RECYCLE_SRC = '''modules/vfs_recycle.c'''
VFS_NETATALK_SRC = '''modules/vfs_netatalk.c'''
VFS_DEFAULT_QUOTA_SRC = '''modules/vfs_default_quota.c'''
VFS_READONLY_SRC = '''modules/vfs_readonly.c modules/getdate.c'''
VFS_CAP_SRC = '''modules/vfs_cap.c'''
VFS_EXPAND_MSDFS_SRC = '''modules/vfs_expand_msdfs.c'''
VFS_SHADOW_COPY_SRC = '''modules/vfs_shadow_copy.c'''
VFS_SHADOW_COPY2_SRC = '''modules/vfs_shadow_copy2.c'''
VFS_AFSACL_SRC = '''modules/vfs_afsacl.c'''
VFS_XATTR_TDB_SRC = '''modules/vfs_xattr_tdb.c'''
VFS_POSIXACL_SRC = '''modules/vfs_posixacl.c'''
VFS_AIXACL_SRC = '''modules/vfs_aixacl.c modules/vfs_aixacl_util.c'''
VFS_AIXACL2_SRC = '''modules/vfs_aixacl2.c modules/vfs_aixacl_util.c modules/nfs4_acls.c'''
VFS_SOLARISACL_SRC = '''modules/vfs_solarisacl.c'''
VFS_ZFSACL_SRC = '''modules/vfs_zfsacl.c modules/nfs4_acls.c'''
VFS_HPUXACL_SRC = '''modules/vfs_hpuxacl.c'''
VFS_IRIXACL_SRC = '''modules/vfs_irixacl.c'''
VFS_TRU64ACL_SRC = '''modules/vfs_tru64acl.c'''
VFS_CATIA_SRC = 'modules/vfs_catia.c'
VFS_STREAMS_XATTR_SRC = 'modules/vfs_streams_xattr.c'
VFS_STREAMS_DEPOT_SRC = 'modules/vfs_streams_depot.c'
VFS_CACHEPRIME_SRC = 'modules/vfs_cacheprime.c'
VFS_PREALLOC_SRC = 'modules/vfs_prealloc.c'
VFS_COMMIT_SRC = 'modules/vfs_commit.c'
VFS_GPFS_SRC = 'modules/vfs_gpfs.c modules/gpfs.c modules/nfs4_acls.c'
VFS_NOTIFY_FAM_SRC = 'modules/vfs_notify_fam.c'
VFS_READAHEAD_SRC = 'modules/vfs_readahead.c'
VFS_TSMSM_SRC = 'modules/vfs_tsmsm.c'
VFS_FILEID_SRC = 'modules/vfs_fileid.c'
VFS_AIO_FORK_SRC = 'modules/vfs_aio_fork.c'
VFS_PREOPEN_SRC = 'modules/vfs_preopen.c'
VFS_SYNCOPS_SRC = 'modules/vfs_syncops.c'
VFS_ACL_XATTR_SRC = 'modules/vfs_acl_xattr.c'
VFS_ACL_TDB_SRC = 'modules/vfs_acl_tdb.c'
VFS_SMB_TRAFFIC_ANALYZER_SRC = 'modules/vfs_smb_traffic_analyzer.c'
VFS_ONEFS_SRC = '''modules/vfs_onefs.c modules/onefs_acl.c modules/onefs_system.c
                modules/onefs_open.c modules/onefs_streams.c modules/onefs_dir.c
                modules/onefs_cbrl.c modules/onefs_notify.c modules/onefs_config.c'''
VFS_ONEFS_SHADOW_COPY_SRC = 'modules/vfs_onefs_shadow_copy.c modules/onefs_shadow_copy.c'
VFS_DIRSORT_SRC = 'modules/vfs_dirsort.c'
VFS_SCANNEDONLY_SRC = 'modules/vfs_scannedonly.c'
VFS_CROSSRENAME_SRC = 'modules/vfs_crossrename.c'

PLAINTEXT_AUTH_SRC = '''auth/pampass.c auth/pass_check.c'''

SLCACHE_SRC = '''libsmb/samlogon_cache.c'''

DCUTIL_SRC  = '''libsmb/namequery_dc.c libsmb/trustdom_cache.c libsmb/trusts_util.c libsmb/dsgetdcname.c'''

AUTH_BUILTIN_SRC = 'auth/auth_builtin.c'
AUTH_DOMAIN_SRC = 'auth/auth_domain.c'
AUTH_SAM_SRC = 'auth/auth_sam.c'
AUTH_SERVER_SRC = 'auth/auth_server.c'
AUTH_UNIX_SRC = 'auth/auth_unix.c'
AUTH_WINBIND_SRC = 'auth/auth_winbind.c'
AUTH_WBC_SRC = 'auth/auth_wbc.c'
AUTH_SCRIPT_SRC = 'auth/auth_script.c'
AUTH_NETLOGOND_SRC = 'auth/auth_netlogond.c'

AUTH_STATIC = ''
AUTH_SRC = '''${AUTH_STATIC} auth/auth.c auth/auth_util.c auth/token_util.c
           auth/auth_compat.c auth/auth_ntlmssp.c auth/user_info.c auth/check_samsec.c
           auth/user_util.c auth/server_info.c auth/server_info_sam.c
           ${PLAINTEXT_AUTH_SRC} ${SLCACHE_SRC} ${DCUTIL_SRC}'''

#FIXME: set IDMAP_STATIC during configuration
IDMAP_STATIC=''
IDMAP_SRC = 'winbindd/idmap.c winbindd/idmap_util.c ${IDMAP_STATIC}'

#FIXME: set NSS_INFO_STATIC during configuration
NSS_INFO_STATIC = ''
NSS_INFO_TEMPLATE_SRC = 'winbindd/nss_info_template.c'
NSS_INFO_SRC = 'winbindd/nss_info.c ${NSS_INFO_STATIC}'

IDMAP_HASH_SRC = '''winbindd/idmap_hash/idmap_hash.c
                    winbindd/idmap_hash/mapfile.c'''

IDMAP_ADEX_SRC = '''winbindd/idmap_adex/idmap_adex.c
                    winbindd/idmap_adex/cell_util.c
                    winbindd/idmap_adex/likewise_cell.c
                    winbindd/idmap_adex/provider_unified.c
                    winbindd/idmap_adex/gc_util.c
                    winbindd/idmap_adex/domain_util.c'''

PERFCOUNT_STATIC = ''
PERFCOUNT_ONEFS_SRC = 'modules/perfcount_onefs.c'
PERFCOUNT_TEST_SRC = 'modules/perfcount_test.c'

WINBINDD_SRC1 = '''winbindd/winbindd.c
                   winbindd/winbindd_group.c
                   winbindd/winbindd_util.c
                   winbindd/winbindd_cache.c
                   winbindd/winbindd_pam.c
                   winbindd/winbindd_misc.c
                   winbindd/winbindd_cm.c
                   winbindd/winbindd_wins.c
                   winbindd/winbindd_msrpc.c
                   winbindd/winbindd_rpc.c
                   winbindd/winbindd_reconnect.c
                   winbindd/winbindd_ads.c
                   winbindd/winbindd_samr.c
                   winbindd/winbindd_dual.c
                   winbindd/winbindd_dual_ndr.c
                   winbindd/winbindd_dual_srv.c
                   librpc/gen_ndr/cli_wbint.c
                   librpc/gen_ndr/srv_wbint.c
                   librpc/gen_ndr/ndr_wbint.c
                   winbindd/winbindd_async.c
                   winbindd/winbindd_creds.c
                   winbindd/winbindd_cred_cache.c
                   winbindd/winbindd_ccache_access.c
                   winbindd/winbindd_domain.c
                   winbindd/winbindd_idmap.c
                   winbindd/winbindd_locator.c
                   winbindd/winbindd_ndr.c
                   winbindd/wb_ping.c
                   winbindd/wb_lookupsid.c
                   winbindd/wb_lookupname.c
                   winbindd/wb_sid2uid.c
                   winbindd/wb_sid2gid.c
                   winbindd/wb_uid2sid.c
                   winbindd/wb_gid2sid.c
                   winbindd/wb_queryuser.c
                   winbindd/wb_lookupuseraliases.c
                   winbindd/wb_lookupusergroups.c
                   winbindd/wb_getpwsid.c
                   winbindd/wb_gettoken.c
                   winbindd/wb_seqnum.c
                   winbindd/wb_seqnums.c
                   winbindd/wb_group_members.c
                   winbindd/wb_getgrsid.c
                   winbindd/wb_query_user_list.c
                   winbindd/wb_fill_pwent.c
                   winbindd/wb_next_pwent.c
                   winbindd/wb_next_grent.c
                   winbindd/wb_dsgetdcname.c
                   winbindd/winbindd_lookupsid.c
                   winbindd/winbindd_lookupname.c
                   winbindd/winbindd_sid_to_uid.c
                   winbindd/winbindd_sid_to_gid.c
                   winbindd/winbindd_uid_to_sid.c
                   winbindd/winbindd_gid_to_sid.c
                   winbindd/winbindd_allocate_uid.c
                   winbindd/winbindd_allocate_gid.c
                   winbindd/winbindd_getpwsid.c
                   winbindd/winbindd_getpwnam.c
                   winbindd/winbindd_getpwuid.c
                   winbindd/winbindd_getsidaliases.c
                   winbindd/winbindd_getuserdomgroups.c
                   winbindd/winbindd_getgroups.c
                   winbindd/winbindd_show_sequence.c
                   winbindd/winbindd_getgrgid.c
                   winbindd/winbindd_getgrnam.c
                   winbindd/winbindd_getusersids.c
                   winbindd/winbindd_lookuprids.c
                   winbindd/winbindd_setpwent.c
                   winbindd/winbindd_getpwent.c
                   winbindd/winbindd_endpwent.c
                   winbindd/winbindd_setgrent.c
                   winbindd/winbindd_getgrent.c
                   winbindd/winbindd_endgrent.c
                   winbindd/winbindd_dsgetdcname.c
                   winbindd/winbindd_getdcname.c
                   winbindd/winbindd_list_users.c
                   winbindd/winbindd_list_groups.c
                   winbindd/winbindd_check_machine_acct.c
                   winbindd/winbindd_change_machine_acct.c
                   winbindd/winbindd_ping_dc.c
                   winbindd/winbindd_set_mapping.c
                   winbindd/winbindd_remove_mapping.c
                   winbindd/winbindd_set_hwm.c
                   winbindd/winbindd_pam_auth.c
                   winbindd/winbindd_pam_logoff.c
                   winbindd/winbindd_pam_chauthtok.c
                   winbindd/winbindd_pam_auth_crap.c
                   winbindd/winbindd_pam_chng_pswd_auth_crap.c
                   auth/auth_util.c
                   auth/token_util.c
                   auth/user_util.c
                   auth/check_samsec.c
                   auth/server_info.c
                   auth/server_info_sam.c
                   auth/user_info.c
                   auth/user_util.c
		   rpc_server/srv_samr_chgpasswd.c
                   ../nsswitch/libwbclient/wb_reqtrans.c'''

WINBINDD_SRC = '''${WINBINDD_SRC1}
                  ${LIBMSRPC_SRC} ${LIBMSRPC_GEN_SRC} ${RPC_PARSE_SRC}
                  ${PROFILE_SRC} ${SLCACHE_SRC}
                  ${LIBADS_SRC}
                  ${DCUTIL_SRC} ${IDMAP_SRC} ${NSS_INFO_SRC}
                  ${AFS_SRC} ${AFS_SETTOKEN_SRC}
                  ${LIBADS_SERVER_SRC}
                  ${RPC_NCACN_NP_INTERNAL} ${RPC_SAMR_SRC} ${RPC_LSA_SRC}
                  ${TDB_VALIDATE_SRC}'''

LIBNET_SRC = 'libnet/libnet_join.c libnet/libnet_keytab.c librpc/gen_ndr/ndr_libnet_join.c'

LIBSMBCONF_SRC = '''../lib/smbconf/smbconf.c ../lib/smbconf/smbconf_util.c
                    ../lib/smbconf/smbconf_txt.c lib/smbconf/smbconf_reg.c
                    lib/smbconf/smbconf_init.c'''

MANGLE_SRC = '''smbd/mangle.c smbd/mangle_hash.c smbd/mangle_hash2.c'''

SMBD_SRC_MAIN = '''smbd/server.c smbd/server_exit.c'''

BUILDOPT_SRC = '''smbd/build_options.c'''

SMBD_SRC_SRV = '''smbd/server_reload.c smbd/files.c smbd/connection.c
               smbd/utmp.c smbd/session.c
               smbd/dfree.c smbd/dir.c smbd/password.c smbd/conn.c
               smbd/share_access.c smbd/fileio.c
               smbd/ipc.c smbd/lanman.c smbd/negprot.c
               smbd/message.c smbd/nttrans.c smbd/pipes.c
               smbd/reply.c smbd/sesssetup.c smbd/trans2.c smbd/uid.c
               smbd/dosmode.c smbd/filename.c smbd/open.c smbd/close.c
               smbd/blocking.c smbd/sec_ctx.c smbd/srvstr.c
               smbd/vfs.c smbd/perfcount.c smbd/statcache.c smbd/seal.c
               smbd/posix_acls.c lib/sysacls.c
               smbd/process.c smbd/service.c smbd/error.c
               printing/printspoolss.c
               lib/sysquotas.c lib/sysquotas_linux.c
               lib/sysquotas_xfs.c lib/sysquotas_4A.c
               smbd/fake_file.c
               smbd/quotas.c smbd/ntquotas.c ${AFS_SRC} smbd/msdfs.c
               ${AFS_SETTOKEN_SRC} smbd/aio.c smbd/statvfs.c
               smbd/dmapi.c smbd/signing.c
               smbd/file_access.c
               smbd/dnsregister.c smbd/globals.c
               smbd/smb2_server.c
               smbd/smb2_signing.c
               smbd/smb2_glue.c
               smbd/smb2_negprot.c
               smbd/smb2_sesssetup.c
               smbd/smb2_tcon.c
               smbd/smb2_create.c
               smbd/smb2_close.c
               smbd/smb2_flush.c
               smbd/smb2_read.c
               smbd/smb2_write.c
               smbd/smb2_lock.c
               smbd/smb2_ioctl.c
               smbd/smb2_keepalive.c
               smbd/smb2_find.c
               smbd/smb2_notify.c
               smbd/smb2_getinfo.c
               smbd/smb2_setinfo.c
               smbd/smb2_break.c
               ../libcli/smb/smb2_create_blob.c
               ${MANGLE_SRC} ${VFS_STATIC}'''

SMBD_SRC_BASE = '''${SMBD_SRC_SRV}
                ${RPC_SERVER_SRC} ${RPC_PARSE_SRC}
                ${LOCKING_SRC} ${PRINTING_SRC}
                ${PROFILE_SRC} ${PRINTBACKEND_SRC}
                ${OPLOCK_SRC} ${NOTIFY_SRC} ${FNAME_UTIL_SRC}
                ${LIBMSRPC_SRC}
                ${LIBMSRPC_GEN_SRC} ${LIBADS_SRC}
                ${LIBADS_SERVER_SRC} ${REG_FULL_SRC}
                ${BUILDOPT_SRC}
                ${LIBNET_SRC} ${LIBSMBCONF_SRC}
                ${RPC_LSA_SRC}
                ${RPC_NETLOG_SRC} ${RPC_SAMR_SRC}
                ${RPC_INITSHUTDOWN_SRC} ${RPC_REG_SRC}
                ${RPC_DSSETUP_SRC} ${RPC_SVC_SRC} ${RPC_WKS_SRC}
                ${RPC_SVCCTL_SRC} ${RPC_NTSVCS_SRC} ${RPC_DFS_SRC}
                ${RPC_SPOOLSS_SRC} ${RPC_EVENTLOG_SRC}
                ${RPC_ECHO_SRC}
                ${AUTH_SRC}
                ${PRIVILEGES_BASIC_SRC}'''

PRINTING_SRC = '''printing/pcap.c printing/print_svid.c printing/print_aix.c
               printing/print_cups.c printing/print_generic.c
               printing/lpq_parse.c printing/load.c printing/print_standard.c
               printing/print_iprint.c'''

PRINTBASE_SRC = '''printing/notify.c printing/printing_db.c'''
PRINTBACKEND_SRC = '''printing/printing.c printing/nt_printing.c
                   printing/nt_printing_tdb.c printing/nt_printing_migrate.c
                   librpc/gen_ndr/ndr_ntprinting.c ../librpc/ndr/ndr_ntprinting.c
                   ${PRINTBASE_SRC}'''

SMBD_SRC = '''${SMBD_SRC_BASE} ${SMBD_SRC_MAIN}'''

NMBD_SRC1 = '''nmbd/asyncdns.c nmbd/nmbd.c nmbd/nmbd_become_dmb.c
            nmbd/nmbd_become_lmb.c nmbd/nmbd_browserdb.c
            nmbd/nmbd_browsesync.c nmbd/nmbd_elections.c
            nmbd/nmbd_incomingdgrams.c nmbd/nmbd_incomingrequests.c
            nmbd/nmbd_lmhosts.c nmbd/nmbd_logonnames.c nmbd/nmbd_mynames.c
            nmbd/nmbd_namelistdb.c nmbd/nmbd_namequery.c
            nmbd/nmbd_nameregister.c nmbd/nmbd_namerelease.c
            nmbd/nmbd_nodestatus.c nmbd/nmbd_packets.c
            nmbd/nmbd_processlogon.c nmbd/nmbd_responserecordsdb.c
            nmbd/nmbd_sendannounce.c nmbd/nmbd_serverlistdb.c
            nmbd/nmbd_subnetdb.c nmbd/nmbd_winsproxy.c nmbd/nmbd_winsserver.c
            nmbd/nmbd_workgroupdb.c nmbd/nmbd_synclists.c'''

NMBD_SRC = '${NMBD_SRC1} ${PROFILE_SRC} ${LIBNDR_GEN_SRC0}'

SWAT_SRC1 = '''web/cgi.c web/diagnose.c web/startstop.c web/statuspage.c
               web/swat.c web/neg_lang.c'''

SWAT_SRC = '''${SWAT_SRC1} ${PRINTING_SRC} ${PRINTBASE_SRC}
           ${LOCKING_SRC}
           ${PLAINTEXT_AUTH_SRC}
           ${RPC_PARSE_SRC} ${LIBMSRPC_GEN_SRC} ${LIBMSRPC_SRC}
           ${PASSCHANGE_SRC} ${FNAME_UTIL_SRC}'''

WBINFO_SRC = '../nsswitch/wbinfo.c ${AFS_SETTOKEN_SRC}'

TESTPARM_SRC = 'utils/testparm.c'

EVTLOGADM_SRC0 = 'utils/eventlogadm.c'

EVTLOGADM_SRC = '''${EVTLOGADM_SRC0}
	        registry/reg_eventlog.c ${LIB_EVENTLOG_SRC}
		../librpc/gen_ndr/ndr_eventlog.c
		../librpc/gen_ndr/ndr_lsa.c'''

DISPLAY_SEC_SRC= '../libcli/security/display_sec.c'

CLIENT_SRC1 = '''client/client.c client/clitar.c ${RPC_CLIENT_SRC}
                 ../librpc/rpc/binding.c client/dnsbrowse.c
                 ${RPC_CLIENT_SRC1} ${RPC_PARSE_SRC2}'''

CLIENT_SRC = '''${CLIENT_SRC1} ${LIBMSRPC_GEN_SRC}
                ${READLINE_SRC} ${DISPLAY_SEC_SRC}'''


LIBS='ICONV'

bld.SAMBA_GENERATOR('build_options',
                    source='include/config.h script/mkbuildoptions.awk',
                    target='smbd/build_options.c',
                    rule='${AWK} -f ${SRC[1].abspath(env)} > ${TGT} < ${SRC[0].abspath(env)}')

t = bld.SAMBA_GENERATOR('build_env.h',
                        source='script/build_env.sh',
                        target='include/build_env.h',
                        rule='${SRC} ${SRCDIR} ${BUILDDIR} ${CC} > ${TGT}')
# todo: work out what is really wanted here
t.env.SRCDIR = bld.path.abspath()
t.env.BUILDDIR = bld.path.abspath()


bld.SETUP_BUILD_GROUPS()

bld.RECURSE('../lib/replace')
print "SBINDIR=%s" % bld.env.SBINDIR
bld.RECURSE('build')

bld.RECURSE('../librpc/idl')
bld.RECURSE('librpc/idl')

bld.SAMBA_MKVERSION('include/version.h')

for prefix in bld.env.MODULE_PREFIXES:
    static_key = "%s_STATIC" % prefix.upper()
    shared_key = "%s_SHARED" % prefix.upper()

    # Set up the static modules
    static_src = locals()[static_key]
    for module in bld.env[static_key]:
        static_src += "${%s_SRC} " % module
    # for some reason static_src doesn't seem to be a reference, so save it
    # back to the locals
    locals()[static_key] = static_src

    # Set up subsystems for the shared modules
    for module in bld.env[shared_key]:
        bld.SAMBA_SUBSYSTEM(module,
                            source="${%s_SRC}" % module,
                            vars=locals())

######################## SUBSYSTEMS #################################

bld.SAMBA_SUBSYSTEM('WBCOMMON',
                    source=WBCOMMON_SRC)

bld.SAMBA_SUBSYSTEM('LIBWBCLIENT',
                    source='''../nsswitch/libwbclient/wbc_guid.c
                              ../nsswitch/libwbclient/wbc_idmap.c
                              ../nsswitch/libwbclient/wbclient.c
                              ../nsswitch/libwbclient/wbc_pam.c
                              ../nsswitch/libwbclient/wbc_pwd.c
                              ../nsswitch/libwbclient/wbc_sid.c
                              ../nsswitch/libwbclient/wbc_util.c''',
                    public_deps='talloc WBCOMMON')


bld.SAMBA_SUBSYSTEM('ASN1_UTIL',
                    source='../lib/util/asn1.c',
                    deps='talloc',
                    local_include=False)

bld.SAMBA_SUBSYSTEM('AVAHI',
                    source=AVAHI_SRC,
                    deps='avahi-common avahi-client',
                    enabled=bld.env.with_avahi)

bld.SAMBA_SUBSYSTEM('GROUPDB',
                    source=GROUPDB_SRC)

bld.SAMBA_SUBSYSTEM('TLDAP',
                    source=TLDAP_SRC,
                    deps='ASN1_UTIL LIBTSOCKET')

bld.SAMBA_SUBSYSTEM('PASSDB',
                    source=PASSDB_SRC,
                    deps='GROUPDB TLDAP SECRETS',
                    vars=locals())

bld.SAMBA_SUBSYSTEM('PARAM_WITHOUT_REG',
                    source=PARAM_WITHOUT_REG_SRC)

bld.SAMBA_SUBSYSTEM('PARAM',
                    source=PARAM_SRC,
                    deps='PARAM_WITHOUT_REG',
                    vars=locals())

bld.SAMBA_SUBSYSTEM('POPT_SAMBA',
                    source=POPT_LIB_SRC,
                    vars=locals())

bld.SAMBA_SUBSYSTEM('KRBCLIENT',
                    source=KRBCLIENT_SRC,
                    deps='krb5 gssapi gssapi_krb5',
                    vars=locals())

bld.SAMBA_SUBSYSTEM('LIBS',
                    source=LIB_SRC,
                    deps='NSS_WRAPPER iconv',
                    vars=locals())

bld.SAMBA_SUBSYSTEM('LIB_NONSMBD',
                    source=LIB_NONSMBD_SRC,
                    deps='LIBS',
                    vars=locals())

bld.SAMBA_SUBSYSTEM('LIBSMB_ERR',
                    source=LIBSMB_ERR_SRC,
                    deps='SECRETS SMBLDAP',
                    vars=locals())

bld.SAMBA_SUBSYSTEM('LIBSAMBA',
                    source=LIBSAMBA_SRC,
                    deps='LIBSMB_ERR',
                    vars=locals())

bld.SAMBA_SUBSYSTEM('LIBSMB',
                    source=LIBSMB_SRC,
                    deps='LIBSAMBA ZLIB',
                    vars=locals())

bld.SAMBA_SUBSYSTEM('SECRETS',
                    source=SECRETS_SRC,
                    vars=locals())

bld.SAMBA_SUBSYSTEM('SMBLDAP',
                    source=SMBLDAP_SRC,
                    deps='ldap lber',
                    vars=locals())

########################## BINARIES #################################

bld.SAMBA_BINARY('smbd/smbd',
                 source=SMBD_SRC,
                 deps='''tdb DYNCONFIG tevent dl krb5 ldap gssapi gssapi_krb5
                 NSS_WRAPPER LIBWBCLIENT crypt nsl cups cap resolv ZLIB PASSDB
                 PARAM_WITHOUT_REG LIBS LIBSMB POPT_SAMBA KRBCLIENT AVAHI''',
                 install_path='${SBINDIR}',
                 vars=locals())

bld.SAMBA_BINARY('nmbd/nmbd',
                 source=NMBD_SRC,
                 deps='''talloc tdb tevent ZLIB cap resolv LIBWBCLIENT dl
                 NSS_WRAPPER DYNCONFIG PASSDB PARAM ldap LIB_NONSMBD LIBSMB
                 POPT_SAMBA KRBCLIENT''',
                 install_path='${SBINDIR}',
                 vars=locals())

bld.SAMBA_BINARY('winbindd/winbindd',
                 source=WINBINDD_SRC,
                 deps='''talloc tdb tevent cap dl DYNCONFIG ZLIB NSS_WRAPPER
                 LIBWBCLIENT PASSDB ldap resolv PARAM LIB_NONSMBD LIBSMB
                 POPT_SAMBA KRBCLIENT''',
                 enabled=bld.env.build_winbind,
                 install_path='${SBINDIR}',
                 vars=locals())

bld.SAMBA_BINARY('web/swat',
                 source=SWAT_SRC,
                 deps='''talloc tevent cap DYNCONFIG LIBS LIBSMB LIBWBCLIENT PARAM
                 LIB_NONSMBD resolv PASSDB POPT_SAMBA KRBCLIENT cups''',
                 enabled=bld.env.build_swat,
                 install_path='${SBINDIR}',
                 vars=locals())

bld.SAMBA_BINARY('smbclient',
                 source=CLIENT_SRC,
                 deps='''talloc tdb cap resolv POPT_SAMBA PASSDB LIBSMB LIB_NONSMBD
                 PARAM_WITHOUT_REG LIBWBCLIENT DYNCONFIG PARAM KRBCLIENT''',
                 vars=locals())

bld.SAMBA_BINARY('wbinfo',
                 source=WBINFO_SRC,
                 deps='''talloc LIBWBCLIENT DYNCONFIG tevent cap
                 NSS_WRAPPER ASN1_UTIL LIBTSOCKET PASSDB ldap PARAM LIB_NONSMBD
                 LIBSAMBA POPT_SAMBA''',
                 vars=locals())

bld.SAMBA_BINARY('testparm',
                 source=TESTPARM_SRC,
                 deps='''talloc tevent DYNCONFIG ldap cap NSS_WRAPPER
                 LIBWBCLIENT ASN1_UTIL LIBTSOCKET PASSDB PARAM LIB_NONSMBD
                 LIBSMB_ERR POPT_SAMBA''',
                 vars=locals())

bld.SAMBA_BINARY('eventlogadm',
                 source=EVTLOGADM_SRC,
                 deps='''talloc tevent cap POPT_SAMBA DYNCONFIG LIBS PARAM
                 LIB_NONSMBD LIBSMB_ERR PASSDB LIBWBCLIENT''',
                 vars=locals())

swat_files=recursive_dirlist('../swat', '../swat', '*')
bld.INSTALL_FILES('${SWATDIR}', swat_files, base_name='../swat')

########################## INCLUDES #################################

bld.RECURSE('../lib/socket_wrapper')
bld.RECURSE('../lib/talloc')
bld.RECURSE('../lib/tdb')
bld.RECURSE('../lib/nss_wrapper')
bld.RECURSE('../lib/tevent')
bld.RECURSE('../lib/popt')
bld.RECURSE('../lib/zlib')
bld.RECURSE('../lib/tsocket')

bld.ENFORCE_GROUP_ORDERING()
bld.CHECK_PROJECT_RULES()
