#!/usr/bin/env python


bld.SAMBA_LIBRARY('MESSAGING',
	source='messaging.c',
	public_deps='samba-util tdb-wrap NDR_IRPC UNIX_PRIVS util_tdb cluster ndr samba_socket dcerpc',
	allow_warnings=True,
	private_library=True
	)

bld.SAMBA_PYTHON('python_messaging',
	source='pymessaging.c',
	deps='MESSAGING events pyparam_util',
	realname='samba/messaging.so'
	)

