#!/usr/bin/env python


bld.SAMBA_LIBRARY('MESSAGING_SEND',
	source='messaging_send.c',
	public_deps='messages_util messages_dgm UNIX_PRIVS cluster server_id_db',
	private_library=True
	)

bld.SAMBA_LIBRARY('MESSAGING',
	source='messaging.c messaging_handlers.c',
	public_deps='''
            samba-util
            NDR_IRPC
            UNIX_PRIVS
            cluster
            ndr
            dcerpc
            messages_util
            server_id_db
            talloc_report_printf
            ''',
	private_library=True
	)

pyparam_util = bld.pyembed_libname('pyparam_util')
pytalloc_util = bld.pyembed_libname('pytalloc-util')

bld.SAMBA_PYTHON('python_messaging',
		source='pymessaging.c',
		deps='MESSAGING events %s %s' % (pyparam_util, pytalloc_util),
		realname='samba/messaging.so'
		)
