#!/usr/bin/env python


bld.SAMBA_SUBSYSTEM('MESSAGING',
	source='messaging.c',
	public_deps='libsamba-util TDB_WRAP NDR_IRPC UNIX_PRIVS UTIL_TDB CLUSTER LIBNDR samba_socket dcerpc'
	)


bld.SAMBA_PYTHON('python_messaging',
	source='pymessaging.c',
	deps='MESSAGING events pyparam_util',
	realname='samba/messaging.so'
	)

