[SUBSYSTEM::LIBCMDLINE_CREDENTIALS]
PRIVATE_PROTO_HEADER = credentials.h
PUBLIC_DEPENDENCIES = CREDENTIALS LIBPOPT

LIBCMDLINE_CREDENTIALS_OBJ_FILES = lib/cmdline/credentials.o

[SUBSYSTEM::POPT_SAMBA]
PUBLIC_DEPENDENCIES = LIBPOPT

POPT_SAMBA_OBJ_FILES = lib/cmdline/popt_common.o

PUBLIC_HEADERS += lib/cmdline/popt_common.h 

[SUBSYSTEM::POPT_CREDENTIALS]
PRIVATE_PROTO_HEADER = popt_credentials.h
PUBLIC_DEPENDENCIES = CREDENTIALS LIBCMDLINE_CREDENTIALS LIBPOPT
PRIVATE_DEPENDENCIES = LIBSAMBA-UTIL

POPT_CREDENTIALS_OBJ_FILES = lib/cmdline/popt_credentials.o
