#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('LIBCMDLINE_CREDENTIALS',
	source='credentials.c',
	autoproto='credentials.h',
	public_deps='CREDENTIALS popt'
	)

bld.SAMBA_SUBSYSTEM('POPT_SAMBA',
	source='popt_common.c',
	public_deps='popt',
	public_headers='popt_common.h:popt.h',
        header_path='samba',
        deps='talloc'
	)


bld.SAMBA_SUBSYSTEM('POPT_CREDENTIALS',
	source='popt_credentials.c',
	autoproto='popt_credentials.h',
	public_deps='CREDENTIALS LIBCMDLINE_CREDENTIALS popt',
	deps='LIBSAMBA-UTIL'
	)

