.\" $Id$
.\"
.Dd Aug 27, 1997
.Dt KLIST 1
.Os HEIMDAL
.Sh NAME
.Nm klist
.Nd
list the current tickets
.Sh SYNOPSIS
.Nm
.Oo Fl c Ar cache \*(Ba Xo
.Fl -cache= Ns Ar cache Oc
.Xc
.Op Fl t | Fl -test
.Op Fl 4 | Fl -v4
.Op Fl T | Fl -tokens
.Op Fl 5 | Fl -v5
.Op Fl v | Fl -verbose
.Op Fl -version
.Op Fl -help
.Sh DESCRIPTION
.Nm
reads and displays the current tickets in the crential cache (also
knows as the ticket file).
.Pp
Options supported:
.Bl -tag -width Ds
.It Xo
.Fl c Ar cache Ns ,
.Fl -cache= Ns Ar cache
.Xc
credentials cache to list
.It Xo
.Fl t Ns ,
.Fl -test
.Xc
Test for there being an active and valid TGT for the local realm of
the user in the credential cache.
.It Xo
.Fl 4 Ns ,
.Fl -v4
.Xc
display v4 tickets
.It Xo
.Fl T Ns ,
.Fl -tokens
.Xc
display AFS tokens
.It Xo
.Fl 5 Ns ,
.Fl -v5
.Xc
display v5 cred cache (this is the default)
.It Xo
.Fl v Ns ,
.Fl -verbose
.Xc
Verbose output. Include all information from tickets.
.El
.Sh SEE ALSO
.Xr kinit 1 ,
.Xr kdestroy 1
