Import('hostenv')
opts = Options(None, ARGUMENTS)
opts.AddOptions(
	BoolOption('socket_wrapper','enable socket wrapper',0)
)

opts.Update(hostenv)

if hostenv['socket_wrapper']:
	hostenv.Append(CPPDEFINES = {'HAVE_SOCKET_WRAPPER': 1})
	socket_wrapper = hostenv.Library('socket_wrapper',['socket_wrapper.c'])
else:
	socket_wrapper = []
