@node Tutorial, , Introduction, Top
@comment  node-name,  next,  previous,  up
@chapter Tutorial

There currently isn't any documentation other than the source. To give
some example how to you might try this code, we give you a quick
`tutorial'.

After you have built everything (don't @samp{make install}) you could do
the following to test the kdc.

@example 
$ cd kdc
$ ../admin/kdb_edit
kdb_edit> init MY.REALM
Realm max ticket life: [infinite] 
Realm max renewable ticket life: [infinite] 
Default ticket life: [86400] 
Default renewable ticket life: [432000] 
@end example

This will create an initial database (in the current directory).

@example
kdb_edit> add me@@MY.REALM 
Max ticket life [86400]: 
Max renewable ticket [432000]: 
Password:
Verifying password - Password:
@end example

This will add a principal for you. You have to specify the realm.

@example
kdb_edit> add host/my.computer@@MY.REALM
Max ticket life [86400]: 
Max renewable ticket [432000]: 
Password:
Verifying password - Password:
@end example

This creates a host entry for your computer (this could be anything, but
a `host' principal is most useful).

Now start the KDC (press control-D to exit kdb_edit).

@example
$ ./kdc &
@end example

You will have to create a @file{/etc/krb5.conf} with the following contents:

@example
[realms]
        MY.REALM = @{
                kdc = my.computer
        @}
[domain_realm]
        my.computer = MY.REALM
@end example

Now, try to get some credentials.

@example
$ ../kuser/kinit me@@MY.REALM
Password: 
$ ../kuser/klist
Credentials cache: /tmp/krb5cc_3008
        Principal: me@@MY.REALM

  Issued           Expires          Principal
Jul 13 07:25:55  Jul 14 07:25:55  krbtgt/MY.REALM@@MY.REALM
$ ../kuser/kfoo host/my.computer@@MY.REALM
$ ../kuser/klist 
Credentials cache: /tmp/krb5cc_3008
        Principal: me@@MY.REALM

  Issued           Expires          Principal
Jul 13 07:25:55  Jul 14 07:25:55  krbtgt/MY.REALM@@MY.REALM
Jul 13 07:25:55  Jul 14 07:25:55  host/my.computer@@MY.REALM
@end example

Extending this example to do a full test of rsh or telnet is left as an
exercise to the reader.
