#            tastes like -*- python -*-

Import('hostenv')
Import('talloc basic popt_common popt param')
registry = hostenv.StaticLibrary('registry',
			[basic,talloc,'common/reg_interface.c','common/reg_util.c'])
hostenv.Program('regtree', ['tools/regtree.c',registry,talloc,basic,popt_common,popt,param])
