#!/usr/bin/env python

bld.SAMBA_LIBRARY('torture',
	source='torture.c subunit.c simple.c',
	vnum='0.0.1',
	pc_files='torture.pc',
	public_deps='samba-hostconfig samba-util errors talloc tevent subunit',
	public_headers='torture.h'
	)
