#!/usr/bin/env python

import Options, Logs

def configure(conf):
    if conf.CHECK_BUNDLED_SYSTEM_PKG('smbclient', minversion='0'):
        conf.define('USING_SYSTEM_LIBSMBCLIENT', 1)

def build(bld):
    if bld.CONFIG_SET('USING_SYSTEM_LIBSMBCLIENT'):
        Logs.info("\tSelected system libsmbclient build")
        return

    Logs.info("\tSelected embedded libsmbclient build")
    bld.SAMBA3_LIBRARY('smbclient',
                       source='''
                              libsmb_cache.c
                              libsmb_compat.c
                              libsmb_context.c
                              libsmb_dir.c
                              libsmb_file.c
                              libsmb_misc.c
                              libsmb_path.c
                              libsmb_printjob.c
                              libsmb_server.c
                              libsmb_stat.c
                              libsmb_xattr.c
                              libsmb_setget.c''',
                       public_deps='''
                                   talloc
                                   param
                                   libsmb
                                   KRBCLIENT
                                   msrpc3
                                   libcli_lsa3''',
                       public_headers='../include/libsmbclient.h',
                       abi_directory='ABI',
                       abi_match='smbc_*',
                       vnum='0.1.0',
                       pc_files='smbclient.pc')
