#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('ntvfs_common',
	source='init.c brlock.c brlock_tdb.c opendb.c opendb_tdb.c notify.c',
	autoproto='proto.h',
	deps='util_tdb tdb-wrap',
	public_deps='NDR_OPENDB NDR_NOTIFY sys_notify sys_lease share'
	)

