#!/usr/bin/env python


bld.SAMBA_SUBSYSTEM('LIBTSOCKET',
	source='tsocket.c tsocket_helpers.c tsocket_bsd.c',
	public_deps='talloc tevent iov_buf socket-blocking',
	public_headers='tsocket.h tsocket_internal.h',
	)

bld.SAMBA_BINARY('test_tsocket_bsd_addr',
                 source='tests/test_bsd_addr.c',
                 deps='cmocka replace LIBTSOCKET',
                 local_include=False,
                 for_selftest=True)

bld.SAMBA_BINARY('test_tstream',
                 source='tests/test_tstream.c tests/socketpair_tcp.c',
                 deps='cmocka replace LIBTSOCKET',
                 local_include=False,
                 for_selftest=True)

