#!/usr/bin/env python

pytalloc_util = bld.pyembed_libname('pytalloc-util')
pyrpc_util = bld.pyembed_libname('pyrpc_util')
provision = bld.pyembed_libname('PROVISION')
name = bld.pyembed_libname('samba-net')
auto_proto='libnet_proto.h'
bld.SAMBA_LIBRARY(name,
        source='libnet.c libnet_passwd.c libnet_time.c libnet_rpc.c libnet_join.c libnet_site.c libnet_become_dc.c libnet_unbecome_dc.c libnet_vampire.c libnet_user.c libnet_group.c libnet_share.c libnet_lookup.c libnet_domain.c userinfo.c groupinfo.c userman.c groupman.c prereq_domain.c',
        autoproto=auto_proto,
        public_deps='samba-credentials dcerpc dcerpc-samr RPC_NDR_LSA RPC_NDR_SRVSVC RPC_NDR_DRSUAPI cli_composite LIBCLI_RESOLVE LIBCLI_FINDDCS cli_cldap LIBCLI_FINDDCS gensec_schannel LIBCLI_AUTH ndr smbpasswdparser %s LIBCLI_SAMSYNC LIBTSOCKET GNUTLS_HELPERS' % (provision),
        private_library=True,
        pyembed=True,
        enabled=bld.PYTHON_BUILD_IS_ENABLED()
        )

bld.SAMBA_PYTHON('python_net',
        source='py_net.c',
        deps='%s %s %s' % (name, pyrpc_util, pytalloc_util),
        realname='samba/net.so'
        )

bld.SAMBA_PYTHON('python_dckeytab',
        source='py_net_dckeytab.c libnet_export_keytab.c',
        deps='%s db-glue krb5 com_err' % (pyrpc_util),
        realname='samba/dckeytab.so',
        enabled=bld.CONFIG_SET('AD_DC_BUILD_IS_ENABLED')
        )
