#!/usr/bin/env python

bld.SAMBA_LIBRARY('samba-net',
	source='libnet.c libnet_passwd.c libnet_time.c libnet_rpc.c libnet_join.c libnet_site.c libnet_become_dc.c libnet_unbecome_dc.c libnet_vampire.c libnet_samdump.c libnet_samsync_ldb.c libnet_user.c libnet_group.c libnet_share.c libnet_lookup.c libnet_domain.c userinfo.c groupinfo.c userman.c groupman.c prereq_domain.c libnet_samsync.c',
	autoproto='libnet_proto.h',
	public_deps='samba-credentials dcerpc dcerpc-samr RPC_NDR_LSA RPC_NDR_SRVSVC RPC_NDR_DRSUAPI cli_composite LIBCLI_RESOLVE LIBCLI_FINDDCS cli_cldap LIBCLI_FINDDCS gensec_schannel LIBCLI_AUTH ndr smbpasswdparser PROVISION LIBCLI_SAMSYNC LIBTSOCKET',
	private_library=True,
	enabled=bld.PYTHON_BUILD_IS_ENABLED()
	)


for env in bld.gen_python_environments():
	pytalloc_util = bld.pyembed_libname('pytalloc-util')
	pyrpc_util = bld.pyembed_libname('pyrpc_util')
	bld.SAMBA_PYTHON('python_net',
		source='py_net.c',
		deps='samba-net %s %s' % (pyrpc_util, pytalloc_util),
		realname='samba/net.so'
		)

	bld.SAMBA_PYTHON('python_dckeytab',
		source='py_net_dckeytab.c libnet_export_keytab.c',
		deps='pyrpc_util db-glue krb5 com_err',
		realname='samba/dckeytab.so',
		enabled=bld.CONFIG_SET('AD_DC_BUILD_IS_ENABLED')
		)
