#!/usr/bin/env python

import sys

# Check for inotify support (Skip if we are SunOS)
#NOTE: illumos provides sys/inotify.h but is not an exact match for linux
host_os = sys.platform
if host_os.rfind('sunos') == -1:
    conf.CHECK_HEADERS('sys/inotify.h', add_headers=False)
    if (conf.CONFIG_SET('HAVE_SYS_INOTIFY_H')):
        conf.DEFINE('HAVE_LINUX_INOTIFY', 1)

conf.CHECK_DECLS('F_SETLEASE', headers='linux/fcntl.h', reverse=True)
conf.CHECK_DECLS('SA_SIGINFO', headers='signal.h', reverse=True)
