#!/usr/bin/env python

bld.SAMBA_LIBRARY('dsdb-module',
	source=[],
	deps='DSDB_MODULE_HELPERS DSDB_MODULE_HELPER_SCHEMA DSDB_MODULE_HELPER_RIDALLOC',
	private_library=True,
	grouping_library=True)

bld.SAMBA_SUBSYSTEM('DSDB_MODULE_HELPERS',
	source='util.c acl_util.c schema_util.c',
	autoproto='util_proto.h',
	deps='ldb ndr samdb-common security-session'
	)

bld.SAMBA_SUBSYSTEM('DSDB_MODULE_HELPER_RIDALLOC',
	source='ridalloc.c',
	autoproto='ridalloc.h',
	deps='MESSAGING',
	)

bld.SAMBA_SUBSYSTEM('DSDB_MODULE_HELPER_SCHEMA',
	source='schema.c',
	autoproto='schema.h',
	deps='SAMDB_SCHEMA'
	)

bld.SAMBA_MODULE('ldb_samba_dsdb',
	source='samba_dsdb.c',
	subsystem='ldb',
	init_function='LDB_MODULE(samba_dsdb)',
	deps='SAMDB talloc events ndr DSDB_MODULE_HELPERS',
	internal_module=False,
	)


bld.SAMBA_MODULE('ldb_samba_secrets',
	source='samba_secrets.c',
	subsystem='ldb',
	init_function='LDB_MODULE(samba_secrets)',
	internal_module=False,
	deps='SAMDB talloc events ndr'
	)


bld.SAMBA_MODULE('ldb_objectguid',
	source='objectguid.c',
	subsystem='ldb',
	init_function='LDB_MODULE(objectguid)',
	internal_module=False,
	deps='SAMDB talloc events ndr'
	)


bld.SAMBA_MODULE('ldb_repl_meta_data',
	source='repl_meta_data.c',
	subsystem='ldb',
	init_function='LDB_MODULE(repl_meta_data)',
	internal_module=False,
	deps='SAMDB talloc events ndr NDR_DRSUAPI NDR_DRSBLOBS ndr DSDB_MODULE_HELPERS security-session'
	)


bld.SAMBA_MODULE('ldb_dsdb_cache',
	source='dsdb_cache.c',
	subsystem='ldb',
	init_function='LDB_MODULE(dsdb_cache)',
	internal_module=False,
	deps='SAMDB talloc events'
	)


bld.SAMBA_MODULE('ldb_schema_load',
	source='schema_load.c',
	subsystem='ldb',
	init_function='LDB_MODULE(schema_load)',
	internal_module=False,
	deps='SAMDB talloc events DSDB_MODULE_HELPERS'
	)


bld.SAMBA_MODULE('ldb_schema_data',
	source='schema_data.c',
	subsystem='ldb',
	init_function='LDB_MODULE(schema_data)',
	internal_module=False,
	deps='SAMDB talloc events DSDB_MODULE_HELPERS'
	)


bld.SAMBA_MODULE('ldb_naming_fsmo',
	source='naming_fsmo.c',
	subsystem='ldb',
	init_function='LDB_MODULE(naming_fsmo)',
	internal_module=False,
	deps='SAMDB talloc events DSDB_MODULE_HELPERS'
	)


bld.SAMBA_MODULE('ldb_pdc_fsmo',
	source='pdc_fsmo.c',
	subsystem='ldb',
	init_function='LDB_MODULE(pdc_fsmo)',
	internal_module=False,
	deps='SAMDB talloc events DSDB_MODULE_HELPERS'
	)


bld.SAMBA_MODULE('ldb_samldb',
	source='samldb.c',
	subsystem='ldb',
	init_function='LDB_MODULE(samldb)',
	internal_module=False,
	deps='talloc events SAMDB DSDB_MODULE_HELPERS DSDB_MODULE_HELPER_RIDALLOC'
	)


bld.SAMBA_MODULE('ldb_samba3sam',
	source='samba3sam.c',
	subsystem='ldb',
	init_function='LDB_MODULE(samba3sam)',
	internal_module=False,
	deps='talloc events ldb smbpasswd security NDR_SECURITY'
	)


bld.SAMBA_MODULE('ldb_samba3sid',
	source='samba3sid.c',
	subsystem='ldb',
	init_function='LDB_MODULE(samba3sid)',
	internal_module=False,
	deps='talloc events ldb security NDR_SECURITY LDBSAMBA DSDB_MODULE_HELPERS'
	)


bld.SAMBA_MODULE('ldb_simple_ldap_map',
                 source='simple_ldap_map.c',
                 subsystem='ldb',
                 init_function='ldb_simple_ldap_map_init',
                 module_init_name='ldb_init_module',
                 internal_module=False,
                 deps='talloc events ldb ndr LDBSAMBA'
                 )


bld.SAMBA_MODULE('ldb_rootdse',
	source='rootdse.c',
	subsystem='ldb',
	init_function='LDB_MODULE(rootdse)',
	internal_module=False,
	deps='talloc events SAMDB MESSAGING security-session DSDB_MODULE_HELPERS'
	)


bld.SAMBA_MODULE('ldb_password_hash',
	source='password_hash.c',
	subsystem='ldb',
	init_function='LDB_MODULE(password_hash)',
	internal_module=False,
	deps='talloc events SAMDB LIBCLI_AUTH NDR_DRSBLOBS authkrb5 hdb krb5 com_err'
	)


bld.SAMBA_MODULE('ldb_local_password',
	source='local_password.c',
	subsystem='ldb',
	init_function='LDB_MODULE(local_password)',
	internal_module=False,
	deps='talloc events ndr SAMDB'
	)

bld.SAMBA_MODULE('ldb_extended_dn_in',
	source='extended_dn_in.c',
	subsystem='ldb',
	init_function='LDB_MODULE(extended_dn_in)',
	internal_module=False,
	deps='talloc events samba-util'
	)


bld.SAMBA_MODULE('ldb_extended_dn_out',
                 source='extended_dn_out.c',
                 init_function='ldb_extended_dn_out_init',
                 module_init_name='ldb_init_module',
                 subsystem='ldb',
                 deps='talloc events ndr samba-util SAMDB',
                 internal_module=False,
                 )


bld.SAMBA_MODULE('ldb_extended_dn_store',
	source='extended_dn_store.c',
	subsystem='ldb',
	init_function='LDB_MODULE(extended_dn_store)',
	internal_module=False,
	deps='talloc events samba-util SAMDB DSDB_MODULE_HELPERS'
	)


bld.SAMBA_MODULE('ldb_show_deleted',
	source='show_deleted.c',
	subsystem='ldb',
	init_function='LDB_MODULE(show_deleted)',
	internal_module=False,
	deps='talloc events samba-util DSDB_MODULE_HELPERS'
	)


bld.SAMBA_MODULE('ldb_partition',
	source='partition.c partition_init.c',
	autoproto='partition_proto.h',
	subsystem='ldb',
	init_function='LDB_MODULE(partition)',
	internal_module=False,
	deps='talloc events SAMDB DSDB_MODULE_HELPERS'
	)


bld.SAMBA_MODULE('ldb_new_partition',
	source='new_partition.c',
	subsystem='ldb',
	init_function='LDB_MODULE(new_partition)',
	internal_module=False,
	deps='talloc events SAMDB DSDB_MODULE_HELPERS'
	)


bld.SAMBA_MODULE('ldb_update_keytab',
	source='update_keytab.c',
	subsystem='ldb',
	init_function='LDB_MODULE(update_keytab)',
	internal_module=False,
	deps='talloc events CREDENTIALS ldb com_err KERBEROS_UTIL'
	)


bld.SAMBA_MODULE('ldb_objectclass',
	source='objectclass.c',
	subsystem='ldb',
	init_function='LDB_MODULE(objectclass)',
	internal_module=False,
	deps='talloc events security NDR_SECURITY SAMDB DSDB_MODULE_HELPERS samba-util DSDB_MODULE_HELPER_SCHEMA'
	)


bld.SAMBA_MODULE('ldb_objectclass_attrs',
	source='objectclass_attrs.c',
	subsystem='ldb',
	init_function='LDB_MODULE(objectclass_attrs)',
	deps='talloc SAMDB samba-util',
	internal_module=False,
	)


bld.SAMBA_MODULE('ldb_subtree_rename',
	source='subtree_rename.c',
	subsystem='ldb',
	init_function='LDB_MODULE(subtree_rename)',
	internal_module=False,
	deps='talloc events samba-util ldb samdb-common'
	)


bld.SAMBA_MODULE('ldb_subtree_delete',
	source='subtree_delete.c',
	subsystem='ldb',
	init_function='LDB_MODULE(subtree_delete)',
	internal_module=False,
	deps='talloc events samba-util DSDB_MODULE_HELPERS'
	)


bld.SAMBA_MODULE('ldb_linked_attributes',
	source='linked_attributes.c',
	subsystem='ldb',
	init_function='LDB_MODULE(linked_attributes)',
	internal_module=False,
	deps='talloc events SAMDB DSDB_MODULE_HELPERS'
	)


bld.SAMBA_MODULE('ldb_ranged_results',
	source='ranged_results.c',
	subsystem='ldb',
	init_function='LDB_MODULE(ranged_results)',
	internal_module=False,
	deps='talloc events samba-util ldb'
	)


bld.SAMBA_MODULE('ldb_anr',
	source='anr.c',
	subsystem='ldb',
	init_function='LDB_MODULE(anr)',
	internal_module=False,
	deps='talloc events samba-util SAMDB'
	)


bld.SAMBA_MODULE('ldb_instancetype',
	source='instancetype.c',
	subsystem='ldb',
	init_function='LDB_MODULE(instancetype)',
	internal_module=False,
	deps='talloc events samba-util SAMDB DSDB_MODULE_HELPERS'
	)


bld.SAMBA_MODULE('ldb_operational',
	source='operational.c',
	subsystem='ldb',
	init_function='LDB_MODULE(operational)',
	internal_module=False,
	deps='talloc tevent samba-util samdb-common DSDB_MODULE_HELPERS auth SAMDB'
	)


bld.SAMBA_MODULE('ldb_descriptor',
	source='descriptor.c',
	subsystem='ldb',
	init_function='LDB_MODULE(descriptor)',
	internal_module=False,
	deps='talloc events security NDR_SECURITY SAMDB DSDB_MODULE_HELPERS DSDB_MODULE_HELPER_SCHEMA'
	)


bld.SAMBA_MODULE('ldb_resolve_oids',
	source='resolve_oids.c',
	subsystem='ldb',
	init_function='LDB_MODULE(resolve_oids)',
	internal_module=False,
	deps='SAMDB talloc events ndr'
	)


bld.SAMBA_MODULE('ldb_acl',
	source='acl.c',
	subsystem='ldb',
	init_function='LDB_MODULE(acl)',
	internal_module=False,
	deps='talloc events security SAMDB DSDB_MODULE_HELPERS DSDB_MODULE_HELPER_SCHEMA'
	)


bld.SAMBA_MODULE('ldb_lazy_commit',
	source='lazy_commit.c',
	subsystem='ldb',
	internal_module=False,
	init_function='LDB_MODULE(lazy_commit)',
	deps='SAMDB DSDB_MODULE_HELPERS'
	)

bld.SAMBA_MODULE('ldb_aclread',
	source='acl_read.c',
	subsystem='ldb',
	init_function='LDB_MODULE(aclread)',
	internal_module=False,
	deps='talloc events security SAMDB DSDB_MODULE_HELPERS',
	)

bld.SAMBA_MODULE('ldb_simple_dn',
	source='simple_dn.c',
	subsystem='ldb',
	init_function='LDB_MODULE(simple_dn)',
	internal_module=False,
	deps='talloc DSDB_MODULE_HELPERS'
	)
