#!/usr/bin/env python


bld.SAMBA_LIBRARY('libevents',
                  source='tevent_s4.c',
                  deps='LIBSAMBA-UTIL',
                  public_deps='tevent',
                  private_library=True
                  )
