#!/usr/bin/env python

import os, Options
from samba_utils import TOUCH_FILE, EXPAND_VARIABLES

# work out what python external libraries we need to install
external_libs = {
    "dns.resolver": "dnspython/dns",
    "subunit": "subunit/python/subunit",
    "testtools": "testtools/testtools"}

list = []

for module, package in external_libs.iteritems():
    try:
        __import__(module)
    except ImportError:
        list.append(package)

for e in list:
    bld.INSTALL_WILDCARD('${PYTHONDIR}/samba/external', e + '/**/*', flat=False,
                         exclude='*.pyc', trim_path=os.path.dirname(e))

if Options.is_install:
    # we need a blank __init__.py in samba/external
    TOUCH_FILE(bld.EXPAND_VARIABLES('${PYTHONDIR}/samba/external/__init__.py'),
               install_dir=True)
