#!/usr/bin/env python

import os, Options

# work out what python external libraries we need to install
external_libs = {
    "dns.resolver": "dnspython/dns",
    "subunit": "subunit/python/subunit",
    "testtools": "testtools/testtools"}

list = []

for module, package in external_libs.items():
    try:
        __import__(module)
    except ImportError:
        list.append(package)

for e in list:
    bld.INSTALL_WILDCARD('${PYTHONDIR}/samba/external', e + '/**/*', flat=False,
                         exclude='*.pyc', trim_path=os.path.dirname(e))

bld.SAMBA_GENERATOR('external_init_py',
                    rule='touch ${TGT}',
                    target='empty_file')

bld.INSTALL_FILES('${PYTHONDIR}/samba/external', 'empty_file', destname='__init__.py')
