Import('hostenv')
tdbenv = hostenv.Copy()
tdbenv.Append(CPPPATH=['include'])
tdb = tdbenv.StaticLibrary('tdb',
	['common/tdb.c','common/dump.c','common/io.c','common/lock.c',
	 'common/open.c','common/traverse.c','common/freelist.c',
	 'common/error.c','common/tdbutil.c'])

tdbtool = tdbenv.Program('bin/tdbtool', ['tools/tdbtool.c',tdb])
tdbtorture = tdbenv.Program('bin/tdbtorture', ['tools/tdbtorture.c',tdb])
tdbdump = tdbenv.Program('bin/tdbdump', ['tools/tdbdump.c',tdb])
tdbbackup = tdbenv.Program('bin/tdbbackup', ['tools/tdbbackup.c',tdb])

