#!/bin/sh
# script to manage nfs in a clustered environment

. /etc/sysconfig/nfs
. /etc/ctdb/functions

[ -z $CTDB_MANAGES_NFS ] && exit 0
[ $CTDB_MANAGES_NFS != "yes" ] && exit 0

cmd="$1"
shift

case $cmd in 
     startup)
	mkdir -p /etc/ctdb/state/nfs

	# wait for all nfs exported directories to become available
	nfs_dirs=`cut -d' ' -f1 /etc/exports`
	ctdb_wait_directories "NFS" $nfs_dirs

	service nfs start
	;;

     shutdown)
	service nfs stop
	;;

     releaseip)
	iface=$1
	ip=$2
	maskbits=$3

	echo $ip >> /etc/ctdb/state/nfs/restart
	exit 0
	;;

     recovered)
        # restart NFS to ensure that all TCP connections to the released ip
	# are closed
	[ -f /etc/ctdb/state/nfs/restart ] && {
		( service nfs status > /dev/null 2>&1 && 
                      service nfs restart > /dev/null 2>&1 ) &
	} > /dev/null 2>&1
	/bin/rm -f /etc/ctdb/state/nfs/restart
	;;

esac

exit 0
