#!/usr/bin/env python

bld.SAMBA_LIBRARY('authkrb5',
                  source='kerberos.c kerberos_heimdal.c kerberos_pac.c krb5_init_context.c keytab_copy.c',
                  autoproto='proto.h',
                  public_deps='krb5 ndr-krb5pac samba_socket LIBCLI_RESOLVE com_err asn1',
                  deps='auth_sam_reply tevent LIBPACKET ndr ldb KRB5_WRAP errors',
                  private_library=True
                  )

bld.SAMBA_SUBSYSTEM('KERBEROS_UTIL',
	autoproto='kerberos_util.h',
	source='kerberos_util.c',
	deps='authkrb5 com_err CREDENTIALS_KRB5',
	)

bld.SAMBA_SUBSYSTEM('KERBEROS_SRV_KEYTAB',
	autoproto='kerberos_srv_keytab.h',
	source='srv_keytab.c',
	deps='authkrb5 samba-credentials',
	)
