#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('KRB_INIT_CTX',
		    source='krb5_init_context.c',
		    deps='gssapi krb5samba'
		   )

bld.SAMBA_LIBRARY('authkrb5',
                  source='kerberos_pac.c',
                  autoproto='proto.h',
                  public_deps='ndr-krb5pac krb5samba samba_socket LIBCLI_RESOLVE asn1',
                  deps='common_auth tevent LIBPACKET ndr ldb krb5samba KRB_INIT_CTX KRB5_PAC samba-errors',
                  private_library=True
                  )

bld.SAMBA_SUBSYSTEM('KERBEROS_UTIL',
	autoproto='kerberos_util.h',
	source='kerberos_util.c',
	deps='authkrb5 krb5samba com_err CREDENTIALS_KRB5',
	)

bld.SAMBA_SUBSYSTEM('KERBEROS_SRV_KEYTAB',
	autoproto='kerberos_srv_keytab.h',
	source='srv_keytab.c',
	deps='authkrb5',
	)
