#!/usr/bin/env python

bld.SAMBA_LIBRARY('LIBSECURITY_SESSION',
                  source='session.c',
                  autoproto='session_proto.h',
                  public_deps='LIBSECURITY',
                  private_library=True
                  )

