def options(opt):
    ''' This is a bit strange, but disable is the flag, not enable. '''
    opt.add_option('--disable-fault-handling', action='store_true', dest='disable_fault_handling', help=('disable the fault handlers'), default=False)

    opt.add_option('--with-systemd',
                   help=("Enable systemd integration"),
                   action='store_true', dest='enable_systemd')

    opt.add_option('--without-systemd',
                   help=("Disable systemd integration"),
                   action='store_false', dest='enable_systemd')

    opt.add_option('--with-lttng',
                   help=("Enable lttng integration"),
                   action='store_true', dest='enable_lttng')

    opt.add_option('--without-lttng',
                   help=("Disable lttng integration"),
                   action='store_false', dest='enable_lttng')

    opt.add_option('--with-gpfs',
                   help=("Directory under which gpfs headers are installed"),
                   action="store", dest='gpfs_headers_dir')
