#!/usr/bin/env python

bld.SAMBA_MODULE('gensec_ntlmssp',
	source='ntlmssp.c ntlmssp_sign.c ../../../libcli/auth/ntlmssp_sign.c ntlmssp_client.c ntlmssp_server.c',
	autoproto='proto.h',
	subsystem='gensec',
	init_function='gensec_ntlmssp_init',
	deps='MSRPC_PARSE CREDENTIALS NDR_NTLMSSP',
	internal_module=True
	)

