#!/usr/bin/env python

bld.SAMBA_MODULE('gensec_ntlmssp',
	source='''ntlmssp.c
                  ntlmssp_client.c ntlmssp_server.c''',
	autoproto='proto.h',
	subsystem='gensec',
	init_function='gensec_ntlmssp_init',
	deps='samba-credentials NTLMSSP_COMMON',
	internal_module=True
	)

