#!/usr/bin/env python

bld.SAMBA_MODULE('gensec_ntlmssp',
	source='''ntlmssp.c ntlmssp_sign.c
                  ntlmssp_client.c ntlmssp_server.c
                  ../../../libcli/auth/ntlmssp_sign.c
                  ../../../libcli/auth/ntlmssp_ndr.c
                  ../../../libcli/auth/ntlmssp.c
                  ../../../libcli/auth/ntlmssp_server.c''',
	autoproto='proto.h',
	subsystem='gensec',
	init_function='gensec_ntlmssp_init',
	deps='MSRPC_PARSE credentials NDR_NTLMSSP',
	internal_module=True
	)

