#!/usr/bin/env python

bld.SAMBA_MODULE('service_smb',
	source='service_smb.c',
	autoproto='service_smb_proto.h',
	subsystem='service',
	init_function='server_service_smb_init',
	deps='SMB_SERVER netif shares samba-hostconfig',
	internal_module=False,
	enabled=bld.AD_DC_BUILD_IS_ENABLED()
	)

bld.SAMBA_SUBSYSTEM('SMB_SERVER',
	source='handle.c tcon.c session.c blob.c management.c smb_server.c',
	autoproto='smb_server_proto.h',
	public_deps='share LIBPACKET SMB_PROTOCOL SMB2_PROTOCOL',
	enabled=bld.AD_DC_BUILD_IS_ENABLED()
	)

bld.RECURSE('smb')
bld.RECURSE('smb2')
