#!/usr/bin/env python

bld.SAMBA_MODULE('SERVICE_SMB',
	source='smb_server.c',
	autoproto='service_smb_proto.h',
	subsystem='service',
	init_function='server_service_smb_init',
	deps='SMB_SERVER',
	internal_module=True
	)


bld.SAMBA_MODULE('SERVICE_SAMBA3_SMB',
	source='smb_samba3.c',
	subsystem='service',
	init_function='server_service_samba3_smb_init'
	)


bld.SAMBA_SUBSYSTEM('SMB_SERVER',
	source='handle.c tcon.c session.c blob.c management.c',
	autoproto='smb_server_proto.h',
	public_deps='share LIBPACKET SMB_PROTOCOL SMB2_PROTOCOL'
	)

bld.RECURSE('smb')
bld.RECURSE('smb2')
