#!/bin/bash

export TEST_SCRIPTS_DIR=$(cd $(dirname $0) ; pwd)
export CTDB_DIR=$(dirname $(dirname $TEST_SCRIPTS_DIR))
var_dir=$CTDB_DIR/tests/var

######################################################################

PATH="${TEST_SCRIPTS_DIR}:${PATH}"

export CTDB_TIMEOUT=60

######################################################################

if [ -n "$CTDB_TEST_REMOTE_DIR" ] ; then
    CTDB_TEST_WRAPPER="${CTDB_TEST_REMOTE_DIR}/test_wrap"
else
    CTDB_TEST_WRAPPER="${TEST_SCRIPTS_DIR}/test_wrap"
fi
export CTDB_TEST_WRAPPER

# If $VALGRIND is set then use it whenever ctdb is called, but only if
# $CTDB is not already set.
[ -n "$CTDB" ] || export CTDB="${VALGRIND}${VALGRIND:+ }ctdb"

######################################################################

"$@"
