#!/bin/sh -e
#
# $Id: unpatch-source,v 1.2.4.1 2003/06/01 04:30:13 peloy Exp $
#

# We want to reverse the patches in the opposite order we applied
#	them, hence the 'ls|sort -r'.
for patch in `ls debian/patches/*.patch | sort -r`; do
	patch -p1 -R < $patch
done

perl -pi -e's/-.* for Debian//' source/include/version.h

# Regenerate configure only if it is older than configure.in
[ source/configure -ot source/configure.in ] && (cd source && autoheader && autoconf)

exit 0
