#! /bin/sh
# $Id$

if [ "$#" -lt 1 -o "$#" -gt 2 ]; then
	echo "Usage: `basename $0` proto-file [output]"
	exit 1
fi

infile="$1"
outfile="$2"
if [ "$outfile" = "" ]; then
    outfile=`basename "$infile" .in`
fi

if rm -f "$outfile" ; then :; else
	echo "Failed to remove $outfile"
	exit 1
fi

d=`dirname $0`

for i in `cat "$infile"`; do
	if [ -f "$i" ]; then
		cat "$i" >> "$outfile"
	elif [ -f "$d/$i" ]; then
		cat "$d/$i" >> "$outfile"
	else
		echo "$i: File not found"
		exit 1
	fi
done
