.\" $Id$
.\"
.Dd Aug 27, 1997
.Dt KDB_EDIT 8
.Os HEIMDAL
.Sh NAME
.Nm kdb_edit
.Nd
edit a local kerberos database
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
allows interactive editing of a local kerberos database. When started
it enters a command mode with line editing and history
functions. Commands may be abbreviated as long as they are
unique. These are implemented:
.Bl -tag -width Ds
.It add_new_key Ar principal
.It ank Ar principal
Create a new entry called
.Ar principal
in the database.
.It modify_entry Ar principal
Change the entry
.Ar principal .
.It dump Op Ar file
Write the database into a ascii-format into the file
.Ar file ,
or standard out if no file is specified.
.It load Ar file
Reads the database from a dump in
.Ar file .
.It merge Ar file
Merge in the contents of the dump in
.Ar file .
.It help
.It init Ar realm
Create entries in the database for a new realm
.Ar realm .
.It get_entry Ar principal
Show the entry for
.Ar principal .
.It delete Ar principal
Remove the entry for
.Ar principal
from the database.
.It ext_keytab Ar principal
Extract the key for
.Ar principal
and write it to a keytab.
.It exit
.El
.Sh SEE ALSO
.Xr ktutil 8
