.\" $Id$
.\"
.Dd Aug 27, 1997
.Dt KTUTIL 8
.Os HEIMDAL
.Sh NAME
.Nm ktutil
.Ar command
.Nd
handle a keytab
.Sh DESCRIPTION
.Nm
is the program for managing a keytab.
.Ar command
can be one of these:
.Bl -tag -width Ds
.It list Op Ar keytab
List the keys stored in the keytab
.Ar keytab .
.It srvconvert
.It srv2keytab Xo
.Op Fl s Ar srvtab
.Op Fl -srvtab= Ns Ar srvtab
.Op Fl k Ar keytab
.Op Fl -keytab= Ns Ar keytab
.Xc
Converts the version 4 srvtab in
.Ar srvtab
to a version 5 keytab and stores it in
.Ar keytab .
.El
.\" .Sh SEE ALSO
.\" .Xr kadmin 8
