#!/usr/bin/env python

bld.SAMBA_LIBRARY('LIBWBCLIENT',
                  source='wbc_guid.c wbc_idmap.c wbclient.c wbc_pam.c wbc_pwd.c wbc_sid.c wbc_util.c',
                  deps='LIBWINBIND-CLIENT',
                  private_library=True
                  )
