#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('ctdb-util',
                     source='''util.c util_file.c util_time.c
                               debug.c fault.c idtree.c signal.c
                               substitute.c''',
                      deps='tdb talloc tevent',
                      local_include=False,
                      )
