#!/usr/bin/env python

VERSION = '0.9.8'

srcdir = '../..'
blddir = 'bin'

import sys
sys.path.insert(0, srcdir+"/buildtools/wafsamba")
import wafsamba

LIBREPLACE_DIR= srcdir + '/lib/replace'
LIBTALLOC_DIR=  srcdir + '/lib/talloc'

def set_options(opt):
    opt.BUILTIN_DEFAULT('replace')
    opt.BUNDLED_EXTENSION_DEFAULT('tevent', noextenion='tevent')
    opt.recurse(LIBREPLACE_DIR)
    opt.recurse(LIBTALLOC_DIR)

def configure(conf):
    conf.sub_config(LIBREPLACE_DIR)
    conf.sub_config(LIBTALLOC_DIR)

    if conf.CHECK_BUNDLED_SYSTEM('tevent', minversion=VERSION,
                                 onlyif='talloc', implied_deps='replace talloc'):
        conf.define('USING_SYSTEM_TEVENT', 1)

    if conf.CHECK_FUNCS('epoll_create', headers='sys/epoll.h'):
        conf.DEFINE('HAVE_EPOLL', 1)

    conf.SAMBA_CONFIG_H()

def build(bld):
    bld.BUILD_SUBDIR(LIBREPLACE_DIR)
    bld.BUILD_SUBDIR(LIBTALLOC_DIR)

    SRC = '''tevent.c tevent_debug.c tevent_fd.c tevent_immediate.c
             tevent_queue.c tevent_req.c tevent_select.c
             tevent_signal.c tevent_standard.c tevent_timed.c tevent_util.c tevent_wakeup.c'''

    if bld.CONFIG_SET('HAVE_EPOLL'):
        SRC += ' tevent_epoll.c'

    if not bld.CONFIG_SET('USING_SYSTEM_TEVENT'):
        bld.SAMBA_LIBRARY('tevent',
                          SRC,
                          deps='replace talloc',
                          enabled= not bld.CONFIG_SET('USING_SYSTEM_TEVENT'),
                          vnum=VERSION)
