#!/usr/bin/env python

APPNAME = 'tevent'
VERSION = '0.9.8'

blddir = 'bin'

import sys, os

# find the buildtools directory
buildtools = 'buildtools'
while not os.path.exists(buildtools) and len(buildtools.split('/')) < 5:
    buildtools = '../' + buildtools
srcdir = os.path.dirname(buildtools) or '.'

sys.path.insert(0, buildtools + "/wafsamba")

import wafsamba, samba_dist

samba_dist.DIST_DIRS('lib/tevent:. lib/replace:lib/replace lib/talloc:lib/talloc buildtools:buildtools')

LIBREPLACE_DIR= '../replace'
LIBTALLOC_DIR=  '../talloc'

def set_options(opt):
    opt.BUILTIN_DEFAULT('replace')
    opt.BUNDLED_EXTENSION_DEFAULT('tevent', noextenion='tevent')
    opt.RECURSE(LIBREPLACE_DIR)
    opt.RECURSE(LIBTALLOC_DIR)

def configure(conf):
    conf.RECURSE(LIBREPLACE_DIR)
    conf.RECURSE(LIBTALLOC_DIR)

    if conf.CHECK_BUNDLED_SYSTEM('tevent', minversion=VERSION,
                                 onlyif='talloc', implied_deps='replace talloc'):
        conf.define('USING_SYSTEM_TEVENT', 1)

    if conf.CHECK_FUNCS('epoll_create', headers='sys/epoll.h'):
        conf.DEFINE('HAVE_EPOLL', 1)

    conf.SAMBA_CONFIG_H()

def build(bld):
    bld.RECURSE(LIBREPLACE_DIR)
    bld.RECURSE(LIBTALLOC_DIR)

    SRC = '''tevent.c tevent_debug.c tevent_fd.c tevent_immediate.c
             tevent_queue.c tevent_req.c tevent_select.c
             tevent_signal.c tevent_standard.c tevent_timed.c tevent_util.c tevent_wakeup.c'''

    if bld.CONFIG_SET('HAVE_EPOLL'):
        SRC += ' tevent_epoll.c'

    if not bld.CONFIG_SET('USING_SYSTEM_TEVENT'):
        bld.SAMBA_LIBRARY('tevent',
                          SRC,
                          deps='replace talloc',
                          enabled= not bld.CONFIG_SET('USING_SYSTEM_TEVENT'),
                          vnum=VERSION)
