Import('hostenv')
dsdb_ldb_modules = []

dsdb_ldb_modules.append(
	hostenv.Library('ldb_objectguid',
	['samdb/ldb_modules/objectguid.c']))

dsdb_ldb_modules.append(
	hostenv.Library('ldb_samldb',['samdb/ldb_modules/samldb.c']))

dsdb_ldb_modules.append(
	hostenv.Library('ldb_samba3sam',
	['samdb/ldb_modules/samba3sam.c']))

Export('dsdb_ldb_modules')

samdb_files = ['samdb/samdb.c','samdb/samdb_privilege.c','common/flag_mapping.c']
hostenv.Library('samdb',samdb_files)
hostenv.proto_headers += hostenv.CProtoHeader(samdb_files)
