# Italian messages for international release of SWAT.
# Copyright (C) 2001 Simo Sorce <idra@samba.org>

msgid ""
msgstr ""
"Project-Id-Version: i18n_swat \n"
"POT-Creation-Date: 2001-09-20 14:05+0100\n"
"PO-Revision-Date: 2000-02-08 14:45+0100\n"
"Last-Translator: Simo Sorce <idra@samba.org>\n"
"Language-Team: (Samba Team) <samba-technical@samba.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=US-ASCII\n"
"Content-Transfer-Encoding: \n"

#: web/swat.c:120
#, c-format
msgid "ERROR: Can't open %s\n"
msgstr "ERRORE: Impossibile aprire %s\n"

#.
#. str = stripspace(parm->label);
#. strlower (str); //monyo
#. d_printf("<tr><td><A HREF=\"/swat/help/smb.conf.5.html#%s\" target=\"docs\">%s</A>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; %s</td><td>",
#. str, _("Help"), parm->label);
#.
#: web/swat.c:211
msgid "Help"
msgstr "Aiuto"

#: web/swat.c:217 web/swat.c:231 web/swat.c:246 web/swat.c:254 web/swat.c:263
#: web/swat.c:272 web/swat.c:278 web/swat.c:284 web/swat.c:297
msgid "Set Default"
msgstr "Imposta Default"

#: web/swat.c:502
#, c-format
msgid "Logged in as <b>%s</b><p>\n"
msgstr "Connesso come <b>%s</b><p>\n"

#: web/swat.c:505
msgid "Home"
msgstr "Home"

#: web/swat.c:507
msgid "Globals"
msgstr "Globali"

#: web/swat.c:508
msgid "Shares"
msgstr "Condivisioni"

#: web/swat.c:509
msgid "Printers"
msgstr "Stampanti"

#: web/swat.c:512
msgid "Status"
msgstr "Stato"

#: web/swat.c:513
msgid "View Config"
msgstr "Visualizza Configurazione"

#: web/swat.c:515
msgid "Password Management"
msgstr "Gestione Password"

#: web/swat.c:539
msgid "Current Config"
msgstr "Configurazione Attuale"

#: web/swat.c:543
msgid "Normal View"
msgstr "Vista Normale"

#: web/swat.c:545
msgid "Full View"
msgstr "Vista Completa"

#: web/swat.c:561
msgid "Global Variables"
msgstr "Variabili Globali"

#: web/swat.c:575 web/swat.c:671 web/swat.c:1014
msgid "Commit Changes"
msgstr "Salva Modifiche"

#: web/swat.c:579 web/swat.c:674 web/swat.c:1016
msgid "Reset Values"
msgstr "Resetta Valori"

#: web/swat.c:581 web/swat.c:676 web/swat.c:1018
msgid "Advanced View"
msgstr "Vista Avanzata"

#: web/swat.c:583 web/swat.c:678 web/swat.c:1020
msgid "Basic View"
msgstr "Vista Semplice"

#: web/swat.c:613
msgid "Share Parameters"
msgstr "Parametri Condivisioni"

#: web/swat.c:642
msgid "Choose Share"
msgstr "Scegli Condivisione"

#: web/swat.c:656
msgid "Delete Share"
msgstr "Cancella Condivisione"

#: web/swat.c:663
msgid "Create Share"
msgstr "Crea Condivisione"

#: web/swat.c:708
msgid "password change in demo mode rejected\n"
msgstr "cambio password in modalita' demo rigettata"

#: web/swat.c:747
msgid " Must specify \"User Name\" \n"
msgstr " \"Nome Utente\" deve essere specificato \n"

#: web/swat.c:763
msgid " Must specify \"Old Password\" \n"
msgstr " \"Vecchia Password\" deve essere specificato \n"

#: web/swat.c:769
msgid " Must specify \"Remote Machine\" \n"
msgstr " \"Macchina Remota\" deve essere specificato \n"

#: web/swat.c:776
msgid " Must specify \"New, and Re-typed Passwords\" \n"
msgstr " "Nuova/Conferma Password" devono essere specificati \n"

#: web/swat.c:782
msgid " Re-typed password didn't match new password\n"
msgstr " la password di conferma non e' uguale alla nuova password\n"

#: web/swat.c:812
#, c-format
msgid " The passwd for '%s' has been changed. \n"
msgstr " La password per '%s' e' stata cambiata. \n"

#: web/swat.c:814
#, c-format
msgid " The passwd for '%s' has NOT been changed. \n"
msgstr " La password per '%s' non e' stata cambianta. \n"

#: web/swat.c:838
msgid "Server Password Management"
msgstr "Gestione Password del Server"

#.
#. * Create all the dialog boxes for data collection
#.
#: web/swat.c:847 web/swat.c:894
msgid " User Name : "
msgstr " Nome Utente : "

#: web/swat.c:850 web/swat.c:896
msgid " Old Password : "
msgstr " Vecchia Password : "

#: web/swat.c:853 web/swat.c:898
msgid " New Password : "
msgstr " Nuova Password : "

#: web/swat.c:855 web/swat.c:900
msgid " Re-type New Password : "
msgstr " Conferma nuova Password : "

#: web/swat.c:863 web/swat.c:911
msgid "Change Password"
msgstr "Cambia Password"

#: web/swat.c:866
msgid "Add New User"
msgstr "Aggiungi Nuovo Utente"

#: web/swat.c:868
msgid "Delete User"
msgstr "Cancella Utente"

#: web/swat.c:870
msgid "Disable User"
msgstr "Disabilita Utente"

#: web/swat.c:872
msgid "Enable User"
msgstr "Abilita Utente"

#: web/swat.c:885
msgid "Client/Server Password Management"
msgstr "Gestione Password Client/Server"

#: web/swat.c:902
msgid " Remote Machine : "
msgstr " Macchina Remota : "

#: web/swat.c:940
msgid "Printer Parameters"
msgstr "Parametri Stampante"

#: web/swat.c:942
msgid "Important Note:"
msgstr "Nota Importante:"

#: web/swat.c:943
msgid "Printer names marked with [*] in the Choose Printer drop-down box "
msgstr "nomi di stampante marcati con [*] nel riquadro a scomparsa Scegli Stampante"

#: web/swat.c:944
msgid "are autoloaded printers from "
msgstr "sono stampanti caricate automaticamente da "

#: web/swat.c:945
msgid "Printcap Name"
msgstr "Nome Printcap"

#: web/swat.c:946
msgid "Attempting to delete these printers from SWAT will have no effect.\n"
msgstr "Il tentativo di cancellare queste stampanti da sWAT non avara' effetto.\n"

#: web/swat.c:980
msgid "Choose Printer"
msgstr "Scegli Stampante"

#: web/swat.c:999
msgid "Delete Printer"
msgstr "Cancella Stampante"

#: web/swat.c:1006
msgid "Create Printer"
msgstr "Crea Stampante"

#: web/statuspage.c:40
msgid "DENY_NONE"
msgstr ""

#: web/statuspage.c:41
msgid "DENY_ALL   "
msgstr ""

#: web/statuspage.c:42
msgid "DENY_DOS   "
msgstr ""

#: web/statuspage.c:43
msgid "DENY_READ  "
msgstr ""

#: web/statuspage.c:44
msgid "DENY_WRITE "
msgstr ""

#: web/statuspage.c:50
msgid "RDONLY     "
msgstr ""

#: web/statuspage.c:51
msgid "WRONLY     "
msgstr ""

#: web/statuspage.c:52
msgid "RDWR       "
msgstr ""

#: web/statuspage.c:60
msgid "EXCLUSIVE+BATCH "
msgstr ""

#: web/statuspage.c:62
msgid "EXCLUSIVE       "
msgstr ""

#: web/statuspage.c:64
msgid "BATCH           "
msgstr ""

#: web/statuspage.c:66
msgid "LEVEL_II        "
msgstr ""

#: web/statuspage.c:68
msgid "NONE            "
msgstr ""

#: web/statuspage.c:195
msgid "Server Status"
msgstr "Stato del Server"

#: web/statuspage.c:200
msgid "Auto Refresh"
msgstr "Rinfresco Automatico"

#: web/statuspage.c:201 web/statuspage.c:206
msgid "Refresh Interval: "
msgstr "Intervallo Rinfresco: "

#: web/statuspage.c:205
msgid "Stop Refreshing"
msgstr "Ferma Rinfresco"

#: web/statuspage.c:220
msgid "version:"
msgstr "versione:"

#: web/statuspage.c:223
msgid "smbd:"
msgstr ""

#: web/statuspage.c:223 web/statuspage.c:235
msgid "running"
msgstr "attivo"

#: web/statuspage.c:223 web/statuspage.c:235
msgid "not running"
msgstr "non attivo"

#: web/statuspage.c:226
msgid "Stop smbd"
msgstr "Ferma smbd"

#: web/statuspage.c:228
msgid "Start smbd"
msgstr "Lancia smbd"

#: web/statuspage.c:230
msgid "Restart smbd"
msgstr "Rilancia smbd"

#: web/statuspage.c:235
msgid "nmbd:"
msgstr ""

#: web/statuspage.c:238
msgid "Stop nmbd"
msgstr "Ferma nmbd"

#: web/statuspage.c:240
msgid "Start nmbd"
msgstr "Lancia nmbd"

#: web/statuspage.c:242
msgid "Restart nmbd"
msgstr "Rilancia nmbd"

#: web/statuspage.c:249
msgid "Active Connections"
msgstr "Connessioni Attive"

#: web/statuspage.c:251 web/statuspage.c:264 web/statuspage.c:272
msgid "PID"
msgstr ""

#: web/statuspage.c:251 web/statuspage.c:264
msgid "Client"
msgstr ""

#: web/statuspage.c:251
msgid "IP address"
msgstr "indirizzo IP"

#: web/statuspage.c:251 web/statuspage.c:264 web/statuspage.c:272
msgid "Date"
msgstr "Data"

#: web/statuspage.c:253
msgid "Kill"
msgstr "Termina"

#: web/statuspage.c:261
msgid "Active Shares"
msgstr "Condivisioni Attive"

#: web/statuspage.c:264
msgid "Share"
msgstr "Condivisione"

#: web/statuspage.c:264
msgid "User"
msgstr "Utente"

#: web/statuspage.c:264
msgid "Group"
msgstr "Gruppo"

#: web/statuspage.c:270
msgid "Open Files"
msgstr "File Aperti"

#: web/statuspage.c:272
msgid "Sharing"
msgstr ""

#: web/statuspage.c:272
msgid "R/W"
msgstr ""

#: web/statuspage.c:272
msgid "Oplock"
msgstr ""

#: web/statuspage.c:272
msgid "File"
msgstr ""

#: param/loadparm.c:641
msgid "Base Options"
msgstr "Opzioni Basilari"

#: param/loadparm.c:643
msgid "dos charset"
msgstr "set caratteri dos"

#: param/loadparm.c:644
msgid "unix charset"
msgstr "set caratteri unix"

#: param/loadparm.c:645
msgid "display charset"
msgstr "set caratteri display"

#: param/loadparm.c:646
msgid "comment"
msgstr "commento"

#: param/loadparm.c:647
msgid "path"
msgstr "percorso"

#: param/loadparm.c:648
msgid "directory"
msgstr ""

#: param/loadparm.c:649
msgid "workgroup"
msgstr ""

#: param/loadparm.c:650
msgid "netbios name"
msgstr "nome netbios"

#: param/loadparm.c:651
msgid "netbios aliases"
msgstr "alias netbios"

#: param/loadparm.c:652
msgid "netbios scope"
msgstr "scope netbios"

#: param/loadparm.c:653
msgid "server string"
msgstr "stringa server"

#: param/loadparm.c:654
msgid "interfaces"
msgstr "interfacce"

#: param/loadparm.c:655
msgid "bind interfaces only"
msgstr "usa solo interfacce definite"

#: param/loadparm.c:657
msgid "Security Options"
msgstr "Opzioni di Sicurezza"

#: param/loadparm.c:659
msgid "security"
msgstr "sicurezza"

#: param/loadparm.c:660
msgid "encrypt passwords"
msgstr "password cryptate"

#: param/loadparm.c:661
msgid "update encrypted"
msgstr "aggiorna criptate"

#: param/loadparm.c:662
msgid "allow trusted domains"
msgstr "permetti domini trusted"

#: param/loadparm.c:663
msgid "alternate permissions"
msgstr "permessi alternativi"

#: param/loadparm.c:664
msgid "hosts equiv"
msgstr ""

#: param/loadparm.c:665
msgid "min passwd length"
msgstr "minima lunghezza passwd"

#: param/loadparm.c:666
msgid "min password length"
msgstr "minima lunghezza password"

#: param/loadparm.c:667
msgid "map to guest"
msgstr "mappa su ospite"

#: param/loadparm.c:668
msgid "null passwords"
msgstr "password nulle"

#: param/loadparm.c:669
msgid "obey pam restrictions"
msgstr "usa restrizioni pam"

#: param/loadparm.c:670
msgid "password server"
msgstr ""

#: param/loadparm.c:671
msgid "smb passwd file"
msgstr ""

#: param/loadparm.c:672
msgid "private dir"
msgstr "directory privata"

#: param/loadparm.c:673
msgid "passdb module path"
msgstr "percorso modulo passdb"

#: param/loadparm.c:674
msgid "root directory"
msgstr ""

#: param/loadparm.c:675
msgid "root dir"
msgstr ""

#: param/loadparm.c:676
msgid "root"
msgstr ""

#: param/loadparm.c:678
msgid "pam password change"
msgstr ""

#: param/loadparm.c:679
msgid "passwd program"
msgstr ""

#: param/loadparm.c:680
msgid "passwd chat"
msgstr ""

#: param/loadparm.c:681
msgid "passwd chat debug"
msgstr ""

#: param/loadparm.c:682
msgid "username map"
msgstr "mappa nomi utenti"

#: param/loadparm.c:683
msgid "password level"
msgstr "livello password"

#: param/loadparm.c:684
msgid "username level"
msgstr "livello nome utente"

#: param/loadparm.c:685
msgid "unix password sync"
msgstr "sincronizza password unix"

#: param/loadparm.c:686
msgid "restrict anonymous"
msgstr "limita anonimo"

#: param/loadparm.c:687
msgid "lanman auth"
msgstr ""

#: param/loadparm.c:688
msgid "ntlm auth"
msgstr ""

#: param/loadparm.c:689
msgid "plaintext to smbpasswd"
msgstr "da plaintext a smbpasswd"

#: param/loadparm.c:690
msgid "use rhosts"
msgstr "usa rhosts"

#: param/loadparm.c:692
msgid "username"
msgstr "nome utente"

#: param/loadparm.c:693
msgid "user"
msgstr "utente"

#: param/loadparm.c:694
msgid "users"
msgstr "utenti"

#: param/loadparm.c:696
msgid "guest account"
msgstr "account ospite"

#: param/loadparm.c:697
msgid "invalid users"
msgstr "utenti non validi"

#: param/loadparm.c:698
msgid "valid users"
msgstr "utenti validi"

#: param/loadparm.c:699
msgid "admin users"
msgstr "utenti amministratori"

#: param/loadparm.c:700
msgid "read list"
msgstr ""

#: param/loadparm.c:701
msgid "write list"
msgstr ""

#: param/loadparm.c:702
msgid "printer admin"
msgstr "amministratore stmapnati"

#: param/loadparm.c:703
msgid "force user"
msgstr "forza utente"

#: param/loadparm.c:704
msgid "force group"
msgstr "forza gruppo"

#: param/loadparm.c:705
msgid "group"
msgstr "gruppo"

#: param/loadparm.c:707
msgid "read only"
msgstr "sola lettura"

#: param/loadparm.c:708
msgid "write ok"
msgstr "ok scrittura"

#: param/loadparm.c:709
msgid "writeable"
msgstr "scrivibile"

#: param/loadparm.c:710
msgid "writable"
msgstr "scrivibile"

#: param/loadparm.c:712
msgid "create mask"
msgstr ""

#: param/loadparm.c:713
msgid "create mode"
msgstr ""

#: param/loadparm.c:714
msgid "force create mode"
msgstr "forza create mode"

#: param/loadparm.c:715
msgid "security mask"
msgstr ""

#: param/loadparm.c:716
msgid "force security mode"
msgstr "forza security mode"

#: param/loadparm.c:717
msgid "directory mask"
msgstr ""

#: param/loadparm.c:718
msgid "directory mode"
msgstr ""

#: param/loadparm.c:719
msgid "force directory mode"
msgstr "forza directory mode"

#: param/loadparm.c:720
msgid "directory security mask"
msgstr ""

#: param/loadparm.c:721
msgid "force directory security mode"
msgstr "forza directory security mode"

#: param/loadparm.c:722
msgid "inherit permissions"
msgstr "eredita permessi"

#: param/loadparm.c:723
msgid "guest only"
msgstr "solo ospite"

#: param/loadparm.c:724
msgid "only guest"
msgstr "solo ospite"

#: param/loadparm.c:726
msgid "guest ok"
msgstr "ok ospite"

#: param/loadparm.c:727
msgid "public"
msgstr "pubblico"

#: param/loadparm.c:729
msgid "only user"
msgstr "solo utente"

#: param/loadparm.c:730
msgid "hosts allow"
msgstr "permetti hosts"

#: param/loadparm.c:731
msgid "allow hosts"
msgstr "permetti hosts"

#: param/loadparm.c:732
msgid "hosts deny"
msgstr "vieta hosts"

#: param/loadparm.c:733
msgid "deny hosts"
msgstr "vieta hosts"

#: param/loadparm.c:736
msgid "Secure Socket Layer Options"
msgstr "Opzioni Secure Socket Layer"

#: param/loadparm.c:737
msgid "ssl"
msgstr ""

#: param/loadparm.c:739
msgid "ssl hosts"
msgstr ""

#: param/loadparm.c:740
msgid "ssl hosts resign"
msgstr ""

#: param/loadparm.c:741
msgid "ssl CA certDir"
msgstr ""

#: param/loadparm.c:742
msgid "ssl CA certFile"
msgstr ""

#: param/loadparm.c:743
msgid "ssl server cert"
msgstr ""

#: param/loadparm.c:744
msgid "ssl server key"
msgstr ""

#: param/loadparm.c:745
msgid "ssl client cert"
msgstr ""

#: param/loadparm.c:746
msgid "ssl client key"
msgstr ""

#: param/loadparm.c:747
msgid "ssl require clientcert"
msgstr "ssl richiede certificato client"

#: param/loadparm.c:748
msgid "ssl require servercert"
msgstr "ssl richiede certificato server"

#: param/loadparm.c:749
msgid "ssl ciphers"
msgstr ""

#: param/loadparm.c:750
msgid "ssl version"
msgstr "ssl versione"

#: param/loadparm.c:751
msgid "ssl compatibility"
msgstr ""

#: param/loadparm.c:754
msgid "Logging Options"
msgstr "Opzioni di Log"

#: param/loadparm.c:755
msgid "log level"
msgstr "livello log"

#: param/loadparm.c:756
msgid "debuglevel"
msgstr "livello debug"

#: param/loadparm.c:757
msgid "syslog"
msgstr ""

#: param/loadparm.c:758
msgid "syslog only"
msgstr "solo syslog"

#: param/loadparm.c:759
msgid "log file"
msgstr "file di log"

#: param/loadparm.c:761
msgid "max log size"
msgstr "massima dimensione log"

#: param/loadparm.c:762
msgid "timestamp logs"
msgstr ""

#: param/loadparm.c:763
msgid "debug timestamp"
msgstr ""

#: param/loadparm.c:764
msgid "debug hires timestamp"
msgstr ""

#: param/loadparm.c:765
msgid "debug pid"
msgstr ""

#: param/loadparm.c:766
msgid "debug uid"
msgstr ""

#: param/loadparm.c:768
msgid "Protocol Options"
msgstr "Opzioni Protocollo"

#: param/loadparm.c:770
msgid "protocol"
msgstr "protocollo"

#: param/loadparm.c:771
msgid "large readwrite"
msgstr ""

#: param/loadparm.c:772
msgid "max protocol"
msgstr "protocollo massimo"

#: param/loadparm.c:773
msgid "min protocol"
msgstr "protocollo minimo"

#: param/loadparm.c:774
msgid "unicode"
msgstr ""

#: param/loadparm.c:775
msgid "read bmpx"
msgstr ""

#: param/loadparm.c:776
msgid "read raw"
msgstr ""

#: param/loadparm.c:777
msgid "write raw"
msgstr ""

#: param/loadparm.c:779
msgid "nt smb support"
msgstr "supporto smb nt"

#: param/loadparm.c:780
msgid "nt pipe support"
msgstr "supporto pipe nt"

#: param/loadparm.c:781
msgid "nt acl support"
msgstr "supporto acl nt"

#: param/loadparm.c:782
msgid "announce version"
msgstr "annuncia versione"

#: param/loadparm.c:783
msgid "announce as"
msgstr "annuncia come"

#: param/loadparm.c:784
msgid "max mux"
msgstr "mux massimo"

#: param/loadparm.c:785
msgid "max xmit"
msgstr "xmit massimo"

#: param/loadparm.c:787
msgid "name resolve order"
msgstr "ordine risoluzione nomi"

#: param/loadparm.c:788
msgid "max packet"
msgstr "pacchetto massimo"

#: param/loadparm.c:789
msgid "packet size"
msgstr "dimensione pacchetto"

#: param/loadparm.c:790
msgid "max ttl"
msgstr "ttl massimo"

#: param/loadparm.c:791
msgid "max wins ttl"
msgstr "wins ttl massimo"

#: param/loadparm.c:792
msgid "min wins ttl"
msgstr "wins ttl minimo"

#: param/loadparm.c:793
msgid "time server"
msgstr ""

#: param/loadparm.c:795
msgid "Tuning Options"
msgstr "Opzioni Tuning"

#: param/loadparm.c:797
msgid "change notify timeout"
msgstr ""

#: param/loadparm.c:798
msgid "deadtime"
msgstr ""

#: param/loadparm.c:799
msgid "getwd cache"
msgstr ""

#: param/loadparm.c:800
msgid "keepalive"
msgstr ""

#: param/loadparm.c:802
msgid "lpq cache time"
msgstr ""

#: param/loadparm.c:803
msgid "max smbd processes"
msgstr "massimo n. processi smbd"

#: param/loadparm.c:804
msgid "max connections"
msgstr "massimo n. connessioni"

#: param/loadparm.c:805
msgid "paranoid server security"
msgstr ""

#: param/loadparm.c:806
msgid "max disk size"
msgstr "massima dimensione disco"

#: param/loadparm.c:807
msgid "max open files"
msgstr "massimo n. file aperti"

#: param/loadparm.c:808
msgid "min print space"
msgstr "spazio stampa minimo"

#: param/loadparm.c:809
msgid "read size"
msgstr ""

#: param/loadparm.c:811
msgid "socket options"
msgstr "opzioni socket"

#: param/loadparm.c:812
msgid "stat cache size"
msgstr "dimensione stat cache"

#: param/loadparm.c:813
msgid "strict allocate"
msgstr "allocazione stretta"

#: param/loadparm.c:814
msgid "strict sync"
msgstr "sincronizzazione stretta"

#: param/loadparm.c:815
msgid "sync always"
msgstr "sincronizza sempre"

#: param/loadparm.c:816
msgid "use mmap"
msgstr "usa mmap"

#: param/loadparm.c:817
msgid "hostname lookups"
msgstr ""

#: param/loadparm.c:818
msgid "write cache size"
msgstr "dimensione write cache"

#: param/loadparm.c:820
msgid "Printing Options"
msgstr "Opzioni di Stampa"

#: param/loadparm.c:822
msgid "total print jobs"
msgstr "job stampa totali"

#: param/loadparm.c:823
msgid "max print jobs"
msgstr "massimo n. job stampa"

#: param/loadparm.c:824
msgid "load printers"
msgstr "carica stampanti"

#: param/loadparm.c:825
msgid "printcap name"
msgstr "nome printcap"

#: param/loadparm.c:826
msgid "printcap"
msgstr ""

#: param/loadparm.c:827
msgid "printable"
msgstr "stmpabile"

#: param/loadparm.c:828
msgid "print ok"
msgstr "ok stampa"

#: param/loadparm.c:829
msgid "postscript"
msgstr ""

#: param/loadparm.c:830
msgid "printing"
msgstr "stampa"

#: param/loadparm.c:831
msgid "print command"
msgstr "comando stampa"

#: param/loadparm.c:832
msgid "disable spoolss"
msgstr "disabilita spoolss"

#: param/loadparm.c:833
msgid "lpq command"
msgstr "comando lpq"

#: param/loadparm.c:834
msgid "lprm command"
msgstr "comando lprm"

#: param/loadparm.c:835
msgid "lppause command"
msgstr "comando lppause"

#: param/loadparm.c:836
msgid "lpresume command"
msgstr "comando lpresume"

#: param/loadparm.c:837
msgid "queuepause command"
msgstr "comando queuepause"

#: param/loadparm.c:838
msgid "queueresume command"
msgstr "comando queueresume"

#: param/loadparm.c:840
msgid "enumports command"
msgstr "cmando enumports"

#: param/loadparm.c:841
msgid "addprinter command"
msgstr "comando addprinter"

#: param/loadparm.c:842
msgid "deleteprinter command"
msgstr "comando deleteprinter"

#: param/loadparm.c:843
msgid "show add printer wizard"
msgstr "mostra wizard aggiungi stampanti"

#: param/loadparm.c:844
msgid "os2 driver map"
msgstr "mappa driver os2"

#: param/loadparm.c:846
msgid "printer name"
msgstr "nome stampante"

#: param/loadparm.c:847
msgid "printer"
msgstr "stampante"

#: param/loadparm.c:848
msgid "use client driver"
msgstr "usa client driver"

#: param/loadparm.c:849
msgid "printer driver"
msgstr "driver stampante"

#: param/loadparm.c:850
msgid "printer driver file"
msgstr "file driver stampante"

#: param/loadparm.c:851
msgid "printer driver location"
msgstr "posizione driver stampante"

#: param/loadparm.c:853
msgid "Filename Handling"
msgstr "Gestione Nomi File"

#: param/loadparm.c:854
msgid "strip dot"
msgstr "togli il punto"

#: param/loadparm.c:856
msgid "mangled stack"
msgstr ""

#: param/loadparm.c:857
msgid "default case"
msgstr ""

#: param/loadparm.c:858
msgid "case sensitive"
msgstr ""

#: param/loadparm.c:859
msgid "casesignames"
msgstr ""

#: param/loadparm.c:860
msgid "preserve case"
msgstr ""

#: param/loadparm.c:861
msgid "short preserve case"
msgstr ""

#: param/loadparm.c:862
msgid "mangle case"
msgstr ""

#: param/loadparm.c:863
msgid "mangling char"
msgstr ""

#: param/loadparm.c:864
msgid "hide dot files"
msgstr ""

#: param/loadparm.c:865
msgid "hide unreadable"
msgstr ""

#: param/loadparm.c:866
msgid "delete veto files"
msgstr ""

#: param/loadparm.c:867
msgid "veto files"
msgstr ""

#: param/loadparm.c:868
msgid "hide files"
msgstr "nascondi file"

#: param/loadparm.c:869
msgid "veto oplock files"
msgstr ""

#: param/loadparm.c:870
msgid "map system"
msgstr "mappa system"

#: param/loadparm.c:871
msgid "map hidden"
msgstr "mappa hidden"

#: param/loadparm.c:872
msgid "map archive"
msgstr "mappa archive"

#: param/loadparm.c:873
msgid "mangled names"
msgstr ""

#: param/loadparm.c:874
msgid "mangled map"
msgstr ""

#: param/loadparm.c:875
msgid "stat cache"
msgstr ""

#: param/loadparm.c:877
msgid "Domain Options"
msgstr "Opzioni Dominio"

#: param/loadparm.c:879
msgid "domain admin group"
msgstr "gruppo amministratori dominio"

#: param/loadparm.c:880
msgid "domain guest group"
msgstr "gruppo ospiti dominio"

#: param/loadparm.c:883
msgid "groupname map"
msgstr "mappa nome gruppo"

#: param/loadparm.c:886
msgid "machine password timeout"
msgstr ""

#: param/loadparm.c:888
msgid "Logon Options"
msgstr "Opzioni di Logon"

#: param/loadparm.c:890
msgid "add user script"
msgstr ""

#: param/loadparm.c:891
msgid "delete user script"
msgstr ""

#: param/loadparm.c:892
msgid "add group script"
msgstr ""

#: param/loadparm.c:893
msgid "delete group script"
msgstr ""

#: param/loadparm.c:894
msgid "add user to group script"
msgstr ""

#: param/loadparm.c:895
msgid "delete user from group script"
msgstr ""

#: param/loadparm.c:896
msgid "add machine script"
msgstr ""

#: param/loadparm.c:897
msgid "shutdown script"
msgstr ""

#: param/loadparm.c:898
msgid "abort shutdown script"
msgstr ""

#: param/loadparm.c:900
msgid "logon script"
msgstr ""

#: param/loadparm.c:901
msgid "logon path"
msgstr ""

#: param/loadparm.c:902
msgid "logon drive"
msgstr ""

#: param/loadparm.c:903
msgid "logon home"
msgstr ""

#: param/loadparm.c:904
msgid "domain logons"
msgstr ""

#: param/loadparm.c:906
msgid "Browse Options"
msgstr "Opzioni Browsing"

#: param/loadparm.c:908
msgid "os level"
msgstr "livello os"

#: param/loadparm.c:909
msgid "lm announce"
msgstr "annuncio lm"

#: param/loadparm.c:910
msgid "lm interval"
msgstr "intervallo lm"

#: param/loadparm.c:911
msgid "preferred master"
msgstr "master preferito"

#: param/loadparm.c:912
msgid "prefered master"
msgstr "master preferito"

#: param/loadparm.c:913
msgid "local master"
msgstr "master locale"

#: param/loadparm.c:914
msgid "domain master"
msgstr "master dominio"

#: param/loadparm.c:915
msgid "browse list"
msgstr "lista browsing"

#: param/loadparm.c:916
msgid "browseable"
msgstr ""

#: param/loadparm.c:917
msgid "browsable"
msgstr ""

#: param/loadparm.c:918
msgid "enhanced browsing"
msgstr ""

#: param/loadparm.c:920
msgid "WINS Options"
msgstr "opzioni WINS"

#: param/loadparm.c:921
msgid "dns proxy"
msgstr ""

#: param/loadparm.c:922
msgid "wins proxy"
msgstr ""

#: param/loadparm.c:924
msgid "wins server"
msgstr ""

#: param/loadparm.c:925
msgid "wins support"
msgstr ""

#: param/loadparm.c:926
msgid "wins hook"
msgstr ""

#: param/loadparm.c:928
msgid "Locking Options"
msgstr "Opzioni Locking"

#: param/loadparm.c:930
msgid "blocking locks"
msgstr ""

#: param/loadparm.c:931
msgid "fake oplocks"
msgstr ""

#: param/loadparm.c:932
msgid "kernel oplocks"
msgstr ""

#: param/loadparm.c:933
msgid "locking"
msgstr ""

#: param/loadparm.c:935
msgid "oplocks"
msgstr ""

#: param/loadparm.c:936
msgid "level2 oplocks"
msgstr ""

#: param/loadparm.c:937
msgid "oplock break wait time"
msgstr ""

#: param/loadparm.c:938
msgid "oplock contention limit"
msgstr ""

#: param/loadparm.c:939
msgid "posix locking"
msgstr ""

#: param/loadparm.c:940
msgid "strict locking"
msgstr ""

#: param/loadparm.c:941
msgid "share modes"
msgstr ""

#: param/loadparm.c:944
msgid "Ldap Options"
msgstr "Opzioni Ldap"

#: param/loadparm.c:946
msgid "ldap server"
msgstr ""

#: param/loadparm.c:947
msgid "ldap port"
msgstr ""

#: param/loadparm.c:948
msgid "ldap suffix"
msgstr ""

#: param/loadparm.c:949
msgid "ldap filter"
msgstr ""

#: param/loadparm.c:950
msgid "ldap root"
msgstr ""

#: param/loadparm.c:951
msgid "ldap root passwd"
msgstr ""

#: param/loadparm.c:954
msgid "Miscellaneous Options"
msgstr "Opzioni Generiche"

#: param/loadparm.c:955
msgid "add share command"
msgstr ""

#: param/loadparm.c:956
msgid "change share command"
msgstr ""

#: param/loadparm.c:957
msgid "delete share command"
msgstr ""

#: param/loadparm.c:959
msgid "config file"
msgstr "file configurazione"

#: param/loadparm.c:960
msgid "preload"
msgstr "precarica"

#: param/loadparm.c:961
msgid "auto services"
msgstr ""

#: param/loadparm.c:962
msgid "lock dir"
msgstr ""

#: param/loadparm.c:963
msgid "lock directory"
msgstr ""

#: param/loadparm.c:965
msgid "utmp directory"
msgstr ""

#: param/loadparm.c:966
msgid "wtmp directory"
msgstr ""

#: param/loadparm.c:967
msgid "utmp"
msgstr ""

#: param/loadparm.c:970
msgid "default service"
msgstr ""

#: param/loadparm.c:971
msgid "default"
msgstr ""

#: param/loadparm.c:972
msgid "message command"
msgstr "comando message"

#: param/loadparm.c:973
msgid "dfree command"
msgstr "comando dfree"

#: param/loadparm.c:974
msgid "remote announce"
msgstr "annuncio remoto"

#: param/loadparm.c:975
msgid "remote browse sync"
msgstr ""

#: param/loadparm.c:976
msgid "socket address"
msgstr ""

#: param/loadparm.c:977
msgid "homedir map"
msgstr ""

#: param/loadparm.c:978
msgid "time offset"
msgstr ""

#: param/loadparm.c:979
msgid "NIS homedir"
msgstr ""

#: param/loadparm.c:980
msgid "-valid"
msgstr ""

#: param/loadparm.c:982
msgid "copy"
msgstr "copia"

#: param/loadparm.c:983
msgid "include"
msgstr "includi"

#: param/loadparm.c:984
msgid "exec"
msgstr "esegui"

#: param/loadparm.c:985
msgid "preexec"
msgstr "pre-esegui"

#: param/loadparm.c:987
msgid "preexec close"
msgstr "pre-esegui e chiudi"

#: param/loadparm.c:988
msgid "postexec"
msgstr "post-esegui"

#: param/loadparm.c:989
msgid "root preexec"
msgstr "root pre-esegui"

#: param/loadparm.c:990
msgid "root preexec close"
msgstr "root pre-esegui e chiudi"

#: param/loadparm.c:991
msgid "root postexec"
msgstr "root post-esegui"

#: param/loadparm.c:992
msgid "available"
msgstr "disponibile"

#: param/loadparm.c:993
msgid "volume"
msgstr ""

#: param/loadparm.c:994
msgid "fstype"
msgstr "tipo file system"

#: param/loadparm.c:995
msgid "set directory"
msgstr ""

#: param/loadparm.c:996
msgid "source environment"
msgstr ""

#: param/loadparm.c:997
msgid "wide links"
msgstr ""

#: param/loadparm.c:998
msgid "follow symlinks"
msgstr ""

#: param/loadparm.c:999
msgid "dont descend"
msgstr "non discendere"

#: param/loadparm.c:1000
msgid "magic script"
msgstr ""

#: param/loadparm.c:1001
msgid "magic output"
msgstr ""

#: param/loadparm.c:1002
msgid "delete readonly"
msgstr "cancella sola-lettura"

#: param/loadparm.c:1003
msgid "dos filemode"
msgstr ""

#: param/loadparm.c:1004
msgid "dos filetimes"
msgstr ""

#: param/loadparm.c:1005
msgid "dos filetime resolution"
msgstr ""

#: param/loadparm.c:1007
msgid "fake directory create times"
msgstr ""

#: param/loadparm.c:1008
msgid "panic action"
msgstr ""

#: param/loadparm.c:1009
msgid "hide local users"
msgstr "nascondi utenti locali"

#: param/loadparm.c:1012
msgid "VFS options"
msgstr "Opzioni VFS"

#: param/loadparm.c:1014
msgid "vfs object"
msgstr ""

#: param/loadparm.c:1015
msgid "vfs options"
msgstr ""

#: param/loadparm.c:1018
msgid "msdfs root"
msgstr ""

#: param/loadparm.c:1019
msgid "host msdfs"
msgstr ""

#: param/loadparm.c:1021
msgid "Winbind options"
msgstr "Opzioni Winbind"

#: param/loadparm.c:1023
msgid "winbind uid"
msgstr ""

#: param/loadparm.c:1024
msgid "winbind gid"
msgstr ""

#: param/loadparm.c:1025
msgid "template homedir"
msgstr ""

#: param/loadparm.c:1026
msgid "template shell"
msgstr ""

#: param/loadparm.c:1027
msgid "winbind separator"
msgstr ""

#: param/loadparm.c:1028
msgid "winbind cache time"
msgstr ""

#: param/loadparm.c:1029
msgid "winbind enum users"
msgstr ""

#: param/loadparm.c:1030
msgid "winbind enum groups"
msgstr ""
