# Swat Turkish Translation
# Copyright (C) 2001 Deniz Akkus Kanca
# Deniz Akkus Kanca <deniz@arayan.com>, 2001.
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
msgid ""
msgstr ""
"Project-Id-Version: i18n_swat \n"
"POT-Creation-Date: 2001-09-20 20:29+0900\n"
"PO-Revision-Date: 2001-09-20 22:51EEST\n"
"Last-Translator: Deniz Akkus Kanca <deniz@arayan.com>\n"
"Language-Team: Turkish <gnu-tr-u12a@lists.sourceforge.net>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ISO-8859-9\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: KBabel 0.9.1\n"

#: web/swat.c:120
#, c-format
msgid "ERROR: Can't open %s\n"
msgstr "HATA: %s açýlamadý\n"

#.
#. str = stripspace(parm->label);
#. strlower (str); //monyo
#. d_printf("<tr><td><A HREF=\"/swat/help/smb.conf.5.html#%s\" target=\"docs\">%s</A>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; %s</td><td>",
#. str, _("Help"), parm->label);
#.
#: web/swat.c:211
msgid "Help"
msgstr "Yardým"

#: web/swat.c:217 web/swat.c:231 web/swat.c:246 web/swat.c:254 web/swat.c:263
#: web/swat.c:272 web/swat.c:278 web/swat.c:284 web/swat.c:297
msgid "Set Default"
msgstr "Öntanýmlýya Ayarla"

#: web/swat.c:502
#, c-format
msgid "Logged in as <b>%s</b><p>\n"
msgstr "<b>%s</b> kimliði ile oturum açýlmýþ<p>\n"

#: web/swat.c:505
msgid "Home"
msgstr "Ev"

#: web/swat.c:507
msgid "Globals"
msgstr "Evrenseller"

#: web/swat.c:508
msgid "Shares"
msgstr "Paylaþýmlar"

#: web/swat.c:509
msgid "Printers"
msgstr "Yazýcýlar"

#: web/swat.c:512
msgid "Status"
msgstr "Durum"

#: web/swat.c:513
msgid "View Config"
msgstr "Ayarlara Gözat"

#: web/swat.c:515
msgid "Password Management"
msgstr "Þifre Yönetimi"

#: web/swat.c:539
msgid "Current Config"
msgstr "Þimdiki Ayarlar"

#: web/swat.c:543
msgid "Normal View"
msgstr "Normal Görünüm"

#: web/swat.c:545
msgid "Full View"
msgstr "Tam Görünüm"

#: web/swat.c:561
msgid "Global Variables"
msgstr "Genel Deðiþkenler"

#: web/swat.c:575 web/swat.c:671 web/swat.c:1014
msgid "Commit Changes"
msgstr "Deðiþiklikleri Kaydet"

#: web/swat.c:579 web/swat.c:674 web/swat.c:1016
msgid "Reset Values"
msgstr "Deðerleri Ýlk Haline Getir"

#: web/swat.c:581 web/swat.c:676 web/swat.c:1018
msgid "Advanced View"
msgstr "Geliþmiþ Görünüm"

#: web/swat.c:583 web/swat.c:678 web/swat.c:1020
msgid "Basic View"
msgstr "Temel Görünüm"

#: web/swat.c:613
msgid "Share Parameters"
msgstr "Paylaþým Parametreleri"

#: web/swat.c:642
msgid "Choose Share"
msgstr "Paylaþým Seçin"

#: web/swat.c:656
msgid "Delete Share"
msgstr "Paylaþým Kaldýr"

#: web/swat.c:663
msgid "Create Share"
msgstr "Paylaþým Oluþtur"

#: web/swat.c:708
msgid "password change in demo mode rejected\n"
msgstr "demo kipinde þifre deðiþikliði kabul edilmedi\n"

#: web/swat.c:747
msgid " Must specify \"User Name\" \n"
msgstr " \"Kullanýcý Adý\" belirtilmeli \n"

#: web/swat.c:763
msgid " Must specify \"Old Password\" \n"
msgstr " \"Eski Þifre\" belirtilmeli \n"

#: web/swat.c:769
msgid " Must specify \"Remote Machine\" \n"
msgstr " \"Uzak Makina\" belirtilmeli \n"

#: web/swat.c:776
msgid " Must specify \"New, and Re-typed Passwords\" \n"
msgstr " \"Yeni ve Tekrar Girilmiþ Þifreler\" belirtilmeli \n"

#: web/swat.c:782
msgid " Re-typed password didn't match new password\n"
msgstr " Tekrar girilen þifre yeni þifre ile eþleþmedi\n"

#: web/swat.c:812
#, c-format
msgid " The passwd for '%s' has been changed. \n"
msgstr " '%s' için þifre deðiþtirildi. \n"

#: web/swat.c:814
#, c-format
msgid " The passwd for '%s' has NOT been changed. \n"
msgstr " '%s' için þifre DEÐÝÞTÝRÝLMEDÝ. \n"

#: web/swat.c:838
msgid "Server Password Management"
msgstr "Sunucu Þifre Yönetimi"

#.
#. * Create all the dialog boxes for data collection
#.
#: web/swat.c:847 web/swat.c:894
msgid " User Name : "
msgstr " Kullanýcý Adý : "

#: web/swat.c:850 web/swat.c:896
msgid " Old Password : "
msgstr " Eski Þifre : "

#: web/swat.c:853 web/swat.c:898
msgid " New Password : "
msgstr " Yeni Þifre : "

#: web/swat.c:855 web/swat.c:900
msgid " Re-type New Password : "
msgstr " Yeni Þifre Tekrarý : "

#: web/swat.c:863 web/swat.c:911
msgid "Change Password"
msgstr "Þifre Deðiþtir"

#: web/swat.c:866
msgid "Add New User"
msgstr "Kull. Ekle"

#: web/swat.c:868
msgid "Delete User"
msgstr "Kull. Sil"

#: web/swat.c:870
msgid "Disable User"
msgstr "Kull. Etkisizleþtir"

#: web/swat.c:872
msgid "Enable User"
msgstr "Kull. Etkinleþtir"

#: web/swat.c:885
msgid "Client/Server Password Management"
msgstr "Ýstemci/Sunucu Þifre Yönetimi"

#: web/swat.c:902
msgid " Remote Machine : "
msgstr " Uzak Makina : "

#: web/swat.c:940
msgid "Printer Parameters"
msgstr "Yazýcý Bilgileri"

#: web/swat.c:942
msgid "Important Note:"
msgstr "Önemli Not: "

#: web/swat.c:943
msgid "Printer names marked with [*] in the Choose Printer drop-down box "
msgstr "Yazýcý Seç kutusunda [*] ile iþaretlenmiþ yazýcý isimleri "

#: web/swat.c:944
msgid "are autoloaded printers from "
msgstr "otomatik yüklenen yazýcýlar "

#: web/swat.c:945
msgid "Printcap Name"
msgstr "Printcap Adý"

#: web/swat.c:946
msgid "Attempting to delete these printers from SWAT will have no effect.\n"
msgstr "Bu yazýcýlarý SWAT'dan silmek etkisiz olacaktýr.\n"

#: web/swat.c:980
msgid "Choose Printer"
msgstr "Yazýcý Seç"

#: web/swat.c:999
msgid "Delete Printer"
msgstr "Yazýcý Sil"

#: web/swat.c:1006
msgid "Create Printer"
msgstr "Yazýcý Oluþtur"

#: web/statuspage.c:40
msgid "DENY_NONE"
msgstr "HERKESE_AÇIK"

#: web/statuspage.c:41
msgid "DENY_ALL   "
msgstr "HERKESÝ_REDDET   "

#: web/statuspage.c:42
msgid "DENY_DOS   "
msgstr "DOSU_REDDET   "

#: web/statuspage.c:43
msgid "DENY_READ  "
msgstr "OKU_REDDET  "

#: web/statuspage.c:44
msgid "DENY_WRITE "
msgstr "YAZ_REDDET "

#: web/statuspage.c:50
msgid "RDONLY     "
msgstr "SALTOKUNUR    "

#: web/statuspage.c:51
msgid "WRONLY     "
msgstr "SALTYAZILIR    "

#: web/statuspage.c:52
msgid "RDWR       "
msgstr "O/Y        "

#: web/statuspage.c:60
msgid "EXCLUSIVE+BATCH "
msgstr "ÞAHSÝ+TOPTAN "

#: web/statuspage.c:62
msgid "EXCLUSIVE       "
msgstr "ÞAHSÝ         "

#: web/statuspage.c:64
msgid "BATCH           "
msgstr "TOPTAN        "

#: web/statuspage.c:66
msgid "LEVEL_II        "
msgstr "SEVÝYE_II        "

#: web/statuspage.c:68
msgid "NONE            "
msgstr "HÝÇ             "

#: web/statuspage.c:195
msgid "Server Status"
msgstr "Sunucu Durumu"

#: web/statuspage.c:200
msgid "Auto Refresh"
msgstr "Oto Tazele"

#: web/statuspage.c:201 web/statuspage.c:206
msgid "Refresh Interval: "
msgstr "Tazeleme Aralýðý: "

#: web/statuspage.c:205
msgid "Stop Refreshing"
msgstr "Tazelemeyi Durdur"

#: web/statuspage.c:220
msgid "version:"
msgstr "sürüm:"

#: web/statuspage.c:223
msgid "smbd:"
msgstr "smbd:"

#: web/statuspage.c:223 web/statuspage.c:235
msgid "running"
msgstr "çalýþýyor"

#: web/statuspage.c:223 web/statuspage.c:235
msgid "not running"
msgstr "çalýþmýyor"

#: web/statuspage.c:226
msgid "Stop smbd"
msgstr "Smbd'yi durdur"

#: web/statuspage.c:228
msgid "Start smbd"
msgstr "Smbd'yi çalýþtýr"

#: web/statuspage.c:230
msgid "Restart smbd"
msgstr "Smbd'yi yeniden çalýþtýr"

#: web/statuspage.c:235
msgid "nmbd:"
msgstr "nmbd:"

#: web/statuspage.c:238
msgid "Stop nmbd"
msgstr "Nmbd'yi durdur"

#: web/statuspage.c:240
msgid "Start nmbd"
msgstr "Nmbd'yi çalýþtýr"

#: web/statuspage.c:242
msgid "Restart nmbd"
msgstr "Nmbd'yi yeniden çalýþtýr"

#: web/statuspage.c:249
msgid "Active Connections"
msgstr "Aktif Baðlantýlar"

#: web/statuspage.c:251 web/statuspage.c:264 web/statuspage.c:272
msgid "PID"
msgstr "PID"

#: web/statuspage.c:251 web/statuspage.c:264
msgid "Client"
msgstr "Ýstemci"

#: web/statuspage.c:251
msgid "IP address"
msgstr "IP numarasý"

#: web/statuspage.c:251 web/statuspage.c:264 web/statuspage.c:272
msgid "Date"
msgstr "Tarih"

#: web/statuspage.c:253
msgid "Kill"
msgstr "Kapat"

#: web/statuspage.c:261
msgid "Active Shares"
msgstr "Aktif Paylaþýmlar"

#: web/statuspage.c:264
msgid "Share"
msgstr "Paylaþým"

#: web/statuspage.c:264
msgid "User"
msgstr "Kullanýcý"

#: web/statuspage.c:264
msgid "Group"
msgstr "Grup"

#: web/statuspage.c:270
msgid "Open Files"
msgstr "Açýk Dosyalar"

#: web/statuspage.c:272
msgid "Sharing"
msgstr "Paylaþýlýyor"

#: web/statuspage.c:272
msgid "R/W"
msgstr "O/Y"

#: web/statuspage.c:272
msgid "Oplock"
msgstr "Oplock"

#: web/statuspage.c:272
msgid "File"
msgstr "Dosya"

#: param/loadparm.c:641
msgid "Base Options"
msgstr "Temel Seçenekler"

#: param/loadparm.c:643
msgid "dos charset"
msgstr "dos karakter kümesi"

#: param/loadparm.c:644
msgid "unix charset"
msgstr "unix karakter kümesi"

#: param/loadparm.c:645
msgid "display charset"
msgstr "karakter kümesini göster"

#: param/loadparm.c:646
msgid "comment"
msgstr "açýklama"

#: param/loadparm.c:647
msgid "path"
msgstr "yol"

#: param/loadparm.c:648
msgid "directory"
msgstr "dizin"

#: param/loadparm.c:649
msgid "workgroup"
msgstr "çalýþma grubu"

#: param/loadparm.c:650
msgid "netbios name"
msgstr "netbios adý"

#: param/loadparm.c:651
msgid "netbios aliases"
msgstr "netbios rumuzlarý"

#: param/loadparm.c:652
msgid "netbios scope"
msgstr "netbios kapsamý"

#: param/loadparm.c:653
msgid "server string"
msgstr "sunucu dizgesi"

#: param/loadparm.c:654
msgid "interfaces"
msgstr "arayüzler"

#: param/loadparm.c:655
msgid "bind interfaces only"
msgstr "yalnýzca arayüzleri baðla"

#: param/loadparm.c:657
msgid "Security Options"
msgstr "Güvenlik Seçenekleri"

#: param/loadparm.c:659
msgid "security"
msgstr "güvenlik"

#: param/loadparm.c:660
msgid "encrypt passwords"
msgstr "þifreyi þifrele "

#: param/loadparm.c:661
msgid "update encrypted"
msgstr "þifrelenmiþ güncelle"

#: param/loadparm.c:662
msgid "allow trusted domains"
msgstr "güvenli alanlara izin ver"

#: param/loadparm.c:663
msgid "alternate permissions"
msgstr "baþka izinler"

#: param/loadparm.c:664
msgid "hosts equiv"
msgstr "hosts eþdeðerlisi"

#: param/loadparm.c:665
msgid "min passwd length"
msgstr "en kýsa þifre uzunluðu"

#: param/loadparm.c:666
msgid "min password length"
msgstr "en kýsa þifre uzunluðu"

#: param/loadparm.c:667
msgid "map to guest"
msgstr "guest (misafir) kullanýcýya eþle"

#: param/loadparm.c:668
msgid "null passwords"
msgstr "boþ þifreler"

#: param/loadparm.c:669
msgid "obey pam restrictions"
msgstr "pam kýsýtlamalarýna uy"

#: param/loadparm.c:670
msgid "password server"
msgstr "þifre sunucusu"

#: param/loadparm.c:671
msgid "smb passwd file"
msgstr "smb þifre dosyasý"

#: param/loadparm.c:672
msgid "private dir"
msgstr "özel dizin"

#: param/loadparm.c:673
msgid "passdb module path"
msgstr "þifre veritabaný modül yolu"

#: param/loadparm.c:674
msgid "root directory"
msgstr "kök dizin"

#: param/loadparm.c:675
msgid "root dir"
msgstr "kök dizin"

#: param/loadparm.c:676
msgid "root"
msgstr "kök"

#: param/loadparm.c:678
msgid "pam password change"
msgstr "pam þifre deðiþikliði"

#: param/loadparm.c:679
msgid "passwd program"
msgstr "þifre yazýlýmý"

#: param/loadparm.c:680
msgid "passwd chat"
msgstr "þifre diyaloðu"

#: param/loadparm.c:681
msgid "passwd chat debug"
msgstr "þifre diyalog hata ayýklamasý"

#: param/loadparm.c:682
msgid "username map"
msgstr "kullanýcý adý eþlemesi"

#: param/loadparm.c:683
msgid "password level"
msgstr "þifre seviyesi"

#: param/loadparm.c:684
msgid "username level"
msgstr "kullanýcý kimliði seviyesi"

#: param/loadparm.c:685
msgid "unix password sync"
msgstr "unix þifre senkronizasyonu"

#: param/loadparm.c:686
msgid "restrict anonymous"
msgstr "anonim eriþimi kýsýtla"

#: param/loadparm.c:687
msgid "lanman auth"
msgstr "lanman auth"

#: param/loadparm.c:688
msgid "ntlm auth"
msgstr "ntlm auth"

#: param/loadparm.c:689
msgid "plaintext to smbpasswd"
msgstr "düz metinden smbpasswd'e"

#: param/loadparm.c:690
msgid "use rhosts"
msgstr "rhosts kullan"

#: param/loadparm.c:692
msgid "username"
msgstr "kullanýcý adý"

#: param/loadparm.c:693
msgid "user"
msgstr "kullanýcý"

#: param/loadparm.c:694
msgid "users"
msgstr "kullanýcýlar"

#: param/loadparm.c:696
msgid "guest account"
msgstr "misafir hesap"

#: param/loadparm.c:697
msgid "invalid users"
msgstr "geçersiz kullanýcýlar"

#: param/loadparm.c:698
msgid "valid users"
msgstr "geçerli kullanýcýlar"

#: param/loadparm.c:699
msgid "admin users"
msgstr "yönetici kullanýcýlarý"

#: param/loadparm.c:700
msgid "read list"
msgstr "okuma listesi"

#: param/loadparm.c:701
msgid "write list"
msgstr "yazma listesi"

#: param/loadparm.c:702
msgid "printer admin"
msgstr "yazýcý yönetimi"

#: param/loadparm.c:703
msgid "force user"
msgstr "kullanýcýyý zorla"

#: param/loadparm.c:704
msgid "force group"
msgstr "grubu zorla"

#: param/loadparm.c:705
msgid "group"
msgstr "grup"

#: param/loadparm.c:707
msgid "read only"
msgstr "salt okunur"

#: param/loadparm.c:708
msgid "write ok"
msgstr "yazma tamam"

#: param/loadparm.c:709
msgid "writeable"
msgstr "yazýlabilir"

#: param/loadparm.c:710
msgid "writable"
msgstr "yazýlabilir"

#: param/loadparm.c:712
msgid "create mask"
msgstr "oluþturma izinleri"

#: param/loadparm.c:713
msgid "create mode"
msgstr "oluþturma kipi"

#: param/loadparm.c:714
msgid "force create mode"
msgstr "oluþturma kipini zorla"

#: param/loadparm.c:715
msgid "security mask"
msgstr "güvenlik izinleri"

#: param/loadparm.c:716
msgid "force security mode"
msgstr "güvenlik kipini zorla"

#: param/loadparm.c:717
msgid "directory mask"
msgstr "dizin izinleri"

#: param/loadparm.c:718
msgid "directory mode"
msgstr "dizin kipi"

#: param/loadparm.c:719
msgid "force directory mode"
msgstr "dizin kipini zorla"

#: param/loadparm.c:720
msgid "directory security mask"
msgstr "dizin güvenlik izinleri"

#: param/loadparm.c:721
msgid "force directory security mode"
msgstr "dizin güvenlik kipini zorla"

#: param/loadparm.c:722
msgid "inherit permissions"
msgstr "izinleri ebeveynden al"

#: param/loadparm.c:723
msgid "guest only"
msgstr "yalnýz misafir"

#: param/loadparm.c:724
msgid "only guest"
msgstr "yalnýz misafir"

#: param/loadparm.c:726
msgid "guest ok"
msgstr "misafir tamam"

#: param/loadparm.c:727
msgid "public"
msgstr "genel"

#: param/loadparm.c:729
msgid "only user"
msgstr "salt kullanýcý"

#: param/loadparm.c:730
msgid "hosts allow"
msgstr "hosts izinli"

#: param/loadparm.c:731
msgid "allow hosts"
msgstr "hosts izinli"

#: param/loadparm.c:732
msgid "hosts deny"
msgstr "hosts izinsiz"

#: param/loadparm.c:733
msgid "deny hosts"
msgstr "hosts izinsiz"

#: param/loadparm.c:736
msgid "Secure Socket Layer Options"
msgstr "Güvenli Soket Katman Seçenekleri"

#: param/loadparm.c:737
msgid "ssl"
msgstr "ssl"

#: param/loadparm.c:739
msgid "ssl hosts"
msgstr "ssl hosts"

#: param/loadparm.c:740
msgid "ssl hosts resign"
msgstr "ssl hosts istifa"

#: param/loadparm.c:741
msgid "ssl CA certDir"
msgstr "ssl CA sertifika dizini"

#: param/loadparm.c:742
msgid "ssl CA certFile"
msgstr "ssl CA sertifika dosyasý"

#: param/loadparm.c:743
msgid "ssl server cert"
msgstr "ssl sunucu sertifikasý"

#: param/loadparm.c:744
msgid "ssl server key"
msgstr "ssl sunucu anahtarý"

#: param/loadparm.c:745
msgid "ssl client cert"
msgstr "ssl istemci sertifikasý"

#: param/loadparm.c:746
msgid "ssl client key"
msgstr "ssl istemci anahtarý"

#: param/loadparm.c:747
msgid "ssl require clientcert"
msgstr "ssl istemci sertifikasý iste"

#: param/loadparm.c:748
msgid "ssl require servercert"
msgstr "ssl sunucu sertifikasý iste"

#: param/loadparm.c:749
msgid "ssl ciphers"
msgstr "ssl þifreleri"

#: param/loadparm.c:750
msgid "ssl version"
msgstr "ssl sürümü"

#: param/loadparm.c:751
msgid "ssl compatibility"
msgstr "ssl uyumluluðu"

#: param/loadparm.c:754
msgid "Logging Options"
msgstr "Günlük Kaydý Seçenekleri"

#: param/loadparm.c:755
msgid "log level"
msgstr "günlük seviyesi"

#: param/loadparm.c:756
msgid "debuglevel"
msgstr "hata ayýklama seviyesi"

#: param/loadparm.c:757
msgid "syslog"
msgstr "sistem günlüðü"

#: param/loadparm.c:758
msgid "syslog only"
msgstr "salt sistem günlüðü"

#: param/loadparm.c:759
msgid "log file"
msgstr "günlük dosyasý"

#: param/loadparm.c:761
msgid "max log size"
msgstr "maksimum günlük büyüklüðü"

#: param/loadparm.c:762
msgid "timestamp logs"
msgstr "zaman damgasý günlükleri"

#: param/loadparm.c:763
msgid "debug timestamp"
msgstr "hata ayýklama zaman damgasý"

#: param/loadparm.c:764
msgid "debug hires timestamp"
msgstr "hata ayýklama yüksek çözünürlüklü zaman damgasý"

#: param/loadparm.c:765
msgid "debug pid"
msgstr "hata ayýklama pid"

#: param/loadparm.c:766
msgid "debug uid"
msgstr "hata ayýklama uid"

#: param/loadparm.c:768
msgid "Protocol Options"
msgstr "Protokol Seçenekleri"

#: param/loadparm.c:770
msgid "protocol"
msgstr "protokol"

#: param/loadparm.c:771
msgid "large readwrite"
msgstr "büyük oku/yaz"

#: param/loadparm.c:772
msgid "max protocol"
msgstr "max protokol"

#: param/loadparm.c:773
msgid "min protocol"
msgstr "min protokol"

#: param/loadparm.c:774
msgid "unicode"
msgstr "unicode"

#: param/loadparm.c:775
msgid "read bmpx"
msgstr "bmpx oku"

#: param/loadparm.c:776
msgid "read raw"
msgstr "ham oku"

#: param/loadparm.c:777
msgid "write raw"
msgstr "ham yaz"

#: param/loadparm.c:779
msgid "nt smb support"
msgstr "nt smb desteði"

#: param/loadparm.c:780
msgid "nt pipe support"
msgstr "nt verihattý desteði"

#: param/loadparm.c:781
msgid "nt acl support"
msgstr "nt acl desteði"

#: param/loadparm.c:782
msgid "announce version"
msgstr "sürümü bildir"

#: param/loadparm.c:783
msgid "announce as"
msgstr "bildir"

#: param/loadparm.c:784
msgid "max mux"
msgstr "maksimum mux"

#: param/loadparm.c:785
msgid "max xmit"
msgstr "maksimum xmit"

#: param/loadparm.c:787
msgid "name resolve order"
msgstr "ad çözümleme sýrasý"

#: param/loadparm.c:788
msgid "max packet"
msgstr "maksimum paket"

#: param/loadparm.c:789
msgid "packet size"
msgstr "paket büyüklüðü"

#: param/loadparm.c:790
msgid "max ttl"
msgstr "maksimum ttl"

#: param/loadparm.c:791
msgid "max wins ttl"
msgstr "maksimum wins ttl"

#: param/loadparm.c:792
msgid "min wins ttl"
msgstr "minimum wins ttl"

#: param/loadparm.c:793
msgid "time server"
msgstr "zaman sunucusu"

#: param/loadparm.c:795
msgid "Tuning Options"
msgstr "Ayar Seçenekleri"

#: param/loadparm.c:797
msgid "change notify timeout"
msgstr "zamanaþýmý bildirmesini deðiþtir"

#: param/loadparm.c:798
msgid "deadtime"
msgstr "ölüzaman"

#: param/loadparm.c:799
msgid "getwd cache"
msgstr "getwd arabelleði"

#: param/loadparm.c:800
msgid "keepalive"
msgstr "hayattatut"

#: param/loadparm.c:802
msgid "lpq cache time"
msgstr "lpq arabellek zamaný"

#: param/loadparm.c:803
msgid "max smbd processes"
msgstr "maksimum smbd süreci"

#: param/loadparm.c:804
msgid "max connections"
msgstr "maksimum baðlantý"

#: param/loadparm.c:805
msgid "paranoid server security"
msgstr "yüksek dereceli sunucu güvenliði"

#: param/loadparm.c:806
msgid "max disk size"
msgstr "maksimum disk büyüklüðü"

#: param/loadparm.c:807
msgid "max open files"
msgstr "maksimum açýk dosya"

#: param/loadparm.c:808
msgid "min print space"
msgstr "minimum yazma alaný"

#: param/loadparm.c:809
msgid "read size"
msgstr "okuma boyu"

#: param/loadparm.c:811
msgid "socket options"
msgstr "soket seçenekleri"

#: param/loadparm.c:812
msgid "stat cache size"
msgstr "durum arabelleði boyu"

#: param/loadparm.c:813
msgid "strict allocate"
msgstr "sýký ayýrma"

#: param/loadparm.c:814
msgid "strict sync"
msgstr "sýký senkronizasyon"

#: param/loadparm.c:815
msgid "sync always"
msgstr "herzaman senkronize"

#: param/loadparm.c:816
msgid "use mmap"
msgstr "bellek eþlemesi kullan"

#: param/loadparm.c:817
msgid "hostname lookups"
msgstr "sunucu adý arama"

#: param/loadparm.c:818
msgid "write cache size"
msgstr "yazma arabellek boyu"

#: param/loadparm.c:820
msgid "Printing Options"
msgstr "Yazdýrma Seçenekleri"

#: param/loadparm.c:822
msgid "total print jobs"
msgstr "toplam yazdýrma iþleri"

#: param/loadparm.c:823
msgid "max print jobs"
msgstr "maksimum yazdýrma iþi"

#: param/loadparm.c:824
msgid "load printers"
msgstr "yazýcýlarý yükle"

#: param/loadparm.c:825
msgid "printcap name"
msgstr "printcap adý"

#: param/loadparm.c:826
msgid "printcap"
msgstr "printcap"

#: param/loadparm.c:827
msgid "printable"
msgstr "yazdýrýlabilir"

#: param/loadparm.c:828
msgid "print ok"
msgstr "yazdýrma tamam"

#: param/loadparm.c:829
msgid "postscript"
msgstr "postscript"

#: param/loadparm.c:830
msgid "printing"
msgstr "yazdýrýyor"

#: param/loadparm.c:831
msgid "print command"
msgstr "yazdýrma komutu"

#: param/loadparm.c:832
msgid "disable spoolss"
msgstr "kuyruðu etkisizleþtir"

#: param/loadparm.c:833
msgid "lpq command"
msgstr "lpq komutu"

#: param/loadparm.c:834
msgid "lprm command"
msgstr "lprm komutu"

#: param/loadparm.c:835
msgid "lppause command"
msgstr "lppause komutu"

#: param/loadparm.c:836
msgid "lpresume command"
msgstr "lpresume komutu"

#: param/loadparm.c:837
msgid "queuepause command"
msgstr "queuepause komutu"

#: param/loadparm.c:838
msgid "queueresume command"
msgstr "queueresume komutu"

#: param/loadparm.c:840
msgid "enumports command"
msgstr "port listele komutu"

#: param/loadparm.c:841
msgid "addprinter command"
msgstr "yazýcý ekle komutu"

#: param/loadparm.c:842
msgid "deleteprinter command"
msgstr "yazýcý sil komutu"

#: param/loadparm.c:843
msgid "show add printer wizard"
msgstr "yazýcý ekleme sihirbazýný göster"

#: param/loadparm.c:844
msgid "os2 driver map"
msgstr "os2 sürücü eþlemesi"

#: param/loadparm.c:846
msgid "printer name"
msgstr "yazýcý adý"

#: param/loadparm.c:847
msgid "printer"
msgstr "yazýcý"

#: param/loadparm.c:848
msgid "use client driver"
msgstr "istemci sürücüsü kullan"

#: param/loadparm.c:849
msgid "printer driver"
msgstr "yazýcý sürücüsü"

#: param/loadparm.c:850
msgid "printer driver file"
msgstr "yazýcý sürücü dosyasý"

#: param/loadparm.c:851
msgid "printer driver location"
msgstr "yazýcý sürücüsü yeri"

#: param/loadparm.c:853
msgid "Filename Handling"
msgstr "Dosyaadý Ýþlenmesi"

#: param/loadparm.c:854
msgid "strip dot"
msgstr "noktalarý bastýr"

#: param/loadparm.c:856
msgid "mangled stack"
msgstr "karýþtýrýlmýþ yýðýt"

#: param/loadparm.c:857
msgid "default case"
msgstr "öntanýmlý büyük/küçük harf"

#: param/loadparm.c:858
msgid "case sensitive"
msgstr "büyük küçük harfe duyarlý"

#: param/loadparm.c:859
msgid "casesignames"
msgstr "casesignames"

#: param/loadparm.c:860
msgid "preserve case"
msgstr "büyük küçük harf ayrýmýný tut"

#: param/loadparm.c:861
msgid "short preserve case"
msgstr "kýsa büyük küçük harf ayrýmýný tut"

#: param/loadparm.c:862
msgid "mangle case"
msgstr "büyük küçük harf harmanla"

#: param/loadparm.c:863
msgid "mangling char"
msgstr "karakter harmanlanýyor"

#: param/loadparm.c:864
msgid "hide dot files"
msgstr "nokta ile baþlayan dosyalarý gizle"

#: param/loadparm.c:865
msgid "hide unreadable"
msgstr "okunamazlarý sakla"

#: param/loadparm.c:866
msgid "delete veto files"
msgstr "veto dosyalarýný sil"

#: param/loadparm.c:867
msgid "veto files"
msgstr "veto dosyalarý"

#: param/loadparm.c:868
msgid "hide files"
msgstr "dosyalarý gizle"

#: param/loadparm.c:869
msgid "veto oplock files"
msgstr "veto oplock dosyalarý"

#: param/loadparm.c:870
msgid "map system"
msgstr "sistemi eþle"

#: param/loadparm.c:871
msgid "map hidden"
msgstr "gizlileri eþle"

#: param/loadparm.c:872
msgid "map archive"
msgstr "arþivi eþle"

#: param/loadparm.c:873
msgid "mangled names"
msgstr "harmanlanmýþ isimler"

#: param/loadparm.c:874
msgid "mangled map"
msgstr "harmanlanmýþ eþleþme"

#: param/loadparm.c:875
msgid "stat cache"
msgstr "durum arabelleði"

#: param/loadparm.c:877
msgid "Domain Options"
msgstr "Alan Seçenekleri"

#: param/loadparm.c:879
msgid "domain admin group"
msgstr "alan yönetici grubu"

#: param/loadparm.c:880
msgid "domain guest group"
msgstr "alan misafir grubu"

#: param/loadparm.c:883
msgid "groupname map"
msgstr "grup adý eþlemesi"

#: param/loadparm.c:886
msgid "machine password timeout"
msgstr "makina þifresi zamanaþýmý"

#: param/loadparm.c:888
msgid "Logon Options"
msgstr "Sistem Giriþ Seçenekleri"

#: param/loadparm.c:890
msgid "add user script"
msgstr "kullanýcý ekleme betiði"

#: param/loadparm.c:891
msgid "delete user script"
msgstr "kullanýcý silme betiði"

#: param/loadparm.c:892
msgid "add group script"
msgstr "grup ekleme betiði"

#: param/loadparm.c:893
msgid "delete group script"
msgstr "grup silme betiði"

#: param/loadparm.c:894
msgid "add user to group script"
msgstr "gruba kullanýcý ekleme betiði"

#: param/loadparm.c:895
msgid "delete user from group script"
msgstr "gruptan kullanýcý silme betiði"

#: param/loadparm.c:896
msgid "add machine script"
msgstr "makina ekleme betiði"

#: param/loadparm.c:897
msgid "shutdown script"
msgstr "sistem kapanýþ betiði"

#: param/loadparm.c:898
msgid "abort shutdown script"
msgstr "sistem kapanýþ betiðini durdur"

#: param/loadparm.c:900
msgid "logon script"
msgstr "sistem giriþ betiði"

#: param/loadparm.c:901
msgid "logon path"
msgstr "sistem giriþ yolu"

#: param/loadparm.c:902
msgid "logon drive"
msgstr "sistem giriþ aygýtý"

#: param/loadparm.c:903
msgid "logon home"
msgstr "sistem giriþ kökü"

#: param/loadparm.c:904
msgid "domain logons"
msgstr "alan giriþleri"

#: param/loadparm.c:906
msgid "Browse Options"
msgstr "Gözatma Seçenekleri"

#: param/loadparm.c:908
msgid "os level"
msgstr "iþletim sistem seviyesi"

#: param/loadparm.c:909
msgid "lm announce"
msgstr "lm bildirimi"

#: param/loadparm.c:910
msgid "lm interval"
msgstr "lm aralýðý"

#: param/loadparm.c:911
msgid "preferred master"
msgstr "tercih edilen ana alan sunucusu"

#: param/loadparm.c:912
msgid "prefered master"
msgstr "tercih edilen ana alan sunucusu"

#: param/loadparm.c:913
msgid "local master"
msgstr "yerel alan sunucusu"

#: param/loadparm.c:914
msgid "domain master"
msgstr "alan sunucusu"

#: param/loadparm.c:915
msgid "browse list"
msgstr "gözatma listesi"

#: param/loadparm.c:916
msgid "browseable"
msgstr "gözatýlabilir"

#: param/loadparm.c:917
msgid "browsable"
msgstr "gözatýlabilir"

#: param/loadparm.c:918
msgid "enhanced browsing"
msgstr "geliþkin gözatma"

#: param/loadparm.c:920
msgid "WINS Options"
msgstr "WINS Seçenekleri"

#: param/loadparm.c:921
msgid "dns proxy"
msgstr "dns proxy"

#: param/loadparm.c:922
msgid "wins proxy"
msgstr "wins proxy"

#: param/loadparm.c:924
msgid "wins server"
msgstr "wins sunucusu"

#: param/loadparm.c:925
msgid "wins support"
msgstr "wins desteði"

#: param/loadparm.c:926
msgid "wins hook"
msgstr "wins giriþi"

#: param/loadparm.c:928
msgid "Locking Options"
msgstr "Kilitleme Seçenekleri"

#: param/loadparm.c:930
msgid "blocking locks"
msgstr "engelleyen kilitler"

#: param/loadparm.c:931
msgid "fake oplocks"
msgstr "sahte oplocklar"

#: param/loadparm.c:932
msgid "kernel oplocks"
msgstr "çekirdek oplocklarý"

#: param/loadparm.c:933
msgid "locking"
msgstr "kilitliyor"

#: param/loadparm.c:935
msgid "oplocks"
msgstr "oplocklar"

#: param/loadparm.c:936
msgid "level2 oplocks"
msgstr "Seviye 2 oplocklar"

#: param/loadparm.c:937
msgid "oplock break wait time"
msgstr "oplock kýrma bekleme süresi"

#: param/loadparm.c:938
msgid "oplock contention limit"
msgstr "oplock ihtilaf limiti"

#: param/loadparm.c:939
msgid "posix locking"
msgstr "posix kilitlemesi"

#: param/loadparm.c:940
msgid "strict locking"
msgstr "sýký kilitleme"

#: param/loadparm.c:941
msgid "share modes"
msgstr "paylaþým kipleri"

#: param/loadparm.c:944
msgid "Ldap Options"
msgstr "Ldap Seçenekleri"

#: param/loadparm.c:946
msgid "ldap server"
msgstr "ldap sunucusu"

#: param/loadparm.c:947
msgid "ldap port"
msgstr "ldap portu"

#: param/loadparm.c:948
msgid "ldap suffix"
msgstr "ldap soneki"

#: param/loadparm.c:949
msgid "ldap filter"
msgstr "ldap filtresi"

#: param/loadparm.c:950
msgid "ldap root"
msgstr "ldap kökü"

#: param/loadparm.c:951
msgid "ldap root passwd"
msgstr "ldap kök þifresi"

#: param/loadparm.c:954
msgid "Miscellaneous Options"
msgstr "Diðer Seçenekler"

#: param/loadparm.c:955
msgid "add share command"
msgstr "paylaþým ekle komutu"

#: param/loadparm.c:956
msgid "change share command"
msgstr "paylaþým deðiþtir komutu"

#: param/loadparm.c:957
msgid "delete share command"
msgstr "paylaþým sil komutu"

#: param/loadparm.c:959
msgid "config file"
msgstr "ayar dosyasý"

#: param/loadparm.c:960
msgid "preload"
msgstr "önyükle"

#: param/loadparm.c:961
msgid "auto services"
msgstr "otomatik servisler"

#: param/loadparm.c:962
msgid "lock dir"
msgstr "kilit dizini"

#: param/loadparm.c:963
msgid "lock directory"
msgstr "kilit dizini"

#: param/loadparm.c:965
msgid "utmp directory"
msgstr "utmp dizini"

#: param/loadparm.c:966
msgid "wtmp directory"
msgstr "wtmp dizini"

#: param/loadparm.c:967
msgid "utmp"
msgstr "utmp"

#: param/loadparm.c:970
msgid "default service"
msgstr "öntanýmlý servis"

#: param/loadparm.c:971
msgid "default"
msgstr "öntanýmlý"

#: param/loadparm.c:972
msgid "message command"
msgstr "ileti komutu"

#: param/loadparm.c:973
msgid "dfree command"
msgstr "dfree komutu"

#: param/loadparm.c:974
msgid "remote announce"
msgstr "uzak bildirim"

#: param/loadparm.c:975
msgid "remote browse sync"
msgstr "uzak gözatma senkronizasyonu"

#: param/loadparm.c:976
msgid "socket address"
msgstr "soket adresi"

#: param/loadparm.c:977
msgid "homedir map"
msgstr "evdizini eþlemesi"

#: param/loadparm.c:978
msgid "time offset"
msgstr "zaman kaydýrmasý"

#: param/loadparm.c:979
msgid "NIS homedir"
msgstr "NIS evdizini"

#: param/loadparm.c:980
msgid "-valid"
msgstr "-geçerli"

#: param/loadparm.c:982
msgid "copy"
msgstr "kopyala"

#: param/loadparm.c:983
msgid "include"
msgstr "ekle"

#: param/loadparm.c:984
msgid "exec"
msgstr "çalýþtýr"

#: param/loadparm.c:985
msgid "preexec"
msgstr "preexec"

#: param/loadparm.c:987
msgid "preexec close"
msgstr "preexec close"

#: param/loadparm.c:988
msgid "postexec"
msgstr "postexec"

#: param/loadparm.c:989
msgid "root preexec"
msgstr "root preexec"

#: param/loadparm.c:990
msgid "root preexec close"
msgstr "root preexec close"

#: param/loadparm.c:991
msgid "root postexec"
msgstr "root postexec"

#: param/loadparm.c:992
msgid "available"
msgstr "mevcut"

#: param/loadparm.c:993
msgid "volume"
msgstr "volume"

#: param/loadparm.c:994
msgid "fstype"
msgstr "dosya sistem tipi"

#: param/loadparm.c:995
msgid "set directory"
msgstr "dizini belirle"

#: param/loadparm.c:996
msgid "source environment"
msgstr "source environment"

#: param/loadparm.c:997
msgid "wide links"
msgstr "wide links"

#: param/loadparm.c:998
msgid "follow symlinks"
msgstr "sembolik baðlarý izle"

#: param/loadparm.c:999
msgid "dont descend"
msgstr "dont descend"

#: param/loadparm.c:1000
msgid "magic script"
msgstr "magic script"

#: param/loadparm.c:1001
msgid "magic output"
msgstr "magic output"

#: param/loadparm.c:1002
msgid "delete readonly"
msgstr "salt okunurlarý sil"

#: param/loadparm.c:1003
msgid "dos filemode"
msgstr "dos dosya kipi"

#: param/loadparm.c:1004
msgid "dos filetimes"
msgstr "dos dosya zamanlarý"

#: param/loadparm.c:1005
msgid "dos filetime resolution"
msgstr "dos dosya zamaný çözünürlüðü"

#: param/loadparm.c:1007
msgid "fake directory create times"
msgstr "dizin oluþma zamanlarýný taklit et"

#: param/loadparm.c:1008
msgid "panic action"
msgstr "panik iþlemi"

#: param/loadparm.c:1009
msgid "hide local users"
msgstr "yerel kullanýcýlarý sakla"

#: param/loadparm.c:1012
msgid "VFS options"
msgstr "VFS Seçenekleri"

#: param/loadparm.c:1014
msgid "vfs object"
msgstr "vfs nesnesi"

#: param/loadparm.c:1015
msgid "vfs options"
msgstr "vfs seçenekleri"

#: param/loadparm.c:1018
msgid "msdfs root"
msgstr "msdfs kökü"

#: param/loadparm.c:1019
msgid "host msdfs"
msgstr "host msdfs"

#: param/loadparm.c:1021
msgid "Winbind options"
msgstr "Winbind seçenekleri"

#: param/loadparm.c:1023
msgid "winbind uid"
msgstr "winbind uid"

#: param/loadparm.c:1024
msgid "winbind gid"
msgstr "winbind gid"

#: param/loadparm.c:1025
msgid "template homedir"
msgstr "örnek ev dizini"

#: param/loadparm.c:1026
msgid "template shell"
msgstr "örnek kabuk"

#: param/loadparm.c:1027
msgid "winbind separator"
msgstr "winbind ayracý"

#: param/loadparm.c:1028
msgid "winbind cache time"
msgstr "winbind arabellek zamaný"

#: param/loadparm.c:1029
msgid "winbind enum users"
msgstr "winbind kullanýcý listele"

#: param/loadparm.c:1030
msgid "winbind enum groups"
msgstr "winbind grup listele"

