#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('ICONV_WRAPPER',
                    source='iconv.c',
                    public_deps='iconv replace talloc')

bld.SAMBA_SUBSYSTEM('CHARSET',
                    public_headers='charset.h',
                    source='codepoints.c convert_string.c util_str.c util_unistr_w.c charcnv.c pull_push.c util_unistr.c',
                    deps='DYNCONFIG ICONV_WRAPPER'
                    )
