#!/usr/bin/env python


bld.SAMBA_SUBSYSTEM('CHARSET',
	source='iconv.c charcnv.c util_unistr.c',
	public_deps='iconv CODEPOINTS',
	public_headers='charset.h',
	)

bld.SAMBA_SUBSYSTEM('CODEPOINTS',
	source='codepoints.c',
	deps='DYNCONFIG'
	)
