#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('ICONV_WRAPPER',
                    source='iconv.c',
                    public_deps='iconv replace talloc')

bld.SAMBA_SUBSYSTEM('charset',
                    public_headers='charset.h',
                    source='codepoints.c convert_string.c util_str.c util_unistr_w.c charcnv.c pull_push.c util_unistr.c',
                    deps='DYNCONFIG ICONV_WRAPPER',
                    public_deps='talloc')

bld.SAMBA_MODULE('charset_weird',
                 subsystem='charset',
                 source='weird.c',
                 init_function='',
                 deps='samba-util',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('charset_weird'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('charset_weird'))

bld.SAMBA_MODULE('charset_CP850',
                 subsystem='charset',
                 source='CP850.c',
                 init_function='',
                 deps='samba-util',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('charset_CP850'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('charset_CP850'))

bld.SAMBA_MODULE('charset_CP437',
                 subsystem='charset',
                 source='CP437.c',
                 init_function='',
                 deps='samba-util',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('charset_CP437'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('charset_CP437'))

bld.SAMBA_MODULE('charset_macosxfs',
                 subsystem='charset',
                 source='charset_macosxfs.c',
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('charset_macosxfs'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('charset_macosxfs'))


