#!/bin/ksh
#
# invoke with -n as the first argument to get this script to tell
# you what it would do without doing anything
#

V=
[ "$1" = "-n" ] && V=echo

CC="cc -Kthread -Kalloca -I/usr/local/include -L/usr/local/lib"
CPP="$CC -E"
CFLAGS="-Xa -Dasm=__asm -DANSICPP -O3"
LDFLAGS="-L/usr/local/lib"
CXX="CC -I/usr/local/include"
CXXFLAGS="-O3 -I/usr/local/include/stl -L/usr/local/lib"
RANLIB=true
MAKE=/usr/local/bin/make
if [ "$V" = "echo" ]
then
    echo "exporting the following shell variables:"
    echo "CC=$CC"
    echo "CPP=$CPP"
    echo "CXX=$CXX"
    echo "RANLIB=$RANLIB"
    echo "MAKE=$MAKE"
    echo "CFLAGS=$CFLAGS"
    echo "CXXFLAGS=$CXXFLAGS"
    echo "LDFLAGS=$LDFLAGS"
else
    export CC CPP CXX RANLIB MAKE CFLAGS CXXFLAGS LDFLAGS
fi

if [ "$V" = "echo" ]
then
    echo "cd ../../../source"
    echo "rm -f mout-1 mout-2 mout-3 mout-4"
    echo "make all 2>&1 | tee mout-1"
    echo "make smbfilter smbtorture debug2html 2>&1 | tee mout-2"
    echo "make bin/smbspool smbwrapper bin/wbinfo 2>&1 | tee mout-3"
    echo "make masktest locktest locktest2 2>&1 | tee mout-3"
else
    cd ../../../source
    rm -f mout-1 mout-2 mout-3 mout-4
    make all 2>&1 | tee mout-1
    make smbfilter smbtorture debug2html 2>&1 | tee mout-2
    make bin/smbspool smbwrapper bin/wbinfo 2>&1 | tee mout-3
    make masktest locktest locktest2 2>&1 | tee mout-3
fi
#
# Not building :
#     nsswitch - no <nss.h>
#     rpctorture - improper use of client_info struct, dunno
