#!/bin/ksh
#
# invoke with -n as the first argument to get this script to tell
# you what it would do without doing anything
#

V=
[ "$1" = "-n" ] && V=echo

#CC="cc -Kthread -Kalloca -I/usr/local/include -L/usr/local/lib"
CC="cc -Kthread -Kalloca"
CPP="$CC -E"
CFLAGS="-Xa -Dasm=__asm -DANSICPP -O3"
#LDFLAGS="-L/usr/local/lib"
LDFLAGS=
#CXX="CC -I/usr/local/include"
CXX="CC"
#CXXFLAGS="-O3 -I/usr/local/include/stl -L/usr/local/lib"
CXXFLAGS="-O3"
RANLIB=true
PREFIX=/usr/lib/samba

if [ -x /usr/gnu/bin/make ]
then
    MAKE=/usr/gnu/bin/make
elif [ -x /usr/local/bin/make ]
then
    MAKE=/usr/local/bin/make
elif [ -x /usr/bin/make ]
then
    MAKE=/usr/bin/make
else
    echo "Can't find make - exiting"
    exit 1
fi

if [ "$V" = "echo" ]
then
    echo "exporting the following shell variables:"
    echo "CC=$CC"
    echo "CPP=$CPP"
    echo "CXX=$CXX"
    echo "RANLIB=$RANLIB"
    echo "MAKE=$MAKE"
    echo "CFLAGS=$CFLAGS"
    echo "CXXFLAGS=$CXXFLAGS"
    echo "LDFLAGS=$LDFLAGS"
    echo "PREFIX=$PREFIX"
else
    export CC CPP CXX RANLIB MAKE CFLAGS CXXFLAGS LDFLAGS PREFIX
fi

cd ../../../source
[ -f mout-config ] && {
    if [ "$V" = "echo" ]
    then
        echo "mv mout-config mout-config$$"
    else
        mv mout-config mout-config$$
    fi
}
if [ "$V" = "echo" ]
then
    echo "./configure \
	--prefix=${PREFIX} \
	--with-profile \
	--with-syslog \
	--with-utmp \
	--with-vfs \
	--with-msdfs \
	--with-sambabook=${PREFIX}/swat/using_samba \
        2>&1 | tee mout-config"
else
    ./configure \
	--prefix=${PREFIX} \
	--with-profile \
	--with-syslog \
	--with-utmp \
	--with-vfs \
	--with-msdfs \
	--with-sambabook=${PREFIX}/swat/using_samba \
        2>&1 | tee mout-config
fi
