#!/usr/bin/env python

bld.SAMBA_LIBRARY('LIBWBCLIENT_OLD',
                  source='wbclient.c',
                  public_deps='errors events',
                  deps='WB_REQTRANS NDR_WINBIND MESSAGING RPC_NDR_WINBIND',
                  private_library=True
	)

