#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('gensec_util',
                    source='gensec_tstream.c',
                    deps='tevent-util tevent samba-util LIBTSOCKET',
                    autoproto='gensec_proto.h')

bld.SAMBA_MODULE('gensec_krb5',
	source='gensec_krb5.c gensec_krb5_util.c',
	subsystem='gensec',
	init_function='gensec_krb5_init',
	deps='samba-credentials authkrb5 com_err gensec_util',
	internal_module=False,
        enabled=bld.AD_DC_BUILD_IS_ENABLED() and bld.CONFIG_SET('SAMBA4_USES_HEIMDAL')
	)


bld.SAMBA_MODULE('gensec_gssapi',
	source='gensec_gssapi.c',
	subsystem='gensec',
	init_function='gensec_gssapi_init',
	deps='gssapi samba-credentials authkrb5 com_err gensec_util'
	)

bld.SAMBA_PYTHON('pygensec',
	source='pygensec.c',
	deps='gensec pytalloc-util pyparam_util',
	realname='samba/gensec.so'
	)

