Import('hostenv')
#            tastes like -*- python -*-

Import('dynconfig basic')
param_files = ['loadparm.c','params.c']
param = hostenv.Library('loadparm',[param_files,dynconfig,basic])
hostenv.proto_headers += hostenv.CProtoHeader('proto.h', param_files)
Export('param')
generic = hostenv.Library('generic',['generic.c'])
Export('generic')
