#            tastes like -*- python -*-

Import('hostenv')
param = hostenv.StaticLibrary('loadparm',['loadparm.c','params.c'])
Export('param')
generic = hostenv.StaticLibrary('generic',['generic.c'])
Export('generic')
