#!/usr/bin/env python

IDMAP_AD_SRC = '''idmap_ad.c'''
IDMAP_RID_SRC = '''idmap_rid.c'''
IDMAP_PASSDB_SRC = '''idmap_passdb.c'''
IDMAP_LDAP_SRC = '''idmap_ldap.c'''
IDMAP_NSS_SRC = '''idmap_nss.c'''
IDMAP_TDB_SRC = '''idmap_tdb.c'''
IDMAP_TDB2_SRC = '''idmap_tdb2.c'''

IDMAP_HASH_SRC = '''idmap_hash/idmap_hash.c
                    idmap_hash/mapfile.c'''

IDMAP_ADEX_SRC = '''idmap_adex/idmap_adex.c
                    idmap_adex/cell_util.c
                    idmap_adex/likewise_cell.c
                    idmap_adex/provider_unified.c
                    idmap_adex/gc_util.c
                    idmap_adex/domain_util.c'''

IDMAP_RW_SRC = 'idmap_rw.c'
IDMAP_SRC = 'idmap.c idmap_util.c ${IDMAP_RW_SRC}'

bld.SAMBA_SUBSYSTEM('IDMAP',
                    source=IDMAP_SRC,
                    vars=locals())

bld.SAMBA_MODULE('IDMAP_AD',
                 subsystem='IDMAP',
                 source=IDMAP_AD_SRC,
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('IDMAP_AD'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('IDMAP_AD'))

bld.SAMBA_MODULE('IDMAP_RID',
                 subsystem='IDMAP',
                 source=IDMAP_RID_SRC,
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('IDMAP_RID'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('IDMAP_RID'))

bld.SAMBA_MODULE('IDMAP_PASSDB',
                 subsystem='IDMAP',
                 source=IDMAP_PASSDB_SRC,
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('IDMAP_PASSDB'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('IDMAP_PASSDB'))

bld.SAMBA_MODULE('IDMAP_LDAP',
                 subsystem='IDMAP',
                 source=IDMAP_LDAP_SRC,
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('IDMAP_LDAP'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('IDMAP_LDAP'))

bld.SAMBA_MODULE('IDMAP_NSS',
                 subsystem='IDMAP',
                 source=IDMAP_NSS_SRC,
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('IDMAP_NSS'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('IDMAP_NSS'))

bld.SAMBA_MODULE('IDMAP_TDB',
                 subsystem='IDMAP',
                 source=IDMAP_TDB_SRC,
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('IDMAP_TDB'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('IDMAP_TDB'))

bld.SAMBA_MODULE('IDMAP_TDB2',
                 subsystem='IDMAP',
                 source=IDMAP_TDB2_SRC,
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('IDMAP_TDB2'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('IDMAP_TDB2'))

bld.SAMBA_MODULE('IDMAP_HASH',
                 subsystem='IDMAP',
                 source=IDMAP_HASH_SRC,
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('IDMAP_HASH'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('IDMAP_HASH'))

bld.SAMBA_MODULE('IDMAP_ADEX',
                 subsystem='IDMAP',
                 source=IDMAP_ADEX_SRC,
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('IDMAP_ADEX'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('IDMAP_ADEX'))

NSS_INFO_TEMPLATE_SRC = 'nss_info_template.c'
NSS_INFO_SRC = 'nss_info.c'

bld.SAMBA_SUBSYSTEM('NSS_INFO',
                    source=NSS_INFO_SRC,
                    vars=locals())

bld.SAMBA_MODULE('NSS_INFO_TEMPLATE',
                 subsystem='NSS_INFO',
                 source=NSS_INFO_TEMPLATE_SRC,
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('NSS_INFO_TEMPLATE'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('NSS_INFO_TEMPLATE'))

bld.SAMBA_MODULE('NSS_INFO_ADEX',
                 subsystem='NSS_INFO',
                 source=IDMAP_ADEX_SRC,
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('IDMAP_ADEX'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('IDMAP_ADEX'))

bld.SAMBA_MODULE('NSS_INFO_HASH',
                 subsystem='NSS_INFO',
                 source=IDMAP_HASH_SRC,
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('IDMAP_HASH'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('IDMAP_HASH'))

bld.SAMBA_MODULE('NSS_INFO_RFC2307',
                 subsystem='NSS_INFO',
                 source=IDMAP_AD_SRC,
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('IDMAP_AD'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('IDMAP_AD'))

bld.SAMBA_MODULE('NSS_INFO_SFU20',
                 subsystem='NSS_INFO',
                 source=IDMAP_AD_SRC,
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('IDMAP_AD'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('IDMAP_AD'))

bld.SAMBA_MODULE('NSS_INFO_SFU',
                 subsystem='NSS_INFO',
                 source=IDMAP_AD_SRC,
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('IDMAP_AD'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('IDMAP_AD'))
