#!/usr/bin/env python


bld.SAMBA_MODULE('LDAP',
	source='ldap_server.c ldap_backend.c ldap_bind.c ldap_extended.c',
	autoproto='proto.h',
	subsystem='service',
	init_function='server_service_ldap_init',
	deps='CREDENTIALS LIBCLI_LDAP SAMDB process_model gensec LIBSAMBA-HOSTCONFIG'
	)

