#!/usr/bin/env python

bld.SAMBA_MODULE('DNS',
        source='dns_server.c',
        subsystem='service',
        init_function='server_service_dns_init',
        deps='LIBSAMBA-HOSTCONFIG LIBTSOCKET LIBSAMBA_TSOCKET',
        local_include=False
        )
