#!/usr/bin/env python

bld.SAMBA_MODULE('service_dns',
        source='dns_server.c dns_query.c dns_update.c dns_utils.c dns_crypto.c',
        subsystem='service',
        init_function='server_service_dns_init',
        deps='samba-hostconfig LIBTSOCKET LIBSAMBA_TSOCKET ldbsamba clidns gensec auth samba_server_gensec',
        local_include=False,
        internal_module=False,
        enabled=bld.AD_DC_BUILD_IS_ENABLED()
        )

# a bind9 dlz module giving access to the Samba DNS SAM
bld.SAMBA_LIBRARY('dlz_bind9',
                  source='dlz_bind9.c',
                  cflags='-DBIND_VERSION_9_8',
                  private_library=True,
                  link_name='modules/bind9/dlz_bind9.so',
                  realname='dlz_bind9.so',
                  install_path='${MODULESDIR}/bind9',
                  deps='samba-hostconfig samdb-common gensec popt',
                  enabled=bld.AD_DC_BUILD_IS_ENABLED())

bld.SAMBA_LIBRARY('dlz_bind9_9',
                  source='dlz_bind9.c',
                  cflags='-DBIND_VERSION_9_9',
                  private_library=True,
                  link_name='modules/bind9/dlz_bind9_9.so',
                  realname='dlz_bind9_9.so',
                  install_path='${MODULESDIR}/bind9',
                  deps='samba-hostconfig samdb-common gensec popt',
                  enabled=bld.AD_DC_BUILD_IS_ENABLED())

bld.SAMBA_LIBRARY('dlz_bind9_for_torture',
                  source='dlz_bind9.c',
                  cflags='-DBIND_VERSION_9_8',
                  private_library=True,
                  deps='samba-hostconfig samdb-common gensec popt',
                  enabled=bld.AD_DC_BUILD_IS_ENABLED())
