#!/usr/bin/env python

bld.SAMBA_MODULE('DNS',
        source='dns_server.c dns_query.c dns_update.c dns_utils.c',
        subsystem='service',
        init_function='server_service_dns_init',
        deps='samba-hostconfig LIBTSOCKET LIBSAMBA_TSOCKET',
        local_include=False
        )
