#!/usr/bin/env python


bld.SAMBA_SUBSYSTEM('LIBCLI_DRSUAPI',
	source='repl_decrypt.c',
	public_deps='LIBCLI_AUTH samdb z'
	)

bld.SAMBA_BINARY(
    'test_repl_decrypt',
    source='tests/test_repl_decrypt.c',
    deps='''
    LIBCLI_DRSUAPI
    cmocka
    talloc
    ''',
    for_selftest=True,
    enabled=bld.AD_DC_BUILD_IS_ENABLED()
)
