/* header auto-generated by pidl */

#include "librpc/ndr/libndr.h"
#include "librpc/gen_ndr/dom_sid.h"

#ifndef _HEADER_NDR_dom_sid
#define _HEADER_NDR_dom_sid

#define NDR_DOM_SID_CALL_COUNT (0)
#endif /* _HEADER_NDR_dom_sid */
