/* header auto-generated by pidl */

#include <stdint.h>

#ifndef _HEADER_ntsvcs
#define _HEADER_ntsvcs


struct PNP_Disconnect {
	int _dummy_element;
};


struct PNP_Connect {
	int _dummy_element;
};


struct PNP_GetVersion {
	int _dummy_element;
};


struct PNP_GetGlobalState {
	int _dummy_element;
};


struct PNP_InitDetection {
	int _dummy_element;
};


struct PNP_ReportLogOn {
	int _dummy_element;
};


struct PNP_ValidateDeviceInstance {
	int _dummy_element;
};


struct PNP_GetRootDeviceInstance {
	int _dummy_element;
};


struct PNP_GetRelatedDeviceInstance {
	int _dummy_element;
};


struct PNP_EnumerateSubKeys {
	int _dummy_element;
};


struct PNP_GetDeviceList {
	int _dummy_element;
};


struct PNP_GetDeviceListSize {
	int _dummy_element;
};


struct PNP_GetDepth {
	int _dummy_element;
};


struct PNP_GetDeviceRegProp {
	int _dummy_element;
};


struct PNP_SetDeviceRegProp {
	int _dummy_element;
};


struct PNP_GetClassInstance {
	int _dummy_element;
};


struct PNP_CreateKey {
	int _dummy_element;
};


struct PNP_DeleteRegistryKey {
	int _dummy_element;
};


struct PNP_GetClassCount {
	int _dummy_element;
};


struct PNP_GetClassName {
	int _dummy_element;
};


struct PNP_DeleteClassKey {
	int _dummy_element;
};


struct PNP_GetInterfaceDeviceAlias {
	int _dummy_element;
};


struct PNP_GetInterfaceDeviceList {
	int _dummy_element;
};


struct PNP_GetInterfaceDeviceListSize {
	int _dummy_element;
};


struct PNP_RegisterDeviceClassAssociation {
	int _dummy_element;
};


struct PNP_UnregisterDeviceClassAssociation {
	int _dummy_element;
};


struct PNP_GetClassRegProp {
	int _dummy_element;
};


struct PNP_SetClassRegProp {
	int _dummy_element;
};


struct PNP_CreateDevInst {
	int _dummy_element;
};


struct PNP_DeviceInstanceAction {
	int _dummy_element;
};


struct PNP_GetDeviceStatus {
	int _dummy_element;
};


struct PNP_SetDeviceProblem {
	int _dummy_element;
};


struct PNP_DisableDevInst {
	int _dummy_element;
};


struct PNP_UninstallDevInst {
	int _dummy_element;
};


struct PNP_AddID {
	int _dummy_element;
};


struct PNP_RegisterDriver {
	int _dummy_element;
};


struct PNP_QueryRemove {
	int _dummy_element;
};


struct PNP_RequestDeviceEject {
	int _dummy_element;
};


struct PNP_IsDockStationPresent {
	int _dummy_element;
};


struct PNP_RequestEjectPC {
	int _dummy_element;
};


struct PNP_HwProfFlags {
	int _dummy_element;
};


struct PNP_GetHwProfInfo {
	int _dummy_element;
};


struct PNP_AddEmptyLogConf {
	int _dummy_element;
};


struct PNP_FreeLogConf {
	int _dummy_element;
};


struct PNP_GetFirstLogConf {
	int _dummy_element;
};


struct PNP_GetNextLogConf {
	int _dummy_element;
};


struct PNP_GetLogConfPriority {
	int _dummy_element;
};


struct PNP_AddResDes {
	int _dummy_element;
};


struct PNP_FreeResDes {
	int _dummy_element;
};


struct PNP_GetNextResDes {
	int _dummy_element;
};


struct PNP_GetResDesData {
	int _dummy_element;
};


struct PNP_GetResDesDataSize {
	int _dummy_element;
};


struct PNP_ModifyResDes {
	int _dummy_element;
};


struct PNP_DetectResourceLimit {
	int _dummy_element;
};


struct PNP_QueryResConfList {
	int _dummy_element;
};


struct PNP_SetHwProf {
	int _dummy_element;
};


struct PNP_QueryArbitratorFreeData {
	int _dummy_element;
};


struct PNP_QueryArbitratorFreeSize {
	int _dummy_element;
};


struct PNP_RunDetection {
	int _dummy_element;
};


struct PNP_RegisterNotification {
	int _dummy_element;
};


struct PNP_UnregisterNotification {
	int _dummy_element;
};


struct PNP_GetCustomDevProp {
	int _dummy_element;
};


struct PNP_GetVersionInternal {
	int _dummy_element;
};


struct PNP_GetBlockedDriverInfo {
	int _dummy_element;
};


struct PNP_GetServerSideDeviceInstallFlags {
	int _dummy_element;
};

#endif /* _HEADER_ntsvcs */
