#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('LIBTLS',
                    source='''
                           tlscert.c
                           tls_tstream.c
                           ''',
                    public_deps='''
                                talloc
                                gnutls
                                GNUTLS_HELPERS
                                samba-hostconfig
                                LIBTSOCKET
                                tevent
                                tevent-util
                                quic
                                libngtcp2
                                libngtcp2_crypto_gnutls
                                ''')
