#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('GENCACHE',
	source='../../source3/lib/gencache.c',
        enabled=False,
	deps='tdb-wrap'
	)


bld.SAMBA_LIBRARY('tdb-wrap',
                  source='tdb_wrap.c',
                  deps='tdb talloc samba-util',
                  public_headers='tdb_wrap.h',
                  private_library=True
                  )

