Import('hostenv')

hostenv.Library('rpcserver_common', 
		[ 'common/server_info.c', 'common/share_info.c'])

#hostenv.Library('rpcserver_dcom', [ 'dcom/oxidresolver.c','dcom/rot.c','dcom/rodb.c','dcom/remact.c', '../librpc/gen_ndr/ndr_dcom_d.c'])

hostenv.Library('rpcserver_echo', ['echo/rpc_echo.c'])
hostenv.Library('rpcserver_epmapper', ['epmapper/rpc_epmapper.c'])
hostenv.Library('rpcserver_remote', ['remote/dcesrv_remote.c'])
hostenv.Library('rpcserver_srvsvc', ['srvsvc/dcesrv_srvsvc.c'])
hostenv.Library('rpcserver_wkssvc', ['wkssvc/dcesrv_wkssvc.c'])
hostenv.Library('rpcserver_unixinfo', ['unixinfo/dcesrv_unixinfo.c'])
hostenv.Library('rpcserver_samr', ['samr/dcesrv_samr.c','samr/samr_password.c'])
hostenv.Library('rpcserver_winreg', [ 'winreg/rpc_winreg.c'])
hostenv.Library('rpcserver_netlogon', [ 'netlogon/dcerpc_netlogon.c'])
hostenv.Library('rpcserver_lsa', ['lsa/dcesrv_lsa.c'])
hostenv.Library('rpcserver_spoolss', ['spoolss/dcesrv_spoolss.c'])
hostenv.Library('rpcserver_drsuapi', ['drsuapi/dcesrv_drsuapi.c','drsuapi/drsuapi_cracknames.c'])
hostenv.Library('rpcserver_dssetup', ['dssetup/dcesrv_dssetup.c'])
hostenv.Library('rpcserver', ['dcerpc_server.c', 'dcerpc_sock.c', 'dcesrv_auth.c', 'handles.c'])
