/* header auto-generated by pidl */

#include "librpc/gen_ndr/security.h"
#ifndef _HEADER_unixinfo
#define _HEADER_unixinfo

struct unixinfo_GetPWUidInfo {
	NTSTATUS status;
	const char * homedir;/* [flag(LIBNDR_FLAG_STR_UTF8|LIBNDR_FLAG_STR_NULLTERM)] */
	const char * shell;/* [flag(LIBNDR_FLAG_STR_UTF8|LIBNDR_FLAG_STR_NULLTERM)] */
};


struct unixinfo_SidToUid {
	struct {
		struct dom_sid sid;
	} in;

	struct {
		uint64_t *uid;/* [ref] */
		NTSTATUS result;
	} out;

};


struct unixinfo_UidToSid {
	struct {
		uint64_t uid;
	} in;

	struct {
		struct dom_sid *sid;/* [unique] */
		NTSTATUS result;
	} out;

};


struct unixinfo_SidToGid {
	struct {
		struct dom_sid sid;
	} in;

	struct {
		uint64_t *gid;/* [ref] */
		NTSTATUS result;
	} out;

};


struct unixinfo_GidToSid {
	struct {
		uint64_t gid;
	} in;

	struct {
		struct dom_sid *sid;/* [unique] */
		NTSTATUS result;
	} out;

};


struct unixinfo_GetPWUid {
	struct {
		uint32_t *count;/* [ref,range(0 1023)] */
		uint64_t *uids;/* [size_is(*count)] */
	} in;

	struct {
		uint32_t *count;/* [ref,range(0 1023)] */
		struct unixinfo_GetPWUidInfo *infos;/* [size_is(*count)] */
		NTSTATUS result;
	} out;

};

#endif /* _HEADER_unixinfo */
