#!/bin/sh
# sample event script for ctdb

cmd="$1"
shift

case $cmd in 
     takeip)
	if [ $# != 3 ]; then
	   echo "must supply interface, IP and maskbits"
	   exit 1
	fi
	iface=$1
	ip=$2
	maskbits=$3
	/sbin/ip addr add $ip/$maskbits dev $iface || {
		 echo "Failed to add $ip/$maskbits on dev $iface"
		 exit 1
	}
	exit 0
	;;

     releaseip)
	if [ $# != 3 ]; then
	   echo "must supply interface, IP and maskbits"
	   exit 1
	fi
	iface=$1
	ip=$2
	maskbits=$3
	/sbin/ip addr del $ip dev $iface || {
		 echo "Failed to del $ip on dev $iface"
		 exit 1
	}
	exit 0
	;;

     recovered)
        # restart any services as necessary, like NFS
	exit 0
	;;

     shutdown)
        # shutdown any services as necessary
	exit 0
	;;
esac

echo "Invalid command $cmd"
exit 1
