#!/bin/sh

. /etc/sysconfig/ctdb

[ -z "$STATD_SHARED_DIRECTORY" ] && exit 0

[ -d $STATD_SHARED_DIRECTORY ] || exit 0

case "$1" in
  add-client)
        for f in `/bin/ls /etc/ctdb/state/ip.*`; do
	    fname=`/bin/basename $f`
	    ip=`echo $fname | cut -d. -f2-`
	    [ -d $STATD_SHARED_DIRECTORY/$ip ] || /bin/mkdir $STATD_SHARED_DIRECTORY/$ip
	    /bin/touch $STATD_SHARED_DIRECTORY/$ip/$2
	done
	;;
  del-client)
        for f in `/bin/ls /etc/ctdb/state/ip.*`; do
	    fname=`/bin/basename $f`
	    ip=`echo $fname | cut -d. -f2-`
	    /bin/rm -f $STATD_SHARED_DIRECTORY/$ip/$2
	done
	;;
  notify)
	# restart the local lock manager and statd
	/sbin/service nfslock stop > /dev/null 2>&1 
	/sbin/service nfslock start > /dev/null 2>&1 
	# send out notifications to any additional ips we now serve
        for f in `/bin/ls /etc/ctdb/state/ip.*`; do
	    fname=`/bin/basename $f`
	    ip=`echo $fname | cut -d. -f2-`
	    [ -d $STATD_SHARED_DIRECTORY/$ip ] && {
		# we must copy to a different directory since rpc.statd gets
		# "upset" if sm-notify touches the files.
		/bin/rm -rf /tmp/statd/$ip
		/bin/mkdir -p /tmp/statd/$ip
		/bin/cp -apr $STATD_SHARED_DIRECTORY/$ip/* /tmp/statd/$ip
		/usr/sbin/sm-notify -P /tmp/statd/$ip -v $ip -n
	    }
	done
	;;
esac

