Import('hostenv')

hostenv.StaticLibrary('mpr',['mpr/miniMpr.c','mpr/var.c'])
hostenv.StaticLibrary('ejs',['ejs/ejsLib.c','ejs/ejsLex.c','ejs/ejsParser.c','ejs/ejsProcs.c'])
hostenv.StaticLibrary('esp',['esp/esp.c','esp/espProcs.c'])
