#!/usr/bin/env python

bld.SAMBA_LIBRARY('http',
	source='http.c http_auth.c http_conn.c',
	deps='talloc tevent gensec dns_lookup',
	private_library=True,
)

bld.SAMBA_MODULE('gensec_http_basic',
	source='gensec/basic.c',
	subsystem='gensec',
	init_function='gensec_http_basic_init',
	deps='samba-util auth_session'
)

bld.SAMBA_MODULE('gensec_http_generic',
	source='gensec/generic.c',
	subsystem='gensec',
	init_function='gensec_http_generic_init',
	deps='samba-util auth_session'
)
