#!/usr/bin/env python

bld.SAMBA3_MODULE('vfs_skel_opaque',
                 subsystem='vfs',
                 source='skel_opaque.c',
                 deps='samba-util',
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('vfs_skel_opaque'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('vfs_skel_opaque'))

bld.SAMBA3_MODULE('vfs_skel_transparent',
                 subsystem='vfs',
                 source='skel_transparent.c',
                 deps='samba-util',
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('vfs_skel_transparent'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('vfs_skel_transparent'))

bld.SAMBA3_MODULE('vfs_shadow_copy_test',
                 subsystem='vfs',
                 source='shadow_copy_test.c',
                 deps='samba-util',
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('vfs_shadow_copy_test'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('vfs_shadow_copy_test'))
