#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('DCERPC_COMMON',
	source='common/server_info.c common/share_info.c common/forward.c',
	autoproto='common/proto.h',
	public_headers='common/common.h',
        header_path='dcerpc_server',
	deps='ldb'
	)


bld.SAMBA_MODULE('dcerpc_rpcecho',
	source='echo/rpc_echo.c',
	subsystem='dcerpc_server',
	init_function='dcerpc_server_rpcecho_init',
	deps='NDR_STANDARD LIBEVENTS'
	)


bld.SAMBA_MODULE('dcerpc_epmapper',
	source='epmapper/rpc_epmapper.c',
	subsystem='dcerpc_server',
	init_function='dcerpc_server_epmapper_init',
	deps='NDR_EPMAPPER'
	)


bld.SAMBA_MODULE('dcerpc_remote',
	source='remote/dcesrv_remote.c',
	subsystem='dcerpc_server',
	init_function='dcerpc_server_remote_init',
	deps='LIBCLI_SMB NDR_TABLE'
	)


bld.SAMBA_MODULE('dcerpc_srvsvc',
	source='srvsvc/dcesrv_srvsvc.c srvsvc/srvsvc_ntvfs.c',
	autoproto='srvsvc/proto.h',
	subsystem='dcerpc_server',
	init_function='dcerpc_server_srvsvc_init',
	deps='DCERPC_COMMON NDR_SRVSVC share'
	)


bld.SAMBA_MODULE('dcerpc_wkssvc',
	source='wkssvc/dcesrv_wkssvc.c',
	subsystem='dcerpc_server',
	init_function='dcerpc_server_wkssvc_init',
	deps='DCERPC_COMMON NDR_STANDARD'
	)


bld.SAMBA_MODULE('dcerpc_unixinfo',
	source='unixinfo/dcesrv_unixinfo.c',
	subsystem='dcerpc_server',
	init_function='dcerpc_server_unixinfo_init',
	deps='DCERPC_COMMON SAMDB NDR_UNIXINFO NSS_WRAPPER LIBWBCLIENT_OLD'
	)


bld.SAMBA_MODULE('dcesrv_samr',
	source='samr/dcesrv_samr.c samr/samr_password.c',
	autoproto='samr/proto.h',
	subsystem='dcerpc_server',
	init_function='dcerpc_server_samr_init',
	deps='SAMDB DCERPC_COMMON NDR_STANDARD'
	)


bld.SAMBA_MODULE('dcerpc_winreg',
	source='winreg/rpc_winreg.c',
	subsystem='dcerpc_server',
	init_function='dcerpc_server_winreg_init',
	deps='registry NDR_STANDARD',
	internal_module=True
	)


bld.SAMBA_MODULE('dcerpc_netlogon',
	source='netlogon/dcerpc_netlogon.c',
	subsystem='dcerpc_server',
	init_function='dcerpc_server_netlogon_init',
	deps='DCERPC_COMMON SCHANNELDB NDR_STANDARD auth_sam LIBSAMBA-HOSTCONFIG'
	)


bld.SAMBA_MODULE('dcerpc_lsarpc',
	source='lsa/dcesrv_lsa.c lsa/lsa_init.c lsa/lsa_lookup.c',
	autoproto='lsa/proto.h',
	subsystem='dcerpc_server',
	init_function='dcerpc_server_lsa_init',
	deps='SAMDB DCERPC_COMMON NDR_STANDARD LIBCLI_AUTH NDR_DSSETUP'
	)


bld.SAMBA_MODULE('dcerpc_spoolss',
	source='spoolss/dcesrv_spoolss.c',
	subsystem='dcerpc_server',
	init_function='dcerpc_server_spoolss_init',
	deps='DCERPC_COMMON NDR_SPOOLSS ntptr RPC_NDR_SPOOLSS',
	internal_module=True
	)


bld.SAMBA_MODULE('dcerpc_drsuapi',
	source='drsuapi/dcesrv_drsuapi.c drsuapi/updaterefs.c drsuapi/getncchanges.c drsuapi/addentry.c drsuapi/writespn.c drsuapi/drsutil.c',
	subsystem='dcerpc_server',
	init_function='dcerpc_server_drsuapi_init',
	deps='SAMDB DCERPC_COMMON NDR_DRSUAPI'
	)


bld.SAMBA_MODULE('dcerpc_browser',
	source='browser/dcesrv_browser.c',
	subsystem='dcerpc_server',
	init_function='dcerpc_server_browser_init',
	deps='DCERPC_COMMON NDR_BROWSER'
	)


bld.SAMBA_SUBSYSTEM('dcerpc_server',
	source='dcerpc_server.c dcesrv_auth.c dcesrv_mgmt.c handles.c',
	autoproto='dcerpc_server_proto.h',
	public_headers='dcerpc_server.h',
	deps='LIBCLI_AUTH LIBNDR dcerpc samba_server_gensec'
	)


bld.SAMBA_MODULE('DCESRV',
	source='service_rpc.c',
	autoproto='service_rpc.h',
	subsystem='service',
	init_function='server_service_rpc_init',
	internal_module=True,
	deps='dcerpc_server'
	)

