#!/usr/bin/env python
bld.SAMBA_LIBRARY('gensec',
	source='gensec.c gensec_start.c',
	pc_files='gensec.pc',
	autoproto='gensec_toplevel_proto.h',
	public_deps='tevent-util samba-util errors LIBPACKET auth_system_session samba-module gensec_util',
	public_headers='gensec.h',
	deps='com_err',
	vnum='0.0.1'
	)

