#!/usr/bin/env python
bld.SAMBA_LIBRARY('gensec',
	source='gensec.c gensec_start.c gensec_util.c',
	pc_files='gensec.pc',
	autoproto='gensec_toplevel_proto.h',
	public_deps='tevent-util samba-util errors LIBPACKET auth_system_session samba-modules gensec_util asn1util',
	public_headers='gensec.h',
	deps='com_err',
	vnum='0.0.1'
	)

bld.SAMBA_MODULE('gensec_spnego',
	source='spnego.c',
	autoproto='spnego_proto.h',
	subsystem='gensec',
	init_function='gensec_spnego_init',
	deps='asn1util samba-credentials SPNEGO_PARSE'
	)
