'\" t
.\"     Title: ltdbtool
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/04/2011
.\"    Manual:  
.\"    Source:  
.\"  Language: English
.\"
.TH "LTDBTOOL" "1" "05/04/2011" "" ""
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ltdbtool \- handle ctdb\*(Aqs local tdb copies
.SH "SYNOPSIS"
.HP \w'\fBltdbtool\ [OPTIONS]\ COMMAND\fR\ 'u
\fBltdbtool [OPTIONS] COMMAND\fR
.SH "DESCRIPTION"
.PP
ltdbtool is a utility to cope with ctdb\*(Aqs local tdb copies (LTDBs) without connecting to a ctdb daemon\&.
.PP
It can be used to
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
dump the contents of a LTDB, optionally printing the ctdb record header information,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
convert between an LTDB and a non\-clustered tdb by adding or removing ctdb headers and
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
convert between 64 and 32 bit LTDBs where the ctdb record headers differ by 4 bytes of padding\&.
.RE
.sp
.SH "COMMANDS"
.PP
help
.RS 4
Print a help text\&.
.RE
.PP
dump <IDB>
.RS 4
Dump the contents of a LTDB file to standard output in a human\-readable format\&.
.RE
.PP
convert <IDB> <ODB>
.RS 4
Make a copy of a LTDB optionally adding or removing ctdb headers\&.
.RE
.SH "OPTIONS"
.PP
\-p
.RS 4
Dump with header information, similar to "ctdb catdb"\&.
.RE
.PP
\-s {0|32|64}
.RS 4
Specify how to determine the ctdb record header size for the input database:
.PP
0
.RS 4
no ctdb header
.RE
.PP
32
.RS 4
ctdb header size of a 32 bit system (20 bytes)
.RE
.PP
64
.RS 4
ctdb header size of a 64 bit system (24 bytes)
.RE
.sp
The default is 32 or 64 depending on the system architecture\&.
.RE
.PP
\-o {0|32|64}
.RS 4
Specify how to determine the ctdb record header size for the output database, see \-s
.RE
.PP
\-S <SIZE>
.RS 4
Explicitly specify the ctdb record header size of the input database in bytes\&.
.RE
.PP
\-O <SIZE>
.RS 4
Explicitly specify the ctdb record header size for the output database in bytes\&.
.RE
.PP
\-h
.RS 4
Print a help text\&.
.RE
.SH "EXAMPLES"
.PP
Print a local tdb in "tdbdump" style:
.sp
.if n \{\
.RS 4
.\}
.nf
      ltdbtool dump idmap2\&.tdb\&.0
    
.fi
.if n \{\
.RE
.\}
.PP
Print a local tdb with header information similar to "ctdb catdb":
.sp
.if n \{\
.RS 4
.\}
.nf
      ltdbtool dump \-p idmap2\&.tdb\&.0
    
.fi
.if n \{\
.RE
.\}
.PP
Strip the ctdb headers from records:
.sp
.if n \{\
.RS 4
.\}
.nf
      ltdbtool convert \-o0 idmap2\&.tdb\&.0 idmap\&.tdb
    
.fi
.if n \{\
.RE
.\}
.PP
Strip 64 bit ctdb headers from records, running on i386:
.sp
.if n \{\
.RS 4
.\}
.nf
      ltdbtool convert \-s64 \-o0 idmap2\&.tdb\&.0 idmap\&.tdb
    
.fi
.if n \{\
.RE
.\}
.PP
Strip the ctdb headers from records by piping through tdbrestore:
.sp
.if n \{\
.RS 4
.\}
.nf
      ltdbtool dump idmap2\&.tdb\&.0 | tdbrestore idmap\&.tdb
    
.fi
.if n \{\
.RE
.\}
.PP
Convert a local tdb from a 64 bit system for usage on a 32 bit system:
.sp
.if n \{\
.RS 4
.\}
.nf
      ltdbtool convert \-s64 \-o32 idmap2\&.tdb\&.0 idmap2\&.tdb\&.1
    
.fi
.if n \{\
.RE
.\}
.PP
Add a default header:
.sp
.if n \{\
.RS 4
.\}
.nf
      ltdbtool convert \-s0 idmap\&.tdb idmap2\&.tdb\&.0
    
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
ctdbd(1), ctdb(1), tdbdump(1), tdbrestore(1),
\m[blue]\fB\%http://ctdb.samba.org/\fR\m[]
.SH "COPYRIGHT/LICENSE"
.sp
.if n \{\
.RS 4
.\}
.nf
Copyright (C) Gregor Beck 2011
Copyright (C) Michael Adam 2011

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at
your option) any later version\&.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&.  See the GNU
General Public License for more details\&.

You should have received a copy of the GNU General Public License
along with this program; if not, see http://www\&.gnu\&.org/licenses/\&.
.fi
.if n \{\
.RE
.\}
