.\"     Title: onnode
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 07/10/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "ONNODE" "1" "07/10/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
onnode \- run commands on ctdb nodes
.SH "SYNOPSIS"
.HP 24
\fBonnode NODE COMMAND ...\fR
.SH "DESCRIPTION"
.PP
onnode is a utility to run commands on a specific node of a CTDB cluster, or on all nodes.
.PP
The NODE option specifies which node to run a command on. You can specify a numeric node number (from 0 to N\-1) or the special node 'all'.
.PP
The COMMAND can be any shell command. The onnode utility uses ssh or rsh to connect to the remote nodes and run the command.
.PP
If the COMMAND starts with a /, then the command is run via the 'at' service. Otherwise the command is run in the foreground.
.SH "EXAMPLES"
.PP
The following command would show the process ID of ctdb on all nodes
.sp
.RS 4
.nf
onnode all pidof ctdbd
      
.fi
.RE
.PP
The following command would show the last 5 lines of log on each node, preceded by the nodes hostname
.sp
.RS 4
.nf
onnode all "hostname; tail \-5 /var/log/log.ctdb"
      
.fi
.RE
.PP
The following command would restart the ctdb service on all nodes.
.sp
.RS 4
.nf
onnode all service ctdb restart
      
.fi
.RE
.SH "SEE ALSO"
.PP
ctdbd(1), ctdb(1),
\fI\%http://ctdb.samba.org/\fR
.SH "COPYRIGHT/LICENSE"
.sp
.RS 4
.nf
Copyright (C) Andrew Tridgell 2007
Copyright (C) Ronnie sahlberg 2007

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, see http://www.gnu.org/licenses/.
.fi
.RE
