#!/bin/sh
# ctdb event script for Samba

PATH=/bin:/usr/bin:$PATH

. /etc/sysconfig/ctdb
. /etc/ctdb/functions

cmd="$1"
shift

case $cmd in 
     startup)
	# wait for the Samba tcp ports to become available
	smb_ports=`testparm -stv 2> /dev/null | egrep '\s*smb ports =' | cut -d= -f2`
	ctdb_wait_tcp_ports "Samba" $smb_ports

	# wait for all shared directories to become available
	smb_dirs=`testparm -st 2> /dev/null | egrep '^\s*path = '  | cut -d= -f2`
	ctdb_wait_directories "Samba" $smb_dirs	
	;;
	
     takeip)
	# nothing special for Samba
	;;

     releaseip)
	# nothing special for Samba
	;;

     recovered)
	# nothing special for Samba
	exit 0
	;;

     shutdown)
	# shutdown Samba when ctdb goes down
	killall -q smbd nmbd winbindd
	;;
esac

# ignore unknown commands
exit 0
