#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM(
    'audit_logging',
    deps='''MESSAGING_SEND
            jansson
            samba-debug
            LIBTSOCKET''',
    source='audit_logging.c'
)

if bld.AD_DC_BUILD_IS_ENABLED():
    bld.SAMBA_BINARY(
        'audit_logging_test',
        source='tests/audit_logging_test.c',
        deps='''
             audit_logging
             jansson
             cmocka
             talloc
             samba-util
             LIBTSOCKET
        ''',
        for_selftest=True
    )

if bld.AD_DC_BUILD_IS_ENABLED():
    bld.SAMBA_BINARY(
        'audit_logging_error_test',
        source='tests/audit_logging_error_test.c',
        deps='''
             audit_logging
             jansson
             cmocka
             talloc
             samba-util
             LIBTSOCKET
        ''',
        for_selftest=True,
        ldflags='''
            -Wl,--wrap,json_object_set_new
            -Wl,--wrap,json_object_update
            -Wl,--wrap,json_array_append_new
            -Wl,--wrap,json_array_extend
            -Wl,--wrap,json_object
            -Wl,--wrap,json_string
            -Wl,--wrap,json_integer
            -Wl,--wrap,json_array
            -Wl,--wrap,json_dumps
            -Wl,--wrap,gettimeofday
            -Wl,--wrap,localtime
            -Wl,--wrap,talloc_named_const
            -Wl,--wrap,talloc_strdup
            -Wl,--wrap,tsocket_address_string
        '''
    )
