#!/usr/bin/env python
Import('hostenv')

hostenv.Library('auth_sam.c')
hostenv.Library('auth_anonymous.c')
hostenv.Library('auth_winbind.c')
hostenv.Library('auth_domain.c')
hostenv.Library('auth_developer.c')
hostenv.Library('auth_unix.c')

if hostenv['configure']:
    conf = hostenv.Configure()
    have_pam = conf.CheckLibWithHeader('pam', 'security/pam_appl.h', 'c', 'pam_start')
    conf.Finish()

proto_files = []
hostenv.Library('pam_errors.c')
proto_files += ['pam_errors.c', 'auth_sam.c']
auth_files = ['auth.c','auth_util.c','auth_sam_reply.c','ntlm_check.c']
proto_files += auth_files
hostenv.Library('auth',auth_files)

ntlmssp_files = ['ntlmssp/ntlmssp_parse.c', 'ntlmssp/ntlmssp.c',
		'ntlmssp/ntlmssp_sign.c','ntlmssp/ntlmssp_client.c',
		'ntlmssp/ntlmssp_server.c'] 
proto_files += ntlmssp_files
hostenv.Library('gensec_ntlmssp', ntlmssp_files)

kerberos_files = ['kerberos/kerberos.c','kerberos/clikrb5.c',
	'kerberos/kerberos_verify.c','kerberos/kerberos_util.c',
	'kerberos/kerberos_pac.c','kerberos/gssapi_parse.c',
	'kerberos/krb5_init_context.c']

proto_files += kerberos_files

hostenv.Library('kerberos', kerberos_files)

hostenv.proto_headers += hostenv.CProtoHeader('proto.h', proto_files)

SConscript(dirs=['gensec'])
