#!/usr/bin/env python


bld.SAMBA_MODULE('service_winbindd',
	source='winbindd.c',
	subsystem='service',
	init_function='server_service_winbindd_init',
	deps='process_model UTIL_RUNCMD',
	internal_module=False,
	)


bld.SAMBA_SUBSYSTEM('IDMAP',
	source='idmap.c',
	autoproto='idmap_proto.h',
	public_deps='samdb-common ldbsamba'
	)

