#!/usr/bin/env python

extra_deps = ''

if bld.CONFIG_SET("HAVE_AESNI_INTEL"):
        extra_deps += ' aesni-intel'

bld.SAMBA_SUBSYSTEM('GNUTLS_HELPERS',
                    source='''
                    gnutls_error.c
                    gnutls_arcfour_confounded_md5.c
                    ''',
                    deps='gnutls samba-errors');

bld.SAMBA_SUBSYSTEM('LIBCRYPTO_AES_CCM',
                    source='aes_ccm_128.c',
                    deps='talloc')

bld.SAMBA_SUBSYSTEM('LIBCRYPTO_AES_GCM',
                    source='aes_gcm_128.c',
                    deps='talloc')

bld.SAMBA_SUBSYSTEM('LIBCRYPTO_AES',
                    source='aes.c rijndael-alg-fst.c',
                    deps='talloc')

bld.SAMBA_SUBSYSTEM('LIBCRYPTO_AES_CMAC',
                    source='aes_cmac_128.c',
                    deps='talloc',
                    enabled=not bld.CONFIG_SET('HAVE_GNUTLS_AES_CMAC'))

bld.SAMBA_SUBSYSTEM('LIBCRYPTO',
        source='''
               md4.c
               ''',
        deps='''
             talloc
             LIBCRYPTO_AES
             LIBCRYPTO_AES_CCM
             LIBCRYPTO_AES_GCM
             LIBCRYPTO_AES_CMAC
             ''' + extra_deps)

bld.SAMBA_SUBSYSTEM('TORTURE_LIBCRYPTO_AES_CCM',
                    source='aes_ccm_128_test.c',
                    autoproto='aes_ccm_test_proto.h',
                    deps='talloc')

bld.SAMBA_SUBSYSTEM('TORTURE_LIBCRYPTO_AES_GCM',
                    source='aes_gcm_128_test.c',
                    autoproto='aes_gcm_test_proto.h',
                    deps='talloc')

bld.SAMBA_SUBSYSTEM('TORTURE_LIBCRYPTO_AES_CMAC',
                    source='aes_cmac_128_test.c',
                    autoproto='aes_cmac_test_proto.h',
                    deps='talloc',
                    enabled=not bld.CONFIG_SET('HAVE_GNUTLS_AES_CMAC'))

bld.SAMBA_SUBSYSTEM('TORTURE_LIBCRYPTO',
        source='md4test.c',
        autoproto='test_proto.h',
        deps='''
             LIBCRYPTO
             TORTURE_LIBCRYPTO_AES_CCM
             TORTURE_LIBCRYPTO_AES_GCM
             TORTURE_LIBCRYPTO_AES_CMAC
             ''')

bld.SAMBA_PYTHON('python_crypto',
                 source='py_crypto.c',
                 deps='gnutls talloc',
                 realname='samba/crypto.so')
