[LIBRARY::TDR]
PUBLIC_HEADERS = tdr.h
VERSION = 0.0.1
SO_VERSION = 0
DESCRIPTION = Simple marshall/unmarshall library
PUBLIC_PROTO_HEADER = tdr_proto.h
REQUIRED_SUBSYSTEMS = LIBTALLOC LIBSAMBA-UTIL
OBJ_FILES = tdr.o
