#!/usr/bin/env python
if bld.CONFIG_SET('AD_DC_BUILD_IS_ENABLED'):
      bld.SAMBA_MODULE('TORTURE_KRB5',
                       source='kdc.c kdc-canon.c',
                       autoproto='proto.h',
                       subsystem='smbtorture',
                       init_function='torture_krb5_init',
                       deps='authkrb5 popt POPT_CREDENTIALS torture KERBEROS_UTIL',
                       internal_module=True
                 )
      
