#!/usr/bin/env python

if bld.CONFIG_SET('AD_DC_BUILD_IS_ENABLED'):
    if bld.CONFIG_SET('SAMBA4_USES_HEIMDAL'):
        bld.SAMBA_MODULE('TORTURE_KRB5',
                         source='kdc-heimdal.c kdc-canon-heimdal.c',
                         autoproto='proto.h',
                         subsystem='smbtorture',
                         init_function='torture_krb5_init',
                         deps='authkrb5 popt POPT_CREDENTIALS torture KERBEROS_UTIL',
                         internal_module=True)
    else:
            bld.SAMBA_MODULE('TORTURE_KRB5',
                             source='kdc-mit.c',
                             autoproto='proto.h',
                             subsystem='smbtorture',
                             init_function='torture_krb5_init',
                             deps='authkrb5 popt POPT_CREDENTIALS torture KERBEROS_UTIL',
                             internal_module=True)
